### ISSUE TITLE
Bytte default branchnavn

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1001]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [ ] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Flere open source prosjekter og Github ser ut til å gå vekk i fra en del begrep som kan ha andre konotasjoner. 

**Beskriv løsningen du ønsker**
Bytte navn på default branchen vår fra `master` til 
* `default`
* `main`
* `primary`
* `prod`
* `production`

**Mer info**
* https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/
* https://github.com/antirez/redis/issues/3185
* https://www.drupal.org/node/2275877
* https://issues.apache.org/jira/browse/COUCHDB-2248
* https://github.com/django/django/pull/2692

**Comment by lfbergee** [comment]
[![](https://api.gh-polls.com/poll/01EB67BW09JBNGA3G6BNX33SRC/default)](https://api.gh-polls.com/poll/01EB67BW09JBNGA3G6BNX33SRC/default/vote)
[![](https://api.gh-polls.com/poll/01EB67BW09JBNGA3G6BNX33SRC/main)](https://api.gh-polls.com/poll/01EB67BW09JBNGA3G6BNX33SRC/main/vote)
[![](https://api.gh-polls.com/poll/01EB67BW09JBNGA3G6BNX33SRC/primary)](https://api.gh-polls.com/poll/01EB67BW09JBNGA3G6BNX33SRC/primary/vote)
[![](https://api.gh-polls.com/poll/01EB67BW09JBNGA3G6BNX33SRC/prod)](https://api.gh-polls.com/poll/01EB67BW09JBNGA3G6BNX33SRC/prod/vote)
[![](https://api.gh-polls.com/poll/01EB67BW09JBNGA3G6BNX33SRC/production)](https://api.gh-polls.com/poll/01EB67BW09JBNGA3G6BNX33SRC/production/vote)

**Comment by lfbergee** [comment]
@gbrownlee eller @eduardodir vil en av dere komme med en avgjørende stemme? Beholde master er ikke et alternativ i listen, men er jo selvsagt et alternativ i virkeligheten, om vi ikke vil bytte hovedbranch.

**Comment by gbrownlee** [comment]
@lfbergee Jeg lurer på om det vil være fint å ta den avgjørelsen i forbindelse med stagingarbeidet som også pågår. Antar vi da får flere brancher som bør navngis i sammenheng.

**Comment by wkillerud** [comment]
Jeg har denne endringen på ønskelista mi @gbrownlee. Er stagingarbeidet fortsatt et work in progress, eller kan vi begynne en innsats for å få gjort navnebyttet her i Jøkul?

**Comment by joms** [comment]
Stagingmiljøet har stått stille i evigheter... Det finnes en [branch](https://github.com/fremtind/jokul/tree/feat/880-staging-deployment-aws) på det som kom _nesten_ i mål

**Comment by wkillerud** [comment]
OK, men da trenger vi kanskje ikke la det være blocking

**Comment by joms** [comment]
Naah, ser ikke for meg det. Heller ta opp igjen stagingmiljøjobben i etterkant
