### ISSUE TITLE
Profilen vår: Farger

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#1015]
## Hva må med

- [x] Forhåndsvisning
- [x] hex
- [x] (cmyk)
- [x] (pantone)

## Ekstra dokumentasjon

- [x] UU og kontrast (f.eks. kontrastkrav/AA/AAA)
- [x] Info om verktøy (Figma-plugins, WebAIM, etc.)

**Comment by Steinop** [comment]
Mangler en pantone for hvit men kan heller ikke se at det finnes. Har ikke tatt med pantonefarger for meldingsfargene - de bør i så fall defineres hvise det er behov.

Her er skisse:
https://www.figma.com/file/dWhCsnlMAmJEBPyGnRrse5RM/J%C3%B8kul-portalen?node-id=4252%3A800

**Comment by Steinop** [comment]
Lagde også en veldig rask mockup for mobilversjon - den krever nok litt mer bearbeiding og tuning men kan være et utgangspunkt for noe:
https://www.figma.com/file/dWhCsnlMAmJEBPyGnRrse5RM/J%C3%B8kul-portalen?node-id=4252%3A1648
