### ISSUE TITLE
Select med optional label

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#1016]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [x] Avklare
- [x] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Vi har en valutakomponent som ser slik ut: 
![image](https://user-images.githubusercontent.com/14551408/85278673-8a2bd580-b485-11ea-933f-d1efe438280c.png)

**Beskriv løsningen du ønsker**
På et vis gjøre at man ikke trenger å ha med label.

**Hvilke alternativer har du vurdert?**
BaseSelect-komponent som kun inneholder selve Select-komponenten.
Gjøre label optional i Select generelt.

**Comment by CamillaDahlstroem** [comment]
Select med optional label har vi til tider sett behov for i Flyt også! Har brukt det som dropdown-meny i headeren vår, blant annet. (Som dere ser er det en svært gammel versjon av select-komponenten)
<img width="253" alt="Skjermbilde 2020-06-22 kl  14 46 29" src="https://user-images.githubusercontent.com/11536996/85289232-62456d80-b497-11ea-8388-12352f7d851d.png">

**Comment by piofinn** [comment]
@CamillaDahlstroem ditt eksempel er nok ikke en `Select`, men en faktisk dropdown-meny 😊 Jeg er ganske sikker på at @Murstam har jobbet med noe tilsvarende for BM, så jeg ville kanskje prøvd å ta en prat med ham/dem! Hvis de har utviklet/skal utvikle noe som funker for dere kan vi jobbe for å få den inn i systemet!

@vegardsoerlie det bør nok fortsatt være en label av noen sort på `Select`'en av tilgjengelighetshensyn, men det kan eventuelt være skjult visuelt. Kanskje en tilsvarende implementasjon som i `<TextInput inline />`?

**Comment by Murstam** [comment]
J, bedriftsvelgeren vår er for øyeblikket select, men burde nok vært dropdown. Har en halvferdig skisse på det, men ble satt litt på hold. https://www.figma.com/proto/23lrZ2wNVtipKIUCKNvr0x/Forsikringer?node-id=1391%3A151&viewport=-6112%2C-5035%2C0.1909113973379135&scaling=min-zoom
