### ISSUE TITLE
Profilen vår: Eksempler på logobruk

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#1027]

**Comment by Steinop** [comment]
https://www.figma.com/file/dWhCsnlMAmJEBPyGnRrse5RM/J%C3%B8kul-portalen?node-id=2999%3A0

**Comment by Steinop** [comment]
Her bør vi også legge inn logooriginaler for nedlasting i relevante vektor- og bitmapformater

**Comment by eduardodir** [comment]
Har sänt ett mail till Charlotte kring detta, så får vi se vart vi landar.
