### ISSUE TITLE
Eksempel: Fungerende skjema i riktig drakt

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1029]

**Comment by Mikkelinski** [comment]
@lfbergee har vi denne egentlig? Vet den ikke er vist på portalen - men selve eksempelet?

**Comment by lfbergee** [comment]
@Mikkelinski https://jokul.fremtind.no/komigang/Eksempler

Men den bør nok kvalitetsikres, og sannsynligvis utvides. Tror også vi trenger flere varianter. Men kan si at denne oppgaven er løst, og heller lage mer konkrete oppgaver på å lage flere/forbedre den som er der.

**Comment by Mikkelinski** [comment]
@lfbergee enig - bør lukke issue eller la det ligge for historikken?

**Comment by lfbergee** [comment]
Foreslår lukke. Blir liggende i historien om noen vil være arkeolog.

**Comment by lfbergee** [comment]
Closed by #1039
