### ISSUE TITLE
Profilen vår: Vise frem ikoner med eksempler

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#1032]

**Comment by eduardodir** [comment]
Fungerar denna? https://fremtind.github.io/jokul/profil/ikoner

**Comment by Mikkelinski** [comment]
> Fungerar denna? https://fremtind.github.io/jokul/profil/ikoner

Den fungerer bra, tommel opp!

**Comment by Mikkelinski** [comment]
Issue solved
