### ISSUE TITLE
Legge til mindre enhet i layout-spacing-skalaen

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#1043]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [x] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Vi bruker spacingen `16px`/`1rem` ganske mye i layout (bl.a. som sidemarginer på mobil). Siden denne ikke er med i `layout-spacing`-skalaen må man bruke en verdi fra `component-spacing`-skalaen, som egentlig er forbeholdt brukt innad i komponenter.

**Beskriv løsningen du ønsker**
Legge til enheten `16px`/`1rem` i `layout-spacing`-skalaen, f.eks. som `$layout-spacing--xs`.

**Hvilke alternativer har du vurdert?**
Beskriv gjerne hvilke andre potensielle løsninger du har vurdert.

**Mer info**
Her kan du legge til mer kontekst, skjermbilder, eller andre ting du ikke synes passer inn over.

**Comment by Steinop** [comment]
16 px layoutspacing er oppdatert i Figmabiblioteket - gjenstår bare å få den inn i kode og oppdatere Jøkul.
