### ISSUE TITLE
Prefer reduced motion i portalen

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1067]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [ ] Undersøke
- [ ] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Det er en nå blitt en del bevegelse i portalen, bildeside og forsiden spesielt. Disse animasjonene respekterer ikke prefered-reduced-motion.

**Beskriv løsningen du ønsker**
Ny hook:
```
const QUERY = '(prefers-reduced-motion: no-preference)';
const getInitialState = () => {
if(typeof window !== 'undefined'){
  return !window.matchMedia(QUERY).matches
};
return false;
};

function usePrefersReducedMotion() {
  const [
    prefersReducedMotion,
    setPrefersReducedMotion
  ] = React.useState(getInitialState);
  React.useEffect(() => {
    const mediaQueryList = window?.matchMedia(QUERY);
    const listener = event => {
      setPrefersReducedMotion(!event.matches);
    };
    mediaQueryList?.addListener(listener);
    return () => {
      mediaQueryList?.removeListener(listener);
    };
  }, []);
  return prefersReducedMotion;
}
```

Med referanse implementasjon igjennom useContext på toppnivå i appen.

Så implementere said hook i Portalen og dermed fjerne animasjon på forsiden og bildesiden gitt at reduced motion er aktivert.

**Hvilke alternativer har du vurdert?**
Kan benytte oss av hooks som finnes allerde ute på verdensveven. Evt må vi fjerne oss fra js-animasjoner. Web-animation APIet er nå i alle evergreen browsere, så det kan være aktuelt å ta i bruk.

**Mer info**
Her kan du legge til mer kontekst, skjermbilder, eller andre ting du ikke synes passer inn over.

**Comment by eduardodir** [comment]
Kan du fixa den?
