### ISSUE TITLE
Rotklasse for Jøkul

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#1077]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [x] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Per i dag har vi ingen mulighet til å begrense utstrekningen av Jøkul på en side. Når du laster inn `core.css` påvirker det alt innholdet på den innlastede nettsiden. Dersom vi for eksempel vil levere enkeltelementer/"applets" til distributørene, eller vil portere løsninger til Jøkul gradvis, bør vi ha mulighet for å avgrense hvor stilene brukes.

Dette er også aktuelt i forbindelse med innramming av applikasjonene våre.

**Beskriv løsningen du ønsker**
Mitt forslag er en ny klasse, `.jkl`, som brukes på rotelementet på siden, eller det elementet som Jøkul skal begrenses til å være innenfor. Denne klassen kan ta inn stilene fra `core.css` slik at Jøkul-komponentene innenfor oppfører seg riktig uten å påvirke andre deler av siden.

```html
<body class="jkl">
    <div class="jkl-accordion"> ... </div>
</body>
```

```html
<span class="some-other-system">Other stuff</span>
<div class="jkl">
    <div class="jkl-accordion"> ... </div>
</div>
```

**Hvilke alternativer har du vurdert?**
~~Enn så lenge har vi ikke noe uttalt behov for dette, så alternativet er å la være.~~

**Comment by lfbergee** [comment]
Da er det uttalt behov for dette.

Problemet vårt er reseten, det setter egenskaper direkte på HTML elementer.

Feks vi setter line-height til 1 på fieldset. Det gjør at vi ikke kan ha FFE og jkl i samme scope.

Forslag til løsning:
1. Scoping: 
Ved å scope, som @piofinn skisserer, hele Jøkul under `.jkl` så kan vi unngå dette. Ulempen er at alle må huske å sette den klassen rundt jøkul-komponenter for å få riktig stil. Det gjør at alle klienter må ta stilling til dette, selvom det er et fåtall som faktisk vil ha problemer med dette.

2. Scoped reset:
I dag resetter vi direkte på HTML element som h1..6, p, div, fieldset osv. Hvis vi isteden reseter på `jkl-h1..6`, `jkl-fieldset`, så vil det kun påvirke jkl komponenter. Vi kan da tilby `reset-document` som en mixin som resetter HTML-komponenter for klienter som vil det. Fortsatt må alle klienter ta stilling til dette, men nå i CSS-verden, isteden for HTML verden, som kanskje er mer logisk siden endringen skjer i CSS, blir også litt tydeligere hva som faktisk skjer, kontra alternativ 1.

**Comment by lfbergee** [comment]
Del 2 av sagaen, dette er ikke et lett problem.

Jeg foreslår at vi stenger denne og løser det i klient med overrides inntil videre. 

Alternativ 3:
Som kommer til å virke, i motsetning til alternativ 1 og 2, er å slutte å kalle normalize og reset i core. Vi kan tilby de, og si at Jøkul er best om du laster disse filene, men om du ikke vil, så må du ikke. Da vil vi kunne få noen margins og diverse greier som ikke som Jøkul forventer og noe som hver enkelt klient som ikke vil laste reset/normalize må finne en måte å håndere.
