### ISSUE TITLE
Feil: Select med mange valg oppfører seg uventet ved valg (visuelt) 

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#1119]
**Feilbeskrivelse**
Når det er mange mulige valg i menyen og man vil endre valg så hopper ikke menyen som forventet. Litt kronglete å forklare, screenshot under og har et opptak av det jeg gjerne sender for å oppklare ytterligere.

**For å reprodusere**
Fortell oss hvordan vi kan gjenskape feilen (det hjelper oss med å fikse den):

1. Lag et eksempel med select med flere valg (testet selv med 13).
2. Klikk på select-boksen og velg det øverste valget.
3. Klikk på den igjen og velg det andre valget.
4. Trykker på den en tredje gang nå så ser du at ditt valg er cropped og ikke vises slik man forventer.

**Forventet oppførsel**
Hva mener du er riktig funksjonalitet når feilen er løst?

**Skjermbilder**
Feil: 
![image](https://user-images.githubusercontent.com/14551408/87422313-b0eab100-c5d8-11ea-86c1-d1b5b9b16d5e.png)

Forventet:
![image](https://user-images.githubusercontent.com/14551408/87422344-c3fd8100-c5d8-11ea-8059-6e683b6a600d.png)

**Mer info**
Chrome: Oppfører seg som over.
Firefox: Blir riktig så lenge man velger et valg som er 100% synlig. Velger man et element som er litt gjemt 'over' menyen så vil den heller ikke scrolle opp dit visuelt etter den er valgt.
Internet explorer: Får ikke testet selv på mac, men har fått følgende tilbakemelding (på valutakomponent): "Testet i IE og der skrolles det automatisk slik at valgte valuta vises øverst."

**Comment by piofinn** [comment]
> "Testet i IE og der skrolles det automatisk slik at valgte valuta vises øverst."

Den ene gangen i historien der det bare er IE som oppfører seg riktig 😆

**Comment by wkillerud** [comment]
Får ikke reprodusert denne lenger. Gi lyd om det mot formodning er et problem fremdeles!
