### ISSUE TITLE
Feil: Select med mange valg kan ikke scrolles hvis reduced motion er enabled

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#1121]
**Feilbeskrivelse**
Hvis reduced motion er enabled vil aldri handleTransitonEnd kjøres i [animation.tsx](https://github.com/fremtind/jokul/blob/master/packages/react-hooks/src/animation.tsx) fordi transitionend-event aldri vil fire. Så `overflow: hidden` blir applied, men aldri fjernet.

Frykter at det gjelder for andre komponenter også hvis det er noen som avhenger av scroll, uten at jeg kan se hvilke (hvis noen) på stående fot.

**For å reprodusere**
Fortell oss hvordan vi kan gjenskape feilen (det hjelper oss med å fikse den):

1. Skru på reduced motion, enten spesifikt i browser eller under systemvalg/innstillinger (mac/windows). [Guide her](https://developer.paciellogroup.com/blog/2019/05/short-note-on-prefers-reduced-motion-and-puzzled-windows-users/).
2. Lag et eksempel av Select-komponenten med mange valg, evt krymp høyden på nettleser slik at det må scrolles for å navigere alle elementene.
3. Prøv å scroll lista med valg.

**Forventet oppførsel**
Det skal gå ann å scrolle selv om man har reduced motion. Burde kanskje se etter flere faktorer enn kun transitionend? Har ikke klart for meg en veldig god løsning.

**Comment by lfbergee** [comment]
Kan nok løses med ideen fra #1067, ved at useAnimation hooken får et forhold til reduced motion?

**Comment by lfbergee** [comment]
@vegardsoerlie ta en titt på https://github.com/fremtind/jokul/pull/1139 , tror den skal løse problemet ditt.
