### ISSUE TITLE
Feil: Checkbox, DatePicker, NativeSelect, Select, TextArea, TextInput krever polyfill av native Nodejs moduler

### ISSUE THREAD

**Issue by Saegrov** [fremtind/jokul#1133]
**Feilbeskrivelse**
Checkbox, DatePicker, NativeSelect, Select, TextArea, TextInput har `nanoid` som dependency som igjen har en dependency på `crypto` som er en native Nodejs modul.

Hvis du prøver å bruke en av disse Componentene så må man polyfille `crypto`-module. For webpack 4 var ikke dette et problem for Webpack 4 la automatisk inn polyfill for native Nodejs-moduler.

Dette blir endret i Webpack 5 og man må eventuelt konfigurere dette manuelt.

Hvis man bruker Webpack 5 så får man følgende error:
```
Module not found: Error: Can't resolve 'crypto' in 'node_modules/@fremtind/jkl-text-input-react/build/browser'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need these module and configure a polyfill for it.
```

**For å reprodusere**
Bruk en av Checkbox, DatePicker, NativeSelect, Select, TextArea, TextInput med Webpack 5 som bundler.

**Forventet oppførsel**
At man kan bruke en react-komponent uten å måtte polyfille Nodejs-moduler.

**Mer info**
Foreslår å bytte tilbake til `uuid` i stedet for `nanoid`. Opprinnelig så ble det byttet fra `uuid` til `nanoid` i #186 på bakgrunn av at `nanoid` er en mindre pakke. Når man tar med NodeJs polyfills er jeg usikker på om det fortsatt stemmer.
Hvis man bruker `uuid` med kun import av `v4`-funksjonen så er pakken på 559B (https://bundlephobia.com/result?p=uuid@8.2.0) mens `nanoid` kommer inn på 494B (https://bundlephobia.com/result?p=nanoid@3.1.10).

**Comment by lfbergee** [comment]
Det er uansett snakk om veldig få bytes i fordel nanoid, så jeg ser ingen spesielt gode argument for å beholde om det blir trøblete med webpack 5.
