### ISSUE TITLE
Tekstlenke: Oppdatere design

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#1167]
Tekstlenkene har et småbrutalt uttrykk i forhold til øvrige komponenter med en massiv bakgrunn og tekstfarge som inverterer med et blink på hover. Har begynt å skissere på en facelift for både light og dark mode der uttrykket er lettere og lenken blir blå på hover i tråd med øvrige oppdaterte komponenter.

Light:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=15564%3A121

Dark:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=15568%3A39

Film av prototyper:
Light: https://vimeo.com/444464827/4bfcb4cd6b
Dark: https://vimeo.com/444464815/5ed35d924e

Kommenter og kom gjerne med innspill 😁

**Comment by Mikkelinski** [comment]
Fan av å oppdatere og å få inn blåfarge som vi har gjort flere steder for interaktive elementer - tror også at fokus outlinen som du har valgt her er enklere å tolke for flere brukere enn full bakgrunn som vi har i dag.

**Comment by Steinop** [comment]
Komponenter for Interne og eksterne lenker i light/dark og normal/kompakt er nå lagt inn i Figmabiblioteket og klare for utvikling.

I Unvisited og Visited state er teksten sort (i light mode) med 1 px strek under. På Hover og Focus blir teksten og strek blå og utvides nedover til 2 px. Ved trykk (Active) er tekst og strek fortsatt blå men streken går tilbake til 1 px tykkelse. 

Pga tekniske begrensninger i AutoLayout er komponentene 1px høyere enn fontens linjehøyde. Bruk fontens linjehøyde ved utvikling. 

Body size: https://www.figma.com/file/Wh8Gfnesn25shH31sKyIaT/J%C3%B8kul-bibliotek?node-id=4969%3A7419
Compact body: https://www.figma.com/file/Wh8Gfnesn25shH31sKyIaT/J%C3%B8kul-bibliotek?node-id=4973%3A700

Prototype: https://www.figma.com/proto/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=15634%3A2&viewport=489%2C-3546%2C0.37281426787376404&scaling=min-zoom
