### ISSUE TITLE
Feil: Hovedmenyen i portalen er ikke power-user friendly grunnet dobbel render

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#1174]
**Feilbeskrivelse**
Når jeg går inn på portalen er det første jeg trykker på "Komponenter" på navigasjonslinjen, siden det nesten alltid er dit jeg vil. Når siden i bakgrunnen scroller ned til bildet (med flotte modeller 😉) så renderer menyen på nytt rett før jeg rekker å trykke på komponenten jeg vil inn på, som gjør at jeg må vente litt ekstra. Dette er veldig pirkete, men blir gradvis mer og mer irriterende.

PS: En veldig rask power-user vil rekke det før re-render, så kanskje det egentlig bare trener oss til å være mer effektive.

**For å reprodusere**
Fortell oss hvordan vi kan gjenskape feilen (det hjelper oss med å fikse den):

1. Gå til https://fremtind.github.io/jokul/ 
2. Klikk umiddelbart på "komponenter" på navigasjonslinjen
3. Prøv å velg feks "Select" komponenten. Man rekker det ikke før menyvalgene blir re-rendered.

**Forventet oppførsel**
Menyen burde ikke bli re-rendered.

**Mer info**
macOS Catalina - chrome

**Comment by piofinn** [comment]
Helt klart en bug! Tror det er jeg som introduserte det med den nye menyen 🤔 Holder på med en liten optimalisering av statehåndtering i menyen nå, så kan godt ta en titt på dette også!

**Comment by Steinop** [comment]
Oppdaget at menyen re-rendres ved scroll. 
Fint om vi også får korrigert animasjonen slik at tekstene animeres sekvensielt inn i masken nedenfra og opp, slik vi snakket om @piofinn 😅

**Comment by piofinn** [comment]
> Oppdaget at menyen re-rendres ved scroll.

Samme bug 😉 Skal se på animasjonen også!
