### ISSUE TITLE
Navigasjonslenke / Navlink (tidligere "pil-knapp")

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#1185]
I portalen bruker vi piler intensivt i menyer og cards.
Komponenten er også nyttig i tilfeller der en vanlig lenke blir for utydelig og en knapp blir for mye.

Pilen bør følge fontstørrelsen der den er knyttet sammen med en tekst. 

I cards kan pilen brukes stort som et signalelement som fremhever interaksjonen i kortet. Pilen bør også her skifte til blå på hover.

**Comment by Steinop** [comment]
Har jobbet videre med pilknappen.
Ser for meg tre ulike scenarier hvor pilen er aktuell å bruke:

1. I menyer (type: Venstremenyer og megamenyer)
2. Som lenker videre til annet innhold (type: Les mer)
3. Som selvstendig pil i et større navigerbart element (type: Cards)

På alle de nye komponentene har vi gjennomgående blå farge på hover og focus.
Dette bør vi innføre som et prinsipp i menyer - og også i toppmenyen/headeren på Jøkul.

Dvs at området som er valgt kun bør være med bold skrift og med sort farge (ref. tilbakemelding fra @CamillaDahlstroem). Aktivt område vil ikke ha en hovereffekt.
På klikk / når knappen trykkes går trekker pila seg inn og ekspanderer ut og tilbake for å understreke at et valgt område aktiveres.

1. Se prototype for meny: https://www.figma.com/proto/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=15727%3A48613&viewport=659%2C-3277%2C1.0883880853652954&scaling=min-zoom

2. Pil-knapp som lenke: https://www.figma.com/proto/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=15727%3A48779&viewport=885%2C228%2C0.24364396929740906&scaling=min-zoom

3. Pil i cards (ref: forsiden på Jøkul): https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=15727%3A48794

Tar gjerne i mot tilbakemeldinger og innspill til denne komponenten 😁
(Mulig disse er tre forskjellige komponenter basert på samme prinsipp?)

**Comment by piofinn** [comment]
> Dvs at området som er valgt kun bør være med bold skrift og med sort farge

Enig at blåfargen bør forbeholdes aktive states. Tror imidlertid det kan være fornuftig å beholde streken i portalmenyen for å vise aktiv seksjon. Det blir veldig anonymt uten:
<img width="923" alt="Skjermbilde 2020-08-10 kl  14 13 51" src="https://user-images.githubusercontent.com/25739615/89781531-ce496700-db13-11ea-9d8d-64b4e5bd8533.png">

vs.

<img width="927" alt="Skjermbilde 2020-08-10 kl  14 13 58" src="https://user-images.githubusercontent.com/25739615/89781541-d30e1b00-db13-11ea-95a7-1230378ba789.png">


> Aktivt område vil ikke ha en hovereffekt.

I så fall bør det heller ikke være klikkbart, imo. Menyen i portalen i dag er et godt eksempel på at det er irriterende å ikke ha hovereffekt på noe klikkbart 😅 Tror nok i så måte jeg foretrekker å faktisk ha en hoverreffekt på aktivt område, selv om det bare er forandring i farge, og selvfølgelig bare hvis det faktisk _er_ klikkbart.

> På klikk / når knappen trykkes går trekker pila seg inn og ekspanderer ut og tilbake for å understreke at et valgt område aktiveres.

Her må vi være obs på at det ikke er sikkert at animasjonen ved klikk (etterr man har sluppet knappen) vil bli spilt ferdig. Hvis dette er en lenke er det jo stor sannsynlighet for at det lastes inn en ny side, og at lenken kanskje tilogmed forsvinner helt. Jeg er heller ikke helt sikker på om dette lar seg gjennomføre i CSS i det hele tatt 😕

Angående tre vs. en komponent tror jeg faktisk jeg vil si det er én og en halv 😝 De to første tenker jeg er den samme komponenten (en lenke til bruk i menyer/navigasjon), og så er det pila i kortet, som da strengt tatt er en del av en annen komponent (kortet).

**Comment by AudunBerdal** [comment]
Synes forslagene ser bra ut :) Eneste kommentaren min er at jeg ikke liker når teksten "gror" mot høyre på bold. Litt vanskelig å forklare, så jeg har funnet et eksempel: [https://codepen.io/hexagoncircle/pen/WNrYPLo]. Her kaller det det "layout shift". Skal flere knapper stå ved siden av hverandre horisontalt kan det føre til at de andre knappene flytter på seg når en av de blir bold. Ser også at det samme skjer i toppmenyen på Jøkul-portalen.

**Comment by Steinop** [comment]
Enig @AudunBerdal. Er heller ikke happy med layout shift som forårsakes av at tekstblokken blir bredere pga bold. Hadde vi hatt en moderne variable font ville vi fortsatt hatt samme utfordring med bredden men overgangen ville oppleves som mye smoothere. Man kan evt prøve å få til noe med kerningen men det ser ikke så bra ut med minuskler sperret  for hardt ut heller. Pseudo-elementet så ut som en bra fix - er den lett å implementere @piofinn ?

**Comment by Steinop** [comment]
@piofinn:
Hovedmeny: Mente ikke å fjerne understreken i hovedmenyen - den er med på å tydeliggjøre. Kun endring til sorl på aktivt område og blå på hover/klikk
Aktivt område uten hovereffekt: Hvis det kan klikkes på kjører vi hovereffekt - ellers ikke. Eller tenker du at et område skal kunne refreshes og dermed bør fremstå som klikkbart?
Animasjon etter klikk: Denne bør vi nok diskutere nærmere ja. Årsaken til at den ligger der er for å tydeliggjøre at denne er valgt. Hvis man er i megameny og åpner et område er den ikke viktig men i en venstremeny vil den se smoothere ut - hvis det lar seg gjøre 😅

**Comment by piofinn** [comment]
@AudunBerdal og @Steinop Vi hadde tidligere en slags mixin for å bekjempe problemet med fet tekst på hover, men man vil aldri kunne finne noe som fungerer helt perfekt. Problemet er at jo lenger teksten er, jo mer vil bredden øke når den blir fet. I løsningen vi hadde knep vi sperringen bittelitt ved hover, slik at endringen i bredde ble minimal. Avhengig av lengde på teksten, og hvilke tegn som var brukt, kunne det imidlertid fortsatt bli litt endring (noen tekster ble tilog med litt kortere).

Jeg kan teste litt og se om jeg får til noe som fungerer tålelig bra 😊

Angående hovereffekt, så tenker jeg at en lenke alltid bør være klikkbar selv om man allerede er der den fører, og at denne komponenten derfor alltid bør ha blå hovereffekt. Vi kan uansett ikke lage en _generell_ komponent som vet om den befinner seg på siden den lenker til og i så fall gjøre den inaktiv. Uttover menyer som sidemenyen i portalen bør den vel uansett ikke brukes med mindre den går til en ny side 😊

**Comment by Steinop** [comment]
Enig @piofinn. Da sier vi det sånn: Alltid blå hover på en lenke - selv om man er på siden den lenker til 😁

**Comment by Steinop** [comment]
Oppsummering/beslutning etter diskusjon på Teams:
For å bedre lesbarhet i små font-størrelser legger vi inn en fixed 2 px space mellom tekst og pil. På den måten vil man få mer luft på de minste størrelsene mens for de største fontstørrelsen vil man fortsatt få et mer "modig" designuttrykk der pila ser ut til å stå uten mellomrom mot teksten.

På Hover og Focus i andre fontstørrelser vil mellomrommet mellom pil og knapp være proposjonal med fontstørrelsen. Referanse er 8 px space mellom pil og tekst i body size ved hover og focus.

**Comment by Steinop** [comment]
Figmakomponenter ligger klare i biblioteket og kan oppdateres i kode - ref kommentaren over.

Dark og lightversjoner
https://www.figma.com/file/Wh8Gfnesn25shH31sKyIaT/J%C3%B8kul-bibliotek?node-id=5055%3A7549

Kompaktversjon i dark og light:
https://www.figma.com/file/Wh8Gfnesn25shH31sKyIaT/J%C3%B8kul-bibliotek?node-id=5055%3A7595

"Chosen state" vil kun være nødvendig ifm menyer. Når man navigerer fra en side til en annen er det kun default state, hover, focus og "while pressing" som vil være synlige.
