### ISSUE TITLE
Portal: Lista senaste Blog posts

### ISSUE THREAD

**Issue by eduardodir** [fremtind/jokul#1198]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [ ] Undersøke
- [ ] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Man ser inte direkt om det är någon ny Blogpost

**Beskriv løsningen du ønsker**
Hade varit bra och lyfta fram senaste 3 blogpost på första siden i Jøkul

**Hvilke alternativer har du vurdert?**
Låta det vara som det är.

**Mer info**

**Comment by lfbergee** [comment]
Er funksjon for å vise siste post på forsiden. Men er litt lite synlig. 

![image](https://user-images.githubusercontent.com/46530368/89892636-4331a500-dbd7-11ea-82d5-451ee298e681.png)

```
const data = useStaticQuery(graphql`
        {
            allSitePage(
                sort: { order: DESC, fields: context___frontmatter___publishDate }
                filter: { path: { regex: "/^/blog/" } }
                limit: 3
            ) {
                edges {
                    node {
                        path
                        context {
                            frontmatter {
                                title
                                description
                            }
                        }
                    }
                }
            }
        }
    `);

    const latestBlogPosts = data?.allSitePage?.edges;
```

Og så gjør noe pent design med det arrayet :+1:

**Comment by wkillerud** [comment]
Siden skjermbildet over ble tatt har forsiden fått en fjerde hovedlenke i Universell utforming. Jeg vil nødig erstatte en av dem med en inngang til bloggen, jeg mener dokumentasjonen er viktigere å fremheve.

Det høres ut som om behovet er å oppdage at det har kommet noe nytt. Jeg tenker det heller kan dekkes med en RSS-feed (#2187) eller å kunne bokmerke bloggsiden direkte (#2188).

Lukker denne issuen, men det er lov å være uenig og ta opp diskusjonen igjen 😄
