### ISSUE TITLE
Accordion - Forslag til små endringer for å bedre opplevelsen på mobil

### ISSUE THREAD

**Issue by mariusthedesigner** [fremtind/jokul#1213]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- Undersøke
- Rapportere

**Er ønsket tilknyttet et problem? Fortell oss mer!**
På mobil blir det liten plass til tekst og det er vanskelig å skille overskrift fra innhold.

**Beskriv løsningen du ønsker**
Forslag til løsning er å la teksten starte helt i fra venstre i modulen på mobil, men dette må ikke gjelde desktop. Når det gjelder overskrift foreslår jeg i første omgang å la overskriften forbli blå når den er åpnet.

Prototype: https://www.figma.com/proto/tkp8rxi7PlO6hiPnxHZ72L/Konsepter-skisser-og-design-Marius?node-id=2618%3A167&viewport=-1225%2C-857%2C0.8573340773582458&scaling=scale-down
 
<img width="427" alt="Skjermbilde 2020-08-13 kl  09 01 45" src="https://user-images.githubusercontent.com/59652564/90104506-aee55080-dd44-11ea-8f85-edd2ebe9c0e0.png">

**Hvilke alternativer har du vurdert?**
Jeg har også vurdert å øke overskrift til enten Bold eller ved å bruke «Lead». Begge interessante veier med hver sin stil.

**Comment by piofinn** [comment]
Bra innspill!

Jeg tror at fet skrift er riktigere som indikasjon på åpen state enn blå farge, siden vi nå beveger oss mot å kun bruke blå på aktive elementer (lenker etc. ved hover/fokus).

**Comment by piofinn** [comment]
Her er en kjapp test med fet skrift ved åpen state, og uten marginer på mobil. Utover at vi må fikse plasseringen av pila ved lange titler synes jeg dette ser ganske ålreit ut!

![accordion-desktop](https://user-images.githubusercontent.com/25739615/90257065-f227e800-de46-11ea-83c9-cafed461fa9e.gif)
![accordion-mobile](https://user-images.githubusercontent.com/25739615/90257082-f6ec9c00-de46-11ea-9a13-496ddcd33aea.gif)

**Comment by Steinop** [comment]
Enig med @piofinn vedr. bold. Det fungerer fint og tydeliggjør at et ledd i accordionet er åpnet. Fungerer det for andre? 
I så fall gjør jeg en endring i Figmabiblioteket. @piofinn: Hva er kerningen i bold versjon? Spør fordi jeg ser at tekstlinjen vokser mindre enn forventet i horisontal retning 😁

**Comment by piofinn** [comment]
@Steinop I eksempelet bruker jeg denne flotte lille saken:
```scss
@mixin no-grow-bold {
    font-weight: $bold-weight;
    letter-spacing: -0.014em;
}
```
Vet ikke hvilke enheter som brukes i Figma, men du får alternativt prøve deg frem 😅 Er samme teknikk som brukes i hovedmenyen og navigasjonslenker i aktiv versjon.

**Comment by Steinop** [comment]
Veldig bra @piofinn . Oppdaterer ikonbiblioteket med bold pil også slik @mariusthedesigner har gjort i Smartbil - det er en naturlig konsekvens av bold tekst.

**Comment by wkillerud** [comment]
Virker for meg som om komponenten alt er oppdatert med ønsket oppførsel (bold tekst når åpen, mer venstrejustert).
