### ISSUE TITLE
Gjør @nrk/core-components til eksterne avhengigheter

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#1215]
Siden vi nå midlertidig patcher funksjonaliteten i `@nrk/core-components` må disse igjen inlines i koden vår. De er derfor ikke lenger markert som `external` i `rollup.config.js` (kommentert ut).

Når `@nrk/core-components` får aktive maintainers igjen, eller vi velger å forke, bør vi "avkommentere" dem i rollup-configen for å generere lettere pakker igjen.

### Steg for tilbakeføring

- [ ] Markere nrk/core-components som external i rollup.config.js
- [ ] Slette patcher i /patches
- [ ] Slette `transformIgnorePatterns` i jest.core.js
- [ ] Flytte tilbake core-toggle/core-datepicker fra devDependency til dependency i pakkene de brukes

**Comment by wkillerud** [comment]
@piofinn, tar gjerne en prat med deg om de gjenstående patchene vi gjør lokalt og om det er noe som er realistisk å få landet upstream. `@nrk/core-components` har fått en maintainer, så tenker vi bør gjøre det vi kan for å gå den veien heller enn å forke.

**Comment by wkillerud** [comment]
I #2436 diskuterte vi oss fram til å på sikt droppe `@nrk/core-datepicker` til fordel for noe eget, gitt interaksjonsutfordringene vi ser og størrelsen på patchen vi allerede gjør.
