### ISSUE TITLE
Ta i bruk Ikon-pakke

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1229]
Ikon pakke er blitt introdusert, men ikke tatt ibruk i komponentene i Jøkul

Pakker som trenger oppdatering
- [ ] Hamburger
- [ ] Accordion
- [ ] Select
- [ ] Icon-button
- [ ] Alert message
- [ ] Message box
- [ ] Datepicker

**Comment by lfbergee** [comment]
Legg til ikon-pakka som dependency, muligens også stilpakka hvis det de animerte utgavene taes i bruk.

**Comment by onordbo** [comment]
Inaktiv.
