### ISSUE TITLE
Ta i bruk minifiserte filer, konsolidere output fra bygg

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1243]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [ ] Undersøke
- [ ] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
I dag bygger vi commonjs, 2x esm og 2x esm minifisert.

Foreslår vi dropper commonjs, dropper "browser" og tar ibruk minifisert "module".

**Comment by wkillerud** [comment]
@piofinn, ser PR #1255 ble avbrutt. Er dette med å slutte å tilby `browser` og `main` fortsatt noe vi tenker gjøre, eller beholder vi dem? Jeg har ingen sterke meninger om temaet, men lukker gjerne issuet om det ikke er tenkt å gjøre noe med.

**Comment by wkillerud** [comment]
Gjenåpner denne siden den kan skrelle av ti sekunder på bygget. Hvis dette er noe vi kan gjøre i forbindelse med dropping av IE-støtte er jeg _all for it_.

**Comment by wkillerud** [comment]
Trenger vi egentlig produsere ferdig minifisert JavaScript? Det koster oss CPU-tid i alle bygg for alle pakker.

Jeg kan kjøpe argumentet for CSSen, men vi legger ikke akkurat opp til direkte import av minifisert JavaScript i nettleseren, spesielt ikke om vi dropper `browser`-entry i `package.json`.

**Comment by wkillerud** [comment]
Økosystemet rundt native ESModules er visst ikke helt på plass ennå, blant annet Jest. Er visst utfordrende å samarbeide med "upstream" for flere prosjekter.
