### ISSUE TITLE
Organismer / Designtemplates 

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#1244]
Designerne har behov for ulike maler for eksempelvis headere, footere, tabeller, skjemaer etc slik at man sparer tid på å skissere ut nye løsninger. Det ligger allerede store muligheter i Figma ved bruk at AutoLayout for stabling av innhold.

Her må vi finne ut hvilke organismer/templates som er mest aktuelle å lage.

**Comment by Steinop** [comment]
Hvor legger vi designtemplates / organismer i Figma og i portalen? 
Skal de ligge under komponentene eller som et eget område, subnivå, etc?
Fungerer instances av en "templatekomponent" med Autolayout i Figma eller må vi legge disse tilgjengelige som frames på en egen page slik at de kan copy/pastes ved behov?

**Comment by Slaine2** [comment]
Jeg og Mona har allerede tenkt på det ... kanskje vi kan bygge en struktur med Atomer, Molekyler, Organismer og Templates i Figma? Instances av templatekomponent med autolayout jeg tror we må prøve...

**Comment by lfbergee** [comment]
Trenger vi full Atomic design? Kan vi ikke starte med "components" og "compound components" ( gjerne bedre navn) i første omgang? Så når bibliotektet vokser og det dukker opp behov for flere abtraksjonsnivå, først da legger vi til flere.

**Comment by Slaine2** [comment]
Jada, jeg synes det er en god løsning. Men vi må huske at biblioteket vil vokse. Det er derfor viktig å bygge en struktur som kan utvides.

**Comment by lfbergee** [comment]
Jepp, viktig å ikke gjøre dumme ting nå, som vi må betale for senere. Men er også veldig for at vi ikke overenigeerer og løser problemer som ikke kommer før om lenge.

**Comment by Steinop** [comment]
Enig med begge her - fint å ha en struktur på dette slik at vi vet hvor vi finner ting. 

I en del artikler jeg har lest om atomic design får jeg inntrykk av at noen har jobbet ut et ferdig designsystem med organismer, templates og oppførsel og så dissekert dette helt ned til atomnivå. Det er vanskelig å lage atomer uten at de tenkt brukt som en helhet/template/organisme og omvendt. Tanken er god men min erfaring er at hvis man gjør en større endring i en komponent er det ikke sikkert at atomene man bruker i komponenten lenger passer inn - så det spørs hvor lang ned i detaljene vi definerer et atom. Er atomene rammen, streken, bakgrunnen, ikonet i en knapp eller er det selve knappen?
Komponenter og templates trenger vi definitivt.
