### ISSUE TITLE
Autoprefixed css

### ISSUE THREAD

**Issue by Saegrov** [fremtind/jokul#125]
Out javascript uses babel-env with spesific browser support.
Our css output should do the same - preferrably using the same [browserlist](https://github.com/browserslist/browserslist) as the scripts to keep a single source of truth for supported browsers.

**Comment by piofinn** [comment]
We also have to look at our current browserlist config. Per now it _only_ picks out Chrome and IE11, which probably is fine for babel, but will break autoprefixing.

**Comment by lfbergee** [comment]
Solved in #34
