### ISSUE TITLE
Feil: Understrek på Link forsvinner

### ISSUE THREAD

**Issue by CamillaDahlstroem** [fremtind/jokul#1270]
**Feilbeskrivelse**
Jeg oppdaget en liten bug på link-komponenten i portalen: Når man inverterer fargene, så "forsvinner" understreken helt til man hovrer over linken. 🤷‍♀️

**For å reprodusere**

1. Bruk Chrome, og gå til https://jokul.fremtind.no/komponenter/link
2. Klikk på 'Invertert'-checkboksen til Link-komponenten.
3. Understreken forsvinner! Men synes igjen om man hovrer over den. Gjelder både for vanlig og ekstern link.

**Forventet oppførsel**
At streken alltid synes. ;) 

**Skjermbilder**
Her er skjermopptak av feilen:
[Skjermopptak 2020-08-25 kl. 14.13.00.zip](https://github.com/fremtind/jokul/files/5123894/Skjermopptak.2020-08-25.kl.14.13.00.zip)

**Mer info**
Jeg bruker Chrome og Mac. I Firefox oppfører komponenten seg som den skal.

**Comment by wkillerud** [comment]
Hei! Jeg rydder litt i gamle issues.

Det ser ut som dette bare skjer i Chrome dersom lenken går fra å være ikke-invertert til invertert. Da forsvinner understreken fram til den hovres over, men etter det er den tilsynelatende der den skal være. Jeg testet å sette lenka i eksemplet til å være invertert til å begynne med, og da vises understreken som den skal med én gang.

Jeg kan ta feil, men mistenker at det bare er i portalen og eksempelet vi har lenker som går fra ikke-invertert til invertert i løpet av sidens "levetid" sånn at dette egentlig ikke er noe problem. Nå er vel også `inverted`-propertyen frarådet til fordel for `data-theme` (https://jokul.fremtind.no/blog/auto-dark-mode/). Tenker derfor vi lukker denne bugen. Vi kan ta opp igjen tråden om det viser seg å fremdeles være et problem.
