### ISSUE TITLE
Feil: feil navn på ikonene på ikonsiden i portalen

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#1299]
**Feilbeskrivelse**
I eksempelet på siden om ikoner i portalen har alle ikonene feil navn. Navnet blir generert fra navnet på React-komponenten (funksjonsnavn), og det blir minifisert ved produksjon til enkeltbokstaver.

**For å reprodusere**
gå til https://jokul.fremtind.no/komponenter/icons

**Forventet oppførsel**
Riktig navn bør vises. Foreslår å legge inn `displayName` eksplisitt i selve komponentene i ikonpakken og bruke `<komponent>.displayName` i stedet for `<komponent>.name` i eksemplet.

**Skjermbilder**
<img width="512" alt="Skjermbilde 2020-09-03 kl  15 35 37" src="https://user-images.githubusercontent.com/25739615/92121964-2e71b700-edfb-11ea-9678-b52fad85496c.png">

**Comment by lfbergee** [comment]
Effektivt da, men ja, displayName burde vært brukt ja.
