### ISSUE TITLE
Legge til 'ref' til button komponent

### ISSUE THREAD

**Issue by SercanSercan** [fremtind/jokul#1362]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Jeg ønsker å implementere en løsning (på SeOpp) som krever bruk av ref på PrimaryButton.

**Beskriv løsningen du ønsker**
Button må akseptere min ref verdi som en prop.

**Comment by lfbergee** [comment]
Antar det er forwardRef du er ute etter på komponenten. Burde være en grei oppgave. Bare husk at dette er en breaking change (selvom det de aller aller fleste ikke trenger å gjøre noe )

```
Note for component library maintainers

When you start using forwardRef in a component library, you should treat it as a breaking change and release a new major version of your library. This is because your library likely has an observably different behavior (such as what refs get assigned to, and what types are exported), and this can break apps and other libraries that depend on the old behavior.
```
https://reactjs.org/docs/forwarding-refs.html
