### ISSUE TITLE
Refactor `core` package

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#139]
## Main issues

Currently, the `core` package is a mess, and is in great need of a refactor. I've outlined some main issues:

- [x] The file structure does not make sense. Things are not where you would think
- [x] We output several empty `.css`-files on build
- [x] Several rules are written multiple times in the final `core.css` file

## Suggestions

Here are some suggested steps to alleviate these issues:

- [x] Move to a flat structure (as already discussed) for _some of_ the files. Specifically, move all files that will have content when parsed on build, to root level
- [x] Let all "pure `scss`" files reside in folders and not get built. This would be most files in the `variables` folder, along with mixins and functions
- [x] Clean up the `@import` chain in all files to remove duplicate code exports
- [ ] Export custom properties for the variables

**Comment by lfbergee** [comment]
Shouldn't the colors file also output the colors as custom-properties? --color-hotmountaingray?

**Comment by lfbergee** [comment]
the position mixin should probably have its api flipped, so values are default initial, and must intentainally be overriden. Now its the other way around.

I would also like a @include flex() mixin.

**Comment by lfbergee** [comment]
Split  Export custom properties for the variables into its own issue
