### ISSUE TITLE
Tilpasse Autosuggest-designet til compact og dark mode

### ISSUE THREAD

**Issue by CamillaDahlstroem** [fremtind/jokul#1417]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [x] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Vi ønsker å bruke Autosuggest i Flyt. Problemet er at komponenten a) ikke er compact, og b) ser rar ut i dark mode/invertert. Her ser dere skjermbilder jeg har tatt av komponenten når jeg har skrudd på dark mode og/eller invertering i Jøkul:
<img width="894" alt="Skjermbilde 2020-10-01 kl  12 25 37" src="https://user-images.githubusercontent.com/11536996/94799595-a83d9600-03e3-11eb-855b-6a0e5dfe5eb9.png">
<img width="888" alt="Skjermbilde 2020-10-01 kl  12 52 18" src="https://user-images.githubusercontent.com/11536996/94800499-f56e3780-03e4-11eb-9014-1068a2499f96.png">

**Beskriv løsningen du ønsker**
Jeg ønsker at designet på komponenten skal stemme bedre overens med de andre skjemafeltene.

**Hvilke alternativer har du vurdert?**
Jeg har skisset et forslag til design som ser slik ut:
<img width="719" alt="Skjermbilde 2020-10-01 kl  12 39 35" src="https://user-images.githubusercontent.com/11536996/94799479-788e8e00-03e3-11eb-9e86-3288edf229c8.png">
Basically er det likt som en select, bare uten pilene. Hvis dere tenker det er greit nok, så kan vi (aka Simen) se om vi får til å implementere endringene. Hva tenker dere?

**Comment by Steinop** [comment]
@CamillaDahlstroem: Synes det er en logisk løsning å følge prinsippene for Select-komponenten men uten pilene i inputfeltet. Kan evt beholde pila i listen idet man velger. Tommelopp 😁

**Comment by piofinn** [comment]
@CamillaDahlstroem siden denne er litt eksperimentell, og baserer seg på en "themeable" tredjepartskomponent, er det ikke sikkert denne vil kunne gjøres helt etter boka designmessig (dessverre). Tipper likevel man kan komme nærmere noe riktig enn slik det er nå. Men her bør det egentlig legges inn en mer langsiktig løsning i form av en komponent vi bygger selv.

Hvis du vil se på det med Simen får dere nesten vurdere om dere vil gå for en enkel fiks, eller om dere har tid til å ta tak i en omskriving 😊 Begge deler tas imot med takk i hvert fall!

**Comment by lotorvik** [comment]
Hva er status på denne saken @CamillaDahlstroem?

**Comment by wkillerud** [comment]
Fikser dark mode som en del av #2631
