### ISSUE TITLE
Megameny: Fjerne animasjon på varde-bakgrunn når man velger et annet område

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#1425]
Når man klikker i på nytt område i hovedmenyen animeres bakgrunnen i megamenyen litt opp. Blinket skjer brått og trekker fokus ned til "hvitblinket" istedenfor å gi fokus på selve innholdsbyttet. Vi kan med fordel fjerne denne animasjonen for å gi en mykere overgang.

**Comment by Steinop** [comment]
Her er en GIF men dårlig frame rate som viser issuet:
![Megameny_2_1](https://user-images.githubusercontent.com/51952891/94903631-60c61100-049a-11eb-8cd6-33a262b774d6.gif)

**Comment by wkillerud** [comment]
Denne viste seg være vanskeligere å rette enn ved første øyekast. Kort fortalt ligger problemet i måten menyen er kodet til å ha hver sin fullskjermsmeny per område i stedet for en overordnet som har ansvaret for varde-bakgrunnen. Da får vi den effekten fordi vi animerer inn en ny meny per klikk. Det lar seg løse, men tar nok litt tid før vi er i mål.
