### ISSUE TITLE
Fremtind stempler

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#1432]
Det er et ønske om mer aktiv bruk av de runde Fremtind-stemplene  i ulike steder - blant annet i distributørsammenheng. Disse bør derfor inn i komponentbiblioteket på lik linje med logo og logosymbol.

Det originale logostempelet var ikke oppdatert med Fremtind Grotesk font men Heidi Stormoen har tegnet utkast til oppdatert variant. Vi bør samtidig vurdere om kerning i tekst skal finjusteres rent optisk eller om den er OK by default.
Opptatert stempel må godkjennes av markedsavdelingen.

**Comment by Steinop** [comment]
![Stempel_Fra SB1 og DNB](https://user-images.githubusercontent.com/51952891/95056515-26a47b80-06f5-11eb-866a-dc5d62b47294.png)


![Stempel_Levert av Fremtind](https://user-images.githubusercontent.com/51952891/95056521-27d5a880-06f5-11eb-9282-7ec5baaae2e6.png)


![Stempel-Innovasjon fra Fremtind](https://user-images.githubusercontent.com/51952891/95056523-27d5a880-06f5-11eb-8113-f897317394c7.png)


![Stempel-Teknologi fra Fremtind](https://user-images.githubusercontent.com/51952891/95056524-286e3f00-06f5-11eb-9c21-9e3151ddbaae.png)

**Comment by MonaHolm72** [comment]
[stempler.zip](https://github.com/fremtind/jokul/files/5450833/stempler.zip)

**Comment by MonaHolm72** [comment]
Stempler ferdig
