### ISSUE TITLE
Forbedring av fargedokumentasjonen, varde og gråtabeller

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1433]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [x] Avklare
- [x] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Øvrige farger er skrevet om til å hente fargen fra DOM elementet, varde og gråtabellen er fortsatt hardkoda verdier, så sjansen for feil der er vesentlig høyere. Spesielt ved endring av disse fargene. 

**Beskriv løsningen du ønsker**
All funksjonalitet burde kunne gjennbrukes.

**Comment by piofinn** [comment]
Tar denne siden det er mitt rot 😅
