### ISSUE TITLE
Dekningsvelger

### ISSUE THREAD

**Issue by idalower** [fremtind/jokul#145]
Lag design for dekningsvelger

**Comment by lfbergee** [comment]
I'm not a 100% convinced this should be in the design system. If so, it must be very flexible to handle quite a varied input. As the insurances are different, and has different structure from the backend.

Maybe we can supply the atoms, and its up to the clients to build it into something?

**Comment by piofinn** [comment]
I think atomic is the intention here, something like a checkmark/cross with text next to it
