### ISSUE TITLE
Feil: jkl-select kan ikke brukes inne i en @nrk/core-toggle

### ISSUE THREAD

**Issue by Saegrov** [fremtind/jokul#1466]
**Feilbeskrivelse**
Når man bruker `jkl-select` inne i en `@nrk/core-toggle` så vil åpning av `select`-nedtrekkslisten trigge åpning/lukking av `@nrk/core-toggle` som ligger utenfor

**For å reprodusere**
Bruk `@nrk/core-toggle` og legg en `jkl-select` inne i den.

**Forventet oppførsel**
`jkl-select` trigger ikke `@nrk/core-toggle` som ligger utenfor seg selv.

**Skjermbilder**
![Screen Recording 2020-10-12 at 13 43 53](https://user-images.githubusercontent.com/124469/95744788-38a59180-0c94-11eb-9100-a9343106d7c1.gif)

**Comment by wkillerud** [comment]
@Saegrov er dette med Select inni core-toggle fremdeles et problem? Jeg prøvde reprodusere det med et kjapt eksempel lokalt, men får ikke samme oppførsel. Togglen holder seg åpen ved interaksjon med Select.

**Comment by wkillerud** [comment]
Lukker denne inntil videre siden jeg ikke kunne gjenskape. Gjenåpne gjerne dersom det fremdeles er et problem.

**Comment by joms** [comment]
https://codesandbox.io/s/gallant-frog-x730t?file=/src/App.tsx Jeg tror du kan finne noe samme oppførselen her. Tror kanskje @kennidenni også har vært borti problemer med kombinasjonen av Select og Accordion.
