### ISSUE TITLE
Feil: Valideringspakken er inkonsekvent i naming, lenken til github fra portalen er feil

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1472]
**Feilbeskrivelse**
Pakken heter: `@fremtind/jkl-validators-util`
Mappa heter: `jokul/packages/validations-util/`

`validators !== validations`, noe bør renames, det har skap trøbbel for forfatteren også, lenka fra https://jokul.fremtind.no/komponenter/validators til github er feil

Enten rename pakka eller kanskje mer fornuftig, rename mappa og fiks dokumentasjon.

**Comment by piofinn** [comment]
> rename mappa og fiks dokumentasjon.

+1 👍
