### ISSUE TITLE
Compact/body har feil linjehøyde i Jøkul

### ISSUE THREAD

**Issue by Murstam** [fremtind/jokul#1479]
Har 24px linjehøyde i Jøkul, skal være 28px. Riktig i Figma.

**Comment by Murstam** [comment]
@joms Kan du hjelpe meg med denne? Burde gå fort?

**Comment by wkillerud** [comment]
Om jeg leser Jøkul bibliotek 2.0 riktig virker det som om 24px linjehøyde er det nye for Compact/Small, slik at vi ikke trenger gjøre noen endringer? Lukker issuet, så får dere gi lyd om det er feil 😄

**Comment by Murstam** [comment]
Det gjaldt compact/body, men den ble fikset med ny typografiskala :)
