### ISSUE TITLE
Compact message box mangler i Jøkul

### ISSUE THREAD

**Issue by Murstam** [fremtind/jokul#1480]
Finnes i Figma, trenger bare å utvikles.

**Comment by wkillerud** [comment]
Det ser ut som Compact message box-varianten kalles Mobile i Jøkul bibliotek 2.0.

Fra hva jeg kan se i portalen virker det som om dagens Message Box støtter de ulike visningene med responsivitet (så ikke med eksplisitte props). Det er kanskje dekkende nok?

**Comment by joms** [comment]
Dette er kanskje en større diskusjon, men jeg tenker at siden vi har muligheten til å bruke `forceCompact` på andre komponenter kan det være lurt å ha på MessageBox også. Tenker at det bør være et gjennomgående mønster å enten ha muligheten til å fremtvinge det, eller kun ha det gjennom responsivitet.

Jeg tror at feks. Flyt er storkonsumenter av `forceCompact` ettersom de har ganske mye innhold i løsningen sin.
