### ISSUE TITLE
Feil: Loader får feil farge i kombinasjon med Image

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1481]
**Feilbeskrivelse**
Image og loader bruker samme css-variabel, så loader får feil farge.

**For å reprodusere**
https://codesandbox.io/s/loaderbug-9nrwb

**Forventet oppførsel**
Image blir grå, loader svart

**Comment by piofinn** [comment]
Aha, det er der den kommer fra ja! Vi burde kanskje se litt nøyere på hvordan vi scoper CSS-variablene våre. Burde sikkert ha `jkl` foran dem også.
