### ISSUE TITLE
Call to action knapp

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1485]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Vi ønsker å differensiere knapper som faktisk gjennomfører kjøp annet enn å bruke PrimaryButton

**Beskriv løsningen du ønsker**
![image](https://user-images.githubusercontent.com/46530368/96258681-a87d8a00-0fbc-11eb-9680-254de08fa6a6.png)

**Hvilke alternativer har du vurdert?**
Kanskje grønn?

**Mer info**
Her kan du legge til mer kontekst, skjermbilder, eller andre ting du ikke synes passer inn over.

**Comment by piofinn** [comment]
+1 for grønn!

**Comment by lfbergee** [comment]
Jeg tenker å legge til støtte for begge, men plan om en AB-test for å lande på en. Noen som har noe imot den tilnærmingen?

**Comment by lfbergee** [comment]
Stenger denne frem til vi har en tydeligere ide på hva som faktisk skal inn i Jøkul. Blir gjennomført AB test på et eller annet tidspunkt i en av klientene.
