### ISSUE TITLE
Utvide Card så den kan brukes i dekningsvelger

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1486]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Card er ikke helt noen ting i dag, kunne vært nyttig i dekningsvelgeren. Innholdet bør styres av klient.

**Beskriv løsningen du ønsker**
![image](https://user-images.githubusercontent.com/46530368/96265986-69543680-0fc6-11eb-9b34-c1611dd31d90.png)

**Hvilke alternativer har du vurdert?**

**Mer info**

**Comment by joms** [comment]
Vi bruker lignende kort i tilgangsoversikten på BM. Det hadde helt klart vært nyttig med noe felles her. https://www.figma.com/file/qiswfjn90aZomZArlAvHMN/Tilganger?node-id=482%3A1
