### ISSUE TITLE
Feil: Inverted/Darkmode fungerer ikke på Select hvis man kun bruker "inverted"-propen

### ISSUE THREAD

**Issue by Saegrov** [fremtind/jokul#1488]
**Feilbeskrivelse**
Select har en prop `inverted`. Hvis man setter den til `true` så skulle komponenten vært den svarte varianten selv om man ikke har satt `data-theme="dark"` noe sted. Slik den er nå så forblir den hvit.

**For å reprodusere**
Fortell oss hvordan vi kan gjenskape feilen (det hjelper oss med å fikse den):

1. Gå til Select Jøkul-portalen
2. Huk av "Inverted" i komboboksen
3. Se resultatet

**Forventet oppførsel**
Hvis man bruker `inverted`-propen så skal komponenten bli svart uavhengig av globalt theme.

**Skjermbilder**
![Screenshot 2020-10-16 at 16 08 44](https://user-images.githubusercontent.com/124469/96269192-56436580-0fca-11eb-8842-7e417f0a87c7.png)
![Screenshot 2020-10-16 at 16 08 48](https://user-images.githubusercontent.com/124469/96269196-56dbfc00-0fca-11eb-90d5-bd1df76e4a68.png)

**Comment by wkillerud** [comment]
`inverted`-propen er markert som deprecated etter #2018. Får du den nye metoden Pio beskriver i pull requesten med `.jkl` og `data-theme="dark"` til å fungere @Saegrov? I så fall tenker jeg vi lukker denne som "won't fix" siden bruk av propen er frarådet.
