### ISSUE TITLE
Feedback komponent

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1490]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Vi vil ha tilbakemelding fra brukerne våre om de finner det de leter etter eller om de har andre kommentarer til oss.

Sannsynligvis finnes det flere ulike behov, som kanskje springer ut ulike komponenter av. Vi ønsker oss en enkel tommel opp eller ned/ smilefjes variant, som blir til tekstfelt hvor brukeren kan skrive inn mer info.

Design er på ingen måte klar.

**Beskriv løsningen du ønsker**
![image](https://user-images.githubusercontent.com/46530368/96270104-80495780-0fcb-11eb-9399-330b94c8b4e9.png)

**Hvilke alternativer har du vurdert?**

**Mer info**

**Comment by joms** [comment]
Anbefaler å snakke med Kathrine Tangård som jobber med dette for BM.

**Comment by vegardsoerlie** [comment]
Dette bruker vi i SeOpp også. Screenshots vedlagt.

<img width="862" alt="Skjermbilde 2020-10-19 kl  09 13 11" src="https://user-images.githubusercontent.com/14551408/96413060-5d958980-11eb-11eb-85d3-944599b97240.png">
Etter en er valgt:
<img width="934" alt="Skjermbilde 2020-10-19 kl  09 13 19" src="https://user-images.githubusercontent.com/14551408/96413065-5f5f4d00-11eb-11eb-9e8a-247c8c6730b9.png">

**Comment by lfbergee** [comment]
Syns ikke det så veldig fremtindsk ut, men greit utgangspunkt. Kanskje løfte den til Jøkul, så kan vi jobbe videre på den?

**Comment by Steinop** [comment]
Sjekk også med Sigve Hagesæter - mener det var han som holdt en demo vedr feedback-komponenter med referanse til statistikk/analyse. Det var klare forskjeller på hva som fungerte best.

**Comment by Steinop** [comment]
Sigve har sluttet i Fremtind men han har gitt meg tilbakemelding om at demoen ble tatt opp. Både opptak og PPT-presentasjon skal ligge i Team Motor-kanalen i Teams. John Rasmus Moen eller Kristin bør kunne hjelpe med å finne dette.
