### ISSUE TITLE
Max bredder

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1491]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [x] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Portalen bruker en max bredde på innhold.
Vi ønsker oss en standardisering på dette, så vi kan konsummere en variabel fra core eller sette en utillity klasse, og få vår ønskede max bredde på innholdet

**Beskriv løsningen du ønsker**
```
 $jkl-content-max-width--default: 800px;
 $jkl-content-max-width--small: 400px;

.jkl-content-max-width--default: {
  max-width: $jkl-content-max-width--default;
}

.jkl-content-max-width--small: {
  max-width: $jkl-content-max-width--small;
}
```

**Hvilke alternativer har du vurdert?**

**Mer info**

**Comment by wkillerud** [comment]
Vi har spesifisert i [Layout-dokumentasjonen](https://jokul.fremtind.no/profil/layout) at vi ikke har noen fast grid. Jeg tenker en variabel som dette havner litt for tett opp til deler av layout Jøkul ikke skal ta stilling til nettop fordi det er vanskelig å standardisere. Jeg ser vi har noen forsøk rundt breakpoints, men selv det er dokumentert som _to be decided_.

Jeg er åpen for diskusjon om temaet, men heller mot at vi ikke tilbyr dette i Jøkul.
