### ISSUE TITLE
Loader i knapp

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1492]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [x] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Når en knapp setter igang en async operasjon, som kan gjøre at man blir stående på siden man er på, så trenger vi en indikasjon på at vi jobber med saken.

**Beskriv løsningen du ønsker**
Vi kan bruke dagens loader inn i knappen, legge til en isLoading-prop og sette riktige aria-tagger.

**Hvilke alternativer har du vurdert?**
Kan også bytte ut knappen med loader, men fortsatt fint med en standardisert måte å gjøre det.

**Mer info**

**Comment by vegardsoerlie** [comment]
Etter å ha tenkt litt på det så liker jeg ideen om å ha Loader i knapp bedre enn å bytte den ut jeg også.
