### ISSUE TITLE
Dokumentasjon og eksempler på animasjon og animasjonsprinsipper

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1493]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [x] Avklare
- [x] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Et avsnitt om bevegelse under designprinsipper er alt om bevegelse. Vi er vel kommet langt nok til at vi burde kunne si noe om animasjonsprinsipper og hvordan vi kan gjøre det i praksis, inkludert hvordan ordentlig håntere universell utforming med bevegelse.

**Beskriv løsningen du ønsker**
En seksjon om animasjon med eksempler og prinsipper.

**Hvilke alternativer har du vurdert?**

**Mer info**

**Comment by Slaine2** [comment]
Eksempleroppdatering 

https://www.figma.com/file/OBJ8HrkvW5FysoDWynP418/Skisser-p%C3%A5-organismer?node-id=2281%3A23367

**Comment by Slaine2** [comment]
Foreløpig vises alle animasjoner på video. For fremtiden vil det være flott om vi også har eksemplene som klikkbare prototyper.
