### ISSUE TITLE
Bilde med offset box

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1502]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [ ] Undersøke
- [ ] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Standardisering av boks over bilde

**Beskriv løsningen du ønsker**
![image](https://user-images.githubusercontent.com/46530368/96445691-9d229c80-1210-11eb-8ca4-658281fd4ee8.png)

**Hvilke alternativer har du vurdert?**

**Mer info**

**Comment by onordbo** [comment]
Inaktiv.
