### ISSUE TITLE
Vis komponenter i responsiv modus når man jobber med dem isolert

### ISSUE THREAD

**Issue by Mikaila94** [fremtind/jokul#1576]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Det hender at utviklere må jobbe med responsive komponenter og slik det er lagt opp nå, så er det ikke så enkelt å teste for responsiv design for ulike skjermbredder fordi de er wrappet av komponenter som DevExample og ComponentExample. Ideelt sett bør komponentene ta hele skjermbredden og høyden, slik at man kan se om det responsive designet passer for de ulike skjermbreddene. 

**Beskriv løsningen du ønsker**
Jeg ønsker muligheten for å jobbe med komponenten i responsiv-modus, dvs at komponenten tar hele bredden og høyden i skjermen og at jeg får testet om det fungerer for ulike skjermbredder. En eller annen knapp som fjerner wrappers eller noe som gjør at komponenten kan jobbes med isolert uten noen wrappers hadde vært topp.

**Hvilke alternativer har du vurdert?**
Et alternativ er å ha en knapp som kan sette på "responsiv"-modus, slik at wrappers blir midlertidig fjernet og komponenten får lov til å ta hele skjermbredden/høyden.

**Mer info**
Dette ble oppdaget da jeg jobbet med Summary Table komponenten.

**Comment by piofinn** [comment]
Hmm, ja. Dette er nok en del av en litt større problemstilling, nemlig hvordan vi organiserer og viser frem større mønstre slik som det du sitter med nå.

Jeg er ikke så overrasket over at en slik komponent/et slikt mønster ikke passer så godt inn i komponenteksemplet vårt, og tenker umiddelbart at dette er et såpass stort mønster at det _ikke_ gir mening å vise det frem inne i et komponenteksempel-vindu. Foreslår at du setter opp slik at den ikke bruker `DevExample` når du kjører opp `yarn dev`, så får du i hvert fall jobbet med den på en enklere måte.

Her ser vi litt av utfordringen med at *alt* er komponenter i React, selv om de kan ha litt forskjellige roller etter atomic design 😅

**Comment by lfbergee** [comment]
Jeg tenker vi kan lage en typ ResponsiveExample, som rendrer ut komponenten i small, medium og large. Evt en av gangen med en toggler for å flippe mellom de. Eller at den viser alle i Dev-mode, men det er en toggler i portalen?

Det henger jo selvsagt sammen med det du nevner @piofinn med sammensatte-komponenter (liker ikke begrepet organismer før vi eventuelt bestemmer oss for at vi faktisk bruker atomic og lager ordentlige definisjoner på hva som hører hjemme hvor). MEN, det er ikke nødvendig å løse det samtidig. Vi kan fint lage en ny type eksempel konteiner uten å restrukturere komponentene, og motsatt. Opplever denne også viktigere, fordi den er et hinder både i utvikling og i bruk, mens restruktureringen er bare et problem i oppdagelse.
