### ISSUE TITLE
Feil: Innholdet i Select er litt lenger til høyre enn innholdet i Text input

### ISSUE THREAD

**Issue by CamillaDahlstroem** [fremtind/jokul#1592]
**Feilbeskrivelse**
Innholdet i selectene liner ikke opp med innholdet i tekstfeltene. Er ganske forstyrrende når man først har lagt merke til det 😅 Her f.eks. er "Politi" i brevmal-selecten ikke på linje med inputtekstene i de tekstfeltene som ligger under.

<img width="561" alt="Skjermbilde 2020-11-13 kl  14 08 26" src="https://user-images.githubusercontent.com/11536996/99076799-09987d80-25bc-11eb-879a-40e4b46977c8.png">

**For å reprodusere**
Sett opp en select og et tekstfelt rett under hverandre. 

**Forventet oppførsel**
Burde se ut som i Figma:

<img width="639" alt="Skjermbilde 2020-11-13 kl  14 08 15" src="https://user-images.githubusercontent.com/11536996/99076749-f1286300-25bb-11eb-9b9f-447c824136c3.png">

**Comment by piofinn** [comment]
Her bør padding endres også på elementene i listen, slik at det ikke ser rart ut når den er åpen 😊
