### ISSUE TITLE
Mulighet for at label/supportlabel er bredere enn select

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#1604]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [x] Avklare
- [x] Spesifisere krav
- [x] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Flere steder i flyten har vi lengre label enn hva ville sett naturlig ut mtp bredden til select.

Screenshot som viser forskjellen på datepicker og select: 
![image](https://user-images.githubusercontent.com/14551408/99378673-fccf9e80-28c7-11eb-9b4d-d43e9630ca0b.png)

**Beskriv løsningen du ønsker**
Ønsker at width ikke settes på `.jkl-select`, men feks på `__outer-wrapper`, slik at det ikke påvirker label og supportlabel.

**Diskusjon**
Burde alle slike elementer ha width-prop, slik at man kan sette en fast bredde i tjenesten sin? Det er kanskje litt rart at datepicker, select og text-input alle har forskjellig bredde. Den eneste komponenten av de som mangler muligheten er datepicker. Dette er vel en egen issue, men kom gjerne med tanker.

**Comment by vegardsoerlie** [comment]
Samtidig ser jeg at Figma ikke er helt enig med kode. I kode har vi `width: 15rem`. I Figma ser det noe friere ut

https://www.figma.com/file/Wh8Gfnesn25shH31sKyIaT/J%C3%B8kul-bibliotek?node-id=47%3A0

**Comment by piofinn** [comment]
@vegardsoerlie, i Figma kan man jo endre størrelsen på det aller meste 😅

Den bredden som er satt i kode (på Select) er nok for øvrig ganske arbitrært valgt ut fra en skisse en gang i tiden, så støtter absolutt ønske om bedre tilrettelegging for endring av bredde i kode også!
