### ISSUE TITLE
Feil: Validator for chassisnummer er feil

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#1662]
**Feilbeskrivelse**
Valideringsfunksjonen for chassisnummer vil feile mot gyldige chassisnumre. Nå tillater den kun tall, men de siste ni tegnene i et chassisnummer inneholder koder for produksjonsår og fabrikk, samt et kontrolltegn, som ofte er bokstaver. Normalt vil det være tre bokstaver og seks tall, men det finnes forskjellige standarder. Se oversikt over formatene som finnes [på Wikipedia](https://en.wikipedia.org/wiki/Vehicle_identification_number).

**Løsningsforslag**
La det være lov med bokstaver, i tillegg til tall.

**Comment by wkillerud** [comment]
@piofinn, trenger validatoren ta høyde for at det "from 1954 to 1981 [...] was no accepted standard for these numbers, so different manufacturers used different formats"? Eller skal vi legge oss på ISO 3779 med 17 tegn, siffer og bokstaver unntatt O(o), I(i) og Q(q)? Ser dagens legger opp til ni siffer, som virker litt funky.

**Comment by piofinn** [comment]
@wkillerud Det første du nevner er litt av grunnen til at det legges opp til ni siffer. Det er som regel kun de siste ni som brukes i bransjen (altså som blir registrert i våre systemer av forhandlere og saksbehandlere etc.), og det er kun de siste seks til åtte sifrene [som identifiserer bilen unikt](https://en.wikipedia.org/wiki/Vehicle_identification_number#Components) (litt som de siste fem i fødselsnummeret).

I Smartforhandler kjører vi rett og slett denne (`replace(/\W/g, '').toUpperCase().slice(0, 9)`) i feltet på `onChange`, men for en generell regel kan det nok være en idé å tillate opptil 17 tegn uansett.

Kanskje noe så enkelt som `^[a-zA-Z0-9]{9,17}$`?
