### ISSUE TITLE
Bilder og tekst på scrollanimasjon

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#1695]
På scrollanimasjoner bør tekst i innhold i størst mulig grad følge normal scrollhastighet for å unngå at tekstinnholdet "sklir".
Under bildebruk på Jøkul ligger bildet rolig mens teksten flytter seg i forhold til annet tekstinnhold - det bør være motsatt.
https://jokul.fremtind.no/profil/bildebruk

Tekst som animerer inn og legger seg statisk slik at den videre følger normal scroll er OK

**Comment by gbrownlee** [comment]
En veldig grov prototype for å "kjenne" på prinsippet: https://k2104.csb.app/

**Comment by Slaine2** [comment]
Mulige eksempler på animasjoner i helter og kort 
https://www.figma.com/file/OBJ8HrkvW5FysoDWynP418/Skisser-p%C3%A5-organismer?node-id=1215%3A481

**Comment by Slaine2** [comment]
Scrollanimasjonseksempler med det nye oppsettet fra Mona 
https://www.figma.com/file/OBJ8HrkvW5FysoDWynP418/Skisser-p%C3%A5-organismer?node-id=2198%3A23138
