### ISSUE TITLE
Oppsummering av feilmeldinger i skjema

### ISSUE THREAD

**Issue by Stormoen** [fremtind/jokul#1697]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [ ] Undersøke
- [ ] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Ikke et problem, men forslag til en bedre brukeropplevelse og uu hvis man ikke har fylt ut et skjema korrekt.

**Beskriv løsningen du ønsker**
Oppsummering av feilmeldinger i forbindelse med skjema. 
- Bruk av eksisterende feilmeldingsboks, med beskrivende liste over eventuelle feil/mangler i skjema
- Utløses nederst i løsningen der man er, uten scroll
- Mulighet for linker eller link til første feil
- Sticky?

SeOpp har allerede en tilsvarende oppsummering i "melde skade"-skjema, men da øverst på siden og uten linker. Det ble diskutert på Designsystemforum at det kanskje var fint å lande et felles prinsipp, alternativt definere noe rundt når det er hensiktsmessig å bruke oppsummering øverst eller nederst i løsningen.

**Hvilke alternativer har du vurdert?**
Jeg tror standard i hacked FFE har vært å scrolle opp til første skjemaelement som er ugyldig, uten oppsummering. Det fungerer også, men kanskje vi skaper en bedre brukeropplevelse med oppsummering? Da gir vi brukeren en pekepinn på omfanget som gjenstår, pluss at vi samler informasjonen som mangler ett sted.

**Mer info**
Skisser/forslag
![Skjermbilde 2020-12-15 kl  15 57 25](https://user-images.githubusercontent.com/64519175/102231435-3fe45800-3eee-11eb-905e-904a6ff3f8d7.png)

"Melde skade"-skjema:
<img width="1321" alt="Skjermbilde 2020-12-15 kl  15 59 04" src="https://user-images.githubusercontent.com/64519175/102231649-79b55e80-3eee-11eb-814f-390cc6cdb7b0.png">

**Comment by lfbergee** [comment]
@Stormoen det er nok ikke helt konsekvent i dagens løsninger, standard i skade/liv er oppsummeringsboks, men det finnes nok tilfeller hvor det ikke er i bruk.

Jeg syns det er pros and cons med den. Den gir jo en tydelig oppsummering, men gjør også at det tar meg lengre tid å få fullført skjemaet. Hadde vært interessant å se statestikk på, men vil anta at det oftest er feil i et felt, da er en oppsummering bare irriterende. Så kan vi selvsagt håndere det, ikke vis oppsummering hvis bare en feil, men da introduserer vi mer kompleksitet, mer  kode.

Versionen med lenker gir jo relativt liten verdi når man scroller seg vekk fra det ved første klikk. Skal vi ha en sånn variant må vi finne en måte å la den være hengede fast på siden.

Forøvrig så tror jeg denne hører hjemme i som en diskusjon, ikke et issue, siden det er ikke noe konkret arbeid som forslåes her sånn jeg tolker det.

**Comment by piofinn** [comment]
W3C [foreslår løsningen med oppsummering av feil](https://www.w3.org/WAI/tutorials/forms/notifications/#listing-errors), og anbefaler det _i tillegg til_ inline feil ved feltene:

> When errors occur, it is helpful to list them at the top of the page, before the form. The list should have a distinctive heading so that it is easy to identify. Each error listed should:

> - Reference the label of the corresponding form control, to help the user recognize the control;
> - Provide a concise description of the error in a way that is easy to understand by everyone;
> - Provide an indication of how to correct mistakes, and remind users of any format requirements;
> - Include an in-page link to the corresponding form control to make access easier for the users.

> Sometimes, for example, when using AJAX techniques, the browser is not loading a new page but shows changes, such as form errors, dynamically on the page. The list of errors should be inserted into a prominent container on the top to inform the user in such a case. In addition to the advice above, this container should have the role attribute set to alert to make assistive technology users aware of this change.

Ellers enig med @lfbergee at dette nok hører hjemme under [diskusjoner](https://github.com/fremtind/jokul/discussions), særlig siden dette fort må bli en implementasjons-spesifikk greie med mindre vi pålegger alle team å bruke en spesifikk skjemahåndterer.

**Comment by Stormoen** [comment]
@lfbergee Hvordan flytter jeg denne over til diskusjoner?

**Comment by lfbergee** [comment]
Ser ikke at det er mulig å gå den veien. Så anbefaller å lage en ny diskusjon og lenke til denne, så kan vi lukke dette issuet.
'
