### ISSUE TITLE
Feil: Autosuggest leser skjermleser "Lukk" på X-en

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#1748]
**Feilbeskrivelse**
Autosuggest leser skjermleser "Lukk" på X-en

**For å reprodusere**
Fortell oss hvordan vi kan gjenskape feilen (det hjelper oss med å fikse den):

1. Gå til Autosuggest i portalen
2. Fyll inn noe
3. Tab til X-en med skjermleser

**Forventet oppførsel**
Den bør lese "Tøm" eller "Fjern" eller "Tøm innhold" eller noe sånt

**Comment by wkillerud** [comment]
Får ikke reprodusert denne feilen med VoiceOver på macOS i Safari eller Chrome. Riktig [aria-label Fjern valg](https://github.com/fremtind/jokul/blob/704d1fcf219b26f7102ca7cb05449e70763b0f4a/packages/text-input-react/src/autosuggest/ControllerButton.tsx#L18) er det som blir lest opp når jeg bruker tab.

Husker du noen flere detaljer fra denne bugen @lfbergee? Annen skjermleser, browser, OS?
