### ISSUE TITLE
Oppdater ikoner i Figma 

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#1793]
**Feilbeskrivelse**
I Figma er det noen ikoner som kompakte og dristige versjoner, men ikke alle. For å ha settet med ikoner komplett - skal vi fortsatt bygge dem? 

**For å reprodusere**
De manglende ikonene må fortsatt utformes og fremfor alt utvikles

Se feilen https://www.figma.com/file/y9JtTf3whfTCHCdYSUXVQ5/%F0%9F%9B%A0-J%C3%B8kul-komponenter-Pull-request?node-id=82%3A1795

**Comment by wkillerud** [comment]
I skrivende stund ser ikonene i Figma ut til å være i de variantene de skal. Vet det er noen initiativ rundt ikoner, men tenker de kan trackes andre steder.

Lukker denne, men om det er noe konkret som bør gjøres her er det bare å gjenåpne 😄

**Comment by wkillerud** [comment]
Se #2713

**Comment by onordbo** [comment]
Foreldet.
