### ISSUE TITLE
Feil: Hamburger-icon ikon har alltid "Lukk" som title og vises ved hover

### ISSUE THREAD

**Issue by Saegrov** [fremtind/jokul#1811]
**Feilbeskrivelse**
Hamburger-ikonet har et <title> element som alltid vises som "Lukk" uavhengig av state.

Ideelt sett så skulle man hatt muligheten til å spesifisere <title> selv via en prop.

**For å reprodusere**
Se GIF
![ezgif com-gif-maker](https://user-images.githubusercontent.com/124469/107518063-df505f00-6bae-11eb-9071-6320df35d8d3.gif)

**Forventet oppførsel**
Forventer at man kan styre title-elementet via en prop.

**Comment by lfbergee** [comment]
Hehe, gjelder pluss/remove også.

Grunnen er at burgeren blir liggende der, bare med opacity 0. Ideelt sett burde den animeres ut av DOMet. Evt kan man sette `z-index: -1` på `--hide` klassen, som den litt stygge løsnigen på problemet.

**Comment by lfbergee** [comment]
I tillegg bør nok title eksponeres som en prop i alle ikonene, med default verdi på hva den er i dag. Som da også må taes inn som prop i disse animated-variantene.
