### ISSUE TITLE
Feil: Validering i datepicker

### ISSUE THREAD

**Issue by kristineSorensen** [fremtind/jokul#1881]
Løsning: Melde skade 

**Feilbeskrivelse**

1. Kritisk: Brukeren taster inn en dato som ikke finnes, feks: 31.11.2020 / 29.02.2021 / 00.03.2021 
Får ingen feilmelding og kommer videre til neste seksjon: 
Datoen blir automatisk gjort om til henholdsvis 01.12.2020 / 01.03.2021 / 28.02.2021

2. Forbedring: Hvis brukeren skriver 7.3.21 / 7.3.2021 --> Ugyldig dato  
Komponenten krever format dd.mm.aa eller dd.mm.aaaa. - 

3. Forbedring: Hvis brukeren skriver f.eks 99.99.9999 får feilmelding: Dato kan ikke være frem i tid.

**Forventet oppførsel**
1. Forventer en feilmelding at det ikke er en gyldig dato/ dato som ikke finnes og at bruker må rette det opp selv. 

2. Forbedringspotensiale ved å også takle d.m.aa og d.m.aaaa? 

3. Forventet "Ugyldig dato".

- Ofte er det viktig for saksbehandler og saken at brukeren har oppgitt riktig dato - hvis en bruker taster inn f.eks 32.01.21 vil jeg anta at kunden ikke egentlig mener 01.02.21 men heller har tastet 31.01.20 feil. Det er da uheldig at dette endres av seg selv med sannsynlighet for at brukeren ikke får det med seg.

**Comment by kristineSorensen** [comment]
Pratet med @SercanSercan  og punkt 3 kan ses bort fra i denne saken og noe vi kan fikse på meld skade.

**Comment by piofinn** [comment]
Angående nr. 2: Vi har vel allerede gått noen runder på det med format, og funnet ut at det er bedre å kun akseptere ett format på tvers av løsningene. Hvis man skriver dato på feil format skal verdien i feltet (ikke teksten, men det som sendes inn) nå settes til `undefined`, så det bør være mulig å gi feilmelding/tilbakemelding basert på det 😊

Har ikke fått testet nr. 1 ennå, men hvis feltet automatisk setter dato til nærmeste gyldige ved inntasting er jo det potensielt en ganske alvorlig bug ja!

**Comment by piofinn** [comment]
Så litt nærmere på dette, og den uforventedet oppførselen i punkt 1 kommer rett og slett fra `Date()`-funksjonen i JavaScript... Den returnerer ikke feil hvis man sender inn f.eks. 33. februar, men legger rett og slett bare til de ekstra dagene så det blir 5. mars 🤦‍♂️ Tror heldigvis vi kan unngå det med et par ganske enkle sjekker!

**Comment by kristineSorensen** [comment]
Jeg forstår ang. punkt 2 - og ja det er jo definitivt punkt 1 som er det store problemet. Så bra - så da kan det hende det er en enkel fiks? krysser fingrene for det. Er det isåfall en fiks som skjer i selve komponenten fra Jøkul? eller er det noe vi må fikse i løsningen vår?

**Comment by piofinn** [comment]
@kristineSorensen det vil være en fiks fra Jøkul. Sitter og ser på det nå 😊
