### ISSUE TITLE
Toggle Switch prototype

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#19]

**Comment by Steinop** [comment]
Crap - Får ikke lastet opp MPG...

**Comment by Steinop** [comment]
![Fremtind_Toggleswitch](https://user-images.githubusercontent.com/51952891/59767378-7c57d900-92a2-11e9-8aff-a7962f38eea6.gif)

Funker det med en GIF mon tro??

**Comment by Steinop** [comment]
Grunnlag for knapper ligger i Figma på "Toggle Switch_Desktop size" Ser for meg at vi også bør lage en mobilverson tilpasset 17pt body tekst. https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-components?node-id=24%3A0

**Comment by lfbergee** [comment]
I'll table this for now. We can use checkbox for this purpose, and we can get back to this when we have more components ready.
