### ISSUE TITLE
Datepicker bør bruke forwardRef

### ISSUE THREAD

**Issue by SercanSercan** [fremtind/jokul#1902]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Jeg ønsker å bruke onKeyDown event ved DatePicker komponent. 

**Beskriv løsningen du ønsker**
Jeg skal transforme DatePicker med forwardRef. 

**Hvilke alternativer har du vurdert?**
-

**Mer info**
-

**Comment by vegardsoerlie** [comment]
Hva skal onKeyDown brukes til?

**Comment by lfbergee** [comment]
Har tenkt litt på dette i dag, ref til inputfeltet kan nok løse problemet ditt, men er ikke sikker på at du kommer til å bli super happy med jobben du må gjøre. Antagelig må du lage en komponent ala Controller i React-form-hooks for å kunne ha meta-state på komponenten din, ala isDirty eller noe sånt. Evt noe smart diffing i onSubmithandleren som sjekker datofeltet.

ForwardRef er sikkert fint å få komponenten uansett, men tror jeg ville sett på å introdusere noe ala react-form-hooks for å gjøre det litt lettere for dere å arbeide med forms.


Prøvde å sette opp en sandbox som illustrerer problemet. Form 1 er controlled og bruker onBlur, ergo vil enter klikk i datoelementet sende inn formet (som i dette tilfellet consollogger staten, som da er feil).
Form 2 bruker react-form-hooks med controller, så vi behøver ikke å ha en lokal-state, ergo trenger vi ikke onBlur og enter klikk sender inn formet med den oppdaterte verdien.
https://codesandbox.io/s/aged-rgb-6zck6?file=/src/App.tsx
