### ISSUE TITLE
fix(portal): Feil i Knapploader

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#1966]
Knapp-lasteren er i feil størrelse.
Dette skal være identisk med den knappe størrelsen (48px).
For øyeblikket er det 42px.

https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=263%3A568

**Comment by wkillerud** [comment]
Ser ut som dette har blitt rettet:

```
$button-height--normal: rem(48px);

...

    &__loader {
        display: flex;
        padding: 0 $button-padding;
        align-items: center;
        height: $button-height--normal;
        min-width: $button-min-width--normal;
    }
```
