### ISSUE TITLE
fix(portal): Toggle Slider

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#1967]
Toggle slider har feil størrelse. Jeg tror det ville vært bra om det var i samme størrelse som knapper

https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=19305%3A58457

**Comment by wkillerud** [comment]
Toggle slider har lik høyde nå i kode som i Figma, både i byggesone og i biblioteket for 2.0. Anser denne som rettet i første omgang, og om det fortsatt er et ønske om endring tror jeg vi må gjennom en runde med forankring i design før vi setter en utvikler på det.
