### ISSUE TITLE
Vulnerabilities Status Badge

### ISSUE THREAD

**Issue by adriandersen** [fremtind/jokul#1993]
**Feilbeskrivelse**
Readme.md viser en statusbadge som sier at Jøkul har 0 vulnerabilities. Snyk ser ut til å kun scanne package.json (ikke yarn.lock eller andre filer.)
Dette er muligens uansett ikke noe som bør vises, selv om Jøkul er open source.

Er det behov for Snyk i tillegg til Dependabot? Isåfall vil jeg tro den bør oppdateres til å scanne alle relevante filer. Om ikke bør statusbadge fjernes, eller byttes ut med dependabot.

- Har noen noe kjennskap til Snyk, eller er det noe Leiv Fredrik har satt opp?

**Comment by joms** [comment]
Fra snyk.io sin JavaScript dokumentasjon:
> Git support for Yarn Workspaces is enabled for all projects in organisations created after March 3rd 2021. To enable this feature for organisations created before this date please contact support@snyk.io.

Jeg mistenker at dette kan ha noe med hvorfor den ikke scanner yarn.lock.

Har du kjennskap til hvorvidt det er noen forskjeller på hvordan Dependabot og Snyk stiller seg til kjente sikkerhetsbrudd kontra bare å holde pakker oppdatert?

@piofinn Har du noe input her?

**Comment by piofinn** [comment]
Usikker på om det er forskjell i hvor de henter data om sårbarheter 🤔 Vi satte jo opp Snyk før vi fikk tilgang til Dependabot, så det er ikke sikkert det er nødvendig eller praktisk lenger! Som @adriandersen sier er det heller ikke sikkert det er nødvendig å vise info om dette. Er jo en grunn til at kun repo-eiere får se varsler fra dependabot 😅
