### ISSUE TITLE
DatePicker Jøkul manøvrering med Tab krever 5 klikk før datovelger lukkes

### ISSUE THREAD

**Issue by oysteinF** [fremtind/jokul#2033]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Det er lite brukervennlig om man taster datoen manuelt og må trykke Tab 5 ganger for å komme ut av DatePicker
1. Tab: Kalenderikonet
2. Tab: År
3. Tab: Måned
4. Tab: Valg av dag
5. Tab: Ut av datovelger
Gi oss en klar og konsis beskrivelse av problemet. F.eks "Det er dumt at jeg alltid må [...]".

**Beskriv løsningen du ønsker**
Dersom man legger inn en fullverdig dato som eks 18.06.2021 så burde det å trykke tab en gang får deg til neste felt og DatePicker lukkes. 

**Hvilke alternativer har du vurdert?**
Evt når siste siffer i datoen er lagt inn kunne DatePicker lukkes og man blir stående i datofeltet.

**Mer info**
Her kan du legge til mer kontekst, skjermbilder, eller andre ting du ikke synes passer inn over.

![image](https://user-images.githubusercontent.com/86096718/122517729-af0f4600-d010-11eb-9afb-d37912dcfddb.png)

**Comment by piofinn** [comment]
Hvis man tabber inn i datovelgeren skal ikke kalenderen åpnes automatisk, og da blir det bare to tast for å komme videre etterpå. Er det mange som klikker for å skrive og så tabber seg ut igjen?

> Dersom man legger inn en fullverdig dato som eks 18.06.2021 så burde det å trykke tab en gang får deg til neste felt og DatePicker lukkes.

Jeg er litt usikker på hvordan man skulle skilt mellom dette og en evt. forhåndsutfylt dato? Da liker jeg bedre det andre alternativet, der kalenderen lukkes når en gyldig dato er lagt inn. Det tror jeg også skal være ganske enkelt å implementere uten å gjøre særlige endringer på hverken struktur eller logikk 😊

**Comment by oysteinF** [comment]
@piofinn Ja variant 2 ville fungerer bare pass på formatet - årstall med 4 siffer (eksemplet ditt har bare 2 før den lukker. dd.mm.åååå

**Comment by piofinn** [comment]
@oysteinF Vi tillater å skrive inn datoer med to siffer i årstallet i dag, så jeg gjorde ingen endringer på det. Tror det kom fra et annet behov en gang, men er enig med deg at det nok er bedre å holde seg til ett tillatt format 😊
