### ISSUE TITLE
Støtte lengre labels i ToggleSlider

### ISSUE THREAD

**Issue by espkva** [fremtind/jokul#2037]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [X] Undersøke
- [x] Rapportere
- [x] Avklare
- [x] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
ToggleSlider har en maksbredde som gir lite rom og mulighet for lengre label-tekster.

**Beskriv løsningen du ønsker**
ToggleSlider tilpasser maksbredden basert på lengde på labels som blir sendt inn.

**Hvilke alternativer har du vurdert?**
Beskriv gjerne hvilke andre potensielle løsninger du har vurdert.

**Mer info**
Nåværende:
![image](https://user-images.githubusercontent.com/1224929/123066219-24fc1e80-d410-11eb-9d08-b6a441a0eb8a.png)

Ønsket:
![image](https://user-images.githubusercontent.com/1224929/123066271-30e7e080-d410-11eb-8ff1-1dd54b9c230d.png)

**Comment by piofinn** [comment]
Veldig enig i denne! Ingen grunn til å ha en arbitrær makslengde her så vidt jeg kan se.

**Comment by kennidenni** [comment]
@espkva I need this 😅
