### ISSUE TITLE
Feil: Lister vises feil i Portalen

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#2070]
**Feilbeskrivelse**
Listepunktene på lister fra Jøkul vises ikke i Portalen

**For å reprodusere**
Fortell oss hvordan vi kan gjenskape feilen (det hjelper oss med å fikse den):

1. Gå til https://jokul.fremtind.no/komponenter/list
2. Scroll ned til et av eksemplene med punktlister
3. Se feilen

**Forventet oppførsel**
Listepunktene vises som normalt i Portalen

**Skjermbilder**
<img width="330" alt="Skjermbilde 2021-07-05 kl  15 40 34" src="https://user-images.githubusercontent.com/25739615/124480243-59c08c00-dda7-11eb-9963-7b561fde491e.png">

**Mer info**
På et eller annet steg i byggeprosessen fjerner Gatsby (eller en plugin i Gatsby) attributtene `width` og `height` fra SVG-ene som utgjør listepunktene. De vises derfor ikke riktig. Dette skjer _kun_ når portalen bygges for produksjon, ikke når den kjøres opp lokalt for utvikling.

Problemet oppstår heller ikke når `List`-komponenten brukes i et standard `create-react-app`-prosjekt.

**Comment by wkillerud** [comment]
Listepunktene vises OK i produksjon i dag. Testet med Safari, Firefox, og Chrome på macOS.
