### ISSUE TITLE
Tekst på Hamburger

### ISSUE THREAD

**Issue by joms** [fremtind/jokul#2093]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [ ] Undersøke
- [ ] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
På BM utvikler vi en ny "megameny" hvor vi bruker Hamburger-komponenten som en kontrollerende knapp. Her har vi behov for å legge en tekst sammen med hamburgeren. Ettersom teksten skal agere sammen med knappen, og det hele skal oppføre seg som én entitet må teksten oppføre seg som en del av knappen.

**Beskriv løsningen du ønsker**
Teksten er lagt til som en funksjonalitet på selve komponenten med to tilstander: 
- openLabel
- closeLabel

https://github.com/fremtind/jokul/pull/2092

Teksten animeres så ved å først fade ut den ene, og så inn den andre. Og motsatt.

Gjenstående arbeid er å synkronisere Jøkul dokumentasjon med den utviklede komponenten.

**Comment by Murstam** [comment]
Tror det ser bedre ut om vi dropper animasjon på teksten. Gir ikke samme mening at teksten vokser og «åpner» seg som selve hamburgeren.

**Comment by Murstam** [comment]
Selve utformingen på hamburgeren bør synces med det som ligger på Icons i Jøkul. Der er det en mer oppdatert versjon av hamburgeren :)

**Comment by joms** [comment]
> Tror det ser bedre ut om vi dropper animasjon på teksten. Gir ikke samme mening at teksten vokser og «åpner» seg som selve hamburgeren.

Det skal jeg få fikset :)



> Selve utformingen på hamburgeren bør synces med det som ligger på Icons i Jøkul. Der er det en mer oppdatert versjon av hamburgeren :)

Da bør den vel oppdateres ihht https://github.com/fremtind/jokul/issues/1969?

**Comment by Murstam** [comment]
Jepp, det er nok siste versjon 👍🏻

**Comment by joms** [comment]
For nå har jeg lagt til støtte for å legge til animasjon på teksten om man ønsker det i #2107. Er det vits i at den muligheten i det hele tatt finnes @Murstam ?

**Comment by onordbo** [comment]
Lukker denne på bakgrunn av foreldelse og #3066.
