### ISSUE TITLE
Feil: Button med og uten loader har forskjellige layout-egenskaper

### ISSUE THREAD

**Issue by hjellek** [fremtind/jokul#2122]
**Feilbeskrivelse**
PrimaryButton med og uten loader rendres helt forskjellig, da loaderen krever en div rundt pga. innholdsbytte.
Dette medfører at layout-egenskapene til knappen endres basert på loader-propertyen, som er uventet.

**For å reprodusere**
Opprett to knapper ved siden av hverandre, og sett loader på den første.

CodeSandbox demo:
https://codesandbox.io/s/eager-cherry-jb7wj?file=/src/App.js

**Forventet oppførsel**
Button med og uten loader har samme layout-egenskaper

**Skjermbilder**
![Screenshot 2021-08-12 at 14 58 16](https://user-images.githubusercontent.com/1640160/129200751-fce799cb-eac8-45da-8a63-6548406d4639.png)

**Mer info**
Chrome 92 på Macos

**Comment by wkillerud** [comment]
Hei @hjellek! Jeg har sett litt nærmere på dette problemet her i dag. Jeg forstår at resultatet kan være forvirrende og gjorde en test lokalt med å gjøre wrapperene inline. Jeg er ikke helt fornøyd med resultatet. Legger ved to videoer.


https://user-images.githubusercontent.com/1223410/132480232-7e26a5d5-3c57-4b72-a9a9-e07ed39cadc5.mov


https://user-images.githubusercontent.com/1223410/132480268-ad0f82a7-d003-46ed-91c8-43d89b7179e4.mov



Vi får en layout shifting om teksten i knappen er under en viss bredde. Vi kunne i prinsippet gjort så alle knapper har en minimumsbredde lik animasjonsbredden. Lange knappetekster (som riktignok frarådes) vil få en del luft mellom animasjonen og neste knapp. Det er kanskje en teoretisk forbedring over dagens situasjon.

Det jeg mistenker er at denne animasjonen ikke ble laget med tanke på å brukes i grupper av knapper som dette. Kan det gi mening å erstatte hele knappegruppen med en `Loader`-komponent? Antar her at tertiærhandlingen ikke kan avbryte jobben som allerede er satt i gang. Har du mulighet til å ta opp problemstillingen med en designer i teamet ditt?

Kjenner jeg trenger litt input fra flere før vi eventuelt gjør noen endringer i selve knappekomponenten.

**Comment by Murstam** [comment]
Hei! Det bør helst være en annen løsning enn å erstatte knappen med loader, det gir litt uheldig resultat. Hva er status på denne?

**Comment by hjellek** [comment]
Hei! Enig med @Murstam , det virker litt rart å bytte ut hele knappegruppen.
Jeg endte opp med å lage en flex-container rundt i prosjektet vårt (kallte den ButtonGroup) da det løser layout-problematikken fint. Usikker på om det kan være en grei nok løsning for Jøkul også.

**Comment by wkillerud** [comment]
Jeg kjenner ikke historikken bak det valget, men er absolutt åpen for å tenke nytt her 😄 Tenker det kan bli et tema på morgendagens designsystemforum @Murstam @hjellek, så tar vi det derfra? Bare å komme med innspill på ønskede løsninger.

**Comment by wkillerud** [comment]
Da ble konklusjonen at vi endrer designet av knappeloader til å vises inni knappen, animert på en liknende måte til å erstatte teksten med loading-indikatoren. På den måten skal knappene som laster forbli inline. Knappen skal heller ikke endre bredde i loading-tilstand.

**Comment by wkillerud** [comment]
@all-contributors please add @hjellek for bug report
