### ISSUE TITLE
Feil: Select viser nest siste verdi for skjermleser

### ISSUE THREAD

**Issue by BjorneOma** [fremtind/jokul#2126]
**Feilbeskrivelse**
Skjermleser leser den forrige valgte verdien når den skal lese opp Select-komponenten. Ved første valg viser den "Velg".

**For å reprodusere**
Fortell oss hvordan vi kan gjenskape feilen (det hjelper oss med å fikse den):

1. Skru på skjermleser 
2. Gå inn på Select-eksempelet på Jøkul
3. Velg et alternativ
4. Se at skjermleser leser "Velg" i stedet for valgt verdi
5. Velg en ny verdi
6. Se at skjermleser leser forrige verdi

**Forventet oppførsel**
Skjermleser burde lese valgt verdi.

**Mer info**
Testet i Chrome på mac med VoiceOver.

**Comment by wkillerud** [comment]
@all-contributors please add @BjorneOma for bug report

**Comment by wkillerud** [comment]
@all-contributors please add @BjorneOmaFremtind  for bug report
