### ISSUE TITLE
Ønsker standalone-mulighet for Select-komponent

### ISSUE THREAD

**Issue by BjorneOma** [fremtind/jokul#2127]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
På SeOpp har me ein CurrencyInput-komponent der bruker kan skrive inn et tall, og velge en valuta. Me har tatt i bruk Label, BaseInputField, Select, SupportLabel og InfoMessage. 
![image](https://user-images.githubusercontent.com/55135175/129553295-c6b0dd6f-43ef-41eb-ac75-936abb207212.png)
Selv med inline-prop er det eit label som er synlig kun for screen-reader. Det resulterer i fleire labels for samme komponent, ettersom me tar i bruk ein custom Label.

**Beskriv løsningen du ønsker**
Tilsvarende BaseInputField.

**Mer info**
Eg er ny i Fremtind, og har ikkje koda til Jøkul, så vil helst ikkje ta tak i denne sjølv.

**Comment by piofinn** [comment]
> Selv med inline-prop er det eit label som er synlig kun for screen-reader. Det resulterer i fleire labels for samme komponent, ettersom me tar i bruk ein custom Label.

Dette er vel strengt tatt ønskelig? Hvordan skal en person som bruker skjermleser vite hva som er hva hvis det ikke blir lest opp et label for hhv. input og select?

For meg virker det naturlig om dette var en `fieldset` (med `FieldGroup`-komponenten fra Jøkul) med inline-varianter av `TextInput` og `Select` (må lages inline-variant i så fall). Da kan feltet f.eks. leses opp slik for skjermleser: "Gruppe, Valuta -> Tekstfelt, velg beløp -> Flervalg, velg valuta"

**Comment by BjorneOmaFremtind** [comment]
@Mikaila94 Nei, me treng fortsatt ein inline-variant av Select.

**Comment by BjorneOmaFremtind** [comment]
Her hadde eg misforstått litt, inline select finnast allereie. Eg lukker denne.
