### ISSUE TITLE
Feil: Ikke konsekvent bruk av cursor på klikkbare elementer

### ISSUE THREAD

**Issue by joms** [fremtind/jokul#2173]
**Feilbeskrivelse**
Bruken av cursor:pointer på klikkbare elementer er ikke konsekvend.

**For å reprodusere**
Fortell oss hvordan vi kan gjenskape feilen (det hjelper oss med å fikse den):

1. Gå til button
2. Hovre over button (den har cursor:pointer)
3. Gå til select
4. Hovre over select (den har ikke cursor:pointer)

**Forventet oppførsel**
Alle klikkebare elementer skal ha cursor:pointer. Dette er vedtatt gjennom en avstemning (10 for, 3 mot) i designsystem-forum. Resultatet er at vi skal følge normen på internett hvor alle klikkbare elementer har cursor:pointer, med det resultat at det er en brukers forventning, i stedet for å følge anbefalingene og operativsystemets oppførsel.

**Comment by joms** [comment]
Skriv også en liten blogg-post om hvordan og hvorfor vi har gått for dette.

**Comment by wkillerud** [comment]
@all-contributors please add @joms for bug report
