### ISSUE TITLE
Portalens sidetitler bør beskrive innholdet mer presist

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#2184]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [x] Avklare
- [x] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Portalen mangler en beskrivende `<title>` på undersider. Det gjør det vanskelig å navigere i nettleserhistorikken for å finne tilbake til enkeltsider, og å bokmerke enkeltsider uten å måtte redigere tittel på bokmerket. Det kan og diskuteres om tittelen beskriver innholdet godt nok [med tanke på UU](https://www.uutilsynet.no/regelverk/testprosedyrar-nettstader/709#suksesskriterium_242_sidetitlar), hvor portalen bør gå foran som et godt eksempel.

![image](https://user-images.githubusercontent.com/1223410/132298818-8dd25794-385f-4873-b2f7-e0e9194a0a57.png)

**Beskriv løsningen du ønsker**
Jeg ønsker at portalen genererer en `<title>` for hver enkelt side som inkluderer sidens tittel i navigasjonsmenyer i formatet `<sidetittel> | Jøkul designsystem`. Dette gjør tittelen mer beskrivende i scenariene over.

**Hvilke alternativer har du vurdert?**
Ulike varianter av skilletegn brukes rundt omkring. Tankestrek `–` er en populær variant. Det kan også vurderes om vi trenger å inkludere `Jøkul designsystem` i `<title>` for andre sider enn forsiden. For eksempel Github og Instapaper sløyfer det og lar URLen og sideinnholdet være branding nok.

**Comment by wkillerud** [comment]
Tar gjerne innspill på tittelformatet og om vi trenger "brand postfix". Når vi lander ønsket løsning kan jeg fint implementere.

**Comment by joms** [comment]
Jeg liker det første forslaget med `<sidetittel> | Jøkul Designsystem`. Pipe er bare en personlig preferanse.

Jeg mener også at "Jøkul Designsystem" hører hjemme i title. Om man browser mange designsystem samtidig og alle fanene heter "Button" kan dette bli forvirrende, selv med bruk av favicon.

**Comment by piofinn** [comment]
Stemmer! Dette hadde vi faktisk tidligere. Tror det ble borte da vi la om håndteringen av Layout :/
