### ISSUE TITLE
Vi burde kunne lenke til bloggen uten å spesifisere en bloggpost

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#2188]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [x] Undersøke
- [x] Rapportere
- [ ] Avklare
- [ ] Spesifisere krav
- [ ] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
Det hadde vært fint om vi kunne lenket til bloggen fra andre sider uten å spesifisere en enkelt bloggpost. Om jeg går til https://jokul.fremtind.no/blog/ i dag får jeg en feilside.

**Beskriv løsningen du ønsker**
Om jeg går til https://jokul.fremtind.no/blog/ uten å spesifisere en bloggpost burde jeg bli redirectet til den nyeste bloggposten.

**Hvilke alternativer har du vurdert?**
Vi kunne sikkert også laget en egen landingsside for bloggen hvor vi gjør listen over bloggposter til hovedinnholdet, med eller uten et kort utdrag fra innholdet. Etter hvert som det blir mange bloggposter burde vi kanskje også lenke direkte til denne siden fra toppmenyen i stedet for å ha et overlay og navigasjon til enkeltposter som i dag.

**Comment by onordbo** [comment]
Kan/burde denne sees i sammenheng med #919?
