### ISSUE TITLE
Tilbakemelding ved feil i DatePicker

### ISSUE THREAD

**Issue by joms** [fremtind/jokul#2198]
Hvilke steg i [prosessen](https://fremtind.github.io/jokul/komigang/prosessen) er utført?
- [X] Undersøke
- [X] Rapportere
- [X] Avklare
- [x] Spesifisere krav
- [x] Utvikle
- [ ] Ferdig!

**Er ønsket tilknyttet et problem? Fortell oss mer!**
I dag får man ikke noen annen tilbakemelding ved feil i DatePicker enn at resultatet er `undefined`. Dette kan bety at formatet er feil, at det ikke er noen input eller at den er utenfor range.

Her mener jeg det er et behov for å få en tilbakemelding som gir et bedre grunnlag for å si noe om hva som gikk galt. Dette for å kunne gi brukeren en god og beskrivende tilbakemelding om hva som er galt, og hvordan de skal kunne komme seg videre.

**Beskriv løsningen du ønsker**
Ett forslag er at man kan returnere en enum som representerer en feiltype, eller et objekt som beskriver feilen som har oppstått i større grad.
Jeg tror det er viktig at man opplyser om hva som har feilet, men at det er konsumenten sitt ansvar å formidle en god feilmelding. denne feiltypen er bare en hjelp i å tilføre kontekst.
ser inn over.

**Comment by wkillerud** [comment]
Enig i at dette trengs. Skal undersøke litt hvordan andre datovelgerkomponenter har løst dette.

**Comment by wkillerud** [comment]
`@material-ui/pickers` sin `DatePicker` løser dette med en `onError`-funksjon som kalles ved valideringsfeil. Den legger opp til å ta inn props for de støttede valideringene og så returnere den propen. Sikkert så man kan gjøre en `setErrorState(foo)` og bare rendre `foo` direkte. Interessant vri, men øker "props-flaten" for hvert feilscenarie. Går an å stjele `onError()`, men gå for en enum-ish variant i stedet.

https://material-ui-pickers.dev/api/DatePicker

**Comment by piofinn** [comment]
Liker siste forslag best!
