### ISSUE TITLE
Create mixin/function for removing dotted line in Firefox

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#220]
Could we place this rather annoying little bastard in normalize?

_Originally posted by @lfbergee in https://github.com/fremtind/jokul/pull/217_

**Comment by piofinn** [comment]
Could be either a mixin/function to use in component styles, or just put it in a normalize/reset file to remove them from everything. The latter approach requires us to be **very** stringent about creating good focus/hover states for all elements.

**Comment by lfbergee** [comment]
Datepicker needs this too.
