### ISSUE TITLE
Humburger – variasjon på stroke

### ISSUE THREAD

**Issue by Murstam** [fremtind/jokul#2220]
Avhengig av hva slags prosentvisning du har i nettleser så endrer strokes seg på hamburger. 

Et lite utvalg:
<img width="57" alt="Skjermbilde 2021-09-16 kl  12 02 03" src="https://user-images.githubusercontent.com/47025023/133593643-33573c60-d5d3-4598-8d1f-5558974a29d6.png">
<img width="67" alt="Skjermbilde 2021-09-16 kl  12 01 58" src="https://user-images.githubusercontent.com/47025023/133593646-a5172f9c-f7f8-482c-8504-b4e3bde4530a.png">
<img width="106" alt="Skjermbilde 2021-09-16 kl  12 01 44" src="https://user-images.githubusercontent.com/47025023/133593649-027841d6-ae65-4c52-b6fb-444f8b2098d5.png">
<img width="86" alt="Skjermbilde 2021-09-16 kl  12 01 37" src="https://user-images.githubusercontent.com/47025023/133593651-f9bf297d-5517-4ec2-88c2-358b480ccf15.png">
<img width="89" alt="Skjermbilde 2021-09-16 kl  12 01 30" src="https://user-images.githubusercontent.com/47025023/133593652-8585b5e4-2d45-43eb-9c74-8c2e3b145d08.png">

Noen som har en løsning?

**Comment by wkillerud** [comment]
> Humburger

Liker det nye navnet! 😄  Kan forske litt, men tar gjerne flere øyne på denne.

**Comment by Murstam** [comment]
Haha, ren tilfeldighet, men det gir jo egentlig mening at en hamburger som ikke oppfører seg blir en humburger 😅

**Comment by wkillerud** [comment]
Tror kanskje dette er noe vi må leve med. Nettleseren gjør et valg om å runde opp eller ned høyden på hvert enkelt element som vanskelig lar seg styre. Ser for eksempel samme oppførsel på https://jonsuh.com/hamburgers/ i Chrome og Safari. Både vi og den eksempelsiden bruker samme tekniske fremgangsmåte for å lage hamburgeren (element og before+after pseudo-elementer med bakgrunnsfarge = tre elementer).

Kanskje i teorien en annen teknisk løsning vil kunne skalere de tre strekene jevnt, men det virket fra søkene mine som at f. eks. en SVG ville kunne få samme problem. SVGer er jo også bygget opp av flere elementer (paths).

**Comment by joms** [comment]
Det henger på greip med min teori også. Jeg har antatt at dette kommer ned til matematikken for hamburgeren, hvor browseren prøver å kompansere for halve pixler i ny og ne.

**Comment by wkillerud** [comment]
NRK sin er ikke like variabel som i alle skjermbildene øverst i saken, men helt pixel perfect er den ikke. Ser noe variasjon i høyden, og en blur-effekt på enkelte zoomnivå. De har gått for en løsning med en SVG med tre `<rect>`.

![image](https://user-images.githubusercontent.com/1223410/134015975-fcf1fede-cc11-4010-b77d-5e991c9bbbcb.png)
110% zoom i Chrome på macOS

![image](https://user-images.githubusercontent.com/1223410/134016066-b783296a-fdc8-4ce9-8959-52790b1b2c4e.png)
90% zoom i Chrome på macOS

Forbedring nok til å ta en omskriving?

**Comment by Murstam** [comment]
Ok, da tror jeg vi lar den være. Virker ikke som det er nok verdi til å bruke masse tid på. Vår hamburger er styggest på zoom ut og jeg vil tro at det er flere som zoomer inn enn ut.
