### ISSUE TITLE
Feil: Spacing inni select komponenten når man velger samme input flere ganger

### ISSUE THREAD

**Issue by karimarkhus** [fremtind/jokul#2246]
**Feilbeskrivelse**
Når man velger samme valg inni select-komponenten flere ganger blir det feil med spacing og teksten gjør et innrykk.

**For å reprodusere**
Fortell oss hvordan vi kan gjenskape feilen (det hjelper oss med å fikse den):
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/91268511/134519249-6a36adeb-4bc2-498c-8915-9532ceee8381.gif)

**Forventet oppførsel**
Spacing forblir den samme uavhengig av hvor mange ganger man velger det samme.

**Mer info**
Testet på Safari og Chrome på Mac

**Comment by wkillerud** [comment]
@all-contributors please add @karimarkhus for bug report
