### ISSUE TITLE
Feil: Lange navn i select-komponenten

### ISSUE THREAD

**Issue by karimarkhus** [fremtind/jokul#2247]
**Feilbeskrivelse**
1. Når valget er for langt "aligner" ikke teksten når den kommer på 2 linjer. 
2. Når man har valgt et langt valg, dukker "check" ikonet opp på linjen under hvis teksten er for lang.
3. Hvis man har et valg med et ord som er lenger enn bredden på inputfeltet så forvinner teksten ut, men man kan scrolle horisontalt. 

**Forventet oppførsel**
1. Teksten bør gå på linje med linjen over. 
2. Det bør alltid være plass til "check" ikonet på høyre side av teksten. 
3. Er usikker på hva som er beste løsning

**Skjermbilder**
![Screenshot 2021-09-23 at 15 56 57](https://user-images.githubusercontent.com/91268511/134523690-0bef08b8-ad51-47f2-82d9-a8aa037f1de2.png)
![Screenshot 2021-09-23 at 15 56 41](https://user-images.githubusercontent.com/91268511/134523691-34bc5763-9a45-40a4-b7b6-0fb0c288c227.png)
![Screenshot 2021-09-23 at 15 58 23](https://user-images.githubusercontent.com/91268511/134523685-5356d472-3698-4cec-95f6-134ecc5c0fe0.png)
![Screenshot 2021-09-23 at 16 00 16](https://user-images.githubusercontent.com/91268511/134523805-2cdaf718-d1bf-4f19-a28d-7f1f8c7ff15d.png)

**Mer info**
Testet i chrome på Mac

**Comment by wkillerud** [comment]
Hei, og takk for feilrapporter!

Enig i at sjekkboksen alltid bør være på linje med valget det gjelder. 

Når det gjelder de to andre tenker jeg nesten vi må bruke `width` som er høy nok til å få plass til det lengste elementet. I dette eksempelet vil f. eks. `width="370px"` gi en bedre opplevelse. Det gjør det enklere å lese mer av den valgte verdien også. Kan det funke @karimarkhus ?

https://user-images.githubusercontent.com/1223410/134646436-25450282-a8c2-4a4e-a8b6-4b087c2e4d54.mov

**Comment by karimarkhus** [comment]
I eksempelet ditt har viser du et eksempel hvor select komponenten er har større bredde. Det er viktig å ha mulighet til at et valg kan gå over 2 linjer, dette er fordi vi ikke alltid har plass til å utvide inputfeltet til å passe størrelsen på teksten inni.
