### ISSUE TITLE
CI: oppdater til npms nye access token format

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#2250]
[Bloggpost](https://github.blog/2021-09-23-announcing-npms-new-access-token-format/)

Key takeaway:

> We strongly encourage you to make the move toward the new format by resetting your existing access tokens. These improvements will help you mitigate any risk to compromised tokens as well as make our secret scanning detection more precise.
>
> You can reset your personal access tokens by clicking on Access tokens under your npm Profile, deleting all of your old tokens, and creating new ones.
>
> Thank you for helping us make npm more secure. ❤️

**Comment by wkillerud** [comment]
@piofinn, sitter du med nøkkelen for publisering på npm og kan ta deg av denne? Er ikke noe som haster, men hadde vært fint om noen kan holde i den (og gjerne løse i løpet av kalenderåret).

**Comment by piofinn** [comment]
Nytt token generert for @fremtind-bot og oppdatert i secrets.
