### ISSUE TITLE
Feil: Oppdatering av testing-library knekker feedback-tester

### ISSUE THREAD

**Issue by espkva** [fremtind/jokul#2251]
**Feilbeskrivelse**
Testene for Feedback-komponenten knekker ved oppdatering av @testing-library/dom

**For å reprodusere**
Oppdater @testing-library/dom til 8.6.0 og kjør testene

**Forventet oppførsel**
All green!

**Comment by wkillerud** [comment]
Rettes av #2258

**Comment by wkillerud** [comment]
@all-contributors please add @espkva for bug report
