### ISSUE TITLE
Oppgrader til lerna-clean-changelogs-cli@^2.0.0

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#2261]
Dependabot åpnet #2255, men denne trenger nærmere review

Pakkens Changelog: https://github.com/codsen/codsen/blob/main/packages/lerna-clean-changelogs-cli/CHANGELOG.md

Godt mulig dette er en drop-in replacement. Kontroller Node-versjon på GitHub actions. Risikoen ser ut til å være begrenset til at changeloggene våre blir litt mer rotete.

**Comment by piofinn** [comment]
Ser ut som `ubuntu-latest` (som vi kjører alle våre actions på) [er på Node 14](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#installed-software), så det skal være innafor å oppgradere 😊
