### ISSUE TITLE
Select - sekundærtekst

### ISSUE THREAD

**Issue by Murstam** [fremtind/jokul#2327]
Vi har behov for en sekundærtekst i select (kunne vært dropdown), i vårt tilfelle er det org. nr som støtter bedriftsnavnet slik at det bli lettere å velge riktig bedrift hvis du har tilgang til flere.

Hvis noen flere har behov for det samme eller mener det brude være en ny komponent, si fra :)
<img width="1507" alt="Skjermbilde 2021-10-05 kl  15 38 32" src="https://user-images.githubusercontent.com/47025023/136034484-e4c0f9d3-b115-41f0-b0ba-140f9c6c38f3.png">

**Comment by wkillerud** [comment]
Vi er i en flytteprosess hvor vi prøver å holde temaer som er på diskusjonsnivå til Discussions-fanen i GitHub 😄 Hopper over til Discussions-taben med denne.
