### ISSUE TITLE
Feil: Unødvendig dependency til jkl-button i CookieConsent

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#2346]
## Feilbeskrivelse

Både `jkl-cookie-consent` og `jkl-cookie-consent-react` depender på `jkl-button` direkte i stedet for indirekte gjennom `jkl-button-react`. Dette kan skape trøbbel med dobbeltversjoner o.l. og skaper unødvendige lenker mellom pakkene. 

## Steg for å gjenskape

Se `package.lock` i de to pakkene

## Forventet oppførsel

Ingen av de to pakkene bør eksplisitt depende på `jkl-button`

## Systeminformasjon

Irrelevant

**Comment by wkillerud** [comment]
@all-contributors please add @piofinn for bug report
