### ISSUE TITLE
Feil: TextInput har feil markering i dark mode

### ISSUE THREAD

**Issue by kennidenni** [fremtind/jokul#2376]
## Feilbeskrivelse

TextInput har feil markering i dark mode (at markeringen er helt sort). Det ser ut som om det fungerer på jokul.fremtind.no, at den får grå markering på tekst. Men i hos oss i kundeklienter så fungerer det ikke.

## Steg for å gjenskape

0. Sett pc/mac til dark mode
1. Gå til et sted der det er brukt dark mode med text input
2. Skriv noe inn, og så marker det med shift og piltast eller dobbelklikk på teksten. 
3. Teksten skal nå være markert, men ser det ikke fordi det er sort bakgrunn.

**Comment by wkillerud** [comment]
@all-contributors please add @kennidenni for bug report
