### ISSUE TITLE
Tabeller

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#2392]
Vi avdekket et stort behov for fellest tabeller i Jøkul, under inventory. Funksjonalitetsønsket er diskutert her: https://github.com/fremtind/jokul/discussions/2333

## Forslag til løsning
Løsningsforslaget er delvis utformet i design og tiltenkt teknisk løsning, en PR er åpnet.

**Pull request:** #2380.
**Designskisser:** [https://www.figma.com/file/R3PB5IS7zdrVQ3DKehRar5/?node-id=62%3A3085](https://www.figma.com/file/R3PB5IS7zdrVQ3DKehRar5/?node-id=62%3A3085)

**Comment by onordbo** [comment]
Ja @wkillerud, der gikk det litt fort 🏎

@Murstam, det er supert om du får lagt inn det du gjorde av designarbeid på tabellene i biblioteket når du har et ledig øyeblikk—enten direkte eller i en egen branch, så får vi det på plass der også. 🎯

**Comment by Murstam** [comment]
Håper å få tid til det neste uke 👍

**Comment by onordbo** [comment]
Hurra! Tabeller merget inn i Figma 🎉 Bra jobba @Murstam 🔥

[https://www.figma.com/file/y9JtTf3whfTCHCdYSUXVQ5/?node-id=3632%3A5363](https://www.figma.com/file/y9JtTf3whfTCHCdYSUXVQ5/?node-id=3632%3A5363)
