### ISSUE TITLE
Feil: Ytelsen i select-komponent med mange items

### ISSUE THREAD

**Issue by HavardPede** [fremtind/jokul#2404]
## Feilbeskrivelse

Hvis du har en select med mange items (1000+), skaper dette ytelsesproblemer for Select komponenten. Jeg er enig i at dette er et unormalt usecase. Det ble møtt på når vi trengte å kunne velge yrke, der vi har en liste på 1500+ valg.

### Big-O: O(n^4)
Slik jeg ser det, har vi en Big(O) notering på O(n^4). Her er de stedene jeg ser, der vi itererer over items-listen.

```
const selectedValueLabel = visibleItems.find((item) => item.value === value)?.label || defaultPrompt;
```
```
items.map(getValuePair).map((item) => ...
```
```
 {visibleItems.map((item, i) => (
 ```

edit: Som nevnt i kommentarer under, er ikke hoved-grunnen til ytelsesproblemer.

### Codesandbox
Jeg har laget en demo codesandbox. Ser ut til at styling har blitt importert feil til prosjektet, men dette har lite betydning.
Kan også importere eksempelet til et lokalt prosjekt og teste der. 

https://codesandbox.io/s/polished-brook-386vb?file=/src/App.js

## Forventet oppførsel

Jeg ønsker at vi skal forbedre ytelsen ved å redusere kompleksiteten i koden.

**Comment by HavardPede** [comment]
@wkillerud Det er godt poeng. Det er rendering som koster mest ja. Her er et eksempel der jeg fjernet ene loopen og det reduserte scripting med 10%, men er som du sier ikke det som krever mest her.

standard komponent: 
![image](https://user-images.githubusercontent.com/30959515/138270329-b146bca7-0b41-451f-81ba-039fea890a06.png)

Fjernet 1/4 loops: 
![image](https://user-images.githubusercontent.com/30959515/138270592-4e88bc93-1c37-4e3e-8f90-14de9c256984.png)


Jeg oppdaget dette i samme perioden jeg lagde en custom versjon av jkl select for å støtte custom search (ref https://github.com/fremtind/jokul/discussions/2403). En ting jeg innser jeg glemte at jeg gjorde var å ha en "max cap" på antall elementer som skal vises, hvis det er en søke-funksjonalitet. Hvis dette "cappes" til fks. 50 elementer som matcher søket, vil dette forbedre rendering slik vi ser her:
![image](https://user-images.githubusercontent.com/30959515/138271492-2f1b15e8-e190-4af0-b918-98f3269be401.png)
![image](https://user-images.githubusercontent.com/30959515/138272001-7a0d3f35-d5ef-4c98-ab4e-4106b4180959.png)

**Comment by piofinn** [comment]
@HavardPede er dette issuet fortsatt aktuelt? Hvis dette fortsatt er noe vi ønsker å løse ville jeg sett på om vi kan [virtualisere](https://www.patterns.dev/posts/virtual-lists) listen med søkeresultater. .

**Comment by HavardPede** [comment]
@piofinn List Virtualization var tøft, har ikke sett det før.

Denne feilen er fortsatt aktuell ja, met er ikke helt krise. Et eksempel vi har er valg av kontor for salg av forsikringer.
For DNB/NSF er det per nå 3649 kontorer i velge mellom (i test ihvertfall). Dette er jo helt klart et edge case. Det gjøres et stykke arbeid for å fjerne utgåtte kontor her, men det lander nok godt innenfor et firesifret antall elementer som vises i listen samtidig uansett.

Komponenten oppleves i det tilfellet som litt laggy, men brukbar.
Vedlagt er performance fra åpning av komponenten.
![image](https://user-images.githubusercontent.com/30959515/229527950-3a814c65-09c1-4d4b-8226-5c9b3b5709cc.png)

Hadde jo vært nice om det var like snappy som med færre elementer.
