### ISSUE TITLE
Feil: feedback-react mangelfulle testids

### ISSUE THREAD

**Issue by henrikhermansen** [fremtind/jokul#2413]
## Feilbeskrivelse

Før omskriving av react-komponenten ga man tilbakemelding ved å velge en smiley 1-5.
Disse hadde hver sine `data-testid`, men dette har blitt borte etter den nylige omskrivingen av komponenten.

Dvs. at Ja/Nei laget med preset, f.eks. "fikk du gjort", ikke har brukbare testid-er. Begge har en testid, men det er den samme id-en på begge knappene.

I tillegg mangler testid på submit-knappen.

Burde også sjekke om man kan nå slideren for preset "Hvor fornøyd 5" med en testid, dette har jeg ikke sjekket.

**Comment by wkillerud** [comment]
Jeg tenkte ta en titt på det med duplikat test-ID @henrikhermansen, men finner bare ett sted i Feedback hvor test-ID kommer fra Jøkul, og det er i det åpne tilleggspørsmålet (fritekstfelt, textarea). Antar dupliseringen kom av at det ble satt en prop fra utsiden – stemmer det?

Tenker som nevnt vi bør kunne klare oss uten test-ID her, så om det ikke er store protester lukker jeg denne buggen.
