### ISSUE TITLE
Tags i Jøkul

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#2415]
## Diskusjon

Funksjonalitetsønsket er diskutert her:

https://github.com/fremtind/jokul/discussions/2341

## Forslag til løsning

@onordbo og jeg lager et forslag basert på innsiktsarbeidet fra inventory

**Comment by onordbo** [comment]
Figma biblioteket (branch: tags) [oppdatert med ny padding 8/2](https://www.figma.com/file/eL15GtAzhsUk9MHWxZ92DP/tags?node-id=1997%3A6990)

**Comment by wkillerud** [comment]
@all-contributors please add @onordbo for design
