### ISSUE TITLE
Feil: Teksten på knappene på hovedsiden til portalen er hvit på hvit bakgrunn

### ISSUE THREAD

**Issue by gbrownlee** [fremtind/jokul#2421]
## Feilbeskrivelse

Når portalen brekker under en viss bredde, forsvinner teksten på knappekortene.

![image](https://user-images.githubusercontent.com/888229/139231531-b8816155-4723-4a4c-a7dd-df01675c0ce6.png)

## Steg for å gjenskape

1. Åpne jokul.fremtind.no på en smal skjerm
2. Skroll til de fire start-knappene.

## Forventet oppførsel

Teksten på disse knappene bør bli sort når bakgrunnen blir hvit. 

## Systeminformasjon

Virker å gjelde alle nettlesere.

**Comment by wkillerud** [comment]
@all-contributors please add @gbrownlee for bug report

**Comment by wkillerud** [comment]
Løst i #2423
