### ISSUE TITLE
Feil: Ser ingenting når jeg trykker på React Hooks i menyen.

### ISSUE THREAD

**Issue by Mikaila94** [fremtind/jokul#2425]
## Feilbeskrivelse
Menyvalget ser tomt ut når man trykker på Komponenter -> React Hooks i menyen.

## Steg for å gjenskape
1. Trykk på Komponenter i menyen.
2. Trykk på Reacy Hooks.
3. Observer at det er ingenting der.

## Forventet oppførsel
Det burde vises en liste med hooks som man kan trykke på.

## Systeminformasjon
macOS Big Sur v11.6.1
Chrome Version 97.0.4681.0 (Official Build) dev (x86_64)

**Comment by piofinn** [comment]
Huh, dette må være en bug som har kommet til i (relativt) nyere tid. Før kom det opp liste over hooks, og det ser ut som det fungerer som det skal på mobil 🤔
