### ISSUE TITLE
Feil: Horisontale breakpoints i portalen

### ISSUE THREAD

**Issue by HavardPede** [fremtind/jokul#2427]
## Feilbeskrivelse

Hvis skjermstørrelsen er fra **992px** til **1014px** blir innholdet i portal forskjøvet ut av skjermen. 
### eksempel
![image](https://user-images.githubusercontent.com/30959515/139262962-c536aba8-c666-483c-9b80-5f5dee015888.png)

I bildet bruker jeg standard instillinger for chrome.

Dette er litt avhengig av tekststørrelse i nettleser. Bla hvis størrelsen økes fra medium til large (chrome spesifikt), blir problemet litt mer åpenbart:
![image](https://user-images.githubusercontent.com/30959515/139260577-2a170492-8bb9-4ac5-8a0c-29ca84526f66.png)

## Steg for å gjenskape

1. Gå til https://jokul.fremtind.no/komponenter/buttons.
2. Bruk DevTools eller lignende til å kunne styre skjermbredden i pixelformat.
I chrome kan dette bla. gjøres ved å toggle visning fra desktop til mobile:
![image](https://user-images.githubusercontent.com/30959515/139259872-8f2d01f7-b203-4d56-8722-fe72a11b03f6.png)
Man kan også teste dette ved å endre størrelsen på nettleser vindu manuelt, hvis pixel-breakpoints ikke er viktig.
3. For å endre tekststørrelse i chrome kan du gå hit: chrome://settings/?search=font+size

## Forventet oppførsel
Jeg antar at med standard nettleser-instillinger skal innholdet i siden vises uten å kreve horisontal scrollbar, selv innenfor den skjermbredden nevnt ovenfor.
Dette kan løses ved å skjule venstre-menyen ved et tidligere breakpoint.

Med økt tekststørrelse er det naturlig at innholdet blir skjøvet ut av skjermen ved mindre skjermstørrelser. Men da bakgrunnsfarge og navigasjonsbar strekkes over hele innholdet.

## Systeminformasjon

Jeg bruker Google Chrome, versjon _95.0.4638.54_.

**Comment by wkillerud** [comment]
@all-contributors please add @HavardPede for bug report
