### ISSUE TITLE
Feil: Forsiden scrolles ikke jevnt etter intro i Safari

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#2437]
## Feilbeskrivelse

Etter "introen" på http://jokul.fremtind.no scrolles vi ned til hovedinnholdet. Det scrolles jevnt i Chrome og Firefox, men i Safari er det et hopp.

## Steg for å gjenskape

1. Gå til http://jokul.fremtind.no i Chrome eller Firefox og vent til animasjonen er ferdig
2. Gå til http://jokul.fremtind.no i Safari og vent til animasjonen er ferdig.

## Forventet oppførsel

Safari bør også scrolle jevnt.

## Systeminformasjon

Desktop Safari 15.1, siste Chrome og Firefox på macOS

**Comment by piofinn** [comment]
[Dette](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior#browser_compatibility) har nok fort noe med saken å gjøre 😅

<img width="628" alt="Skjermbilde 2021-11-05 kl  15 15 06" src="https://user-images.githubusercontent.com/25739615/140524381-409dd083-0eda-49b9-8cb3-5366d342a345.png">

Ser ut som det finnes [en polyfill](https://www.npmjs.com/package/smoothscroll-polyfill), men det føles litt feil å skulle dra inn en polyfill i det vi er i ferd med å droppe support for IE 😑

**Comment by wkillerud** [comment]
Ser det er landet som default (ikke lenger bak flagg) i Safari Technology Preview ([for tre uker siden](https://trac.webkit.org/changeset/284029/webkit/)). Når det lander i prod vet bare de selv 🤷‍♂️

Det er ikke helt gunstig, hverken det ene eller det andre. Kjedelig å shippe en polyfill når støtten er såpass bred...

**Comment by piofinn** [comment]
Pleier faktisk å være ganske kort vei fra Tech Preview til Prod i Safari i min erfaring! Så hvis der er kommet med der tenker jeg at det beste er å la være å gjøre noe: Polyfill er kjipt å dra inn, mekke en egen implementasjon for bare denne tingen virker overkill, og dette er jo strengt tatt progressive enhancement slik det er i dag.

Er ikke veldig nice i Safari slik det er nå, men er jo heller ikke noe som brekker funksjonalitet 😊

**Comment by wkillerud** [comment]
Lukker som wontfix, vi venter til dette lander i Safari

**Comment by wkillerud** [comment]
[Shippet i Safari 15.4](https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/#web-apis) 🎉
