### ISSUE TITLE
Feil: Kode eksempler vises ikke i portalen

### ISSUE THREAD

**Issue by tomef96** [fremtind/jokul#2440]
## Feilbeskrivelse

Det skulle vært en knapp med teksten "Vis kode" under kodeeksempelet på komponenter som har dokumentert det.

## Steg for å gjenskape
1. Gå til https://jokul.fremtind.no/komponenter/tag
3. Scroll ned til komponenteksempelet
4. Se at "Vis kode" knappen ikke finnes

## Forventet oppførsel

"Vis kode" knappen skulle vært der, og koden skal dukke opp når man trykker på den.

## Systeminformasjon
Chrome 95 på macOS Big Sur

**Comment by wkillerud** [comment]
Er bare Tag-dokumentasjonen som er kodet feil. F. eks. https://jokul.fremtind.no/komponenter/table er i orden. Ser koden for å vise koden ble skrevet om, sikkert underveis i PRen for Tags uten at jeg fikk det med meg.

**Comment by wkillerud** [comment]
@all-contributors please add @tomef96 for bug report
