### ISSUE TITLE
Feil: GitHub actions trigges ikke av oppdaterte Cypress-snapshots

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#2455]
## Feilbeskrivelse

Når det blir lagt til nye Cypress-snapshots som føge av en PR blir det laget en automatisk commit som inneholder de nye snapshot-ene. Denne trigger ikke de påkrevde sjekkene i GitHub Actions, og PRen blir derfor aldri merket grønn.

## Steg for å gjenskape

Se f.eks. b61311e i PR #2441 

## Forventet oppførsel
Nye snapshots bør trigge sjekker (eller merke som skipped) slik at PRen kan passere som normalt

**Comment by wkillerud** [comment]
Fjernet `on: push` fordi dokumentasjonen overalt sier at workflowen skal kjøres ved push til en pull request, men det stemmer tydeligvis ikke i dette tilfellet... Får legge det tilbake.
