### ISSUE TITLE
Feil: `Select` og `NativeSelect` kan ikke brukes med `react-hook-form` uten `Controller`

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#2456]
## Feilbeskrivelse

Som tittelen sier, `Select` og `NativeSelect` lar seg ikke bruke uten `Controller`. Jeg prøvde [ta den i bruk i en importkalkulator jeg laget for meg selv](https://github.com/wkillerud/wllm-importkalkulator/blob/d50d8531201a2d860c4bef5a774d214b83d537f1/pages/index.js#L102), men fikk det ikke til å funke med `register`.

## Steg for å gjenskape

Forsøk å ta i bruk `Select` eller `NativeSelect` med `register` fra `react-hook-form`. 
https://github.com/wkillerud/wllm-importkalkulator kan sjekkes ut for et eksempel.

## Forventet oppførsel

Skjemakomponenten bør kunne brukes som en _uncontrolled component_ (`register`, ikke `Controller`)

**Comment by piofinn** [comment]
Huh, det er jo _veldig_ rart at ikke `NativeSelect` skal funke med `react-hook-form`, den er jo bokstavelig talt et vanlig `<select>`-element. Har det med den nye måten `register` funker på i v7?

**Comment by wkillerud** [comment]
Mulig jeg ikke sjekket grundig nok nå når jeg ser at både `ref`, `value` og `onChange` m.m. settes på `select` i `NativeSelect`. Vi har ingen `...rest`-props, så om det er noe mer som trengs for `register` så vil ikke det settes.

**Comment by piofinn** [comment]
Er bare dette som kommer fra `register`, så tror det skal være good! Men kunne nok fint vært en `rest` på den uansett 😊
![Skjermbilde 2021-11-09 kl  13 20 43](https://user-images.githubusercontent.com/25739615/140923261-7833cbda-8a91-4c02-99cc-b8af1730660a.png)

**Comment by wkillerud** [comment]
Gjorde en retest nå, og det stemmer at `NativeSelect` _ikke_ fungerer uten `Controller`. Endringer jeg gjør i skjemaet blir ikke rendret riktig av komponenten, sannsynligvis fordi den ["gjør seg selv controlled" om vi ikke gir en `value`-prop](https://github.com/fremtind/jokul/blob/898b029002e979d0a5e9fc472d76f2aba2bbd051/packages/select-react/src/NativeSelect.tsx#L55).
