### ISSUE TITLE
Clean up library in Figma

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#247]
Find, and use, a definite system for presenting/organizing the components in Figma. The library should only contain production-ready designs, with all experimentation and suggestions living in different projects.

- [x] Buttons
- [x] Radio buttons
- [x] Checkbox
- [x] Toggle
- [x] Accordion
- [] Datepicker
- [x] Dropdown
- [ ] Typography (?)
- [x] Input
- [ ] Textarea
- [x] Message
- [ ] Logo (?)
- [ ] Loading indicator

**Comment by Mikkelinski** [comment]
Figma oppdatert - utestående komponenter i limbo for hvordan de skal løses, men oppryddingsarbeidet er gjort og biblioteket er publisert
