### ISSUE TITLE
Add Figma sketches to component pages in the portal

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#249]
All components should have links to the Figma page using the `figma` prop of the `Example` component.

- [x] Buttons
- [ ] Radio buttons
- [ ] Checkbox
- [ ] Toggle
- [ ] Accordion
- [ ] Datepicker
- [ ] Dropdown
- [ ] Typography (?)
- [ ] Input
- [ ] Textarea
- [ ] Message
- [ ] Logo (?)
- [ ] Loading indicator
- [ ] Divider line
- [ ] Card
- [ ] List
- [ ] Hamburger menu

**Comment by lfbergee** [comment]
@piofinn maybe this is not relevant anymore? Close?
