### ISSUE TITLE
Støtte for benevnelse i inputfelt

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#2493]
## Forum update 09/11/21
Teamet går vekk fra prefix der det finnes, og suffix innføres som standard for input-felter med benevnelse. @piofinn ser på utvikling sammen med @Stormoen, som parallellt ferdigstiller designet i en Figma-branch.

_Originally posted by @onordbo in https://github.com/fremtind/jokul/discussions/2454#discussioncomment-1612713_

**Comment by wkillerud** [comment]
Koden ble fullført i #3291, men ser at vi aldri gjorde noe i Figma for denne featuren (issuet er vel fra før vi ble flinkere med issue-mal for å tracke både kode og Figma).

Er dette en _you need it you build it_-sak, eller skal vi gjøre noe i biblioteket for å forenkle? Cc @Slaine2 @onordbo

**Comment by onordbo** [comment]
@wkillerud: Vi skal nok klare å få inn en prop for det på ett eller annet vis. Jeg kan ta en kikk på mulighetene.
