### ISSUE TITLE
Kort!

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#2501]
## Diskusjon

Funksjonalitetsønsket er diskutert her: https://github.com/fremtind/jokul/discussions/2345

## Forslag til løsning

Etter et innledende nøte har vi kommet frem til noen hovedmønstre som spinger ut av paraplyen "kort". Dette er derfor også et paraply-issue. Issues for deler av arbeidet, og for de resulterende komponentene/mønstrene vil henvises til herfra.

### Innledende oppgaver

- [x] Finne uttømmende eksempler på innholdskort
- [x] Definere grunnprinsipper for organisering av innhold i kort
- [x] Finne grunnlegende visuelle egenskaper for innholds- og lenkekort

## Mer info

Vi har funnet to hovedmønstre som er aktuelle for Jøkul per nå; **lenkekort** og **innholdskort**. Innholdskortene har potensielt en undervariant **oppgavekort**. I tillegg finnes det et mønster i PM for **kort som er skjemaelementer**.

### Lenkekort

- Lenkekort fungerer som en lenke, men har mer innhold
- Hele kortet **er** klikkbart
- Må ha støtte for både tekst og bilde

### Innholdskort

- Inholdskort har som funksjon å gruppere innhold som hører sammen
- Innholdet kan være statisk eller interaktivt
- Kortet kan potensielt ekspanderes for å vise mer innhold
- Selve kortet er **ikke** klikkbart

### Kort som er skjemaelementer

- Oppfører seg som en radio button eller checkbox, men har mer innhold
- Har en tilstand (valgt/ikke valgt)

**Comment by onordbo** [comment]
Prøvde å få assignet alle som er i kjernegruppa på dette issuet, dog ser det ut til at det fortsatt mangler å legge til noen designer-brukere inne på repoet vårt (selvom de har egne Github kontoer).
