### ISSUE TITLE
TextInput støtter ikke type="search"

### ISSUE THREAD

**Issue by joms** [fremtind/jokul#2508]
## Diskusjon

Usikker på om dette er en feil eller et funksjonalitetsønske, men TextInput støtter ikke `type="search"` som automatiserer en del rundt universell utforming:
- legger til ikon for å tømme feltet
- legger til en handler for å tømme feltet når man trykker på esc

## Forslag til løsning

Implementere støtte for `type="search"` eller bruke en egen prop. Egen prop tenker jeg kan være gunstig når man bruker TextInput med en action.

**Comment by wkillerud** [comment]
Uvisst for meg hvorfor vi ikke har inkludert `search` i `type`. Jeg vil tro vi kan støtte den, men er litt usikker på hva vi bør gjøre hvis feltet har en action.

Jeg vet ikke om jeg er enig i at krysset og fjerning av innholdet ved Esc er et UU-tema. Firefox gjør for eksempel ingen av de to tingene. Det er ikke en del av standarden, bare opp til den enkelte browser. Det sagt skader det ikke at vi legger opp til å følge Chrome og Safari.

**Comment by wkillerud** [comment]
@piofinn, navnet ditt dukker opp i Git-historikken for BaseInputProps rundt hvor `type`-propen er definert. Husker du hva som skjedde for to år siden? 😄

**Comment by joms** [comment]
> Firefox gjør for eksempel ingen av de to tingene

Det er veldig interessant. Ser ikke ut som det var så mye spennende i [speccen](https://html.spec.whatwg.org/multipage/input.html#text-(type=text)-state-and-search-state-(type=search)) heller. Det gjør det egentlig mer irriterende siden det er mer uforutsigbart hvordan man skal håndtere en sånn funksjonalitet.

**Comment by wkillerud** [comment]
Sniker inn støtte for `type="search"` i #2733 

Jeg gjør ingenting for å samkjøre oppførselen på tvers av nettlesere, men da kan man i det minste få nativeoppførselen med en søke-stylet TextInput.
