### ISSUE TITLE
Design toggle switch

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#251]
We need a finished design for this component that is more aligned with the general design

**Comment by Steinop** [comment]
Toggle Switch (or in norwegian "Svitsjknapp") animated prototype for on/off states and focus states. Note that the toggle switch height is adjusted to 24 px for a closer match to Radiobuttions and Checkmarks

![Fremtind_Toggle switch_v5_24px small_Focus](https://user-images.githubusercontent.com/51952891/62688053-527c8200-b9c8-11e9-8120-3bb8d2311983.gif)
![Fremtind_Toggle switch_v5_24px small](https://user-images.githubusercontent.com/51952891/62688054-527c8200-b9c8-11e9-91a9-df94523eec7b.gif)

Design updated in FIgma: 
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-components?node-id=1690%3A0

- Still need for a WCAG compliant update of the green color and a broader range of grays for dark vs light modes. Will add a new issue for this.

**Comment by lfbergee** [comment]
Implemented
