### ISSUE TITLE
Design link style

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#254]
We need a designed style for links. There are unfortunately some technical limitations regarding styling of these, so this should be a close coop between dev/design.

See temporary implementation in `core`

**Comment by Steinop** [comment]
Text link prototype. 
The conversion from MP4 to GIF format makes the animation av bit wonky. Transition time between states is set to 150 ms but might be even faster. 

![Fremtind_Tekstlenke](https://user-images.githubusercontent.com/51952891/62525363-9429f300-b837-11e9-89d8-c47367c8e4c3.gif)

Check out Figma for designspecs:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-components?node-id=1551%3A0

Inspired by: https://codepen.io/geoffgraham/pen/GXoOdK
