### ISSUE TITLE
Feil: Kan ikke flytte markør i søkbar select med klikk

### ISSUE THREAD

**Issue by tomef96** [fremtind/jokul#2581]
## Feilbeskrivelse

Når man skriver noe i en søkbar select, og prøver å klikke på teksten et sted for å flytte markøren, så trigges klikk hendelsen og selecten lukkes.

## Steg for å gjenskape

1. Gå til 'https://jokul.fremtind.no/komponenter/select'
2. Klikk på 'Med søk'
3. Trykk på komponenten og skriv inn en tekst
4. Trykk på teksten et sted for å flytte markøren
4. Se at selecten lukker seg

## Forventet oppførsel

Man skal kunne flytte markøren ved å klikke uten at selecten lukker seg. Klikk hendelsen burde trigges når man trykker på et element i listen i stedet.

## Systeminformasjon

Chrome 96 på macOS 11.6.1

**Comment by wkillerud** [comment]
Hei @tomef96! Takk for bugrapport. Det ser ut som en duplikat av #2400. Du og @joms må gjerne ta en titt på det sammen for å finne rotårsaken.
