### ISSUE TITLE
Feil: Select komponent håndhever ikke value prop

### ISSUE THREAD

**Issue by joms** [fremtind/jokul#2589]
## Feilbeskrivelse

Select komponenten håndhever ikke lenger value propen om den settes programmatisk fra utsiden. Hverken med prop, eller ved bruk av react-hook-form som bruker refs.

## Steg for å gjenskape

[CodeSandbox](https://codesandbox.io/s/musing-bose-h3utn?file=/src/App.tsx)

## Forventet oppførsel

I eksempelet skal selecten bli oppdatert til å vise "Max Mekker" når man trykker på knappen for å sette en tilfeldig valgt verdi.

**Comment by wkillerud** [comment]
Jeg vet ikke helt hvorfor, men av en eller annen grunn velger React ikke å re-rendre `<Select />` i eksempelet ditt, selv om `selected` definitivt blir endret. Mulig det er noe med `forwardRef` jeg ikke helt har forstått.

I eksempelet ditt kan det løses ved å gi `<Select />` en `key={selected}`, slik at React tvinges til å re-rendre når verdien endres.

https://codesandbox.io/s/weathered-bash-ekd2f?file=/src/App.tsx:637-645

**Comment by wkillerud** [comment]
> Select komponenten håndhever ikke lenger value propen om den settes programmatisk fra utsiden [...] ved bruk av react-hook-form som bruker refs.

Jeg forstår ikke helt denne beskrivelsen @joms. Mener du at `register` ikke funker? [Skjemadesign](https://jokul.fremtind.no/profil/skjemadesign)-siden har et [eksempel med bruk av `react-hook-form` og `register`](https://github.com/fremtind/jokul/blob/main/portal/src/components/form-components/FormComponentsExample.tsx) som fungerer som det skal.

**Comment by joms** [comment]
> Jeg forstår ikke helt denne beskrivelsen @joms. Mener du at `register` ikke funker?

Nei, register funker fint. Men om man endrer verdien fra utsiden av `Select` så oppdaterer ikke komponenten seg. Har ikke testet, men jeg vil tro som du sier at det kan løses ved å tvinge en re-render ved å endre `key`, men det er bare en workaround. Skal se om jeg får gravd mer i det etter hvert for å finne en rotårsak
