### ISSUE TITLE
Feil: lenke til React Hooks fungerer ikke i menyen i portalen

### ISSUE THREAD

**Issue by joms** [fremtind/jokul#2590]
## Feilbeskrivelse

Når man trykker på React Hooks i menyen i portalen forsvinner bare lenkene i menyen, men man blir ikke flyttet til en ny route.

## Steg for å gjenskape

1. Gå til https://jokul.fremtind.no/
2. Trykk på komponenter
3. Trykk på React Hooks

## Forventet oppførsel

Man blir flyttet til siden for React Hooks

## Systeminformasjon

MacOS med Chrome og Safari

**Comment by wkillerud** [comment]
Hei og hopp. Det er en kjent sak, rapportert tidligere i #2425. Vi tenkte i utgangspunktet drøye den til en redesign av navigasjonen og portalen for øvrig, men mulig det blir for lenge å vente?

**Comment by joms** [comment]
Så lenge det er kjent, er det good 👍
