### ISSUE TITLE
Feil: Skviste radio-buttons

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#2593]
## Feilbeskrivelse

Radio-button ser ut til å ha blitt skvist.

## Steg for å gjenskape

Ta en kikk på [https://jokul.fremtind.no/komponenter/radiobutton](https://jokul.fremtind.no/komponenter/radiobutton)

![image](https://user-images.githubusercontent.com/4263132/145790345-0206dea5-b4b8-470b-ad83-660f576c488f.png)

_(Fra Chrome 96 on macOS (Catalina))_

## Forventet oppførsel
Runde radio-buttons.

**Comment by wkillerud** [comment]
@onordbo er dette på 100% zoom?

Ser sånn her ut for meg i Chrome 96 på Big Sur.
![Skjermbilde 2021-12-16 kl 11 34 53](https://user-images.githubusercontent.com/1223410/146355621-fb2e27a8-733c-4b9f-94c6-64f2b0282d15.png)

**Comment by onordbo** [comment]
Hm, nei! Bra catch. Jeg får ikke replikert original-screenshottet nå. Men hvis jeg går i 90% eller 110% zoom, _(eller noen som helst annen zoom enn 100% egentlig)_ får jeg en «ny» deformasjon, i stedet. I stedet for en skvist/strukket radio-button så blir den fylte sirkelen i valgt-state malplassert utenfor midtpunktet, dette varierer mellom zoom-nivåene.

![image](https://user-images.githubusercontent.com/4263132/146357834-cd5fd9e3-6773-4e62-8e4f-97baa012c5d5.png)

**Comment by wkillerud** [comment]
Det er forsåvidt en kjent sak, og noe vi lever med i andre komponenter (hamburger for eksempel, som ser litt rar ut på ulike zoomnivå). Så lenge de er brukbare har vi ikke for vane å være pixel perfect på ikke-standard zoomnivå.
