### ISSUE TITLE
Implementasjonsdetaljer: Summary Table skal være mer fleksibel

### ISSUE THREAD

**Issue by Mikaila94** [fremtind/jokul#2617]
### Discussed in https://github.com/fremtind/jokul/discussions/2520

Vi kom frem til at vi beholder Summary Table  og ønsker å gjøre den mer fleksibel slik at den kan bedre tilpasses til ulike formål, f.eks ha celler med grå tekst som dere ser på bildet under.

![image](https://user-images.githubusercontent.com/10635523/146746457-f3e680f4-9e9a-499a-aa57-e2d30334c7db.png)

1. Først og fremst  tenker jeg å den komponenten i mindre komponente i mindre biter, altså at man har en delkomponent for table, thead, tbody, tfooter, th, tr, td  som delkomponenter, men da gjerne med noen predefinerte properties som man kan override evt.

2. Jeg synes også at SummaryTable bør ha en listevisning som Table. Jeg tror det kan gjøre det enklere å jobbe med denne på mindre skjermer. @Stakset , hva tenker du?

<img width="498" alt="Screenshot 2021-12-20 at 11 34 02" src="https://user-images.githubusercontent.com/10635523/146753635-2f8f6ab4-0eef-4755-818a-934f6a1ef407.png">

3. Ønsker vi begrensning på antall kolonner? 2-3 ? 

Tanker, innspill?

**Comment by wkillerud** [comment]
Re mobilvisning: en summering er vanskeligere å følge om regnestykket ikke kan "scannes" vertikalt. Jeg tror ikke en listevisning er så gunstig for denne komponenten. Men, mulig det finnes en løsning.

Tror det kan være fornuftig å splitte opp i flere komponenter, men samtidig har det noen fordeler med props på én komponent så lenge de propsene er fleksible nok (se f. eks. Feedback). Det er lettere å sørge for at alle summary tables har en footer om det er en påkrevd footer-prop, for eksempel.

**Comment by Mikaila94** [comment]
Enig, jeg lager et forslag så kan folk komme med forslag til endringer der eventuelt.
