### ISSUE TITLE
Accordable (Accordion med Table)

### ISSUE THREAD

**Issue by Mikaila94** [fremtind/jokul#2618]
### Discussed in https://github.com/fremtind/jokul/discussions/2520

Både SAM og Flyt bruker en kombinasjon av Accordion + Table om jeg ikke tar feil.  Dette kan enten bli implementert som egen komponent (Accordable) eller så kan vi utvide Table til å støtte ekspanderbare rader. Ekspanderbare rader er noe vi ønsker på sikt ifølge dokumentasjonen til Table.  En annen mulighet jeg ser er å kombinere ekspanderbare rader i Table sammen med Summary Table.  Men trenger mer diskusjon før vi kan gjøre noe med dette.

Tanker, innspill? @AudunBerdal noe du ønsker å legge til? Jeg trenger også innspill fra en representant fra Flyt, om hvordan de bruker tabeller. Bildet under viser eksempel fra SAM. 

![image](https://user-images.githubusercontent.com/10635523/146756816-51d9419f-2426-406b-a2f7-6c5737c7836b.png)

**Comment by Mikaila94** [comment]
For min del utifra skissene, så virker disse løsningene som veldig spesifikke og jeg vet ikke om vi bør ha en komponent for det i Jøkul

**Comment by wkillerud** [comment]
Jeg vil si Accordion + Table som oftest er en tabell med rader som kan ekspanderes. Ser ut som alle eksemplene så langt har minst to kolonner i raden, og så et vilkårlig innhold som ekspanderes ut (ofte en ny tabell, ofte noe "ikke tabellete", og noen ganger flere rader i den samme tabellen).

Tabell nummer to (nøstet expand) er ett av casene jeg løste med Table i det første forslaget mitt. Forslaget mitt ble for knyttet til `<table>`-kode som innhold, så vi droppet det i første omgang. Hvis vi lager en generell ekspanderbar Table-rad bør det kunne løses med Jøkul-komponenter, med andre ord.

**Comment by piofinn** [comment]
Kan vi merke denne diskusjonen som løst etter #2652?

**Comment by wkillerud** [comment]
Vil tro det – vi kan gjenåpne om det skulle være udekkede behov :)
