### ISSUE TITLE
Feil: ContentToggle animerer ikke lenger

### ISSUE THREAD

**Issue by joms** [fremtind/jokul#2649]
## Feilbeskrivelse

Når man bytter verdi på ContentToggle i portalen animerer den ikke innholdet lenger :(

## Steg for å gjenskape

https://jokul.fremtind.no/komponenter/contenttoggle

**Comment by wkillerud** [comment]
Det gjelder nok bare i portalen. Når jeg fjerner memoiseringen som ble introdusert i #2620 er vi tilbake igjen med animasjon. Jeg synes å huske jeg la det til på grunn av dårlig brukeropplevelse i ett av eksemplene når jeg skulle se på koden og komponenten re-rendret. Men, viktigere at selve eksempelet fungerer, så får reverte om jeg ikke finner en workaround 😄
