### ISSUE TITLE
Feil: ExpandButton fungerer ikke som forventet uten å importere styling fra jkl-icons

### ISSUE THREAD

**Issue by hjellek** [fremtind/jokul#2656]
## Feilbeskrivelse

Ved å ta i bruk kun ExpandButton får man piler i begge retningene samtidig

![Screenshot 2022-01-12 at 13 54 57](https://user-images.githubusercontent.com/1640160/149144258-f4239a8c-023a-4ee8-bfea-75cf44df8b60.png)

## Steg for å gjenskape

Importer ExpandButton med CSS, uten å også importere CSS fra jkl-icons

https://codesandbox.io/s/flamboyant-wave-mfcec?file=/src/App.js

## Forventet oppførsel

ExpandButton viser pil i riktig retning, uten at man eksplisitt må importere jkl-icons

**Comment by wkillerud** [comment]
Jeg ser det ikke er nevnt i README-fila til `expand-button-react` – det burde det vært.

Vi har flere pakker (f. eks. datepicker, text-input) som krever at man importerer en avhengighet sin CSS i prosjektet sitt, for å bruke enkelte features:

```
import { TextInput, TextArea, BaseInputField } from "@fremtind/jkl-text-input-react";
import "@fremtind/jkl-text-input/text-input.min.css";
import "@fremtind/jkl-icon-button/icon-button.min.css";
```
> Legg merke til at vi også importerer stilen fra jkl-icon-button. Denne pakken blir automatisk installert som en avhengighet, og brukes til å vise eventuelle handlinger i tekstfeltet.

Tenker fixen her blir å legge til en liknende tekst i README om `icons`-pakka.

Alternativet ville vært å importere ikon-CSSen i `expand-button` og bundlet det med som en del av bygget, men da ender vi fort opp med å laste ned duplikat CSS.
