### ISSUE TITLE
Feil: For dårlig kontrast på overskriften i interaktive eksempel

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#2661]
## Feilbeskrivelse

Se https://jokul.fremtind.no/komponenter/summarytable i Dark Mode. Kontrasten mot bakgrunnen feiler på kontrastkrav AA for overskriften til eksempelet, og radene Livsforsikring og Rabatt.

## Steg for å gjenskape

1. Gå til https://jokul.fremtind.no/komponenter/summarytable
2. Bytt til dark mode i eksempelet
3. Sjekk kontrasten med devtools for overskriften Komponent

## Forventet oppførsel

Kontrasten mot bakgrunnen må minst være AA. Svaberg?

**Comment by wkillerud** [comment]
Må nok dessverre slette Cypress-snapshots for alle komponentene etter fixen

**Comment by kennidenni** [comment]
Dark: --help-text-color: #{jkl.$color-svaberg};
Light: --help-text-color: #{jkl.$color-stein};
