### ISSUE TITLE
Feil: Datepicker - siste tall delvis skjult

### ISSUE THREAD

**Issue by SercanSercan** [fremtind/jokul#2707]
## Feilbeskrivelse

Siste tallet i årstallet i datovelgeren er delvis skjult.

## Steg for å gjenskape

1. Gå til https://jokul.fremtind.no/komponenter/datepicker
2. Velg 'Utvidet velger'
3. Klikk på kalender ikon
4. Siste tallet i årstallet i datovelgeren er delvis skjult.

## Forventet oppførsel

Siste tallet i årstallet i datovelgeren bør være synlig nok.

**Comment by wkillerud** [comment]
@all-contributors please add @SercanSercan for bug report

**Comment by SercanSercan** [comment]
Jeg har undersøkt problemet i flere kilder og foreslår at vi bør fjerne inner/outer button i datepicker/year-selector input. Det er to grunner for dette:

Cross-browser compatibility er komplisert. For eksempel, se på beskjed i https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-inner-spin-button
Hvis vi prøver å style det, må vi designe det også. Jeg er usikker om dette blir prioritert i dag.
Derfor har jeg skrevet en mixin som fjerner default inner/outer button. Hvis vi trenger å gjøre samme for en andre input[type=number], kan vi bruke samme mixin.
