### ISSUE TITLE
Brødsmulesti 🍞

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#2720]
BM har en versjon som også er brukt som inspirasjon i SeOpp. Det er en kandidat for en Jøkul-komponent. Ta utgangspunkt i BMs løsning.

**Discussion:** #2716
**Pull request:** #2722 
**Designskisser:** [feat: brødsmulesti](https://www.figma.com/file/y9JtTf3whfTCHCdYSUXVQ5/branch/jjMeSoNPQJgTUIOyG3jGsK/J%C3%B8kul-bibliotek-2.0?node-id=4446%3A43575)

## 🎯 Sjekkliste

Gjør deg kjent med [huskelista for nye bidrag](https://jokul.fremtind.no/komigang/prosessen#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-), i tillegg til minstekravene for dokumentasjon i [Figma](https://www.figma.com/file/y9JtTf3whfTCHCdYSUXVQ5/J%C3%B8kul-bibliotek-2.0?node-id=3795%3A5927), i [portalen og på GitHub](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md).

### 🎨 For designere

-   [x] Laget et forslag inkludert dokumentasjon i en egen branch i Figma-biblioteket, og åpnet en merge request
-   [x] Sjekket at [auto-layout regler](https://jokul.fremtind.no/komigang/mobil), animasjoner og variants fungerer som de skal
-   [x] Merge request er blitt godkjent

### 🧑‍💻 For utviklere

-   [x] Laget et forslag inkludert dokumentasjon på en egen branch, og åpnet en pull request
-   [x] Testet [responsivitet](https://jokul.fremtind.no/komigang/mobil) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [ ] Pull request er blitt godkjent

**For ekstra ✨bonuspoeng✨ legger du ved eksempler på bruk, referanser til andre relevante komponenter og skriver et par kontrollspørsmål for bruk.**

**Comment by onordbo** [comment]
![image](https://user-images.githubusercontent.com/4263132/153585309-bb7b6527-dd37-416e-89cb-5efdd5fc3a77.png)
