### ISSUE TITLE
Text input i Figma – fixed width

### ISSUE THREAD

**Issue by Murstam** [fremtind/jokul#2747]
Text input har fixed width så man kan ikke dra i framen for å endre størrelse
<img width="560" alt="Skjermbilde 2022-02-22 kl  14 42 45" src="https://user-images.githubusercontent.com/47025023/155144956-45029dbf-e2db-461d-875b-3bf3216e3a50.png">
<img width="394" alt="Skjermbilde 2022-02-22 kl  14 42 21" src="https://user-images.githubusercontent.com/47025023/155144961-941b1fae-c3d1-4a22-9bd8-6ba4c6dd7485.png">
.

**Comment by onordbo** [comment]
Hm, kan du legge ved noen steg for å reprodusere buggen, @Murstam? Jeg finner ikke feilen når jeg tester Text Input selv.

![Kapture 2022-02-24 at 11 00 27](https://user-images.githubusercontent.com/4263132/155502691-9bd809f1-a052-4dfc-9a04-112d1e555ee6.gif)

**Comment by Murstam** [comment]
Stemmer @wkillerud  Med label, helplabel og errorlabel.

**Comment by onordbo** [comment]
Lukker denne da vi hotfixet Text Input for [en måned siden](https://www.figma.com/file/y9JtTf3whfTCHCdYSUXVQ5/J%C3%B8kul-bibliotek-2.0?version-id=1731196836&node-id=3423%3A76192&viewport=241%2C48%2C0.45). Se #2844 for ytterligere vedlikehold av biblioteket.
