### ISSUE TITLE
Feil: Ikonstørrelse endrer seg ikke parallelt med skriftstørrelse

### ISSUE THREAD

**Issue by fremtind-tony** [fremtind/jokul#2779]
## Feilbeskrivelse

Dersom en bruker endrer skriftstørrelse i nettleseren sin endrer ikke størrelsen på ikonene seg parallelt med dette.

## Steg for å gjenskape

Dette kan sees ved å endre skriftstørrelse f.eks. her: https://jokul.fremtind.no/komponenter/icons .

Se ellers vedlagte eksempler av dekningstabell for moped:
<img width="1468" alt="Very large" src="https://user-images.githubusercontent.com/54317847/156557482-b22cc326-8318-4d2d-8b6d-21c397f10599.png">
<img width="1415" alt="Very small" src="https://user-images.githubusercontent.com/54317847/156557489-20e6f13b-3576-4901-8287-3b6c82880705.png">
<img width="1572" alt="Medium" src="https://user-images.githubusercontent.com/54317847/156557492-d062217e-1416-4c71-bf93-6af47e83d9b2.png">

## Forventet oppførsel

At størrelsen på ikoner endrer seg parallelt med at skriftstørrelsen endrer seg.

## Systeminformasjon

Chrome 98 på macOS 12.2.1

**Comment by wkillerud** [comment]
Hei @fremtind-tony, takk for bugrapport! 

Det stemmer at de fleste eksemplene på ikoner på https://jokul.fremtind.no/komponenter/icons ikke skalerer med brukerens fontstørrelse. Størrelsene på `small`, `medium` og `large` er satt i pixler, men burde nok vært satt i en skalerbar enhet.

I mellomtiden finnes det en variant av ikoner som baserer seg på fontstørrelsen til teksten rundt. Kan dere prøve med `inherit`-varianten og se om det løser problemet? Hvis dere bruker komponentene fra `@fremtind/jkl-icons-react` så skal dette være standardvarianten.

I bildet under har jeg valgt `inherit` og satt fontstørrelsen til `6rem`:
![](https://user-images.githubusercontent.com/1223410/156559040-f4463482-b06b-466a-b640-f883a9e67135.png)

**Comment by wkillerud** [comment]
Input for #3066 @onordbo?

**Comment by wkillerud** [comment]
Dette skal være løst nå med de nye ikonene.

I skjermbildene under har jeg zoomet inn med nettleseren. Ikonene blir også zoomet.

![](https://user-images.githubusercontent.com/1223410/223750418-b1d54389-5507-4dfe-a69e-9df0ea547e94.png)
![](https://user-images.githubusercontent.com/1223410/223750417-50e9c864-fce1-4c62-9842-b3c866b5d6c2.png)
