### ISSUE TITLE
Checkbox mangler fra figma bibliotek

### ISSUE THREAD

**Issue by ivnai** [fremtind/jokul#2813]
## Feilbeskrivelse

Det finnes ikke-checkbox komponenter under "checkbox" i figma bibliotek
<img width="303" alt="Screenshot 2022-03-25 at 11 41 48" src="https://user-images.githubusercontent.com/93194579/160108642-c0b3837c-ed48-4ff7-825d-42e5ee5d9c13.png">

## Forventet oppførsel

Å finne komponent

**Comment by onordbo** [comment]
@ivnai: Jeg ser ikke ut til å kunne å reprodusere feilen. Er du sikker på a du søker i riktig versjon av biblioteket, og ikke en branch? [Her ligger Checkbox](https://www.figma.com/file/y9JtTf3whfTCHCdYSUXVQ5/?node-id=3423%3A45134) i dagens produksjonsbibliotek.

**Comment by onordbo** [comment]
Det ser ut til at det har gått en glipp i løpet av en publisering, som skjulte Checkbox fra komponentlisten. Den var tilgjengelig i biblioteket, men ikke synlig i søket. Nå er den fremme igjen 🎯
