### ISSUE TITLE
Feil: Rar skygge i ToggleSwitch

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#2823]
## Feilbeskrivelse

ToggleSlider har en ganske kraftig skygge rundt markøren som ikke matcher skisser

<img width="767" alt="Skjermbilde 2022-04-01 kl  13 14 27" src="https://user-images.githubusercontent.com/25739615/161253145-94f99143-cb54-4582-a8d5-8211eefe8ccd.png">

## Steg for å gjenskape

1. Gå til [Toggle-komponenten i portalen](https://jokul.fremtind.no/komponenter/toggleswitch)
2. Scroll ned til eksempelet for ToggleSlider
4. Se feilen

## Forventet oppførsel

Komponenten bør se ut som skissene

## Systeminformasjon

Mac OS Monterey 12.2.1, Firefox Developer Edition 99.0b4

**Comment by Mikaila94** [comment]
Jeg snakket med Joakim om dette før jeg slutta på Fremtind.
Så det er en issue I kfp-frontend-components, der jeg har lenke til ny skisse for dekningsoversikt-komponenten (som også inneholder Toggle-switch komponenten)
Espen skulle fikse bug i Toggle-komponenten, så jeg ba han inkludere design-endringene også , blant annet fjerning av skygge. Vet ikke om det er til den skyggen vi snakker om her, men da vet dere hvertfall det :D

**Comment by wkillerud** [comment]
Fikset i #2854
