### ISSUE TITLE
Feil bakgrunnsfarge ved feilmelding for Select

### ISSUE THREAD

**Issue by Saegrov** [fremtind/jokul#2874]
## Feilbeskrivelse

Bakgrunnsfargen for TextInput og Select er ulik 

## Steg for å gjenskape

Vis oss hvordan feilen kan gjenskapes:

1. Gå til https://jokul.fremtind.no/komponenter/select
2. Huk av "Feilmelding" og "Dark mode"
3. Se bakgrunnsfarge

Se skjermbilde med komponentene ved siden av hverandre:

![Screenshot 2022-05-13 at 15 09 19](https://user-images.githubusercontent.com/124469/168291690-26658eec-9104-4622-a64e-650d7c8d2457.png)

## Forventet oppførsel

Feilmeldingsfarger er konsistente på tvers av jøkul-komponenter.

**Comment by wkillerud** [comment]
Oops:

- [lyst tema](https://github.com/fremtind/jokul/blob/main/packages/select/select.scss#L37)
- [mørkt tema](https://github.com/fremtind/jokul/blob/main/packages/select/select.scss#L51)

Mørkt tema bruker fortsatt gammel feilfarge. Må endre Sass-koden og slette [snapshots i dark mode](https://github.com/fremtind/jokul/tree/main/packages/select-react/integration/__image_snapshots__).
