### ISSUE TITLE
Feil: TextArea med teller vises ikke riktig med: data-compactlayout="true"

### ISSUE THREAD

**Issue by Chrihenn** [fremtind/jokul#2931]
## Feilbeskrivelse

TextArea komponent med teller vises ikke riktig med: data-compactlayout="true"

## Steg for å gjenskape

1. Gå til TextArea eksempel https://jokul.fremtind.no/komponenter/textinput
2. Huk av på "Med teller"
3. Inspect  > Legg til data-compactlayout="true" i section element for eksempel:  
    `<Section class="jkl-portal-component-example" data-compactlayout="true" >`
4. Se feilen
![text-area-feil](https://user-images.githubusercontent.com/25311543/176184773-415232da-e36e-4d67-8657-ad720c6d15cb.png)

## Forventet oppførsel
At komponenten vises som når du ikke bruker data-compactlayout="true"

![text-area-riktig](https://user-images.githubusercontent.com/25311543/176184768-a2c32c1b-6e47-46b6-8336-98d764a5cf4b.png)

**Comment by wkillerud** [comment]
Takk for bugrapport!

@all-contributors please add @Chrihenn for bug
