### ISSUE TITLE
Feil: Kodeeksemplet for Tag i portalen har feil

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#2970]
## Feilbeskrivelse

Kodeeksemplet for Tag i portalen har feil når man velger "dismissable" i forhåndsvisningen: I stedet for riktige verdier for propen `dismissAction` vises `[object Object]`.

## Steg for å gjenskape

1. Gå til https://jokul.fremtind.no/komponenter/tag
2. Huk av for egenskapen "Dismissable" i eksemplet
3. Åpne kodeeksemplet
4. Se feilen

## Forventet oppførsel

Kodeeksemplet viser kode som gjenspeiler forhåndsvisningen.

**Comment by wkillerud** [comment]
Fikset i #2976
