### ISSUE TITLE
Forslag: eksponere prop på Table header for å skru av sticky headers

### ISSUE THREAD

**Issue by mariusingjer** [fremtind/jokul#2993]
Sticky table headers ser ikke alltid pent ut, burde være mulig å slå av her:

https://github.com/fremtind/jokul/blob/b1a7aaf6561304be8ac1c76bebe16e66e64a2770/packages/table-react/src/TableHeader.tsx#L22

workaround:

overstyr med css, men det er litt fiklete i lengden :-)

.jkl-table-header {
  position: static;
}

**Comment by wkillerud** [comment]
Jeg vurderer å fjerne hele `position: sticky` på grunn av #2965

**Comment by wkillerud** [comment]
Løst i #2990 ved å snu om på situasjonen så `jkl-table-header` ikke lenger er sticky. Har lagt til forslag til CSS om man likevel ønsker sticky headers, med påminnelse om å sette bakgrunnsfarge på headers i så fal.
