### ISSUE TITLE
Feil: Kan ikke klikke på valg i select dersom første valget wrapper på grunn av pil

### ISSUE THREAD

**Issue by Saegrov** [fremtind/jokul#3001]
## Feilbeskrivelse

Dersom det første valget i select-valgene er maks lengde for ikke å wrappe over to linjer, så er det ikke mulig å velge et annet av valgene.

Årsaken til at dette ikke fungerer er at når man får "mouse-down"-eventen på det valget man trykker på, så flytter pilen seg til det valget, og det skjer en layout-shift som gjør at "mouse-up havner på et annet element.

![Screen Recording 2022-08-09 at 08 02 37](https://user-images.githubusercontent.com/124469/183582038-2325f3a8-cd48-4547-8d4b-b2606de7a7a5.gif)

## Steg for å gjenskape

<!--
Vis oss hvordan feilen kan gjenskapes:

1. Gå til select på jøkul-portalen
2. Som førstevalg, legg inn "Pelletitten Langemann" (eller et annet valg som er akkurat bredden til select-boksen)
3. Åpne select.
4. Prøv å trykk på valget under "Pelletitten Langemann"
5. Man får da ikke valgt valget under (Samsung).

Merk at feilen kun oppstår dersom det ikke er valgt noe i select fra før.

## Forventet oppførsel

Man skal kunne trykke på valget under "Pelletitten Langemann". 
Helst så ønsker man at det ikke skjer en layout shift når pilen forsvinner.

**Comment by wkillerud** [comment]
@all-contributors please add @Saegrov for bug

**Comment by wkillerud** [comment]
cc @onordbo, trenger se på designet rundt pila

**Comment by onordbo** [comment]
Vi skisser et forslag rett i browseren _(takket være snappy prototyping skills alá @wkillerud),_ eksemplet vedlagt løser utfordringen vår med en visuell justering. Dark mode differansen er foreslått Snøhvit(tekst) over Stein(bakgrunn) på hover.

https://user-images.githubusercontent.com/4263132/183593572-5cc1afef-126b-4d1b-a866-4dd0cbdd97e1.mp4

cc @MonaHolm72 @Stakset
