### ISSUE TITLE
Ikonet på ErrorAlertMessage er tvetydig

### ISSUE THREAD

**Issue by ghost** [fremtind/jokul#3019]
ErrorAlertMessage har ein "X" på venstesida. Den er lett å feiltolke som ein dismiss-knapp, og me burde derfor endre ikonet til noko mindre tvetydig.
Bilde frå SeOpp:
![image](https://user-images.githubusercontent.com/89779105/184905420-c468c9ef-561f-4fa4-8ab5-e47da129d7cb.png)

Eg antar at viss me endrer ikonet i ErrorAlertMessage, burde me også endre det andre plassar det blir brukt (f.eks. ErrorMessageBox).

Design:
- Designe nytt ikon til ErrorAlertMessage

Kode:
- Impementere designet

**Comment by piofinn** [comment]
## Litt inspo

**Carbon Design System**
<img width="600" alt="Skjermbilde 2022-08-18 kl  13 09 45" src="https://user-images.githubusercontent.com/25739615/185384656-a23c0cf2-9bb8-4cc7-a383-8d4c050e05a4.png">

**GitLab Design System**
<img width="600" alt="Skjermbilde 2022-08-18 kl  13 18 05" src="https://user-images.githubusercontent.com/25739615/185384930-c14bf998-994f-4dea-bcb8-2f9402b5ed4e.png">

**Salesforce Lightning**
<img width="600" alt="Skjermbilde 2022-08-18 kl  13 19 05" src="https://user-images.githubusercontent.com/25739615/185384993-dff6353e-c427-4718-9fdf-f9aba5858c6c.png">

**Material Design Symbols**
<img width="210" alt="Skjermbilde 2022-08-18 kl  13 15 20" src="https://user-images.githubusercontent.com/25739615/185385045-3ff95fdf-7332-403c-965d-5c4c61d46298.png">

**Comment by onordbo** [comment]
> Keep it simple. Den enkleste løsningen er ofte den beste
> 
> ![Image](https://user-images.githubusercontent.com/64286523/218685219-91d11886-617e-44be-9b6e-c26dc842e4f3.png)

Nice! Dette blir fint og tydelig. Ser du har slettet komponenten med det forrige ikonet i stedet for å oppdatere innholdet, om vi merger denne vil vi få breaking changes og doble komponenter med manglende linker til master ute i andre filer. Kan du ta det nye ikonet ditt inn i en ny branch og _kun endre vektorinnholdet_ i det eksisterende `error` ikonet?

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/4263132/218690671-bfc5e573-fdc5-409a-af70-a491af4b8b29.png">

**Comment by onordbo** [comment]
@Slaine2: Ser også at ikonet ikke er slått sammen til ett vektor-lag, og elementene følger ikke navnekonvensjonene for ikonbiblioteket. Om det ikke er likt på tvers av alle ikon-komponentene vil ikke stilendringer vi gjør ute i komponentene bære over, og breaking følgefeil kan uforutsigbart oppstå. Se eksempel i screenshot under 😊


### Riktig ✅

![Image](https://user-images.githubusercontent.com/4263132/219019378-4d70ef2b-2d06-466a-a29a-cab903f4888c.png)


### Feil ⛔️
![Image](https://user-images.githubusercontent.com/4263132/219019484-c957ca62-a3a8-4623-8f8e-95aa29e43e17.png)

**Comment by onordbo** [comment]
@Slaine2: Strøkent! Da er denne klar for merging i Figma. @piofinn vil du ta inn det [nye ikonet](https://www.figma.com/file/DektfpgSnhwTVyrcXKwdem/branch/U7mm59uzTQDJgyIqVy3Zsk/Assets?node-id=1133%3A9&t=HR2wHdQqOL95caS3-11) i kodebasen?
