### ISSUE TITLE
Legg til Title Small typografinivå i Jøkul slik det ble foreslått

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3045]
Som tittelen sier, legg til Title Small. Vi ble enige på forum om å gå for forslaget i diskusjonstråden.

**Discussion:** https://github.com/fremtind/jokul/discussions/2994
**Pull request:** https://github.com/fremtind/jokul/pull/3046
**Designskisser:** [Core](https://www.figma.com/file/zDQv1SbhVdIBeyP1aDRzKb/fix%3A-typography%2Ftitle-small?node-id=602%3A497), [Components](https://www.figma.com/file/4LxyVaUrdIQEgDlYxsrqPt/fix%3A-title%2Ftitle-small?node-id=594%3A4252)

## 🎯 Sjekkliste

Gjør deg kjent med [huskelista for nye bidrag](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-), i tillegg til minstekravene for dokumentasjon i [Figma](https://www.figma.com/file/y9JtTf3whfTCHCdYSUXVQ5/J%C3%B8kul-bibliotek-2.0?node-id=3795%3A5927), i [portalen og på GitHub](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md).

### 🎨 For designere

-   [x] Laget et forslag inkludert dokumentasjon i en egen branch i Figma-biblioteket, og åpnet en merge request
-   [x] Sjekket at [auto-layout regler](https://jokul.fremtind.no/universell-utforming/responsivt-design), animasjoner og variants fungerer som de skal
-   [x] Merge request er blitt godkjent

### 🧑‍💻 For utviklere

-   [x] Laget et forslag inkludert dokumentasjon på en egen branch, og åpnet en pull request
-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [ ] Pull request er blitt godkjent

**For ekstra ✨bonuspoeng✨ legger du ved eksempler på bruk, referanser til andre relevante komponenter og skriver et par kontrollspørsmål for bruk.**

**Comment by onordbo** [comment]
Stilsettet i Core har blitt oppdatert med ekstra tittelnivå og godkjent ([figma-branch](https://www.figma.com/file/zDQv1SbhVdIBeyP1aDRzKb/fix%3A-typography%2Ftitle-small?node-id=338%3A1326)). Components/Text/[Title](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/Components?node-id=594%3A4252) vil få en boolean for Small på merge.

**Comment by onordbo** [comment]
[Components/Title/Small](https://www.figma.com/file/4LxyVaUrdIQEgDlYxsrqPt/fix%3A-title%2Ftitle-small?node-id=594%3A4252) lagt til.
