### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3052]
Hente inn tooltip fra KFP Components inn i Jøkul

**Discussion:** https://github.com/fremtind/jokul/discussions/2699
**Pull request:**  https://github.com/fremtind/jokul/pull/3053
**Forhåndsvisning:** https://jokul.fremtind.no/preview/tooltip/komponenter/tooltip
**Designskisser:** [components → feat: tooltip] https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/odWuOtTJUf8WuNHmVcBUc6/Components?node-id=1543%3A2046

## 🎯 Sjekkliste

Gjør deg kjent med [huskelista for nye bidrag](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-), i tillegg til minstekravene for dokumentasjon i [Figma](https://www.figma.com/file/y9JtTf3whfTCHCdYSUXVQ5/J%C3%B8kul-bibliotek-2.0?node-id=3795%3A5927), i [portalen og på GitHub](https://github.com/fremtind/jokul/blob/main/CONTRIBUTING.md).

### 🎨 For designere

-   [x] Laget et forslag inkludert dokumentasjon i en egen branch i Figma-biblioteket, og åpnet en merge request
-   [ ] Sjekket at [auto-layout regler](https://jokul.fremtind.no/universell-utforming/responsivt-design), animasjoner og variants fungerer som de skal
-   [ ] Merge request er blitt godkjent

### 🧑‍💻 For utviklere

-   [x] Laget et forslag inkludert dokumentasjon på en egen branch, og åpnet en pull request
-   [x] Testet [responsivitet](https://jokul.fremtind.no/universell-utforming/responsivt-design) og [UU](https://jokul.fremtind.no/universell-utforming/testguide) ([tastaturnavigasjon](https://jokul.fremtind.no/universell-utforming/tastatur), [skjermleser](https://jokul.fremtind.no/universell-utforming/skjermleser))
-   [ ] Pull request er blitt godkjent

**For ekstra ✨bonuspoeng✨ legger du ved eksempler på bruk, referanser til andre relevante komponenter og skriver et par kontrollspørsmål for bruk.**

**Comment by Slaine2** [comment]
Første Figma versjon er klar.

**Comment by onordbo** [comment]
PS: Vi kan til fordel bygge om Figma-komponenten til å ha enda færre varianter, men vi prioriterte å få en første fungerende versjon ut. Så kan vi eventuelt refactor/forenkle komponenten "under panseret" enda mer senere 😊

**Comment by wkillerud** [comment]
Allright, jeg kan oppdatere branchen

**Comment by wkillerud** [comment]
@Slaine2 er Figma-branchen ferdig, eller er det fortsatt design som må gjøres?

**Comment by onordbo** [comment]
> @Slaine2 er Figma-branchen ferdig, eller er det fortsatt design som må gjøres?

Jeg tror det mangler noe Figma-akrobatikk for å få komponenten til å spille på lag med plasseringsfleksibiliteten vi ønsker og auto-layout.

**Comment by Slaine2** [comment]
Måtte fortsatt kjempe med en bug, men fungerer nå perfekt og er ute i Figma Bibliotek.

**Comment by wkillerud** [comment]
Skal ta en siste oppdatering og sjekk av koden før vi merger den også. Regner med å ferdigstille i morgen.

**Comment by onordbo** [comment]
Hold an denne litt @wkillerud, vi snubla over litt mer stæsj i Figma.

**Comment by onordbo** [comment]
Components/Tooltip er [merget til main](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/Components?version-id=2392710460&node-id=13%3A6839&viewport=326%2C62%2C0.26) i Figma.

<img width="300" src="https://user-images.githubusercontent.com/4263132/192541819-2ad18418-f136-4caa-b678-564bac166f7b.png">

cc @wkillerud

**Comment by onordbo** [comment]
> Branchen er klar til visuell QA: [jokul.fremtind.no/preview/tooltip/komponenter/tooltip](https://jokul.fremtind.no/preview/tooltip/komponenter/tooltip)

- [ ] Det ser ut som det er veldig mange flere muligheter for plassering _(døpt Direction i Figma)_ i koden. Trenger vi så mange? cc @Slaine2 
- [ ] Ser ut til at det mangler en aktiv-state på ikonet
- [ ] Hvilke animasjonstokens er brukt her? Eller, hvordan sjekker hvilke som er i bruk selv?

**Comment by wkillerud** [comment]
- Har kuttet ned på antallet posisjoner
- Har lagt til aktiv-state ved hover, ikke bare tastaturfokus
- Ser det er lagt inn `easInOut`, som ikke er i easings-lista vår. Timing ser ut til å være `expressive`, 250ms.

**Comment by wkillerud** [comment]
Endret animasjon til `easeIn` og `100ms`, og la til den samme animasjonen på aktiv state i selve knappen .
