### ISSUE TITLE
Select sin popup trenger en tydeligere scrollindikator

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3057]
Fra Sven Håkon på Teams (17.08 i Support Designsystem):

> Jeg mener at lengden på dropdown burde være lik x linjer - 1/2 linje for å tydeliggjøre at det finnes mer innhold lenger ned. Slik den er i dag stopper den akkurat mellom to linjer og gir ingen indikator på at man kan scrolle for å vise flere alternativer.
>
> Se for eksempel:

<img width="320" alt="Skjermbilde som tilsynelatende viser alle elementer, men som kan scrolles." src="https://user-images.githubusercontent.com/1223410/188869209-5c4f661e-d8f4-467e-ae05-7a64238b8533.png">

## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** `Link til PR, ved endringer på kode`
**Designskisser:** `Link til Figma-branch, ved designendringer`
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

- [ ] Du har laget en branch i Figma og bedt om feedback
- [ ] Du har sjekket at alt av kode og tester kjører som det skal
- [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by wkillerud** [comment]
Dekkes kanskje av #3130 @piofinn ?

**Comment by piofinn** [comment]
Denne ble lukket av #3130
