### ISSUE TITLE
Select bør kunne støtte å merke flere valg (feat: multiselect)

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3063]
Det ble meldt inn et behov for en multiselect-komponent over sommeren. 

Vi bør utforske hvordan en sånn komponent kan se ut og fungere i Jøkul-drakt.

## 🔗 Praktiske lenker

**Designskisser:** `Link til Figma-branch, ved designendringer`
**Pull request:** `Link til PR, ved endringer på kode`
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

- [ ] Du har laget en branch i Figma og bedt om feedback
- [ ] Du har sjekket at alt av kode og tester kjører som det skal
- [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by leon-ho** [comment]
+1 

Flyt vil gjerne ha en multiselect med søk.

Rask skisse her:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/1818882/192789864-e4dac31f-6b49-4d0e-9a63-1b554e067b41.png">

For ekstra kompleksitet, gjerne med separasjon mellom tekst som vises i listen, og tekst som vises i valgt tag.

Deilig nøtt å tygge på mtp UU og tastaturnavigasjon ❤️

**Comment by wkillerud** [comment]
Trackes i #3282
