### ISSUE TITLE
Ta i bruk sommerens nye tilbakemeldingstjenste som backend for feedback i portalen

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3068]
Vi fikk demonstrert en ny backend for å samle tilbakemeldinger her tidligere i høst. Vår variant i dagens backend-løse portal er ikke spesielt innbydende til tilbakemeldinger. Med den nye løsningen trenger vi kanskje ikke noen egen backend?

- [ ] Finn ut hvordan integrere med den nye løsningen – kanskje vi kan få noen eksempler fra PM/BM?
- [ ] Gjør tingen

**Comment by onordbo** [comment]
Potensielt en god idé å ta med inn i **#reloaded**?

**Comment by wkillerud** [comment]
Lukker denne inntil videre. Vi har tatt snarveien via Mixpanel, så får vi heller ta i bruk denne om det blir et behov på sikt.
