### ISSUE TITLE
Feil: Issues startet fra figma-biblioteket.md malen blir ikke lagt til i Projects automatisk

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#3072]
Som tittelen sier.

## Steg for å gjenskape

1. Start et nytt issue fra 'Figma-biblioteket'
2. Submit
3. Project er ikke assignet automatisk

## Forventet oppførsel

Issues blir lagt til i Jøkul-prosjektet automatisk.

**Comment by onordbo** [comment]
Ser ut som det gjelder for alle issues (denne ble heller ikke lagt til), uavhengig av templates. Gjør jeg noe galt, @wkillerud?

**Comment by onordbo** [comment]
Ser ut som det er noe funky permissions greier som ikke er helt på stell: https://github.com/fremtind/jokul/actions/runs/3008916965

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/4263132/188923671-e57865c5-4ca2-44a9-a1bf-0006832a9e61.png">

**Comment by wkillerud** [comment]
@piofinn, noe du kan feilsøke som "eier" av fremtind-bot?
