### ISSUE TITLE
Visuell check av det nye biblioteket

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#3094]
Visuell check av det nye biblioteket.

Det er noen endringer i det nye Figmabiblioteket til det gamle (2.0). En rask sjekk er nødvendig for å se om dette er forbedringer eller om det ene eller det andre fortsatt må justeres.

Branch: https://www.figma.com/file/Zl7PdbUGjBxzJ1E2jd08Hn/VD-forum-2022?node-id=1%3A3

**Comment by onordbo** [comment]
Veldig bra gjennomgang! For enkelhetens skyld, kan du klistre inn bemerkelsene dine som en liste her? Enten som en kommentar eller direkte i innlegget ditt 😊 Det er mulig noen av tilbakemeldingene er såpass omfattende at man burde ta tak i de separat fra en enklere visuell justering.

**Comment by onordbo** [comment]
Lukker denne, da den har blitt delt opp i separate saker der det var hensiktsmessig.
