### ISSUE TITLE
Bytt issue-status til 'in progress' når en oppgave blir assignet

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#3098]
For å gjøre det enklere for alle å bevege forvaltningsoppgaver i design og kode gjennom brettet kan det være greit at et issue automatisk blir satt til `in progress` hvis man assigner seg selv _(eller noen andre?)_ til det. Akkurat nå kan kun deltakere med skrivetilgang i prosjekttavla flytte issues, det skaper en unødvendig terskel hvis noen utenfor Jøkul-teamet ønsker å lage eller plukke en oppgave.

**Comment by wkillerud** [comment]
Hvordan er dette etter arbeidet med å få alle inn i organisasjonen – er behovet like stort? Oppdaget at det ikke er trivielt å gjøre disse statusendringene via GitHub Actions. 

I tillegg er det ikke alltid sånn at en assign == jeg skal jobbe med dette _nuh_, hvertfall fra min side.

**Comment by onordbo** [comment]
Tror vi kan la det ligge enn så lenge @wkillerud, men det hadde vært smud å få til en eller annen form for mekanisme som gjør det lett å holde oversikt over hvem som har lagt noe inn _(uten å måtte åpne hver enkelt sak)_ og samtidig sørge for at vi ikke har uassignede tasks liggende lenge.

Kanskje vi kan nøye oss med å stille forfatteren av en issue som assignee automatisk når en sak opprettes?

**Comment by wkillerud** [comment]
Vi dropper å gjøre noe med dette
