### ISSUE TITLE
Select - Hover og valgt har samme utseende

### ISSUE THREAD

**Issue by Murstam** [fremtind/jokul#3099]
Raden som er valgt og raden man hovrer over har likt utseende. Tenker det burde være en forskjell, ser litt rart ut. 
<img width="271" alt="Skjermbilde 2022-09-12 kl  14 03 42" src="https://user-images.githubusercontent.com/47025023/189648938-a96d7e0f-2bce-4897-b664-68ae17fb42af.png">

**Comment by onordbo** [comment]
Enig! Dette oppstod nok i #3001, da markøren ble fjernet i en hotfix av et interaksjonsproblem. Har du noen tanker om hvordan det burde løses visuelt, @Murstam? Vi kan eventuelt reintrodusere en markør, og fjerne bakgrunnsfargen for det elementet som er valgt—men beholde det for hover/fokus.

@piofinn / @wkillerud: Hvis vi skal reintrodusere en markør må vi kanskje rydde litt i implementeringen, så vi ikke støter på samme utfordring?

**Comment by piofinn** [comment]
Se mitt forslag til løsning i PR'en lenket over (#3103). Der har jeg både fikset problemet med at to verdier virker markert, og lagt til en markør for det *valgte* elementet. Det går også an å bare få inn den første fiksen hvis man ikke vil ha markøren.

**Comment by onordbo** [comment]
**✏️ Skisse:** [fix: select/markør](https://www.figma.com/file/y2xtjVJ7FBI9mneGDnl7tk/fix%3A-select%2Fmark%C3%B8r-og-error-handling?node-id=1149%3A9613)

Følger opp @piofinn's forslag satt i Figma-komponenten. Vi kan selvfølgelig endre ikonet til hvaenn vi måtte ønske om pil ikke er hensiktsmessig. Hva synes du @Murstam?

**Comment by Murstam** [comment]
På en måte så kommer jo det valgte elementet veldig godt frem ved at det står i øverst i komponenten, så man kan jo spørre seg om det er nødvendig å markere i listen? Hvis vi mener det, så tror jeg at en checkmark er tydeligere og mer i tråd med hvordan det løses i den innebygde løsningen. Vi vi bruker jo pil mye i navigasjon.

**Comment by onordbo** [comment]
> På en måte så kommer jo det valgte elementet veldig godt frem ved at det står i øverst i komponenten, så man kan jo spørre seg om det er nødvendig å markere i listen? Hvis vi mener det, så tror jeg at en checkmark er tydeligere og mer i tråd med hvordan det løses i den innebygde løsningen. Vi vi bruker jo pil mye i navigasjon.

Jeg er enig, det er ikke sikkert vi trenger en markør i det hele tatt, og personlig ville jeg nok gått den veien da det ser renere og ryddigere ut. Hvis vi skal gå ned ruta med markør burde vi nok matche native mest mulig. Slik kan det se ut med dagens checkmark 👇 

<img width="650" src="https://user-images.githubusercontent.com/4263132/189891225-4d5c27e7-fe88-4c94-8278-6c1a0fea9375.png">

_Vi har nok et behov for å visuelt justere selve ikonet så det er plassert litt bedre på griddet sitt, men det er en egen/separat sak vi må se på._

**Comment by onordbo** [comment]
Alternativt kunne vi ha gått en tredje vei og gjort det enda tydeligere hvilket valg som er satt i feltet ved å legge til et ikon i toppelementet i stedet for selve listen? Det er ganske langt unna native da. 🤷🏻‍♂️

<img width="650" src="https://user-images.githubusercontent.com/4263132/189892515-1c81de62-b458-4731-b2f1-b9684718c88d.png">

![image](https://user-images.githubusercontent.com/4263132/189892515-1c81de62-b458-4731-b2f1-b9684718c88d.png)

**Comment by onordbo** [comment]
> Hadde ellers vært spennende å vite om det faktisk bare er jeg som ikke synes det er superåpenbart hva som er valgt etter å ha sett litt rundt i listen 😅

@piofinn: [Nyeste forslag](https://jokul.fremtind.no/preview/feat/select-focus-handling/komponenter/select) funker for meg.

@Murstam: Hva synes du? Skal vi la det være som det er, eller skal vi utforske en av retningene ovenfor?

Vi kan evt ta det med på forum i morgen?

**Comment by leon-ho** [comment]
<img width="278" alt="image" src="https://user-images.githubusercontent.com/1818882/191255754-12a1c13b-8bbf-427c-8abf-18633523761d.png">

Det er mulig man ikke ser hele valget pga maksbredde, og da kan det være greit å se hele teksten i listen?

**Comment by Stakset** [comment]
![Screenshot 2022-09-20 at 14 19 37](https://user-images.githubusercontent.com/72978199/191256086-60d4a42c-b660-44a0-82ff-e57738acade2.png)

**Comment by Murstam** [comment]
Syns den som er i Jøkul nå fungerer bra 👍
