### ISSUE TITLE
Hook eller annet hjelpemiddel for animasjon FLIP/exit uten eksterne biblioteker

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#3100]
I dag trekker vi veldig fort inn [Framer Motion](https://www.framer.com/motion/) (eller lignende) for å animere elementer som bytter posisjon eller går inn/ut av DOM. Det er for så vidt ikke noe galt i det, men det drar potensielt med ganske store kodemengder for til tider enkle animasjoner.

Det hadde vært fint å kunne tilby ett eller flere hjelpemidler for å animere objekter som går inn/ut av DOM eller endrer posisjon (vha. [FLIP](https://css-tricks.com/animating-layouts-with-the-flip-technique/) eller andre etablerte mønstre). Alternativt finne en standardisert løsning via et bibliotek som ikke er så tungt som Framer Motion.

## 🎯 Sjekkliste

- [ ] Du har laget en branch i Figma og bedt om feedback
- [ ] Du har sjekket at alt av kode og tester kjører som det skal
- [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by wkillerud** [comment]
Noen ressurser:

- [Om FLIP-animasjoner og React](https://css-tricks.com/everything-you-need-to-know-about-flip-animations-in-react/) (lifecycles å huke seg på, f. eks.).
- [Salesforce om implementering av animasjoner](https://www.lightningdesignsystem.com/kinetics/implementing-kinetics/) (CSS > JS. Hvis JS, native WAAPI > GreenSock [pga eksisterende bruk, i vårt tilfelle Framer] > Lottie).
- [WAAPI på MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API)
- [react-flip-toolkit](https://github.com/aholachek/react-flip-toolkit) (prior art, API-design for Jøkul-hooks).
- [Motion One](https://motion.dev/guides/quick-start) (potensiell reserveløsning, bruker WAAPI under panseret).

**Comment by wkillerud** [comment]
Ramlet over [React Transition Group](https://github.com/reactjs/react-transition-group), og ser [MUI bruker det til blant annet å tilby noen Transition-komponenter](https://mui.com/material-ui/transitions/) som [Zoom](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Zoom/Zoom.js)

**Comment by leon-ho** [comment]
Hoi - Til info: Vi kikker på animasjoner i Flyt, så ta gjerne en prat med utviklerne i Flyt-teamet om dere har noen best practices eller annet. Jeg har nevnt dette for noen av Flyt-utviklerne, så mulig de dukker opp i designsystemforum snart for å ta en prat.
