### ISSUE TITLE
Feil: table-react krever props som skal være optional

### ISSUE THREAD

**Issue by henrikhermansen** [fremtind/jokul#3108]
Etter bump av table-react fra 7.4.3 til 9.0.3 får jeg beskjed om at Table må ha med props align, bgcolor, border, frame og rules.
Det samme har skjedd for minst ett annet team på huset.

## Steg for å gjenskape
Hittil har jeg ikke klart å gjenskape dette i et "rent" miljø.

## Forventet oppførsel
Jeg forventer at ovennevnte props er optional.

## Systeminformasjon
react: 17.0.2
jkl-core: 11.0.2
jkl-table-react: 9.0.3
typescript: 4.4.4 / 4.8.3 (prøvd begge)
Har kjørt rm -rf node_modules og slettet lockfile for full reinstall, uten at det hjalp.

**Comment by henrikhermansen** [comment]
Kanskje denne typen har noe med saken å gjøre? Den er brukt som en del av typingen til Table. Her er det noen props som ikke er optional.
```
interface HTMLTableElement extends HTMLElement {
    /**
     * Sets or retrieves a value that indicates the table alignment.
     * @deprecated
     */
    align: string;
    /** @deprecated */
    bgColor: string;
    /**
     * Sets or retrieves the width of the border to draw around the object.
     * @deprecated
     */
    border: string;
```

**Comment by piofinn** [comment]
> Kanskje denne typen har noe med saken å gjøre?

Svarer her også, så ikke info blir borte i en Teams-tråd: Interfacet `HTMLTableElement` skal ikke blir brukt direkte, men gjennom `TableHTMLAttributes` der alle disse propsa er markert som optional. Men det kan hende måten typene blir hentet ut på i dag skaper en mulighet for blanding av props på en måte.

Jeg skal se om jeg får tatt en titt på å få forenklet de eksporterte typedefinisjonene litt!
