### ISSUE TITLE
Feil: Søkbar select med "tom" liste har for tykk bunnstroke og mangler runde hjørner

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#3111]
Tittelen sier det meste. Gjelder både Comfortable og Compact.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/4263132/190404544-36120f9c-033d-43c8-9d15-9b6108921496.png">

## Steg for å gjenskape

1. Gå til https://jokul.fremtind.no/komponenter/select
2. Slå på 'med søk'
3. Skriv noe tullete langt eller feil
4. ???
5. Profit

## Forventet oppførsel

Se bildet nedenfor 👇 _(2pt granitt stroke, 2pt border radius)_

<img width="600" src="https://user-images.githubusercontent.com/4263132/190405995-15f367fb-f6ba-490f-bd38-0d5299ae9974.png">

**Comment by wkillerud** [comment]
@hegebjo denne må du gjerne ta en titt på når du har tid. Tips fra Pio: "problemet er at listen er åpen, men tom".
