### ISSUE TITLE
Pattern: Menu

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#3114]
"Ny" komponent for Menu på bakgrunn av #3049. Vi går for mønster-approachen da det [virker litt rart](https://github.com/fremtind/jokul/discussions/3049#discussioncomment-3572590) å tilby bare `<Menu Item />` frittstående. Se discussion for ytterligere historikk.

## 🔗 Praktiske lenker

**Discussion:** https://github.com/fremtind/jokul/discussions/3049
**Designskisser:** [patterns → feat: menu](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/nGpYlGGJBZGbyJHl7A0SMu/Patterns?node-id=1035%3A8630&viewport=532%2C427%2C0.51)
**Pull request:** `Link til PR, ved endringer på kode`
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`

## 🎯 Sjekkliste

- [x] Du har laget en branch i Figma og bedt om feedback
- [ ] Du har sjekket at alt av kode og tester kjører som det skal
- [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tag

**Comment by wkillerud** [comment]
Duplikat av #3440
