### ISSUE TITLE
Breadcrumb

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#3128]
Branch: https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/Xuf2hZInbmUYoKRkbK7sKz/Components?node-id=552%3A8990

### 🎯 Sjekkliste

- [x] Du har sjekket at alt av auto-layout, animasjoner, o.l er satt opp riktig
- [x] Du har sjekket at designet matcher kodekomponenten (visuelt, animert og interaktivt)
- [x] Du har sjekket at endringen din ikke har overrides (hvis importerte komponenter er i bruk)
- [ ] Du har gjort arbeidet i en Figma-branch og bedt om feedback

**Comment by Slaine2** [comment]
@wkillerud I portalen er det foreløpig også en hover for ikke-klikkbare elementer. Er det en grunn til dette eller kan vi fjerne dette?

**Comment by onordbo** [comment]
Merget inn [her](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/Components?version-id=2392607368&node-id=2%3A2&viewport=-78%2C267%2C0.35). Skal vi la denne issuen befatte sammensatte crumbs til en gruppe breadcrumbs?

cc @Slaine2

**Comment by onordbo** [comment]
Her er et forslag: https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/e0zOSBvs3NkgsL09F9x4AC/Patterns?node-id=1461%3A10364&viewport=50%2C366%2C0.73

**Comment by onordbo** [comment]
@piofinn: har du et godt navn til en gruppe breadcrumbs?

**Comment by Slaine2** [comment]
A trail of Breadcrumb? ✨ 🤣

**Comment by wkillerud** [comment]
> @wkillerud I portalen er det foreløpig også en hover for ikke-klikkbare elementer. Er det en grunn til dette eller kan vi fjerne dette?

Den siste "crumb" er også en link, til den nåværende siden. Jeg husker ikke 100% hvorfor vi valgte at den skal være en link. Jeg finner eksempler både med link og med bare tekst.

Med (eller som en option):

- [Chakra UI](https://chakra-ui.com/docs/components/breadcrumb)
- [MUI](https://mui.com/material-ui/react-breadcrumbs/)
- [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current)


Uten:

- [Carbon](https://carbondesignsystem.com/components/breadcrumb/usage/) (skjuler også current page by default, med option om å vise)
- [Eufemia](https://eufemia.dnb.no/uilib/components/breadcrumb/) (btw, 🤯 over "back link is just a single breadcrumb")
- [~~Figma~~ Adobe Experience Manager](https://aemcomponents.dev/content/core-components-examples/library/core-structure/breadcrumb/hidden/level-1/level-2/breadcrumb.html)

**Comment by Slaine2** [comment]
@wkillerud Skall vi ikke bare fjerne det?

**Comment by Slaine2** [comment]
@wkillerud synes for Fremtind er det rett uten. Er det mulig å fjerne dette i Portal? Da er det det samme i design som i kode.

**Comment by wkillerud** [comment]
Vi kan godt fjerne det for min del. Kanskje spørre rundt på forum i morgen om det er greit for de som bruker komponenten? @Slaine2

**Comment by onordbo** [comment]
@wkillerud: Vi konkluderte vel i forum med at _current_ breadcrumb ikke trenger å ha utseendet til `Link` under hover, etc men av UU grunner må den oppføre seg som en? _(Focus state, etc)_ cc @joms

**Comment by wkillerud** [comment]
Har notert ned det samme @onordbo, at vi fjerner hovereffekten men lar resten være som det er nå i dag.

**Comment by wkillerud** [comment]
Preview: https://jokul.fremtind.no/preview/fix/breadcrumb-hover/komponenter/breadcrumb

PR er godkjent.

**Comment by onordbo** [comment]
@wkillerud: LGTM 👍

**Comment by onordbo** [comment]
@wkillerud: LGTM 👍
