### ISSUE TITLE
Legg til styring av maks. antall valg i Select

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#3130]
Nedtrekkslisten på Select kan fort blir lang, slik at den stikker utenfor skjermbildet og brukere ikke får med seg alle valgene. Det bør legges til funksjonalitet for å begrense antallet valg som er synlig før listen scroller, og settes en fornuftig standard, slik at det er lettere å bruke listen.

Ref. diskusjon i DS-forum.

## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** #3127 
**Designskisser:** [Link til Figma-branch](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/vPvxGh8Fv2euZNOXv4kltJ/Patterns?node-id=354%3A7537)
**Forhåndsvisning:** https://jokul.fremtind.no/preview/feat/select-scrolling/

## 🎯 Sjekkliste

- [x] Du har laget en branch i Figma og bedt om feedback
- [x] Du har sjekket at alt av kode og tester kjører som det skal
- [x] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by onordbo** [comment]
Ser bra ut 👍  Det er kanskje litt mange valg påslått som standard i Figma? Skjønner at det er for å vise når "clip" slår inn ved fem valg, men jeg lurer på om vi til fordel kan justere den litt ned og beholde clip'en så komponenten blir litt mer håndterlig i skisser.

**Comment by Slaine2** [comment]
- Nice 👍  Spørsmålet er om man ønsker å tilby mer prototyping «out of the box» eller om dette er overflødig.

- i portalen under eiendommer er det et nytt søk. Jeg tror vi kan fjerne det

**Comment by onordbo** [comment]
> * Nice 👍  Spørsmålet er om man ønsker å tilby mer prototyping «out of the box» eller om dette er overflødig.

Det følger med litt prototyping ut av boksen siden Select importerer Input. I de tilfellene hvor man skal lage en Figma-prototype med Select ser jeg for meg at det er mer hensiktsmessig å sette opp klikkfunksjonen selv, siden man uansett må legge inn eget innhold for at det skal bli realistisk.

**Comment by onordbo** [comment]
Vi kjører som det er enn så lenge. Figma er merget med endringene dine @piofinn.

<img width="235" alt="image" src="https://user-images.githubusercontent.com/4263132/192500241-2cacb255-59f2-47cd-afaa-cc26857c3ce2.png">
