### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#3132]
Justering og oppdatering av Accordion i design og kode.

## 🔗 Praktiske lenker (om tilgjengelig)

**Designskisser:** [Components → fix: accordion](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/QWg0IZP9gxYcHJG3gFZheR/Components?node-id=581%3A4533&viewport=138%2C188%2C0.45)
**Forhåndsvisning:** https://jokul.fremtind.no/preview/chore/trekkspill/komponenter/accordion
**Pull request:** `Link til PR, ved endringer på kode`

## 🎯 Sjekkliste

- [x] Du har laget en branch i Figma og bedt om feedback
- [x] Du har sjekket at alt av kode og tester kjører som det skal
- [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by onordbo** [comment]
Det ser ut til å ligge to versjoner av hele komponenten i Figma. Hva er det du har endret, og hvilken er det som gjelder?

**Comment by Slaine2** [comment]
Accordion er tilgjengelig med ny padding og pil til høyre.

Feel free to test 🥇

**Comment by onordbo** [comment]
> Accordion er tilgjengelig med ny padding og pil til høyre.
> 
> Feel free to test 🥇

@Slaine2: Nå nærmer det seg! 👏 La inn en Figma-spesifikk kommentar på branchen din ang. hover-states og animasjon 😊

**Comment by onordbo** [comment]
Jeg har sett litt nærmere på endringsforslaget i Figma, og tror det er lurt at vi samkjører oss om bruk og behov. Setter denne 'On Hold' inntil videre. cc @Slaine2

**Comment by onordbo** [comment]
Oppdaterer denne i kjølvannet av dagens forum. Endringene på Accordion i Figma har ført til designvalg som påvirker kodekomponenten. Skisser er på vei 📝 

- [ ] Vi flytter pilen fra venstre til høyre side, og toppjusterer den når tittelen er mer enn én linje
- [ ] Juster spacingen i henhold til skissene (eksakte verdier kommer når skissene er klare)

cc @wkillerud

**Comment by onordbo** [comment]
Figma-komponenten er oppdatert og [klar for review](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/QWg0IZP9gxYcHJG3gFZheR/Components?node-id=581%3A4533&viewport=138%2C188%2C0.45) 🎯 


**Endringer** 👇 
- [ ] flytt pilen fra venstre til høyre
- [ ] toppjuster pilen hvis tittelen er mer enn en linje
- [ ] oppdater hover-animasjonen (y: 4pt +/- ved hover)
- [ ] oppdater horisontal padding (16/8)

**Comment by onordbo** [comment]
@wkillerud: Ser bra ut. Hva synes du @Murstam?

**Comment by wkillerud** [comment]
https://jokul.fremtind.no/preview/chore/trekkspill/komponenter/accordion

**Comment by onordbo** [comment]
Accordion i Figma er [merget](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/Components?version-id=2450168682&node-id=211%3A4712&viewport=259%2C435%2C0.3).



![Image](https://user-images.githubusercontent.com/4263132/195102170-99823118-38a0-4f6d-8843-880efe980944.png)
