### ISSUE TITLE
Feat: Microanimations i Figma

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#3134]
For øyeblikket har vi fortsatt noen få mikroanimasjoner i de nye komponentene. Vi bør forbedre dette.

[**Branch:** `Legg til Figma-link (hvis du har laget et forslag)`](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/LMX4eeVp6yPdKyAOoSLqen/Components?node-id=0%3A1)

### 🎯 Sjekkliste

- [ ] Du har sjekket at alt av auto-layout, animasjoner, o.l er satt opp riktig
- [ ] Du har sjekket at designet matcher kodekomponenten (visuelt, animert og interaktivt)
- [ ] Du har sjekket at endringen din ikke har overrides (hvis importerte komponenter er i bruk)
- [ ] Du har gjort arbeidet i en Figma-branch og bedt om feedback

**Comment by ivnai** [comment]
@Slaine2 kan du vær så snill tagge meg, dette er test. takk!

**Comment by onordbo** [comment]
Duplikat av #3073
