### ISSUE TITLE
Skjemakomponenter i Figma

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#3136]
Vi trenger en praktisk måte å tilby fleksible skjemakomponenter (som også er enkle å oppdatere). Mange typer input fremkommer ofte med en label og en hjelpetekst/feilmelding. Noen typer burde kanskje ha dette innebygget, og andre ikke.

I tillegg må vi finne en praktisk måte å deale med spacing på tvers av label størrelser. På generell basis prøver vi å unngå å bygge spacing rett inn i frittstående komponenter. I en perfekt verden løser vi dette med en token, men Figma har ingen praktisk måte å løse dette uten en plugin (enda).

**Figma:** [Patterns → feat: input-group](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/07eafxwxphgSyoGa0fZXUi/Patterns?node-id=0%3A1)

### 🎯 Sjekkliste

- [ ] Du har sjekket at alt av auto-layout, animasjoner, o.l er satt opp riktig
- [ ] Du har sjekket at designet matcher kodekomponenten (visuelt, animert og interaktivt)
- [ ] Du har sjekket at endringen din ikke har overrides (hvis importerte komponenter er i bruk)
- [ ] Du har gjort arbeidet i en Figma-branch og bedt om feedback

**Comment by Murstam** [comment]
Samme problematikken gjelder også for avstander mellom checkbokser og radio buttons når vi har fjernet innebygget spacing. Man får ingen hjelp til å definere riktig spacing og det er nok ikke mange som husker at det skal være 16px vertikal spacing mellom hver checkboks.

**Comment by onordbo** [comment]
**Konkulsjon fra forrige forum:** Vi utforsker om en InputGroup / Field Group komponent _(kombinert med noen eksempler?)_ kan løse behovet. Kommenter gjerne om det er noe jeg har glemt å legge til _(cc @Murstam)_

**Comment by onordbo** [comment]
Input/Field Group er [underveis](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/07eafxwxphgSyoGa0fZXUi/Patterns?node-id=224%3A2126&viewport=1034%2C500%2C0.38), men ikke helt i boks enda. Vi må finne ut av hvordan API'et (komponentvalgene) eventuelt skal være. Vi kan potensielt utforske en separasjon av "rå" komponenter og "skjemakomponenter" så det blir lettere å søke etter den komplette/sammensatte varianten av de mest brukte typene og kombinasjonene av inputs.

**Comment by onordbo** [comment]
Første forslag til Input Group er klar 🎯 Sammen med komponenten har vi laget eksempler med Radio Button og Checkbox, da disse ofte opptrer samlet. Selve komponenten er bygget opp med en `slot` og tilhørende eksempler som egne komponenter. Du finner ferdige eksempler fra Jøkul i nedtrekksmenyen `Input Type` _(via Figma's nye Instance Swap funksjon, Preferred Components)_ som vist nedenfor. Siden komponenten er bygget med en slot kan du velge å bruke medfølgende eksempler, eller sette inn eget innhold etter behov.

![Image](https://user-images.githubusercontent.com/4263132/196351395-0573225c-9d94-4bf9-aef0-f4aa16bed6ef.png)

**Skisse:** [Patterns → feat: input-group](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/07eafxwxphgSyoGa0fZXUi/Patterns?version-id=2480783043&node-id=224%3A581&viewport=706%2C374%2C0.33) (cc @fremtind/design)

**Comment by Murstam** [comment]
Ved første øyekast så har avstandene mellom radio buttons og og checkboxer krympet fra 16px til 8px.

**Comment by ivnai** [comment]
Så bra! Ser først at noen av spacingene bør være proporsjonelle. 
De mellom label og slot boks (f.eks desktop(8), da mobil(4) og compact(2), nå er de alle 8). 
<img width="1073" alt="Screenshot 2022-10-18 at 12 17 05" src="https://user-images.githubusercontent.com/93194579/196406419-73ca3ad9-57e8-4ce8-83f6-37a454154c5e.png">


Og så spacing mellom Radios i Row hos d/m/c.
<img width="1122" alt="Screenshot 2022-10-18 at 12 17 33" src="https://user-images.githubusercontent.com/93194579/196406472-131d98f8-7796-4d24-8c12-af6617b9934e.png">


Lurer på om det er lurt å begrense bruk av kombo: når man bruker Input Group Compact, så blir det mulig å bruke kun Radio Row Compact inni slot.

**Comment by shvoldum** [comment]
Best practice for radio buttons (eller valg generelt) er å stable dem loddrett; I dag bruker vi mye vannrett stabling, især for 'Ja/Nei'-spørsmål. Er dette spikret i Jøkul, eller bare noe som har blitt vanlig hos oss? Jeg spør fordi det kan bli rart i skjemaer hvor det også er lengre svaralternativer, og det følgelig blir en kombinasjon.

![Skjermbilde 2022-10-18 kl  13 23 30](https://user-images.githubusercontent.com/17295531/196416457-85c7aa89-2c6b-4556-875b-ed41b3b4b15b.png)

**Comment by onordbo** [comment]
> Ved første øyekast så har avstandene mellom radio buttons og og checkboxer krympet fra 16px til 8px.

@Murstam: Bra catch! Sticky tetthet-innstillinger fra eksempelet i portalen ga meg et litt _vel kompakt_ (hehe) referansepunkt. Fiksa det nå.

> Så bra! Ser først at noen av spacingene bør være proporsjonelle.
De mellom label og slot boks (f.eks desktop(8), da mobil(4) og compact(2), nå er de alle 8).

@ivnai: De skal være spacet proporsjonalt allerede, men det er knyttet til hvilken `Group Title` som er i bruk, og har følgende verdier fra skalaen 16/8/4 for Large/Medium/Small.

**Comment by onordbo** [comment]
@shvoldum: Vi har ingen etablert/spikret standard for hvordan feltgruppe-layout, utover litt generell dokumentasjon av skjemadesign[^2].

I utgangspunktet skal ikke _enkeltkomponenter_ fra designsystemet være løsningsutskrivende eller førende for øvrig layout, da det er opp til den enkelte designer å definere komposisjonen. Når det er sagt så er denne komponenten et slags _mønster_, og det burde følge med et par gode tips og råd om bruk. 


Enn så lenge er [dette dokumentasjonen](https://jokul.fremtind.no/komponenter/radiobutton#:~:text=du%20p%C3%A5%20GitHub.-,Bruk,av%20et%20forh%C3%A5ndsvalg.%20Da%20kan%20vi%20sette%20opp%20radioknapper%20uten%20forh%C3%A5ndsvalg.,-Fikk%20du%20gjort) som medfølger Radio Button fra Jøkul.

> _En gruppe radioknapper kan enten settes opp under eller ved siden av hverandre. Det er mest brukervennlig å sette dem opp vertikalt. I mange tilfeller er det viktig at brukeren selv velger, uten å bli påvirket av et forhåndsvalg. Da kan vi sette opp radioknapper uten forhåndsvalg._

Dette ble skrevet for en god del år siden[^1] og trenger nok en oppdatering. I tillegg handler det @shvoldum nevner om hvordan man grupperer flere valg sammen, og ikke en enkelt radio button. Mat for designsystemforum, kanskje?




[^1]: @piofinn om [bruk av Radio Button](https://github.com/fremtind/jokul/blame/main/packages/radio-button-react/documentation/RadioButton.mdx#L31-L34) (~3 år siden).
[^2]: [Skjemadesign](https://jokul.fremtind.no/profil/skjemadesign) i Fremtind/Jøkul.

**Comment by onordbo** [comment]
Vi publiserer [Input Group](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/Patterns?node-id=224%3A2126&viewport=863%2C495%2C0.35) som den er i Figma nå og ser hvordan den funker. Prøv den ut og gi litt feedback, så justerer vi underveis om noe mangler eller må endres på. I første omgang har jeg fjernet eksemplene med rader av enkeltvalg, da vi har særdeles få slike eksempler i bruk _(såvidt jeg vet)_. Si fra om det trengs, så legger vi det til igjen!

![Image](https://user-images.githubusercontent.com/4263132/200280232-5146bc7d-0ba6-4b58-b06b-0df27c6b4508.png)

cc @fremtind/design
