### ISSUE TITLE
Feil: Det går ikke an å scrolle i TextArea som starter åpent

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#3140]
Det går ikke an å scrolle i et TextArea som starter åpent dersom det er mer tekst enn det som får plass i den.

## Steg for å gjenskape

1. Gå til https://jokul.fremtind.no/komponenter/textinput og scroll ned til TextArea-eksemplet
2. Velg "Starter åpen"
3. Skriv inn masse tekst slik at det  blir flere linjer enn det er plass til (du kan bruke linjeskift)
4. Prøv å scrolle i feltet
5. Se feilen

## Forventet oppførsel
Det bør gå an å scrolle i feltet, sånn som i de andre variantene

## Systeminformasjon
Testet i både Safari og Chrome i MacOS 12.6

**Comment by onordbo** [comment]
**Pro(tal)-tip:** Alle komponenteksempler har fått id så man kan linke direkte til de 👀

Eks: https://jokul.fremtind.no/komponenter/textinput#text-area 🔗
