### ISSUE TITLE
Fix: Datepicker i Figma

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#3166]
endring:
- Avstand mellom plukker og inndatafelt
- Farge i mørk modus
- Bold tall på valgt i hvit sirkel
- Current har ikke sirkel
- Kanskje med label og hjelpetekst?

**Branch:** https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/E3sk2kdqLqfmsXzWSr2Wrn/Patterns?node-id=209%3A580

### 🎯 Sjekkliste

- [ ] Du har sjekket at alt av auto-layout, animasjoner, o.l er satt opp riktig
- [ ] Du har sjekket at designet matcher kodekomponenten (visuelt, animert og interaktivt)
- [ ] Du har sjekket at endringen din ikke har overrides (hvis importerte komponenter er i bruk)
- [ ] Du har gjort arbeidet i en Figma-branch og bedt om feedback

**Comment by onordbo** [comment]
@Slaine2: Kan du legge inn hva som eventuelt er feil og hva du vil endre det til? Detaljene du har lagt inn er uspesifikke. Flytter til `On Hold` inntil videre.
