### ISSUE TITLE
Fix: Feedback i Figma

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#3168]
Å endre:

- Padding følger ikke lengre Spacingskala

- Legg til smileys igjen

**Branch:** [`Legg til Figma-link (hvis du har laget et forslag)`](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/eUVBQRgLUjdVPCkcX0bIlC/Patterns?node-id=210%3A582)

### 🎯 Sjekkliste

- [ ] Du har sjekket at alt av auto-layout, animasjoner, o.l er satt opp riktig
- [ ] Du har sjekket at designet matcher kodekomponenten (visuelt, animert og interaktivt)
- [ ] Du har sjekket at endringen din ikke har overrides (hvis importerte komponenter er i bruk)
- [ ] Du har gjort arbeidet i en Figma-branch og bedt om feedback

**Comment by onordbo** [comment]
Denne kan løses via med #3176
