### ISSUE TITLE
Fix: Button i Figma

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#3169]
Juster padding ny.

Desktop/Mobile:
horisontal padding:
- 16 > 24
- 8 > 16
- Mellomrom mellom pil og tekst mindre

**Branch:** [`Legg til Figma-link (hvis du har laget et forslag)`](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/dj7PQ2AiMa58rhkgIKvYHb/Components?node-id=545%3A7389)

### 🎯 Sjekkliste

- [ ] Du har sjekket at alt av auto-layout, animasjoner, o.l er satt opp riktig
- [ ] Du har sjekket at designet matcher kodekomponenten (visuelt, animert og interaktivt)
- [ ] Du har sjekket at endringen din ikke har overrides (hvis importerte komponenter er i bruk)
- [ ] Du har gjort arbeidet i en Figma-branch og bedt om feedback

**Comment by onordbo** [comment]
Merget og klar for publisering.
