### ISSUE TITLE
Feedback-komponenten trenger litt kjærlighet og dokumentasjon

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#3176]
Feedback-komponenten vår har kommet og gått litt over det siste året. Deler av komponenten _(bl.a. smiley varianten)_ var borte en liten stund, før den kom tilbake med varierende grad av støtte i kode og design om hverandre. Det er på tide å kartlegge behovene denne skal dekke. Før vi foretar oss noe er det nok lurt at vi får diskutert et par punkter:

- Hvordan brukes komponenten i dag?
- Hvilke behov dekker ikke komponenten?
- Hvor fleksibel skal komponenten være i sammensetning?
- Hvor mange (eller hvilke) varianter burde vi tilby?

## 🔗 Praktiske lenker (om tilgjengelig)

**Designskisser:** [components → fix: feedback/simplify](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/EuN2uPb6arlopVgxHAfenX/Patterns?node-id=2090%3A14534&viewport=-295%2C469%2C0.13)
**Pull request:** `Link til PR, ved endringer på kode`
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`

## 🎯 Sjekkliste

- [x] Du har laget en branch i Figma og bedt om feedback
- [ ] Du har sjekket at alt av kode og tester kjører som det skal
- [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by onordbo** [comment]
Denne saken kan samle opp og ta med seg #3168 og #3086 i samme slengen. (cc @Slaine2)

**Comment by Murstam** [comment]
Noen varianter av det vi bruker fra BM:

![forsikring-bedrift test sparebank1 no_bedrift_forsikringer_WTQwOjE3ODI3MTA1 (1)](https://user-images.githubusercontent.com/47025023/199214225-9613e0af-3e8c-4813-b6e9-6114c572bd10.png)
![forsikring-bedrift test sparebank1 no_bedrift_forsikringer_WTQwOjE3ODI3MTA1](https://user-images.githubusercontent.com/47025023/199214233-e7af563c-ad7d-4fa0-b050-5b8491cefedd.png)
![forsikring-bedrift test sparebank1 no_bedrift_tilganger-andre-bedrifter (1)](https://user-images.githubusercontent.com/47025023/199214236-cecad3ed-c77d-4573-a16c-8d767647ae68.png)
![forsikring-bedrift test sparebank1 no_bedrift_tilganger-andre-bedrifter](https://user-images.githubusercontent.com/47025023/199214237-629ec3cf-d9cf-46fc-86ef-72239969a120.png)
![forsikring-bedrift test sparebank1 no_bedrift_forsikringer (1)](https://user-images.githubusercontent.com/47025023/199214239-2ce6bd2e-1766-4d15-a0d3-77520170b6be.png)
![forsikring-bedrift test sparebank1 no_bedrift_forsikringer](https://user-images.githubusercontent.com/47025023/199214240-f89f770e-3d87-427c-87f1-31e471e545b1.png)

**Comment by Murstam** [comment]
Noen varianter av det vi bruker på BM:
<img width="1213" alt="Screenshot 2022-11-01 at 11 34 18" src="https://user-images.githubusercontent.com/47025023/199214622-04cf05ee-cf29-491d-b435-a2966e79d1e3.png">

**Comment by onordbo** [comment]
Her er et forslag til en [forenklet versjon av Feedback](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/EuN2uPb6arlopVgxHAfenX/Patterns?node-id=2090%3A14534&viewport=-295%2C469%2C0.13) som ikke har noe states eller linking, bare de forskjellige stegene. I tillegg er det en fleksibel komponent med slot for oppfølgingsspørsmål.

**Comment by onordbo** [comment]
@Slaine2: Nei, denne varianten av Feedback skal ikke interaktiv (i samme grad) siden [vi har en fra før av](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/Patterns?node-id=394%3A6503&viewport=1164%2C819%2C0.12) som viser eksempelet i [portalen](https://jokul.fremtind.no/komponenter/feedback). Tanken her er at designsystemet tilbyr stegene enkeltvis så man kan sette sammen flyten etter egne behov.

**Comment by Stormoen** [comment]
@onordbo Kommer feedback i figma med smileys etterhvert?

**Comment by onordbo** [comment]
@Stormoen: Det ligger en variant med smileys i det [forenklede forslaget](https://www.figma.com/file/EuN2uPb6arlopVgxHAfenX/fix%3A-feedback%2Fsimplify?node-id=210%3A582) 😊

**Comment by onordbo** [comment]
Nå er en forenklet variant av feedback-komponenten [klar for merging](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/EuN2uPb6arlopVgxHAfenX/Patterns?node-id=2090%3A13017&viewport=-866%2C815%2C0.16&t=dAkWYwDEm3MaNhZQ-11). I ekte progressive enhancement-stil hoppet jeg galant over diverse Prototype-funksjonalitet, ettersom behovet ikke er særlig stort for øyeblikket. Om det skulle vise seg veldig nødvendig kan vi implementere det i etterkant.

cc @Stormoen @Murstam @Slaine2

**Comment by onordbo** [comment]
[Merget](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/Patterns?version-id=2680133654&node-id=224%3A581&viewport=1681%2C673%2C0.75&t=Ak1RWuUbWUvPgpNE-0) og [publisert](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/Patterns?version-id=2680137774&node-id=224%3A581&viewport=1681%2C673%2C0.75&t=Ak1RWuUbWUvPgpNE-0).
