### ISSUE TITLE
Feil: Ulik størrelser på tekst etter endring av tekststørrelse på mobil

### ISSUE THREAD

**Issue by kennidenni** [fremtind/jokul#3195]
![image](https://user-images.githubusercontent.com/31621649/195094352-2ffc69fc-1117-4199-be8b-6c1b4893b86d.png)
![image](https://user-images.githubusercontent.com/31621649/195094398-427ed3db-85d8-48c0-8069-8b098a7e3926.png)

## Steg for å gjenskape
Gikk i innstillinger på min android mobil og skrudde opp tekststørrelsen til maks. 
Så logget jeg inn her: https://kundeforsikring.sparebank1.no/privat/forsikring/motor/moped 

## Forventet oppførsel
Forventer at det er ca lik størrelse på det meste av tekststørrelsene som kommer fra Jøkul. 
 
## Systeminformasjon
Samsung S21 Ultra med Android og Chrome som browser

**Comment by wkillerud** [comment]
Har prøvd å reprodusere dette nå med Safari, Firefox og Chrome på desktop (øke minste fontstørrelse til 72, så også sidezoom til 400%). Også prøvd å reprodusere på Safari i iOS med samme metode (øke sidezoom til 400% og minste tekststørrelse via Tilgjengelighet-innstillinger).

Ingen av testene viser det samme resultatet du ser @kennidenni. Alt blir zoomet, og størrelsesforholdene er riktige.

Ingen av oss på Jøkul-teamet har en Android-dings å teste med. Kunne du hjulpet oss med å feilsøke?

**Comment by kennidenni** [comment]
Hmm så rart. Nå prøvde jeg igjen, og restartet til og med mobilen før jeg gikk inn på løsningen, men det er fortsatt samme feil. 
Har du noen tips om hva annet jeg kan gjøre? @wkillerud

**Comment by piofinn** [comment]
Ser at denne har ligget brakk en stund. Er dette fortsatt et problem, @kennidenni? Hvis det er det, kanskje du kan forsøke å [inspisere nettsiden fra mobilen din](https://raygun.com/blog/debug-android-chrome/) og se hva som er annerledes med Radio Button/Select som gjør at de vises feil?

**Comment by kennidenni** [comment]
@piofinn Ja, sjekket i forrige uke og da var det samme feil. 
Har det ganske travelt denne uken og neste, men kan se om jeg kan få sneket det inn i neste uke

**Comment by piofinn** [comment]
Har du fått sjekket dette, @kennidenni ? 🙃

**Comment by kennidenni** [comment]
@piofinn Har gått bort fra Samsungen som jeg hadde, men ser bra ut i Pixel mobilen min nå 😅

**Comment by piofinn** [comment]
Kan ikke lenger reproduseres
