### ISSUE TITLE
Feil: Tool Tip vises dradd på iPhone

### ISSUE THREAD

**Issue by matrund** [fremtind/jokul#3223]
Tool Tip vises som "dradd" i bredderetning på iPhone

![f19905d8-ee56-44dc-9406-2bbb43fbd9d8](https://user-images.githubusercontent.com/55445268/199208700-cbe724e3-3e8c-4f23-adc5-c8a4306d3816.jpg)

## Steg for å gjenskape

1. Gå til [https://kundeforsikring.sparebank1.no/privat/forsikring/motor/bil](https://kundeforsikring.sparebank1.no/privat/forsikring/motor/bil) 
2. Logg inn med BankID
3. Endre URL til [https://kundeforsikring.sparebank1.no/privat/forsikring/motor/**bil2**](https://kundeforsikring.sparebank1.no/privat/forsikring/motor/bil2) 
4. Fyll inn nødvendig info og trykk "Fortsett"
5. Scroll ned til spørsmål om bonus hvor Tool Tip blir brukt

## Forventet oppførsel
Forventet at Tool Tip vises med sirkulær form.

## Systeminformasjon
iPhone 13 i Safari og Chrome.

**Comment by wkillerud** [comment]
@all-contributors please add @matrund for bug

**Comment by wkillerud** [comment]
@matrund ser du den samme effekten om tooltip [ikke ligger for seg selv på egen linje](https://jokul.fremtind.no/komponenter/tooltip#når-bruker-vi-tooltip)?

> En tooltip skal ikke ligge på en egen linje, men være tilknyttet tekst eller et interaktivt element. Bruk non-breaking space eller andre metoder for å holde Tooltip på samme linje.

**Comment by matrund** [comment]
@wkillerud Nei, Tooltip er brukt tilknyttet til en tekst, og vi har brukt non-breaking space. Se koden under. "JaNeiQuestion" er et sett med radioButtons i en RadioButtonGroup. 


```
<JaNeiQuestion
                className="jkl-spacing-xl--top"
                name="bonus"
                legend={
                    <>
                        {`Du får ${bonus.bonus} hos oss, vil du bruke den? ${unicode.nbsp}`}
                        <Tooltip content="Bonus er en rabattordning der vi belønner skadefri kjøring med lavere pris på forsikringen." />
                    </>
                }
                otherLabels={{
                    nei: 'Nei, jeg vil overføre bonus',
                }}
 />
```

**Comment by piofinn** [comment]
> ```tsx
> {`Du får ${bonus.bonus} hos oss, vil du bruke den? ${unicode.nbsp}`}
> ```

@matrund ser ut som det er et vanlig mellomrom her før `nbsp` (rett etter spørsmålstegnet) slik at linjen uansett får lov til å bryte. Får dere fortsatt samme feil dersom man fjerner det ekstra mellomrommet?
