### ISSUE TITLE
Components: Accordion

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#323]
https://www.figma.com/file/Wh8Gfnesn25shH31sKyIaT/J%C3%B8kul-bibliotek?node-id=47%3A1

**Comment by Steinop** [comment]
Accordion updated with new design and different sizes - both as a regular page component and as full width Accordion sections on a page.

Animated version:
![Fremtind_Accordion v 1](https://user-images.githubusercontent.com/51952891/63027324-09876a80-bead-11e9-85eb-9b11a0c8db12.gif)

Figma (Final design will be updated to Figma Bibliotek at a later stage):
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-components?node-id=218%3A348

**Comment by stianlik** [comment]
I'm working on this.

**Comment by Mikkelinski** [comment]
Further work handled by #394
