### ISSUE TITLE
Feil: Select på valg i "Demo" har for svak kontrast 

### ISSUE THREAD

**Issue by kennidenni** [fremtind/jokul#3231]
![image](https://user-images.githubusercontent.com/31621649/199736189-f1d44eae-d2ee-4c3a-a1d9-fd9a01d53f42.png)

## Steg for å gjenskape
Gå til f.eks https://jokul.fremtind.no/komponenter/select og åpne select slik som i bildet.

## Systeminformasjon
På Mac med Chrome

**Comment by piofinn** [comment]
Set ut som denne bugen bare opptrer i dark mode.
