### ISSUE TITLE
Feil: Flere pakker mangler `@fremtind/jkl-core` som `dependency`

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3232]
Nyere versjoner av package managers vil feile dersom de merker at en pakke er i bruk, men ikke listet som en `dependency`.

Enkelte pakker i Jøkul har `@fremtind/jkl-core` merket som `devDepencency`, men bruker for eksempel typer som `WithChildren` og skulle derfor hatt pakken som en `dependency`.

1. Flytt `@fremtind/jkl-core` til `dependency` der den ligger som `devDependency`.
2. Kontroller at alle `-react`, `hooks` og `-utils`-pakker har  `@fremtind/jkl-core` som `dependency`.

**Comment by wkillerud** [comment]
Cc @hjellek. Om du ikke har startet alt tenker jeg begynne med denne i morgen fredag.

**Comment by hjellek** [comment]
> Cc @hjellek. Om du ikke har startet alt tenker jeg begynne med denne i morgen fredag.

Dessverre ikke fått tid til å se på det ennå, supert om du har tid! :)

**Comment by wkillerud** [comment]
Publiseringsjobben har litt trøbbel etter refactor, skal fikse.

**Comment by wkillerud** [comment]
_Tror_ releasejobben skal fungere neste gang, men @piofinn kjører en manuell publisering nå på grunn av at Lerna rakk å versjonere og tagge.

- #3241 
- #3242 
- #3243 
- #3244 
- #3245 
- #3246

_First try!_
