### ISSUE TITLE
Figma: Legg til maksbredde på Tooltip i Figma

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#3233]
Som @ivnai nevner er det ikke mulig å replikere utseendet til kodekomponenten i Figma.

<img width="921" alt="image" src="https://user-images.githubusercontent.com/4263132/199810740-135e2c29-17b5-4450-ab24-2d35eccdcff7.png">

**Branch:** [components → fix: tooltip/max-width](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/94LXKWKzCocz0OSTF5jy6n/Components?node-id=1858%3A2554&viewport=5146%2C487%2C0.6)

### 🎯 Sjekkliste

- [x] Du har sjekket at alt av auto-layout, animasjoner, o.l er satt opp riktig
- [x] Du har sjekket at designet matcher kodekomponenten (visuelt, animert og interaktivt)
- [x] Du har sjekket at endringen din ikke har overrides (hvis importerte komponenter er i bruk)
- [x] Du har gjort arbeidet i en Figma-branch og bedt om feedback

**Comment by onordbo** [comment]
Vi kan løse dette ved å sette tekstlagene for Message til `fill` og legge en maksbredde på Message-laget i komponenten.

**Comment by onordbo** [comment]
Hva synes du om [denne løsningen](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/94LXKWKzCocz0OSTF5jy6n/Components?node-id=3645%3A4609&viewport=7597%2C1257%2C0.91), @ivnai?



![Image](https://user-images.githubusercontent.com/4263132/200556716-8fc4a792-1679-4095-82d8-7a662d46f31c.png)

**Comment by onordbo** [comment]
Da var det fiksa i Figma og [klart for å merges](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/94LXKWKzCocz0OSTF5jy6n/Components?node-id=1858%3A2554&viewport=5723%2C1136%2C0.59&t=OHQPTWtXKRrtp6a0-11). Får vi plassert tuppen av tooltipen litt lengre inn fra kanten `(16pt/1rem)` i samme slengen, @wkillerud? See screenshots nedenfor.

## Design


![Image](https://user-images.githubusercontent.com/4263132/201629786-6d5616c5-e279-4acd-be38-c87ab4177b22.png)



## Kode

![Image](https://user-images.githubusercontent.com/4263132/201628551-ae617431-95f3-4c96-bab5-a6705af1c635.png)

![Image](https://user-images.githubusercontent.com/4263132/201628595-352c8892-bdbe-4767-891a-54390dca073b.png)

**Comment by wkillerud** [comment]
Lag gjerne et nytt issue på det @onordbo, så det ikke blir glemt.

**Comment by onordbo** [comment]
<img width="241" alt="image" src="https://user-images.githubusercontent.com/4263132/201654641-b5869a2a-2028-46e7-8bfd-867ad379a5bf.png">

[Merget og publisert](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/Components?version-id=2608805043&node-id=1543%3A2046&viewport=8769%2C228%2C1&t=yqdTkqpS9DtcWeoZ-0) i Figma.

> Lag gjerne et nytt issue på det @onordbo, så det ikke blir glemt.

@wkillerud: ✅ https://github.com/fremtind/jokul/issues/3256
