### ISSUE TITLE
Figma: Button Hover Effect

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#3236]
Legg til Hovereffekt (zoom)

**Branch:** (https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/WX2B8yD5aeHznQ0DPaxz2o/Components?node-id=3583%3A5109)

### 🎯 Sjekkliste

- [x] Du har sjekket at alt av auto-layout, animasjoner, o.l er satt opp riktig
- [x] Du har sjekket at designet matcher kodekomponenten (visuelt, animert og interaktivt)
- [x] Du har sjekket at endringen din ikke har overrides (hvis importerte komponenter er i bruk)
- [x] Du har gjort arbeidet i en Figma-branch og bedt om feedback

**Comment by wkillerud** [comment]
Jeg synes A, så vi holder oss til at ikoner er samlet i assets. Om vi starter med unntak ender vi til slutt opp der vi var før, at vi har en samling ikoner som ikke blir brukt. Det blir en mer naturlig mapping til kode også, hvor vi bruker ikonkomponenten og ikke tekst.

Figma kommer aldri til å være 100% likt nettleseren i _alle_ tilfeller, så en liten visuell quirk som dette er OK synes jeg, for at biblioteket skal ha god kvalitet.

**Comment by wkillerud** [comment]
Cc @leon-ho

**Comment by fremtindelise** [comment]
Dette er ikke en nødvendig feature.

**Comment by leon-ho** [comment]
Enig, men hver nye designer skal få lov til å prøve å implementere denne zoom-effekten i Figma 😜
