### ISSUE TITLE
Spacingskala

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#3255]
Mange designere går glipp av et trinn i Spacingskalaen mellom 24px og 40px.
32px det ville være den logiske konklusjonen.

**Designskisser:** [`Link til Figma-branch, ved designendringer`](https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/branch/dk0A1vRAqSiOqbdofu7uiC/Core?t=xBQfZejX8EIEDgoY-1)

## 🎯 Sjekkliste

- [ ] Du har laget en branch i Figma og bedt om feedback
- [ ] Du har sjekket at alt av kode og tester kjører som det skal
- [ ] Dere har sammen sjekket at resultatet av design og kode matcher

**Comment by onordbo** [comment]
cc @piofinn

**Comment by wkillerud** [comment]
Er en teknisk diskusjon i full sving på #3249. Ser ut som et løsningsforslag begynner å ta form.

**Comment by onordbo** [comment]
Jeg skjønte det slik på @piofinn var det @Stakset som dro i gang den diskusjonen her? Har du noen tanker om det som har blitt nevnt her, og i #3249?

**Comment by piofinn** [comment]
> Er det ferdig designet at det er tre steg i den responsive/dynamiske spacingen @Slaine2?

## Brannfakkel 🔥

Med en gang vi begynner å legge til flere steg inni her er vi på full fart utenfor en slippery slope av kompleksitet både i kode og (særlig) i definisjon av verdier. Vil derfor påstå følgende:

**Hvis det ikke holder med to steg for dynamiske størrelser bør vi gå for størrelser som endrer seg kontinuerlig.**

Da kan vi si at "denne skal ikke være mindre enn steg/verdi x og ikke større enn steg/verdi y" og at "den minste størrelsen skal vises t.o.m. XXX px og den største skal vises f.o.m YYY px". Da slipper vi også å forholde oss til breakpoints, noe som fjerner både en hel masse kodekompleksitet og all diskusjon om hva som er "riktig" sted å brekke om.

Det som vises i skissen fra @Slaine2 over er jo egentlig tre forskjellige spacing-skalaer, med helt unike verdier, så vi måtte nok uansett sett litt annerledes på det enn vi har gjort i forslaget i #3249 for å lage dette. Man går jo da ikke lenger mellom _forskjellige steg i samme skala_, men mellom _samme steg i forskjellige skalaer_. Det går fint an, men er noe annet enn det vi har jobbet ut fra.

Brannfakkelen min over gjelder uansett, IMO: Definer ytterpunktene og bytt gradvis og mykt mellom dem.

**Comment by piofinn** [comment]
> Disse kan imidlertid ikke lages i figma, men jeg tror at spacing i forskjellige størrelser ikke lenger spiller noen rolle, ikke sant?

Stemmer, da skal spacingen automatisk justeres mellom ytterpunktene man har satt 😊 Som du sier er det ikke mulig å gjenskape 100% i Figma, så da må nesten dere designere stole på at det blir riktig, hehe. På den positive siden frigjør det oss jo helt fra faste breakpoints ved litt arbitrære bredder, så det blir kanskje lavere terskel for å legge inn breakpoints der det gir mening for akkurat det innholdet man lager 😊

**Comment by Murstam** [comment]
@Slaine2 Tror vi kan beholde 40px for å ta vare på ønske om kortere gap mellom de«små» verdiene. Men litt vanskelig å si før man har brukt det 😅

**Comment by Murstam** [comment]
Hvorfor står det pt og ikke px i Figma?

**Comment by onordbo** [comment]
> Hvorfor står det pt og ikke px i Figma?

Det er vel egentlig bare en gammel vane[^1] som ramlet med på lasset da Figma-biblioteket ble oppdatert i sommer. Vi kan godt gå tilbake til `px`, alt er jo relativt under panseret uansett. 🤷‍♂️

[^1]: [Gregory Schmidt: When is a pixel not a pixel?](http://www.gregoryschmidt.ca/writing/when-is-a-pixel-not-a-pixel-pixels-points-dps#:~:text=Logical%20resolution%20essentially%20is%20what,that%20is%20in%20logical%20resolution.)

**Comment by wkillerud** [comment]
På forum i dag diskuterte vi løsningsforslaget i kode og behovene ute i teamene rundt det med dynamisk spacing. Oppsummert:

- Det er et behov for dynamisk spacing med to trinn (small, medium device og høyere [basert på forslaget til @henrikhermansen]) _og_ tre trinn (small, medium, large device og høyere [ønsket av SeOpp via @BjorneOma ]) .
- Den tekniske løsningen ser bra ut (bort fra t-skjortestørrelser til pixelbaserte grunnverdier).
- Ferdige CSS-klasser fra Jøkul for disse nye spacingene er nice-to-have, ikke must-have (så lenge det finnes mixin). Sjekker om CSSen blir uakseptabelt stor med alle de nye klassene og media queries.
- På lengre sikt vil vi gjerne utforske _flytende_ spacing (ikke basert på trinn med media queries), men det vil måtte være et supplement. Det er et ønske om å beholde trinn/media query-basert dynamisk spacing også i fremtiden. Løses ikke i denne omgangen.

Cc (si gjerne fra om jeg glemte noe/husker feil) @piofinn @BjorneOma @Stakset @kennidenni

**Comment by piofinn** [comment]
Lukket via #3249 og [denne Figma-mergen](https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/Core?version-id=2725046140&node-id=0%3A1&viewport=-1218%2C1856%2C0.53&t=I1QAR6unHIFbhcwq-0)
