### ISSUE TITLE
Oppdatere guiden "Hvordan kode i Jøkul?"

### ISSUE THREAD

**Issue by fremtindelise** [fremtind/jokul#3260]
Oppdatere guiden "Hvordan kode i Jøkul?" i portalen med nye kommandoer.

## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** `Link til PR, ved endringer på kode`
**Designskisser:** `Link til Figma-branch, ved designendringer`
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

- [ ] Du har sjekket at alt av kode og tester kjører som det skal
- [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by wkillerud** [comment]
Ser ut som det ikke har gått noen deploy av portalen siden endringen ble gjort. Releasen etter vi merget inn `pnpm` feilet. Vi pushet nye pakker manuelt, men ikke portalen. Etter det har det ikke vært noen endringer ennå, så de ligger fortsatt og venter.

- https://github.com/fremtind/jokul/actions/runs/3427732590/jobs/5711094976
- https://github.com/fremtind/jokul/actions/runs/3445494494/jobs/5749274064

**Comment by wkillerud** [comment]
Nå skal det være mulig å gjøre en vilkårlig endring i en fil i portalmappa for å trigge en ny deploy, om du vil fremskynde prosessen @fremtindelise
