### ISSUE TITLE
Rydd i tilganger i Jøkul-repoet etter innrullering i organisasjonen

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#3281]
Nå som vi har rullert samtlige kreatører inn i github org'en er det ingen grunn til at man skal være lagt til som external collaborator her lenger. Det skaper en del forvirring i systemet i det man skal søke etter folk i bl.a. mentions.

**Comment by wkillerud** [comment]
Rydder i lista nå. Om du mister tilgang du har hatt før, si ifra så skal vi undersøke hva som er feil 😄
