### ISSUE TITLE
Combobox

### ISSUE THREAD

**Issue by ivnai** [fremtind/jokul#3282]
Det er behov å legge til multi-select mulighet til Select komponent.

## 🔗 Praktiske lenker (om tilgjengelig)

**Designskisser:** [Patterns → fix: combobox-select](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/0ZVnJi5VvrisZJVNsdpw5K/Components?node-id=6445%3A7812&t=6ylK31uJF9UEqVcD-11)
**Pull request:** https://github.com/fremtind/jokul/pull/3414
**Forhåndsvisning:** https://jokul.fremtind.no/preview/feat/combobox/komponenter/combobox#combobox
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

- [x] Du har laget en branch i Figma og bedt om feedback
- [ ] Du har sjekket at alt av kode og tester kjører som det skal
- [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by onordbo** [comment]
[Figma forslag](https://www.figma.com/proto/0ZVnJi5VvrisZJVNsdpw5K/fix-select-rebuild?node-id=6045%3A4536&viewport=4125%2C2770%2C0.54&scaling=min-zoom&starting-point-node-id=6445%3A8597) til Combobox klart for testing og merging.

Branch: https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/0ZVnJi5VvrisZJVNsdpw5K/Components?node-id=6445%3A8597&t=6ylK31uJF9UEqVcD-11

cc @ivnai @EliseBrenna

**Comment by ivnai** [comment]
Hei @onordbo dette funker jo fint. Hva med å endre på bg farge når hover på selected i lista? sånn;

<img width="267" alt="Screenshot 2023-02-16 at 22 07 12" src="https://user-images.githubusercontent.com/93194579/219682205-bbad26bd-ccc1-40af-b070-7f99e87fa678.png">

**Comment by onordbo** [comment]
@ivnai: oppdaterte Figma med forslaget ditt. Når er det også en [forhåndsvisning av Combobox](https://jokul.fremtind.no/preview/feat/combobox/komponenter/combobox#combobox) tilgjengelig i portalen.
