### ISSUE TITLE
Feil: Måneds-selecten i utvidet datovelger blir ikke alltid oppdatert

### ISSUE THREAD

**Issue by BjorneOma** [fremtind/jokul#3287]
Selecten i utvidet datovelger viser i visse tilfeller feil måned. Viss man bytter måned ved å klikke på en dato utenfor den valgte måneden i kalenderen blir ikke verdien i selected oppdatert. Videoen under forklarer feilen litt lettere enn med ord...

## Video av feilen + korleis man gjenskaper:

https://user-images.githubusercontent.com/55135175/204296657-d9e75940-8f4a-4d88-9153-71c0448796af.mov

## Systeminformasjon
Chrome, MacOS 13.0

**Comment by wkillerud** [comment]
@fremtindelise @piofinn, kan dette være noe liknende som #3264 men for Selecten?

**Comment by fremtindelise** [comment]
> @fremtindelise @piofinn, kan dette være noe liknende som #3264 men for Selecten?

Det er mye mulig. Jeg kan sjekke det ut!
