### ISSUE TITLE
Labels for Checkboxes and Radiobuttons vs labels for Dropdowns and Input fields

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#330]
Case for "SeOpp - Melde Skade"

In some cases a dropdown label can be written as a question which will give the minimised label text a reduced readability due to a smaller font size, gray colour and longer lines of text.

**Comment by Steinop** [comment]
Figma reference for Input label v2.0:

Normal size: 
https://www.figma.com/file/Wh8Gfnesn25shH31sKyIaT/J%C3%B8kul-bibliotek?node-id=559%3A1519

Small size:
https://www.figma.com/file/Wh8Gfnesn25shH31sKyIaT/J%C3%B8kul-bibliotek?node-id=563%3A1626

**Comment by Steinop** [comment]
Animation Preview:
![Fremtind_Inputfelt_Aug2019](https://user-images.githubusercontent.com/51952891/64165623-bc603e00-ce45-11e9-8c14-bd5a27bf59f7.gif)

**Comment by Mikkelinski** [comment]
Solved in separate issue
