### ISSUE TITLE
Feil: (portalen) Oppslagsguiden til Universell Utforming gir duplikater og feil kategori

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#3316]
Heisann 👋 Jeg bruker fortsatt UU-guiden og var innom oppslagsguiden nå nylig. Oppdaget at et krav med tittel "Lyd og bilde" kommer opp mange ganger, og med feil tekstlig innhold. Beskrivelsen omhandler lister.

## Steg for å gjenskape

1. Gå til https://jokul.fremtind.no/universell-utforming/guide
2. Scroll ned og finn "Lyd og bilde". Observer at den inneholder feil informasjon

evt.

1. Gå til https://jokul.fremtind.no/universell-utforming/guide
2. Huk av for noen valg, for eksempel "bilder" og "innlogging"
3. Scroll ned og observer at "lyd og bilde" vises to ganger i listen og har feil innhold

På det meste har jeg fått 4 duplikater av "lyd og bilde".

## Forventet oppførsel

Forventet riktig innhold og ingen duplikater

## Systeminformasjon

Mac: Ventura 13.0.1

Chrome: 108.0.5359.94 

Også observert i chrome på Android

**Comment by wkillerud** [comment]
@all-contributors please add @vegardsoerlie for bug
