### ISSUE TITLE
Navneendring og rekkefølge på fonter i Figmabiblioteket

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3337]
Foreslått i https://github.com/fremtind/jokul/discussions/3334

<div type='discussions-op-text'>

<sup>Originally posted by **Stormoen** December 22, 2022</sup>
1) Kan "bold" døpes om til "body bold"? Ordene er så like at jeg trykker feil så ofte  Da følges også samme prinsipp som "small" - "small bold".
2) Tipper de fleste bruker de minste fontstilene mest i hverdagen. Kunne man vært så gæren å snudd lista, og starta med de minste stilene innenfor desktop? Da hadde man sluppet scroll til body.

![8dba0dc8-6cd8-4ab6-86bc-076654e0d9f4](https://user-images.githubusercontent.com/64519175/209103185-b21304b1-ffd2-410d-8cb2-d3e01abd5b02.jpg)
</div>

## Sjekkliste

- [ ] Døp om `Bold` til `Body Bold` i Figma.
- [ ] Snu om på rekkefølgen så de mindre (men oftere brukte) størrelsene blir lettere tilgjengelig i velgeren.
- [ ] 👽 portal: Endre navn i dokumentasjonen til å matche Figma – fra `Bold` til `Body Bold`.

**Comment by onordbo** [comment]
Jeg tror @Slaine2 fikset dette før jul 🤔 Det ble merget inn en endring for en [drøy måned siden](https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/Core?version-id=2725054312&node-id=15%3A1189&viewport=25%2C138%2C0.76&t=MCa1xbtft6avpDdO-0) hvertfall.

**Comment by wkillerud** [comment]
Rekkefølgen i dropdownen er fortsatt den samme for meg @onordbo (testet i eksisterende og ny fil):

![](https://user-images.githubusercontent.com/1223410/210227121-59d1246c-08e7-4101-9784-7f2c8bda865b.png)

Ser at definisjonen er i omvendt rekkefølge (som den er ønsket). Mangler det en publish?

**Comment by onordbo** [comment]
@wkillerud: Det manglet en [publish](https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/Core?version-id=2815491620&node-id=15%3A1189&viewport=219%2C184%2C1&t=k1BvATMTUZee8c7o-0).

**Comment by wkillerud** [comment]
Cc @Stormoen: da er rekkefølgen på fontene endret og _bold_ døpt om til _body bold_.
