### ISSUE TITLE
Gjenbrukbar modal

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3348]
Under forum i dag ble vi enige om at det trengs en gjenbrukbar modal i Jøkul. Fire team har hver sin implementasjon. Jøkul har i tillegg en ikke-gjenbrukbar modal i [CookieConsent](https://jokul.fremtind.no/komponenter/cookieconsent).

En modal må være fleksibel med tanke på innhold. Tenk [TaskCard](https://jokul.fremtind.no/komponenter/card#oppgavekort).

## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** #3542 
**Designskisser:** [Link](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/gnbTHf42d4JqMwC5yiPGqi/Patterns?node-id=3685%3A27238&t=3NCZ1jhr8wJOFeyz-1)
**Forhåndsvisning:** https://jokul.fremtind.no/preview/feat/modal/komponenter/modal/

## 🎯 Sjekkliste

-   [x] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by wkillerud** [comment]
Jeg har noen tanker om modal-komponenten @Slaine2. Jeg får ikke delt Figma drafts, men her er et screen recording for å vise litt hva jeg tenker. Vi kan kanskje prate litt mer om det på mandag?

https://user-images.githubusercontent.com/1223410/236388987-898fec05-df09-46ed-bd4b-cec913f2d736.mov

In essence:

- "Subkomponenter" for tittel, hovedinnhold og knappegruppe.
- Absolute positioning for lukk-knapp.

**Subkomponenter**
Gir oss fleksibilitet, samtidig som vi for eksempel:

- Unngår at modaler får ulik headingnivå.
- Gir knappegrupper lik layout i bunnen.
- Hinter om hvilke "parts" som bør brukes i en modal.

**Absolutt posisjon av lukk**
Unngår at vi får en lang kolonne med whitespace på høyre side. Vi kan bygge inn padding i tittelkomponenten som skaper en "safe zone", så vi ikke får tekst under knappen.

**Comment by wkillerud** [comment]
Vi trenger også kanskje ikke like mange padding-variants som `TaskCard`? Mindre å vedlikeholde ;)

**Comment by leon-ho** [comment]
Har kikket raskt på Modal i figma, synes det ser bra ut, og har foreløpig tilbakemelding:
* Kan vi lage figma-komponent på en måte som ikke innebærer 20 varianter? (Det er tidkrevende å vedlikeholde, og lett å gjøre feil når man gjør endringer). Kanskje en hjelpekomponent som tar seg av bl.a. bg-farge, shadow?
* Kan vi vurdere å droppe compact Modal? Som jeg har forsøkt å foreslå i andre komponenter, det er hovedsaklig enkeltelementer som skal inn vises i informasjonstette omgivelser som behøver compact, e.g. inputs, knapper osv. Ting som "ligger over", dvs. popups og modals (datepicker-kalender, toast), har mindre behov for compact. Det er i tillegg mulig å velge padding separat, så da blir det litt overlappende funksjonalitet mellom padding og size?

**Comment by wkillerud** [comment]
Kan godt droppe compactvariant ja

**Comment by wkillerud** [comment]
Preview link: https://jokul.fremtind.no/preview/feat/modal/komponenter/modal/

Jeg har skrevet et førsteutkast til dokumentasjonen. Kom gjerne med endringsforslag, eksempel-screenshots, eller ønsker @Slaine2 @leon-ho :)

**Comment by wkillerud** [comment]
Huh, rart at overlay ikke synes i dark mode. Skal fikse.

Og skal legge på skifer som bakgrunnsfarge 👍
