### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3349]
Toast ble tatt opp på forum i dag, og er en gjenganger. 

BM har en variant i dag hvor en MessageBox animeres inn fra bunnen av viewporten og er sticky. Dagens løsning må dismisses før den forsvinner. Toasts som forsvinner må kunne pauses/holdes synlige av UU-hensyn.

Vi ser behov for å designe og lage en gjenbrukbar Toast-komponent i Jøkul.

## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** https://github.com/fremtind/jokul/pull/3574
**Designskisser:** [Toast](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/di0pbMcKZd6OcSYelauivx/Components?node-id=7812%3A12826&t=929Ii7iJVXyiq9hw-1) ([Dokumentasjon](https://www.figma.com/file/CnLHtbKuY7V3yPNGpEVPhy/Toast-dokumentation?type=design&node-id=3%3A7774&t=lFubWz3WO9f2iD1Y-1))
**Forhåndsvisning:** https://jokul.fremtind.no/preview/feat/toast/komponenter/toast/
**Discussion:** https://github.com/fremtind/jokul/discussions/2816

## 🎯 Sjekkliste

-   [ ] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by glennbarosen** [comment]
Har vært veldlig fornøyd med [notistack](https://notistack.com/features/basic) tidligere.

**Comment by wkillerud** [comment]
Tror jeg venter med dokumentasjon av kode til jeg har laget komponenten @Slaine2. Litt lettere å vite hvilke "gotchas" som må forklares, og hvordan eksemplene skal se ut, når komponenten er ferdig (ish) kodet.
