### ISSUE TITLE
Feil: Feil på ExpandButton med variant small

### ISSUE THREAD

**Issue by kennidenni** [fremtind/jokul#3364]
![image](https://user-images.githubusercontent.com/31621649/212342977-acd74341-f0de-4ac8-9c25-da826cac519e.png)
![image](https://user-images.githubusercontent.com/31621649/212343097-b345e1f5-64c6-4193-9fbf-3009d4ebf86a.png)

Ser ut som feilen kommer fordi pilen har variant small? 

![image](https://user-images.githubusercontent.com/31621649/212343472-a576bbd8-c8e3-49dc-a75a-88d2bf2551db.png)
![image](https://user-images.githubusercontent.com/31621649/212343505-3c74d201-b041-46e6-adff-b016c03fad36.png)

## Forventet oppførsel
Forventer at pilen skal se fin ut ❤️

## Systeminformasjon
Fant feilen på Chrome på Mac
-->

**Comment by kennidenni** [comment]
Vent, ser ikke feil i eksempelet i Jøkul for en eller annen grunn. Skal sjekke litt mer opp i dette

**Comment by wkillerud** [comment]
Er det latest and greatest? Det minner mistenkelig om noe jeg rettet i #3332

**Comment by kennidenni** [comment]
Oi, se der ja. Trodde vi hadde oppgradert, men bare til nyeste av 3.x, ikke til 4.x 👀 Gjør det på mandag og ser om det fikser feilen 👍
