### ISSUE TITLE
Innholdet i MessageBox blir veldig smalt i enkelte tilfeller

### ISSUE THREAD

**Issue by BjorneOma** [fremtind/jokul#3387]
### Problemet
I en smal MessageBox (for eksempel på en mobilskjerm) blir innholdet veldig smalt. Dette er fordi ikonet øverst i venstre hjørne krever en del av plassen til innholdet. Dersom innholdet er en liste blir det enda mindre plass til tekst, og om man i tillegg gjør MessageBoxen dismissable blir innholdet enda smalere (se bildeeksempel).

### Hva er løsningen?
Godt spørsmål. Tok dette opp i designsystemforum og noen av forlagene var:
- Wrap teksten rundt dismiss-knappen
- Fjern ikonet i venstre hjørne helt
  - Hvilken farge bakgrunnen har er en god indikator på meldingstypen for de som kan se den
  - For de som ikke ser fargen burde tittel/innhold være beskrivende nok

![image](https://user-images.githubusercontent.com/55135175/217554437-a7cde21b-61b1-4da0-ac99-f9c11bbbd538.png)

**Comment by onordbo** [comment]
@BjorneOma: Hvis vi fjerner ikonet er det ekstra viktig at vi gjør det enkelt å forstå hva slags type melding det er utenom selve fargen (hilsen hilsen fargeblinde og generell universell utforming). Hvis vi skal fjerne ikonet helt Må vi kanskje ty til en prefix av typen 'Feil: ...' 'Advarsel: ...' og da er vi kanskje like langt med tanke på plassbruk?

Når det er sagt, så kan vi uavhengig av hva som skjer med "tittelfeltet" gi litt mer plass til innholdet ved å strekke det fra kant til kant med hele boksen, i stedet for å begrense det til bredden av tittelen. Thoughts?



![Image](https://user-images.githubusercontent.com/4263132/219026918-69fb95cb-8ba3-4e58-b282-4af3a68e9dc6.png)

**Comment by BjorneOma** [comment]
Denne løsninga løser problemet på en elegant måte uten å gjøre det mindre tydelig kva slags type melding det er for fargeblinde. 

Ein utfordring er tittel er optional på MessageBox, så alle steder MessageBox blir brukt uten tittel på oppdateres. For oss på SeOpp kan det bli mykje jobb fordi man kan lage MessageBoxer fra admin-løsningen vår uten påkrevd tittel. Me må finne svaret på dette spørsmålet: Fins det steder messagebox blir brukt uten tittel der det å legge til tittel er negativt?

Her er nokre eksempler på MessageBox uten tittel frå SeOpp:
![image](https://user-images.githubusercontent.com/55135175/219393944-8268a492-49f3-4b43-94f9-773a0ad90fdb.png)
![image](https://user-images.githubusercontent.com/55135175/219393994-42265363-3b31-4ab2-b337-2d1ef3504740.png)
![image](https://user-images.githubusercontent.com/55135175/219394063-7537c840-6744-42d4-94bc-2ffc013f8a58.png)

**Comment by BjorneOma** [comment]
Det hjelper absolutt!

Men - når jeg  ser eksemplene dine ble jeg litt enig med @onordbo igjen. Boksen med 'Oppgi Kontonummeret' kunne like gjerne vært en feilmelding som en infomelding. Dermed blir det vanskelig for noen som ikke ser forskjell på fargene å forstå hvilken type melding dette er. Kanskje ikonene er viktige likevel? 😅 

Hvordan tenker du vi kan få konkludert dette arbeidet? Å sende det frem og tilbake med meg som dommer er kanskje ikke særlig effektivt.

**Comment by onordbo** [comment]
Jeg synes vi gjør oss selv en bjørnetjeneste om vi fjerner ikonet helt og holdent uten å kreve et prefiks. Det er "shaky at best" å lene seg utelukkende på farge for å signalisere hva slags type melding man får. Om behovet vi løser for her er plassmangel til innholdet så gjør hjelper det ikke nevneverdig å fjerne ikonet.

Korteste vei til maksimal plassutnyttelse _(gitt dagens form)_ blir nok å wrappe ikon, tittel og lukkeknapp sammen, og deretter vise medfølgende innhold nedenfor i hele bredden av komponenten. Samtidig er det vel så viktig å nevne at selv de romsligste varianter vil kunne knekke under bruk om man fyller de med for mye innhold.

cc @Slaine2

**Comment by BjorneOma** [comment]
Supert! Ingen breaking change og problemet løst 👏

**Comment by BjorneOma** [comment]
Eg kan fikse kodebiten :)

**Comment by wkillerud** [comment]
Forhåndsvisning: https://jokul.fremtind.no/preview/message-box-innhold-mobil/komponenter/messagebox

Cc @onordbo
