### ISSUE TITLE
Finn ut hvordan vi kan gi alle i Fremtind-organisasjonen tilgang

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3388]
Vi ryddet litt i tilganger i #3281, men det virker som om ikke alle i organisasjonen er dekket av de teamene vi har gitt tilgang. Vi må finne ut av hvordan vi skal løse det uten å gå tilbake til individuelle tilganger.

**Comment by piofinn** [comment]
Løst av IAM-integrasjon
