### ISSUE TITLE
Contextual meny

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3390]
## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** https://github.com/fremtind/jokul/pull/3416
**Designskisser:** [Patterns → navigation/contextual-menu](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/2v8jYATtqzgPnTCVxOKhSg/Patterns?node-id=3563%3A53229&t=GinHNI3ma6UKEXH2-11)
**Forhåndsvisning:** https://jokul.fremtind.no/preview/feat/contextual-menu/komponenter/contextualmenu#komponent
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

-   [x] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by fremtindelise** [comment]
@Chrihenn har jobbet på [denne](https://github.com/fremtind/jokul/tree/feat/contextual-menu) under Jøkul-uka og bidrar med å ferdigstille kode.

**Comment by onordbo** [comment]
[Merget i Figma](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/Patterns?node-id=3563%3A53229&t=SbdyjDkhcOa04LEV-11).

**Comment by wkillerud** [comment]
[Fargebruken i triggerknappen](https://github.com/fremtind/jokul/pull/3416#discussion_r1124223262) er fortsatt litt problematisk, i den forstand at vi teknisk sett lager to nye nyanser (granitt i 5% og 10% opacity). 

Er det egentlig en redesignet [IconButton](https://jokul.fremtind.no/komponenter/iconbutton) vi har med å gjøre her? Hva gjør vi?

Preview: https://jokul.fremtind.no/preview/feat/contextual-menu/komponenter/contextualmenu

Cc @onordbo @Slaine2

**Comment by wkillerud** [comment]
> [Fargebruken i triggerknappen](https://github.com/fremtind/jokul/pull/3416#discussion_r1124223262) er fortsatt litt problematisk, i den forstand at vi teknisk sett lager to nye nyanser (granitt i 5% og 10% opacity).
> 
> Er det egentlig en redesignet [IconButton](https://jokul.fremtind.no/komponenter/iconbutton) vi har med å gjøre her? Hva gjør vi?

Vi diskuterte dette under standup. Vi går for å bare bruke dagens IconButton.
