### ISSUE TITLE
Interaksjonsforbedringer i datepicker

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3391]
## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** #3415 
**Designskisser:** [Components → feat: datepicker/refactor](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/JxptTc7wCh5jR7r1Hh61gJ/Components?node-id=6622%3A15045&t=Lm5zPj4n9ig6OwBc-11)
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

-   [x] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by onordbo** [comment]
[Figma-komponenten](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/JxptTc7wCh5jR7r1Hh61gJ/Components?node-id=6622%3A15045&t=Lm5zPj4n9ig6OwBc-11) begynner å bli klar for merging. Hva synes du @kjetilbendik?

**Comment by onordbo** [comment]
Nye datepicker er nå merget i Figma cc @maciejost @piofinn @kjetilbendik
