### ISSUE TITLE
Valgfri font size på Expandbutton

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3392]
<div type='discussions-op-text'>

<sup>Originally posted by **ivnai** February  9, 2023</sup>
Hallo! Er det ikke god idee, bruke ExpandButton til både, overskrift og åpne/skjul funksjon?
Her på Flyt ønsker vi oss knappen hvor man kan endre fontstil til en annen fra Jøkul.
Hva er tankene?
Er det mulig å utføre endringene? 
<img width="985" alt="Screenshot 2023-02-09 at 09 45 18" src="https://user-images.githubusercontent.com/93194579/217763524-99dd738b-73dc-4b84-8c6f-fa3a188e3bb6.png">
</div>

## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** #3397 
**Designskisser:** `Link til Figma-branch, ved designendringer`
**Forhåndsvisning:** https://jokul.fremtind.no/preview/feat/expandbutton-fontsize/komponenter/expandbutton#andre-fonstørrelser
**Discussion:** https://github.com/fremtind/jokul/discussions/3389

## 🎯 Sjekkliste

-   [ ] Du har laget en branch i Figma og bedt om feedback
-   [x] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by wkillerud** [comment]
I kode styres fontstørrelse og størrelse på ikonet med [disse CSS-variablene](https://github.com/fremtind/jokul/blob/main/packages/expand-button/expand-button.scss#L20-L22). 

- Kan hende vi kan arve fontstørrelsen fra _parent_.
- Eller kan hende vi bør ta inn en React-prop (eks `textStyle` for å matche Sass-mixin) som overstyrer CSS-variablene inline.
- Et tredje alternativ er å utforske [container-patternet](https://www.designsystems.com/react-containers-some-assembly-required/) og henvise til det for tilfeller som dette hvor det trengs noe annet enn body.

**Comment by wkillerud** [comment]
@ivnai, trengs en endring i Figma-komponenten synes du, for å gjøre det enklere å lage med annen fontstørrelse? Eller fungerer det OKi dag?

Jeg har gjort endring i kode så det er lett å endre størrelsen. Preview-link (scroll ned til _Varianter_ og _Andre fonstørrelser_):
https://jokul.fremtind.no/preview/feat/expandbutton-fontsize/komponenter/expandbutton#andre-fonstørrelser

**Comment by ivnai** [comment]
Så bra du @wkillerud ! Tja, nå i Figma arver variants ikke de nye størrelsene så det kan være utfordrende spes. på prototyper.
Dette bør fungere som den skal etter hvert tror jeg. Kunne vi trace alle expandbuttons i bruk slik at vi lager variants til de mest brukte størrelser? Kanskje kunne vi ta dette videre @Slaine2 eller @onordbo f.eks :)
![Screenshot 2023-02-10 at 14 55 33](https://user-images.githubusercontent.com/93194579/218111919-22c85a2b-fe02-4f98-a4a1-5a86bf3d81b3.png)

**Comment by wkillerud** [comment]
@piofinn, vet du om det er noen Figma-branch for dette som er merget?
