### ISSUE TITLE
Figma: innramming

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#3399]
Jeg jobber med å gjøre footer og header tilgjengelig i Jøkul slik at den blir en ferdig mønster.

**Branch:** [`Legg til Figma-link (hvis du har laget et forslag)`](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/fAdUrUqUcbxpInTmQqzDxD/Patterns?node-id=2981%3A13510&t=UhdyTNdGD2XQYb4q-1)

### 🎯 Sjekkliste

-   [ ] Du har sjekket at alt av auto-layout, animasjoner, o.l er satt opp riktig
-   [ ] Du har sjekket at designet matcher kodekomponenten (visuelt, animert og interaktivt)
-   [ ] Du har sjekket at endringen din ikke har overrides (hvis importerte komponenter er i bruk)
-   [ ] Du har gjort arbeidet i en Figma-branch og bedt om feedback

**Comment by onordbo** [comment]
![Image](https://user-images.githubusercontent.com/4263132/219025748-506b2fcf-d4b0-4a4c-920e-b821b2aba8e6.png)

@Slaine2: Jeg tror disse komponentene kan ligge på samme side slik at vi holder kompleksiteten/størrelsen på hele figma-fila nede. I tillegg har alle tre komponentene samme tema, så blir det færre nivåer å forholde seg til under bruk 😊

## Forslag 👇 

- Patterns.fig
  - […]
  - Innramming
    - Header
    - Kontakt
    - Footer
  - […]

**Comment by onordbo** [comment]
### Header
Det mangler en instance swap for å gjøre det mulig å bytte innholdet i komponenten.

![Image](https://user-images.githubusercontent.com/4263132/222085562-92eeaaa9-d2b1-4f35-9be0-fe3e63a4a6b0.png)

### Kontakt og footer

Auto-layouten på desktop-variantene reagerer ikke under bruk, det samme gjelder alle mobilvariantene.

https://user-images.githubusercontent.com/4263132/222086215-01d87b2a-0c30-43ac-b737-69bc80a7ee5f.mov



![Image](https://user-images.githubusercontent.com/4263132/222086428-48c03c70-1493-493a-9f25-2a1db6d7131e.png)



![Image](https://user-images.githubusercontent.com/4263132/222086717-410e5566-8033-4864-ba1c-9b64d6dbc0e5.png)
