### ISSUE TITLE
Feil: Select sender ut en onChange-event på første render

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#3421]
Select-komponenten fyrer av en `onChange`-event på første render, uavhengig av om brukeren har valgt noen verdi eller om det er satt noen verdi i det hele tatt.

## Steg for å gjenskape

1. Gå til https://jokul.fremtind.no/komponenter/select
2. Åpne Javascript-konsollen
3. Se at det er logget ut en onChange-event (evt. last siden på nytt med konsollen åpen for å se det tydeligere)

## Forventet oppførsel

Select-komponenten burde bare fyre av en `onChange`-event når det faktisk har skjedd en endring/blitt valgt en verdi.

## Systeminformasjon

MacOS 13.2.1 og Safari TP 162/Firefox Developer Edition 111.0b2

**Comment by henrikhermansen** [comment]
Jeg opplever at komponenten går i evig loop dersom jeg endrer på `value` selv utenfor komponenten. Da trigges `onChange` fra komponenten med den interne `selectedValue`.

**Comment by wkillerud** [comment]
Er nok innført i #3402

**Comment by wkillerud** [comment]
Hjelper det å sette versjonen til `@fremtind/jkl-select-react` til `13.0.3` @henrikhermansen ?

**Comment by henrikhermansen** [comment]
Jeg satte versjon til `13.0.1`, @wkillerud , siden det var forrige innslag i changelog. Det hjelper i hvert fall, ja, 13.0.1 fungerer som forventet. Jeg rekker ikke teste 13.0.3, for jeg har fri i dag og i morgen :smile:

**Comment by henrikhermansen** [comment]
Det ser ut til at `13.0.5` fra #3424 fikser biffen :smile: :raised_hands:
