### ISSUE TITLE
Komponent/Mønster: Menu + MenuItem

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#3440]
Det er flere team som per nå har implementert hver sin variant av same type komponent. Toppmeny med tilhørende lenker. Tidligere har dette vært en komponent i Figma, men såvidt meg kjent har det ikke eksistert en ekvivalent i kodebasen. Nå ønsker vi å reintrodusere dette på tvers av designsystemet.

Vi starter med en enkel variant i første versjon, ett enkelt menyelement sammen med en toggle for å skjule/vise menyen på smale skjermer. På sikt kan mønsteret utvides i det uendelige med tillegg for kontekstuelle menyer, badges, statusmeldinger og liknende.

![image](https://user-images.githubusercontent.com/4263132/222138730-aec575b0-a598-4c97-b6dc-b26d768ba7c2.png)

## 🔗 Praktiske lenker (om tilgjengelig)

**Designskisser:** [Patterns → feat: navigation/top-menu](https://www.figma.com/file/9b2lNofbSyTNdmO0sGOlrx/branch/nGpYlGGJBZGbyJHl7A0SMu/Patterns?node-id=3957-28004&t=grwWyTLJl2Nomvg2-11)
**Pull request:** `Link til PR, ved endringer på kode`
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

-   [x] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by onordbo** [comment]
Denne er mer eller mindre klar for utvikling. (cc @Murstam)

**Comment by onordbo** [comment]
Er det en idé å supplere et mønster for selve lenkelisten på smale skjermer? Har sett et par versjoner av denne menyen hvor mobilversjonen er en liste med `NavLink` elementer. Er det ikke litt inkonsekvent å bytte komponent sånn uten videre på tvers av brekkpunkter?

**Comment by Murstam** [comment]
Nice. Vi bruker ikke den komponenten, så blir nok ikke vårt team som utvikler hvis du tenkte det.

**Comment by Murstam** [comment]
Var @ivnai som savnet den.
