### ISSUE TITLE
Flytt actions fra `actions/` til egne repoer så andre kan gjenbruke de

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3452]
Vi har to custom GitHub Actions i [`actions/`](https://github.com/fremtind/jokul/tree/main/actions)

- changed files
- paths filter

De to actionene må være commitet som ferdig bygget JavaScript for å kunne kjøre på riktig tid i CI-flyten. 

- Vi bruker paths-filter til å styre hvilke actions som kjører, for eksempel om vi i det hele tatt installerer avhengigheter og bygger. 
- Vi bruker changed files til å se etter og commite nye snapshots for visuell regresjonstesting med Cypress.

**Hvorfor flytte**

Det har skapt litt støy når folk har ulike versjoner av `esbuild` i `node_modules`, som har gitt forskjell i output for `actions/` pga ulik håndtering av kommentarer i kode.

Ved å flytte de støtteverktøyene vi kan ut av Jøkul-repoet slipper vi skape forvirring for folk som bare ønsker å shippe en bugfix eller ny feature.

En annen fordel er at actionene blir mulig å gjenbruke ellers i Fremtind.

**Nye åpne repoer i Fremtind-org**

For at Jøkul skal kunne bruke dem må repoene være public, som resten av Jøkul. Det er en (liten) prosess for å få til. Ta kontakt med Adrian for å komme i gang.

**Comment by piofinn** [comment]
Vi burde nok sjekke om vi kan slippe unna med å bruke standard actions i stedet
