### ISSUE TITLE
Ta stilling til pnpm versus npm og følgene det får for lokal linking

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3453]
Se https://github.com/fremtind/jokul/issues/3309#issuecomment-1342372948 for mer bakgrunnsinformasjon.

> Linking av lokale pakker fungerer ikke lenger for `npm` og `yarn` Classic etter at vi byttet til `pnpm` som package manager. Det er en kjent sak for `npm`, og en wontfix. Forstår at de ikke kan forventes å forstå `node_modules`-strukturen til alle andre package managers under solen.
>
> Jeg er fristet til å si at det å ikke kunne linke opp Jøkul med standard package manager i økosystemet er _not good_, og taler til fordel for å droppe `pnpm` til fordel for vanilla `npm`.

- [ ] Ta et valg om link-situasjonen med `pnpm` er noe vi er OK med.

Avhengig av avgjørelse (lag nytt issue):

- [ ] Migrer til `npm`, vekk fra `pnpm`.
- [ ] Oppdater [Hvordan teste kodeendringer i eget prosjekt](https://jokul.fremtind.no/guider/hvordan-teste-endringer-eget-prosjekt).

**Comment by piofinn** [comment]
Gitt at dette fortsatt er viktig for utvikling i teamene må vi finne ut av hvordan vi angriper dette på tvers av teamene (mtp. forskjellige package managers)

**Comment by piofinn** [comment]
Det virker som de andre teamene er på vei over til pnpm, så da holder vi oss der.
