### ISSUE TITLE
Redesign ToggleSwitch

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3458]
Dagens [ToggleSwitch](https://jokul.fremtind.no/komponenter/toggleswitch) har noen problemer. Det er uklart visuelt om den er skrudd på eller av. Vi ønsker å redesigne komponenten for å løse det problemet.

## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** `Link til PR, ved endringer på kode`
**Designskisser:** `Link til Figma-branch, ved designendringer`
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

-   [ ] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by ivnai** [comment]
@Slaine2 vippebryteren?! cmon med språk man, har jeg ikke tøff nok? haha ;) 
Tja var på den men måtte plutselig forlate unfinished pga teamarbeid. Beklager, jeg fortsetter så snart mulig!

**Comment by ivnai** [comment]
Tenkte ikke på hover nei, så blir den set samme som ToggleSlider; no hover nå.
Det er flere interaktive komponenter som ikke har state-effects, tror dette kan tas på en mer systematisk måte senere? 
Fokus 2px outline som de andre @Slaine2
