### ISSUE TITLE
Feil: Noen av demoene på Animasjoner lastes ikke inn

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3463]
Noen av demoene på Animasjoner har forsvunnet.

![](https://user-images.githubusercontent.com/1223410/225931108-9e561823-e424-44b3-a78a-33d297ff3cc4.png)

## Steg for å gjenskape

1. Gå til https://jokul.fremtind.no/profil/animasjon
2. Scroll ned til Timing

## Forventet oppførsel

Videoene bør være tilgjengelige

**Comment by piofinn** [comment]
Vi fikser ikke dette, i påvente av flytting til ny portal
