### ISSUE TITLE
Gjør SupportLabel mer fleksibel i bruk

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#3474]
For å gjøre `Support Label` mer anvendelig utover feilmeldinger burde vi refaktorere "feilmelding" varianten til noe mer generisk, som "validering" eller noe liknende, med støtte for valgfritt ikon. Dette gir oss en enkel og subtil måte å gi flere typer systemrespons underveis i en skjemaflyt.

## Eksempler
`Hjelpetekst:` "Støttede filtyper er .png og .jpg"
`Hjelpetekst:` "Klar til opplastning"
`Hjelpetekst:` "Laster opp..."
`Validering:` "✅ Lastet opp"
`Validering:` "⚠️ Filen er for stor"
`Validering:` "⛔️ Noe gikk galt"

## Forslag: Komponent-API i Figma
<img width="288" alt="image" src="https://user-images.githubusercontent.com/4263132/227171880-2dad9cb4-3458-4951-9380-85b7b1704287.png">

## 🔗 Praktiske lenker

**Designskisser:** [fix: support-label/validation](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/gQxNj5SEg72dvDL5z7uJzb/Components?node-id=4-2162&t=uTgJpURafVVd5S7C-11)
**Pull request:** `Link til PR, ved endringer på kode`
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

-   [x] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by wkillerud** [comment]
Forslag til løsning i kode for SupportLabel ligger med som en del av #3447. Konkret: https://github.com/fremtind/jokul/pull/3447/commits/403894c0a0d1c645682a0e5a2973deb0ca804ce6

**Comment by leon-ho** [comment]
https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/Components?type=design&version-id=3412564938&node-id=6237-4942&viewport=1157%2C-1622%2C0.47&t=ERsD6H2RXbUgm9lQ-0

Merget inn i Figma 🎉
