### ISSUE TITLE
Feil: Spacing mangler i Fieldgroup på iPhone Chrome og Safari

### ISSUE THREAD

**Issue by BjorneOma** [fremtind/jokul#3481]
Får en rar styling-feil på Fieldgroup på iPhone. Margin under label mangler på iPhone både på Safari og Chrome (har kun testet disse to nettleserene på iPhone). Har ikkje klart å gjenskape feilen på windows eller mac på diverse nettlesere. IPhonen ble nettopp oppdatert til siste iOS-versjon.

## Steg for å gjenskape
1. Gå til https://jokul.fremtind.no/kom-i-gang/lekegrind på iPhone Safari eller Chrome
2. Slett alt og skriv inn denne koden:
`<FieldGroup legend="I am legend" labelProps={{variant:"large"}}><input /></FieldGroup>`
3. Se at margin under label mangler
4. Sammenlign med mac eller windows der margin vises

**Comment by piofinn** [comment]
Hvilken versjon av iOS/Safari bruker du? Klarer ikke å gjenskape dette på min egen telefon (iPhone XS, iOS/Safari 16.4).

**Comment by BjorneOma** [comment]
Det viste seg at eg var på ein eldre versjon 😅 Trudde eg hadde oppdatert til siste versjon, men måtte visst oppdatere på nytt. Eg klarer heller ikkje gjenskape denne på iPhone 12 etter oppdatering til 16.4.1. Lukker saken.
