### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [fremtind/jokul#3494]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by wkillerud** [comment]
Hi @igibek

Thank you for reaching out. We've enabled the Private vulnerability reporting feature now.

**Comment by wkillerud** [comment]
Closing this, as the private vulnerability reporting feature is active.
