### ISSUE TITLE
Docs (portal) does not reflect actual packages

### ISSUE THREAD

**Issue by 42tte** [fremtind/jokul#351]
**Describe the bug**
The documentation [portal](https://fremtind.github.io/jokul/components/) has the latest and greatest future release features and does not reflect what you actually get when installing a package.

**To Reproduce**
Install @fremtind/jkl-core add a link with classes from docs. Styling is missing hover effects.

**Expected behavior**
Docs should reflect actual package content.

**Comment by lfbergee** [comment]
The reason is the portal is built on merge to master, the release to npm is done manually. 

Yeah, one possible solution is to publish to npm in the same step as we build the portal. ( I like this)

Or we can wait with deploy of the portal untill we publish to npm.
