### ISSUE TITLE
Figma: Fix Tooltip

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#3514]
det er en feil der figmaet er forskjellig fra komponenten i biblioteket.

[**Figma Branch**](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/XNhDUaG84eNcf7kYdN226G/Components?node-id=1543%3A2046&t=LCdBrQYMn8079mam-1)

### 🎯 Sjekkliste

-   [x] Du har sjekket at alt av auto-layout, animasjoner, o.l er satt opp riktig
-   [x] Du har sjekket at designet matcher kodekomponenten (visuelt, animert og interaktivt)
-   [x] Du har sjekket at endringen din ikke har overrides (hvis importerte komponenter er i bruk)
-   [x] Du har gjort arbeidet i en Figma-branch og bedt om feedback

**Comment by leon-ho** [comment]
(Ref: Saken handler om at tooltip popout skal vises ved klikk, istedenfor hover)
