### ISSUE TITLE
Feil: logostempelet har havnet på venstre side om man ikke godtar statistikk

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3519]
Logostempelet i bunnen av siden har havnet på venstre side på alle sidene, bortsett fra forsiden. Sikkert en regresjon fra da vi byttet ut footeren. 

## Steg for å gjenskape

1. Gå til https://jokul.fremtind.no/komponenter/accordion
2. Scroll ned til bunnen. Se at stempelet er på venstre side.

## Forventet oppførsel

Stempelet skulle vært på høyre side, slik som på forsiden.

## Systeminformasjon

Safari 16.4

**Comment by fremtindelise** [comment]
Hos meg er det på høyre side 🤔 

![Image](https://user-images.githubusercontent.com/117173936/237024305-90c577c3-b882-4173-bf41-8a48912ecce3.png)

**Comment by wkillerud** [comment]
Aah, det skjer bare hvis man ikke godtar statistikk i cookie consent 😅
