### ISSUE TITLE
Combobox: Forslag til forbedringer

### ISSUE THREAD

**Issue by leon-ho** [fremtind/jokul#3530]
Forslag til forbedringer (åpen for diskusjon):

Tastaturnavigasjon
* ~~Backspace i tekstfelt fjerner foregående valg.~~ ✅
* ~~Fokus på øverste treff i listen mens man skriver, slik at man kan trykke "enter" for å velge med en gang (uten å trykke ⬇️) (Da kan man skrive, trykke "enter", og raskt få inn flere valg etter hverandre)~~ 🚫

UI
* #3846 Klikking i komponenten, men utenfor det usynlige input-feltet bør likevel gi fokus til komponenten.
   * <img width="527" alt="image" src="https://github.com/fremtind/jokul/assets/1818882/cb6cc187-f6bf-4a48-b890-32580b36cf06"> 
* ~~Bug at tekstinput ligger under "X (Fjern alle)" og "⬇"~~ ✅
   * <img width="239" alt="image" src="https://user-images.githubusercontent.com/1818882/237040569-77f1bcea-63cd-45ef-aaa6-2332b37da2a5.png">
* #3848 Litt vanskelig å se hvilket alternativ som er i fokus? (Er det den med lys bakgrunn eller litt mørkere?)
   * <img width="251" alt="image" src="https://github.com/fremtind/jokul/assets/1818882/fa74a1b6-9a65-4e86-bea8-0fb9ffa1965b">
* ~~Vis en melding (customisable?) når man ikke får noen treff på søkeordet?~~ ✅

Dokumentasjon
* #3847 Ser ut som "value" og "label" er påkrevd i items-objektene, men kanskje dette kommer fra "ValuePair" som er et velkjent begrep/objekt i Jøkul? For meg så var det ikke selvsagt, skulle gjerne sett mer dokumentasjon på dette.

Kode
* #3847 Ref over, "value" og "label" er hardkodet, men man kan (kanskje?) få data med andre formater, e.g. { id: 123, name: 'Fremtind' }, det hadde vært fint å ha f.eks. valueProp og labelProp så man kan tilpasse mer fleksibel data. (Bedre utvikleropplevelse?)

## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** `Link til PR, ved endringer på kode`
**Designskisser:** `Link til Figma-branch, ved designendringer`
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

-   [ ] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by fremtindelise** [comment]
Bug at tekstinput ligger under "X (Fjern alle)" og "⬇": #3531

**Comment by leon-ho** [comment]
La til en liten sak i listen over: 
* Klikking i komponenten, men utenfor det usynlige input-feltet bør likevel gi fokus til komponenten.

**Comment by fremtindelise** [comment]
Ref: "Litt vanskelig å se hvilket alternativ som er i fokus? (Er det den med lys bakgrunn eller litt mørkere?)"

<img width="251" alt="237063883-fa74a1b6-9a65-4e86-bea8-0fb9ffa1965b" src="https://github.com/fremtind/jokul/assets/117173936/94216bb9-2a1f-4e5b-8793-62498483d13c">

@ivnai Har du noen forslag her?

**Comment by piofinn** [comment]
Opprettet egne issues for det som ikke allerede er fikset
