### ISSUE TITLE
Ny padding på tertiærknappen

### ISSUE THREAD

**Issue by Slaine2** [fremtind/jokul#3556]
Det kan trenges visuelle endringer på tertiærknappen. Det har nå en padding på 8px. Det pleide å være 2px. 
Usikker på hvor endringen kom fra, men mange visuelle designere ønsker at dette skal begrenses tilbake til 2px.

## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** https://github.com/fremtind/jokul/pull/3572
**Designskisser:** [`Figma-branch med ny padding`](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/qFT1AjsAHspC9hpuBQ57fM/Components?type=design&t=ZoEm7VnSjqwreD4C-1)
**Forhåndsvisning:** https://jokul.fremtind.no/preview/fix/button-padding/komponenter/buttons/

## 🎯 Sjekkliste

-   [ ] Du har laget en branch i Figma og bedt om feedback
-   [x] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by wkillerud** [comment]
Husker ikke motivasjonen for akkurat _denne_ endringen, men det ble innført da vi ryddet opp i Compact versus Mobile (#2996).

Jeg antar det menes left og right padding, slik at vi ikke endrer høyden på tertiærknappen?



![default](https://github.com/fremtind/jokul/assets/1223410/f364087a-6d3e-4ac2-973f-62045bfd7ba8)
![compact](https://github.com/fremtind/jokul/assets/1223410/03074edf-b25a-485b-9154-650af4dc9209)

**Comment by wkillerud** [comment]
Koden er klar, men jeg får ikke gjort endringen i Figma.

**Comment by wkillerud** [comment]
Figma mangler fremdeles
