### ISSUE TITLE
Feil: SkeletonAnimation mangler role

### ISSUE THREAD

**Issue by henrikhermansen** [fremtind/jokul#3557]
Lighthouse klager på at SkeletonAnimation mangler role.

Selv om aria-busy skal kunne brukes med alle roller, så er det allikevel ikke godkjent å unngå å spesifisere rolle.

![image](https://github.com/fremtind/jokul/assets/435037/729715ee-372d-436a-9c91-d3f291160fd2)

I en kort diskusjon på Teams ble det også nevnt at aria-busy skal brukes i aria-live-regioner av siden, og at kanskje en container må ha aria-live. I så fall, hadde det vært lurt om Jøkul eksponerte en passende komponent man kan bruke som wrapper, for å gjøre det lettere for konsumenter å gjøre dette riktig?

**Comment by piofinn** [comment]
Det er mulig å sette `role` på komponenten ved bruk, og siden det er umulig å vite sikkert hvordan den brukes i hvert enkelt tilfelle er det bedre at det er opp til bruker.
