### ISSUE TITLE
Feil: DatePicker - dårlig kontrast på kalenderikon i dark mode når data-invalid=true

### ISSUE THREAD

**Issue by markusleitvoll** [fremtind/jokul#3595]
I DatePicker komponenten, når bruker har valgt mørkt tema og "Med feil" er checket, er kalenderikonet nesten usynlig. Dette overholder ikke WCAGs krav om kontrastforhold på minimum 4,5:1.
![Skjermbilde 2023-06-30 kl  09 44 02](https://github.com/fremtind/jokul/assets/61907991/0f63b520-30e5-42d4-a854-96650d37d571)

## Steg for å gjenskape

1. Gå til DatePicker komponenten
2. Check "Med feil"
![Skjermbilde 2023-06-30 kl  09 57 43](https://github.com/fremtind/jokul/assets/61907991/792010ba-bdce-4977-8e50-53989f52eac8)
3. Check "Tema Dark"
![Skjermbilde 2023-06-30 kl  09 59 40](https://github.com/fremtind/jokul/assets/61907991/f9d211ef-7b50-47e0-98eb-090b44fdb2c8)

**Comment by wkillerud** [comment]
@all-contributors please add @markusleitvoll for bug
