### ISSUE TITLE
ExpandableTableRow - mulighet for å kontrollere expanded state

### ISSUE THREAD

**Issue by glennbarosen** [fremtind/jokul#3597]
ExpandableTableRow har foreløpig ikke noe måte å kontrolleres på. Ønsker å få inn en expanded-prop for å styre open/closed state.

I SAM brukes dette nå for å ekspandere rader med feilvalidering og lukke ferdig validerte rader.
<img width="1245" alt="Screenshot 2023-06-30 at 12 47 27" src="https://github.com/fremtind/jokul/assets/42523289/9ba81fea-0213-45b6-967e-e62ed69e9dff">

## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** `Link til PR, ved endringer på kode`
**Designskisser:** `Link til Figma-branch, ved designendringer`
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

-   [ ] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by wkillerud** [comment]
@all-contributors please add @glennbarosen for idea
