### ISSUE TITLE
Search for components in portal

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#361]
**Is your feature request related to a problem? Please describe.**
When the component libary continues to grow, finding the excact component you're looking for will increase in difficulty. A search function can mitigate this.

**Describe the solution you'd like**
Add a search-bar in the main menu under components that filters the list of links

**Describe alternatives you've considered**
Add a search-bar in the top header that links to the components

**Additional context**
For FFE I use this feature pretty much every time I'm looking for a component.

**Comment by eduardodir** [comment]
@Mikkelinski Mikkelinski is there a "design" done for this one?

**Comment by Mikkelinski** [comment]
@eduardodir not yet unfortunately - I think the end point would be an input field with optional label + a search icon at the end of the underline (similar placement as the chevron on our dropdown) but we haven't drawn one yet
