### ISSUE TITLE
Sørg for at skjemaelementer aligner bedre i horisontal retning

### ISSUE THREAD

**Issue by ivnai** [fremtind/jokul#3614]
Når brukes i skjema sammen horisontalt: textInput og radio/checkInput, så sitter ikke radio/check innhold på optisk god plass.
Snakker kun om compact nå. Det bør sjekkes om det er flere komponenter som trenger slik justering og om/hvordan endringen evt påvirker design i andre kontekster. Også andre størrelser.
Dessverre får ikke grundigere jobbe på dette nå. Blir Jøkuluka snart?
![Screenshot 2023-07-04 at 13 34 58](https://github.com/fremtind/jokul/assets/93194579/b22dd8f1-5e68-41be-b4ab-e8463d64f092)

https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/6JDFrMUfG3wLO0M7QMjxI5/Components?type=design&node-id=12057%3A18537&mode=design&t=Ti0lOGThxy1BwKKS-1

**Comment by ivnai** [comment]
Dette bør være i Discussion kanskje

**Comment by piofinn** [comment]
Dette bør fikses ved å sørge for at alle inputs har riktig høyde, og at det er riktige avstander over/under labels

**Comment by piofinn** [comment]
@ivnai Dette skal bli løst i Figma når vi tar i bruk felles komponent for label/support label i alle input-komponentene. Gi beskjed hvis dette fortsetter å være et problem, så kan vi ta det opp igjen 😊
