### ISSUE TITLE
Undersøk en migrering til Vite og Vitest

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3618]
Erfaringene fra BM og SeOpp er gode. I dag har vi en kombinasjon av Jest, esbuild, tsc, gulp, og webpack (for Gatsby). 

Det hadde vært interessant å erstatte i hvertfall esbuild og Jest med vite og vitest, og undersøke mulighetene for å skifte ut Gulp.

**Comment by piofinn** [comment]
Blir gjort i #4061
