### ISSUE TITLE
Tab – Mobil

### ISSUE THREAD

**Issue by Murstam** [fremtind/jokul#3638]
40px padding på mobil er for mye og lite funksjonelt. Taben vokser veldig fort ut av view frame. Har satt opp et eksempel på 24px og 16px. Tanker?
<img width="1330" alt="Screenshot 2023-08-09 at 12 51 18" src="https://github.com/fremtind/jokul/assets/47025023/37a67a7e-8ca6-42ca-9156-61da1049b099">

**Comment by fremtindelise** [comment]
I fix!
