### ISSUE TITLE
Datepicker/Textinput: Gjør det enklere å fylle inn dato manuelt. Datoformatering i input.

### ISSUE THREAD

**Issue by leon-ho** [fremtind/jokul#3648]
<img width="882" alt="image" src="https://github.com/fremtind/jokul/assets/1818882/5bb69f83-016c-474e-96ab-f7d990361f55">

<img width="407" alt="image" src="https://github.com/fremtind/jokul/assets/1818882/a7443c34-fbcb-4cd1-8487-d3ab4d5b9a10">

**Comment by piofinn** [comment]
Få inn støtte for å kun skrive tall (uten punktum) potensielt med input mask.
