### ISSUE TITLE
Message box mobile: Ikon på linje med heading

### ISSUE THREAD

**Issue by Stakset** [fremtind/jokul#3651]
Foreslår at vi justerer message box sitt ikon til å oppføre seg likt som desktop og compact. 

Ble diskutert på DS-forum 15. august. 

Branch: https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/branch/gJgD7LSgesUEbtGhb86zqZ/Core?type=design&node-id=2007%3A8918&mode=design&t=HkVkGOtnsgcYAtYu-1

**Comment by Stormoen** [comment]
Mobilversjon av Message Box har nå ikon og kryss på samme linje som tittel. Ikon og kryss er beholdt i samme str som desktop.

https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/Components?type=design&node-id=2007%3A8918&mode=design&t=f3qXMuWgoXInPl5w-1

### 🎯 Sjekkliste

-   [ ] Du har sjekket at alt av auto-layout, animasjoner, o.l er satt opp riktig
-   [ ] Du har sjekket at designet matcher kodekomponenten (visuelt, animert og interaktivt)
-   [ ] Du har sjekket at endringen din ikke har overrides (hvis importerte komponenter er i bruk)
-   [ ] Du har gjort arbeidet i en Figma-branch og bedt om feedback

**Comment by Stormoen** [comment]
Denne må oppdateres i kode.
