### ISSUE TITLE
Standardising and formalising Form-components

### ISSUE THREAD

**Issue by Mikkelinski** [fremtind/jokul#366]
We have created a new structure for form components to be able to build consistent forms across our various applications.

The new form requires changes to the Input field and Dropdown components, and standardisation of the "Form group" component(?).

**New structure:**
Every form component will consist of a label + the form component itself. There will be 2 label sizes available to chose from depending on if the form component stands alone in its section or if it is in a section with multiple form components.

For sizes and references see the Figma link and ask Mikkel / Stein Olav

**Changes to inputs & dropdowns:**
Input and Dropdown components will not have animation to change label size, instead they will have a placeholder text until input or selection is made. 

**Figma link**
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=4055%3A6026

**Comment by piofinn** [comment]
Have we decided what to do with datepicker in relation to this? It uses both a text input and a select field in the dropdown itself, so it will either need a redesign or custom labels for the inputs..

**Comment by Mikkelinski** [comment]
@piofinn  I knew we'd forgotten something - the datepicker in the default closed state is just an input field - but for the open picker if possible it could remain as is until we get to it and we'll prioritise figuring out how it should look / act. If I remember correctly there are some limitations to it due to it being based on the NRK component (like no styling on the dropdown)?

**Comment by piofinn** [comment]
Since we are now implementing input variants that are basically the same as the old ones, this should not be a problem anymore 🎉
