### ISSUE TITLE
Oppdatering basert på endringer i Figma: Card

### ISSUE THREAD

**Issue by fremtindjonas** [fremtind/jokul#3660]
- Padding er nå dynamisk basert på device
- Bakgrunnsfarge endret for darkmode
- Taskcard: Skal ha tre mulige farger (det var fire før)
- Infokort: Heter Infocard i Figma, og Infoblock i kode, vi må velge ett felles navn
- Infokort: Fjernet mulighet for å legge til bilde
- Infokort: Endret default bakgrunnsbilde
- Infokort bug: Title har ikke riktig element

Figmaskisse: https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/Core?type=design&node-id=2022%3A1884&mode=design&t=yHPu7GSAEiLUrwHv-1

**Comment by fremtindelise** [comment]
@fremtindjonas Er det umulig å få se de tre fargene til TaskCard skal ha i dark mode også? Jeg kan ikke finne de i lenken 🤔

**Comment by fremtindjonas** [comment]
@fremtindelise Nå er eksempler for highlighted og subdued lagt til :)
