### ISSUE TITLE
Oppdatering basert på endringer i Figma: Checkbox

### ISSUE THREAD

**Issue by fremtindjonas** [fremtind/jokul#3661]
- Farge på fokus er endret
- Legg til ny padding topp og bunn

Figmaskisse: https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/Core?type=design&node-id=2006%3A3728&mode=design&t=yHPu7GSAEiLUrwHv-1

**Comment by ivarni** [comment]
@fremtindjonas Jeg finner ikke helt fram til hvilken padding som er ny, er det avstanden mellom de forskjellige checkboxene?

**Comment by fremtindjonas** [comment]
@ivarni Det er lagt til spacing-8-8-4 på topp og bunn av komponenten, altså 8px padding topp og bunn på desktop og mobil, og 4px padding topp og bunn på desktop. Før var det 0px padding topp og bunn. Har lagt ved et bilde som viser forskjellen på komponenten før (venstre) og nå (høyre) (eksempelet er komponenten i desktop)

![image](https://github.com/fremtind/jokul/assets/141401316/6401fe8a-62ec-4ceb-a8ab-4a2110ff873c)

**Comment by ivarni** [comment]
@fremtindjonas Skjønner. I koden nå er det 12 på dekstop og 8 på mobil så da reduserer jeg til 8 og 4.
