### ISSUE TITLE
Oppdatering basert på endringer i Figma: Combobox og Select

### ISSUE THREAD

**Issue by fremtindjonas** [fremtind/jokul#3662]
- Ny farge på input og bakgrunn
- Ny farge bakgrunn på liste
- Ny farge bakgrunn på hover og selected

Figmaskisse: https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/Core?type=design&node-id=2007%3A14370&mode=design&t=yHPu7GSAEiLUrwHv-1

**Comment by ivarni** [comment]
@fremtindjonas State med feil kom ikke med på Figma-skissen og jeg ser også at om jeg endrer text-fargen til stein i "error modus" er ikke kontrasten til den røde bakgrunnen innafor AA, skal jeg beholde den som den er der?

**Comment by fremtindjonas** [comment]
@ivarni Jeg og Heidi tok en prat om det nå, vi tenker vi kan endre fargen til stein i "error modus"

**Comment by ivarni** [comment]
Endring på padding i tagen for valgte elementer i Combobox ligger i #3670

**Comment by ivarni** [comment]
Endring på farge i hjelpetekst ligger i #3671
