### ISSUE TITLE
Oppdatering basert på endringer i Figma: Contextual menu

### ISSUE THREAD

**Issue by fremtindjonas** [fremtind/jokul#3663]
- Endret padding
- Lagt til ekstern lenke ikon på menu item
- Farge endret i dark mode

Figmaskisse: https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/Core?type=design&node-id=2010%3A589&mode=design&t=yHPu7GSAEiLUrwHv-1

**Comment by ivarni** [comment]
Denne har en avhengighet til ToggleSwitch via CSS-klasser, kanskje se på denne samtidig med #3677
