### ISSUE TITLE
Oppdatering basert på endringer i Figma: Datepicker

### ISSUE THREAD

**Issue by fremtindjonas** [fremtind/jokul#3664]
- Ny farge på background i aktiv og fokus state
- Ny hovedfarge på måneds- og årsvelger
- Nye farger i darkmode

https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/Components?type=design&node-id=2007-4824&mode=design&t=h29UnIhYXBSBh1Yy-0

**Comment by ivarni** [comment]
Endring på text-inputs farger ligger i #3671
