### ISSUE TITLE
Oppdatering basert på endringer i Figma: Select

### ISSUE THREAD

**Issue by fremtindjonas** [fremtind/jokul#3669]
- Ny farge på input og bakgrunn
- Ny farge bakgrunn på liste
- Ny farge bakgrunn på hover og selected

Figmaskisse: https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/Core?type=design&node-id=2007%3A14370&mode=design&t=yHPu7GSAEiLUrwHv-1

**Comment by ivarni** [comment]
Tatt i #3662
