### ISSUE TITLE
Oppdatering basert på endringer i Figma: Tag

### ISSUE THREAD

**Issue by fremtindjonas** [fremtind/jokul#3670]
- Skal ha 0px spacing i compact

Figmaskisse: https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/Core?type=design&node-id=2004%3A257&mode=design&t=yHPu7GSAEiLUrwHv-1

**Comment by ivarni** [comment]
Dette ble en no-op, koden lå litt foran Figma her :)
