### ISSUE TITLE
Oppdatering basert på endringer i Figma: TextArea/TextInput

### ISSUE THREAD

**Issue by fremtindjonas** [fremtind/jokul#3671]
- Bakgrunnsfarge endret på darkmode fokus
- Endret farge på counter

Figmaskisse: https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/Core?type=design&node-id=2007%3A2252&mode=design&t=yHPu7GSAEiLUrwHv-1

**Comment by ivarni** [comment]
Merk at vi per i dag kun støtter å ha et icon i høyre ende av feltet
