### ISSUE TITLE
Oppdatering basert på endringer i Figma: Toast

### ISSUE THREAD

**Issue by fremtindjonas** [fremtind/jokul#3672]
- Skal ha 4px radius
- Padding skal endres basert på device og compact
- Endret farge darkmode neutral toast

Figmaskisse: https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/Core?type=design&node-id=2007%3A18637&mode=design&t=yHPu7GSAEiLUrwHv-1

**Comment by ivarni** [comment]
@fremtindjonas Skal nøytral toast også ha ikon nå eller er det bare litt copy-paste i skissene?

**Comment by fremtindjonas** [comment]
@ivarni Hmm, det vet jeg ikke. Jeg ikke vært med på å designe komponenten, så vet ikke om tanken var å endre eller om det er en glipp. Jeg tror vi kan la den være uten ikon inntil videre, så kan jeg ta en vurdering med Heidi
