### ISSUE TITLE
Figma: Nye funksjonsfarger light- og darkmode

### ISSUE THREAD

**Issue by Stormoen** [fremtind/jokul#3701]
Funksjonsfargene trenger en oppdatering for å skape et mer helhetlig og likt uttrykk på tvers av light- og darkmode, samt at fargene også skal fungere på mindre flater som check- og kryss ikoner. Oppdateringen bør også sørge for litt bedre kontrast mot de mørkere lightmode bakgrunnene sand og dis enn i dag. 

Dette gjør også at vi kan kvitte oss med fire ikonfarger som kun har eksistert hos PM/KFP teamene. 

Skisse https://www.figma.com/file/Zl7PdbUGjBxzJ1E2jd08Hn/VD-forum-2023?type=design&node-id=1056%3A19321&mode=design&t=8JX9LxJITK0JC5K6-1

I figma må fargevariablene oppdateres.
**Branch:** `Legg til Figma-link (hvis du har laget et forslag)`

### 🎯 Sjekkliste

-   [ ] Du har sjekket at alt av auto-layout, animasjoner, o.l er satt opp riktig
-   [ ] Du har sjekket at designet matcher kodekomponenten (visuelt, animert og interaktivt)
-   [ ] Du har sjekket at endringen din ikke har overrides (hvis importerte komponenter er i bruk)
-   [ ] Du har gjort arbeidet i en Figma-branch og bedt om feedback

**Comment by Stormoen** [comment]
Branch: https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/branch/wXvBuNpWGKZHBtxS6CH7vy/Components?type=design&mode=design&t=aKo3k8Kz4KdlIWY2-1

**Comment by ivarni** [comment]
@Stormoen @fremtindelise Er det noe mer vi trenger å gjøre med denne saken?

**Comment by fremtindelise** [comment]
> @Stormoen @fremtindelise Er det noe mer vi trenger å gjøre med denne saken?

Ikke på utvikler siden i alle fall!

**Comment by Stormoen** [comment]
Oppdatert i FIgma også
