### ISSUE TITLE
PopupTip: funksjon som gjør at den holdes åpen og lukkes ved klikk utenfor 

### ISSUE THREAD

**Issue by fremtindelise** [fremtind/jokul#3726]
I DS-forum 10. oktober er det kommet spørsmål om å legge til funksjonalitet i PopupTip som gjør at den holdes åpen ved klikk utenfor (likt som ContextualMenu). 

<img width="413" alt="MicrosoftTeams-image (1)" src="https://github.com/fremtind/jokul/assets/117173936/21e83d56-61fc-462f-b236-ea1ac689f168">

## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** `Link til PR, ved endringer på kode`
**Designskisser:** `Link til Figma-branch, ved designendringer`
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

-   [ ] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by piofinn** [comment]
Dette er ikke det problemet PopupTip skal løse, så her er det bedre å finne en annen løsning på problemstillingen. Kanskje det vil hjelpe med mer generaliserte kort?
