### ISSUE TITLE
Drag-icon

### ISSUE THREAD

**Issue by Stormoen** [fremtind/jokul#3731]
Drag-icon er nå lagt til i Figma-biblioteket. 
- sm
- sm-bold
- md
- md-bold

Må legges til i kode også. Trenger dere svg? 

Enn så lenge bruker ikke ikonene fargevariablene, men de skal oppføre seg i som de andre i light- og darkmode.

https://www.figma.com/file/DektfpgSnhwTVyrcXKwdem/Assets?type=design&node-id=2444%3A204&mode=design&t=jxXICgsmlfK0QKtR-1

**Comment by ivarni** [comment]
@Stormoen Preview av denne og dottene tilgjengelig på https://jokul.fremtind.no/preview/3731-3732-icons/komponenter/icons/

Jeg eksporterte SVGene fra Figma, ser ut som det ble riktig tror jeg
