### ISSUE TITLE
Dekker/dekker ikke icon

### ISSUE THREAD

**Issue by Stormoen** [fremtind/jokul#3733]
"Dekker/dekker ikke ikoner" er lagt til i Figma. Oppfører seg likt i light- og darkmode. 
Vi ser ikke behovet for en small utgave her, etter en sjekk med PM. Der brukes de i liste og alene i tabell.

De eksisterer i portalen i dag under liste og dekning, men må oppdateres
https://jkl-portal.aws.fremtind.no/komponenter/list

Navngitt slik enn så lenge, åpen for forslag:
red-cross-md
green-check-md

Figma:
https://www.figma.com/file/DektfpgSnhwTVyrcXKwdem/Assets?type=design&node-id=2476%3A1065&mode=design&t=jxXICgsmlfK0QKtR-1

**Comment by ivarni** [comment]
@Stormoen Er tanken at de skal være tilgjengelig for bruk på lik linje som alle andre ikoner også? Jeg tolker det litt sånn siden det står at PM også bruker dem alene i tabell.

**Comment by ivarni** [comment]
@Stormoen Forskjellig variant for dark/light kan jeg nok håndtere så lenge jeg får eksporert begge variantene fra Figma, er det noen måte jeg kan toggle light/dark på det som er lenket over?

**Comment by Stormoen** [comment]
La en vising av det her uansett: https://www.figma.com/file/DektfpgSnhwTVyrcXKwdem/Assets?type=design&node-id=2553%3A12&mode=design&t=Qv3CUwhHlmsaAS44-1
