### ISSUE TITLE
Feil: dekningsikoner ser rare ut i compact

### ISSUE THREAD

**Issue by fremtindelise** [fremtind/jokul#3749]
Dekningsikoner blir rare i liste i compact mode. Er noe buggy med størrelsen.

![Skjermbilde 2023-11-07 kl  09 49 23](https://github.com/fremtind/jokul/assets/117173936/3f75533a-546e-4a7b-ae51-befc072e2152)

**Comment by ivarni** [comment]
@fremtindelise Husker du hvilken browser det var i?

**Comment by ivarni** [comment]
Skulle ikke lukke denne, hadde en commit med feil issue ID bare

**Comment by fremtindelise** [comment]
@ivarni denne ble løst i [3755](https://github.com/fremtind/jokul/pull/3755)?

**Comment by ivarni** [comment]
@fremtindelise Nei, denne skulle ikke lukkes, jeg hadde en commit med feil issue ID så jeg åpnet den igjen.

**Comment by fremtindelise** [comment]
> @fremtindelise Husker du hvilken browser det var i?

Chrome :)

**Comment by piofinn** [comment]
Lukkes, se heller #3793
