### ISSUE TITLE
Feil: Logo-komponenten gir et flash of unstyled content der logoen tar opp så mye plass den får på skjermen

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#3752]
Logo-komponenten gir et flash of unstyled content der logoen tar opp så mye plass den før på skjermen.
Vi bør sørge for at logoen har en fornuftig størrelse også før JS/CSS er lastet inn på siden.

## Steg for å gjenskape

1. Gå til en side som bruker logo-komponenten fra Jøkul
2. Last inn siden på nytt (sett gjerne på throttling fr å se feilen bedre)
3. Se at logoen tar opp mer plass før stilarkene lastes

## Forventet oppførsel

Ingen svære logoer eller ikoner før stilene lastes

## Systeminformasjon

MacOS 13.6.1, Arc 1.15.1 (Chromium 119)

**Comment by ivarni** [comment]
@piofinn Jeg er usikker på om det var riktig å gi Jøkul "skylden" for dette. Det er ingenting i CSSen her som styrer størrelsen på logoen, den oppfører seg bare som alle andre SVGer og skalerer ut til den plassen konsumenten gir den. 

Det som derimot er Jøkul sin skyld er at typene ikke tillater noen form for inline kontroll på bredden utenfra :) Det er to alternativer, `width` attributtet til SVG eller inline styles. Jeg heller mot det siste siden det føles litt mer som det vi vil er å sette en maks bredde.

**Comment by ivarni** [comment]
@piofinn Da jeg skulle verifisere en fiks på dette klarte jeg ikke å gjenskape problemet... i fremtind.no appen laster vi jo CSSen i `<head>` som jo skal gjøre det blocking. Kan det være at dette bare var et problem i dev-mode?
