### ISSUE TITLE
Ingen måte å "fjerne" selection av elementer i combobox

### ISSUE THREAD

**Issue by ivarni** [fremtind/jokul#3762]
Tester litt med keyboard-navigasjon i forbindelse med oppdatering av komponenter i jkl-portal
(https://jkl-portal.aws.fremtind.no/komponenter/combobox)

## Steg for å gjenskape

1. Fokuser comboboxen
2. Velg et par elementer
3. Bruk cmd/ctrl + a for å velge alle
4. Det virker ikke som det er mulig å fjerne valget igjen

## Forventet oppførsel

Det burde være en måte å "unselecte" de valgte elementene. Kanskje Escape? Litt usikker på hva som blir mest riktig

**Comment by piofinn** [comment]
Denne komponenten er sykt komplisert. Skal vi vurdere et tredjepartsbibliotek snart...?
