### ISSUE TITLE
Figma: Combobox har ny prop

### ISSUE THREAD

**Issue by fremtindelise** [fremtind/jokul#3781]
Combobox har fått en ny prop `hasTagHover`. Dette er foreløpig kun implementert i kode og komponenten må oppdateres i Figma også.

Lenke:
https://jokul.fremtind.no/komponenter/combobox/

**Branch:** `Legg til Figma-link (hvis du har laget et forslag)`

### 🎯 Sjekkliste

-   [ ] Du har sjekket at alt av auto-layout, animasjoner, o.l er satt opp riktig
-   [ ] Du har sjekket at designet matcher kodekomponenten (visuelt, animert og interaktivt)
-   [ ] Du har sjekket at endringen din ikke har overrides (hvis importerte komponenter er i bruk)
-   [ ] Du har gjort arbeidet i en Figma-branch og bedt om feedback

**Comment by piofinn** [comment]
Skal vi vurdere å gjøre dette til et standardvalg (dersom `tagLabel` er i bruk)?

**Comment by piofinn** [comment]
Vi trenger ikke dette nivået av detaljer på Figma-komponenten
