### ISSUE TITLE
Feil: Searchable select submitter forms når du ikke bruker piltaster

### ISSUE THREAD

**Issue by kennidenni** [fremtind/jokul#3783]
Searchable select submitter forms dersom du klikker enter uten at du har tatt piltast ned først. 

Ønsker at enter velger den verdien som er øverst i listen slik at den IKKE submitter formet. 
Dette vil også være et problem dersom du velger noe som er feil, så går du inn i select igjen for å velge noe annet og trykker enter (se video)
Når det da er valgt en verdi i den Select-en så vil du ikke få en form-error på denne komponenten og du vil potensielt gå til neste side dersom det er det submit knappen din gjør.

## Steg for å gjenskape

1. Gå til f.eks https://kundeforsikring.sparebank1.no/privat/forsikring/motor/bil og velg modellvelger
2. Bruk tastatur navigasjon og skriv inn f.eks testa
3. Press enter uten å ta piltast ned, da vil formet submitte. 

Se denne videoen 

https://github.com/fremtind/jokul/assets/31621649/10592295-9cf0-4243-b91d-8aa8b75b9e06

## Forventet oppførsel

"Enter"-knappen velger første element i listen dersom du ikke har klikket piltast ned for å velge et element.
Se modellvelger for bil hos Gjensidige hvordan det ser ut

**Comment by ivarni** [comment]
Mulig dette da ble oversett i fiksen av https://github.com/fremtind/jokul/issues/3776

Fiksen for dette bør være veldig lignende det som ble gjort der.

**Comment by ivarni** [comment]
@kennidenni Hvilken versjon er dere på?

**Comment by kennidenni** [comment]
@ivarni Vi er på 14.1.16. Har det kommet noen fiks på dette etter denne versjonen?

**Comment by joms** [comment]
Jeg er enig med du @ivarni. Her gir det mer mening enter bør lukke komponenten og stoppe event-propagering i stedet for å submitte formet. 

Native funksjonaliteten til en select ser ut til å være at enter på et valg i åpen select lukker select uten form submit. Det samme gjelder om man trykker enter på en select mens den er lukket.
Derimot kan den ikke åpnes med enter. Selv synes jeg det er behagelig at den kan interageres med enter også.

**Comment by ivarni** [comment]
Etter litt mer diskusjon kom vi fram til at det gir mer mening om Enter ikke lukker søkeboksen, dvs at vi bare stopper eventet.
