### ISSUE TITLE
Legge til søppelbøtteikon for sletting

### ISSUE THREAD

**Issue by Fordiboii** [fremtind/jokul#3784]
Hei! Jeg savner et ikon for sletting, f.eks. et søppelbøtteikon som dette:
https://cdn2.vectorstock.com/i/1000x1000/01/71/trash-can-icon-vector-13490171.jpg
Det hadde vært utrolig kjekt å ha der man ønsker sletting, men har lite plass.

Eksempel:
![Skjermbilde 2024-01-05 kl  10 44 47](https://github.com/fremtind/jokul/assets/26767597/472099e4-3466-4d83-b6bd-bc7cf7d12290)

Ønsker å legge en sletteknapp i listen til venstre, på listeelementene.

**Comment by Stormoen** [comment]
Trash ikoner er lagt til her: https://www.figma.com/file/DektfpgSnhwTVyrcXKwdem/Assets?type=design&node-id=2964%3A250&mode=design&t=vrZAX2XPKs2B1sds-1

Publiseres i morgen

**Comment by Fordiboii** [comment]
Herlig! Takk :)
