### ISSUE TITLE
Button v1.0.0

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#379]
## Make button component ready for publishing of v1.0.0

The following should be ready in the style (`jkl-button`) and react (`jkl-button-react`) packages before we can publish v1.0.0

### Style package should…
- [x] …have a `README.md` file containing _something_ that is **not** "TODO: …", preferrably simple usage instructions
- [x] …use only variables from `jkl-core` to define spacing, colors and font size/line height
- [x] …cover all variants found in the design sketches

### React package should…
- [x] …have a `README.md` file containing link to documentation on the portal
- [x] …properly document all types/props in use and when/how to use them
- [x] …implement all variants present in style package
- [x] …implement all expected functionality (see below)
- [x] …generate WCAG-compliant and accessible HTML

### Expected functionality
- [x] Accepts text content
- [x] Accepts an `onClick` function
- [x] Accepts custom `className`s (e.g. for spacing)
- [x] Can be forced to be small even on large screens

**Comment by Mikkelinski** [comment]
Er det for ambisiøst å ha et bilde av korrekt bruk? Føler at svaret kanskje er ja, men det er jo noe vi ønsker å få til

**Comment by Saegrov** [comment]
Typescript types/props should be properly documented - when to use it and why.

**Comment by piofinn** [comment]
> Er det for ambisiøst å ha et bilde av korrekt bruk? Føler at svaret kanskje er ja, men det er jo noe vi ønsker å få til

Probably too ambitious for v1, but this is definitely a milestone we should work towards as soon as possible.

**Comment by Mikkelinski** [comment]
Have checked off things I could validate here: https://fremtind.github.io/jokul/components/button
