### ISSUE TITLE
DetHaddeVærtFintHvis: Mulighet for å styre bold/ikke-bold variant av ikoner via CSS

### ISSUE THREAD

**Issue by ivarni** [fremtind/jokul#3795]
Problemstilling:
Vi har et design der vi bruker bold-variant av et ikon på store flater og vanlig variant på små flater. Siden vi også gjør SSR er det ikke mulig for oss å vite hvilken variant vi skal rendre og man vil få en paint med "feil" ikon før vi plutselig oppdager client-side at vi egentlig skulle rendret et annet.

Dersom vi kunne hatt en sass-mixin eller lignende sånn at vi kunne styrt dette med CSS media queries i stedet for via React APIet hadde det vært veldig praktisk

**Comment by piofinn** [comment]
> Hadde vært fint med en ikonfont!

Vi har fått ikonfont! 🎉
