### ISSUE TITLE
Toggleswitch disabled state

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#3803]
Ref designsystemforum: Toggleswitch med disabled state. 
Siden det er en ny fargevariabel her (vi bruker den også på fremtind.no for å duse ut andre menypunkter ved hover) er det greit at vi utvikler den og fikser i Figma.

Bakgrunn: De bruker toggleswitch for samtykker - og det tar litt tid for systemet og lagre endringen. Derfor trenger de en mellomstate som "låser" svaret til svaret er notert. 

Joakim har laget en branch (vi må gå over denne @fremtindjonas)
https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/branch/m0QDaXeu9sjuhedmpdo5Ra/Components?type=design&node-id=2007%3A18913&mode=design&t=LovftYYZeJpij8NQ-1

## 🎯 Sjekkliste

-   [ ] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

Flyttet over fra https://github.com/fremtind/fremtind.no/issues/163

**Comment by ivarni** [comment]
@fremtindjonas @Stormoen 

Jeg laget en branch basert på Eksisterende figma-skisse med preview her:
https://jokul.fremtind.no/preview/3803-disabled-toggle-switch/komponenter/toggleswitch/

**Comment by fremtindjonas** [comment]
@ivarni Det ser bra ut!

**Comment by fremtindjonas** [comment]
Figmaskisser er oppdatert https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/Components?type=design&node-id=2007%3A18913&mode=design&t=Jl4qp2MV148oZuFg-1
