### ISSUE TITLE
Lenke vises ikke i tooltip når man er i darkmode 

### ISSUE THREAD

**Issue by Stakset** [fremtind/jokul#3807]
Får ikke opp lenke i tooltip når man er i darkmode i våre løsninger. Gå på detaljside for å se feilen eller se bilde under. 

![image-20240201-115117(1)](https://github.com/fremtind/jokul/assets/72978199/89be481c-6ea2-43d2-a75d-2114aa781338)

**Comment by ivarni** [comment]
@Stakset Jeg er litt usikker på om vi burde støtte dette, i utgangspunktet skal ikke tooltip inneholde interaktive elementer (https://jokul.fremtind.no/komponenter/tooltip/). 

Feks vil det ikke være mulig for en bruker som navigerer med tastaturet å nå denne lenken siden tooltipen vil lukkes i det fokus forlater trigger-elementet.

**Comment by piofinn** [comment]
Som Ivar nevner vil ikke skjermlesere/tastaturnavigasjon få tilgang til lenker her, så de bør uansett ikke brukes inne i PopupTip.
