### ISSUE TITLE
Feil: feilmelding knekker under ikon

### ISSUE THREAD

**Issue by carolinewtuftin** [fremtind/jokul#3810]
<img width="456" alt="Screenshot 2024-02-02 at 11 17 23" src="https://github.com/fremtind/jokul/assets/141148051/bee50c84-88ee-4e6d-8917-28f3dfcbe718">

Dersom feilmeldingen er mer enn en linje knekker den under ikonet.

**Comment by ivarni** [comment]
Fiksa du dette så vi kan lukke issuet @joms ?

**Comment by joms** [comment]
Ah yes, takk for påminnelse @ivarni
