### ISSUE TITLE
Feil: ContextualMenu legger til en div ved siden av triggerElement

### ISSUE THREAD

**Issue by olejorgenbakken** [fremtind/jokul#3813]
Når man åpner ContextualMenu med triggerelementet vil det legges en div uten klasse og id rett under triggerlementet i DOM-en. Dette gjør at alt innhold skyves i vårt tilfelle.

## Forventet oppførsel

ContextualMenu burde vise menyen uten at det gjør noe forskjell på layout.

**Comment by ivarni** [comment]
humm... den diven brukes som target for en ref men jeg kan ikke se at den ref'en brukes til noe som helst så her skal det bare være å slette ting vil jeg tro.
