### ISSUE TITLE
Vi trenger et MinusIkon vi kan bruke sammen med Pluss'en

### ISSUE THREAD

**Issue by ivarni** [fremtind/jokul#3818]
## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** `Link til PR, ved endringer på kode`
**Designskisser:** `Link til Figma-branch, ved designendringer`
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

-   [ ] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by ivarni** [comment]
@Stormoen Kanskje du kan ta Figma-biten av dette så legger jeg det til i Jøkul?

**Comment by ivarni** [comment]
Forhåndsvisning:

**Comment by Stormoen** [comment]
Vi har visst allerede minusikon i Figma. Baserer seg på plusstegnet hva gjelder bredde og tykkelse, så da er vi vel good to go :)
