### ISSUE TITLE
Company wide browserslist config

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#382]
**Is your feature request related to a problem? Please describe.**
The customer facing application have a diverget set of browserslist, by quality assuring this, we can consume this in all customer facing application, ensuring compaitbility with jøkul and the application

**Describe the solution you'd like**
A discussion and decition on what browsers to support, adding it to the config and publishing

**Additional context**
Liv targets Android 4 and iOS 8, I dont think we need that

**Comment by lfbergee** [comment]
@piofinn

**Comment by piofinn** [comment]
Yeah, this would definitely be nice to have! Is this something we have a mandate to decide on? Either way, we would benefit from getting usage statistics from the applications in question.

There is also a lot to be said for progressive enhancement though, and I think we should encourage that over spending tons of effort trying to get pixel-perfection on older devices/browsers. Some sort of baseline for when things should look "right" is still needed, though.

**Comment by lfbergee** [comment]
I think it's valuable to lift this discussion out of each application, PO and architect out there. As this also can be used by babel, its a bit larger discussion than just pixel-perfect css.

By moving it here, instead of each and every application we can also maintain and improve this over time, forexample by comsuming our analytics data to create a our very own selfmaintanable config.
