### ISSUE TITLE
Feil: Toast blir værende i DOM og hindrer interaksjon

### ISSUE THREAD

**Issue by Tvedt1** [fremtind/jokul#3834]
Toast-region blir igjen i DOMet ved redusert bevegelse - hindrer at man kan trykke på knapper som ligger bak

## Steg for å gjenskape

1. Aktiver "Redusert bevegelse" f.eks på mac, innstillinger -> Tilgengeligjet -> Reduser bevegelse
2. Åpne Chrome og bruk jøkul Toast, f.eks i portalen.
3. Åpne inspect og se at jkl-toast-region fortsatt er i DOMet etter at Toast er ferdig animert. 
4. Dette gjør at man ikke kan trykke på knapper som ligger bak jkl-toast-region

<img width="1728" alt="Skjermbilde 2024-03-05 kl  16 12 32" src="https://github.com/fremtind/jokul/assets/22234742/fb6f1096-87b7-49d3-8e8d-bfc22eb23f18">

## Systeminformasjon

Chrome, Mac

**Comment by ivarni** [comment]
Vi har funnet buggen, elementet fjernes i en `onAnimationEnd` callback men siden det er CSS i core som setter `animation-duration: 0ms !important` for alle som har prefers-reduced-motion skjer det aldri noen animasjon og callbacken fyres ikke.

Må bare finne best løsning på dette nå. Det er ikke helt rett fram å overstyre den regelen fra core og dersom vi endrer core til å bruke 0.1ms duration i stedet for 0ms vil det eventuelt begynne å fyre av callbacks på steder der det ikke har vært gjort før.
