### ISSUE TITLE
Figma: Lage komponent Description List

### ISSUE THREAD

**Issue by fremtindjonas** [fremtind/jokul#3842]

**Comment by Stormoen** [comment]
branch https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/branch/Qh34NlPvXChYuu8qVUg2IO/Components?type=design&node-id=6542%3A2618&mode=design&t=Xeu3NoYuYKclpsZn-1

Satt opp som to varianter, en horsontal og vertikal versjon - som kan brukes på tvers av desktop/mobil/compact. Måtte bli slik for å få med layout og spacing - slik at komponenten blir mer nyttig for brukerne. Alternativet er å ha en "title cell" og en "content cell", så må man bygge opp layouten selv.

Har du innspill til dette @piofinn?
