### ISSUE TITLE
Figma: Utforske bedre måte å løse inputkomponentene

### ISSUE THREAD

**Issue by fremtindjonas** [fremtind/jokul#3845]
Det er nå flere inputkomponenter med veldig mange likheter. Hvordan kan disse forenkles?

**Branch:** `Legg til Figma-link (hvis du har laget et forslag)`

### 🎯 Sjekkliste

-   [ ] Du har sjekket at alt av auto-layout, animasjoner, o.l er satt opp riktig
-   [ ] Du har sjekket at designet matcher kodekomponenten (visuelt, animert og interaktivt)
-   [ ] Du har sjekket at endringen din ikke har overrides (hvis importerte komponenter er i bruk)
-   [ ] Du har gjort arbeidet i en Figma-branch og bedt om feedback

**Comment by piofinn** [comment]
Se #3792
