### ISSUE TITLE
Figma: Implementer typografi-variabler

### ISSUE THREAD

**Issue by leon-ho** [fremtind/jokul#3862]
Figma har endelig lansert variabler for typografi nå - Må oppdatere i Jøkul 💕

* Implementere styles med variabler
* Oppdatere komponenter til å bruke nye styles (komponenter som tidligere hadde en workaround med å bruke booleans med variable modes for å vise/skjule desktop-text, mobile-text og compact-text)
* Sette "deprecated" på gamle styles 
* Fase ut gamle tekst-styles etter rimelig tid

@fremtindjonas - Wish I were there! (Savner Jøkul+Figma 🥲)

https://www.youtube.com/watch?v=APNWWhXIg04

**Comment by fremtindjonas** [comment]
@leon-ho Hurra, endelig 🥳 Oppdateringer skal skje!
