### ISSUE TITLE
Ny knapp (ghost button)

### ISSUE THREAD

**Issue by HannahBrech** [fremtind/jokul#3871]
Vi ser at det er behov for en knapp uten ramme og understrek. 

## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** `Link til PR, ved endringer på kode`
**Designskisser:** https://www.figma.com/design/F65UrpWc7JsWYhDJgMD8F8/branch/55ykaN4LD8qtz6y4Dcskn0/Components?m=auto&node-id=8351-2946&t=QhtQeTgdDBHLQHcF-1
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

-   [x] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by fremtindjonas** [comment]
@piofinn Oppdaterte lenke til Figma nå. Som padding på topp og bunn bruker jeg nå 8-8-4. Var veldig usikker på om jeg skulle bruke 4px padding på desktop og mobil, men gikk for 8px fordi det er paddingen til tertiary. Bare si fra om du har noen tanker/Innspill :)
