### ISSUE TITLE
Ny komponent: Popover

### ISSUE THREAD

**Issue by fremtindjonas** [fremtind/jokul#3875]
Ivana har behov for en dropdown med mye forskjellig innhold. I utgangspunktet tenker vi at dette burde bli en slot component med en ramme ettersom forskjellige team kan ha veldig forskjellig behov for innhold. Hypotese er at denne komponenten vil bli mest brukt som menykomponent.

<img width="533" alt="Screenshot 2024-04-30 at 10 24 22" src="https://github.com/fremtind/jokul/assets/141401316/91e47a02-4157-4fb3-8f05-8cc8e43174e8">

**Pull request:** `Link til PR, ved endringer på kode`
**Designskisser:** [`Link til Figma-branch, ved designendringer`](https://www.figma.com/file/F65UrpWc7JsWYhDJgMD8F8/branch/bVu5hursWrDdBdFkVUqIfU/Components?type=design&node-id=7365%3A335&mode=design&t=PgnIzhWQ5rzBMswW-1)
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

-   [ ] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by piofinn** [comment]
Har et navneønske for denne: **Popover**. Det er vanlig betegnelse på denne typen beholder som skal åpnes ved klikk og legge seg oppå annet innhold :)

Her er et par referanser 🤓:
https://bootcamp.uxdesign.cc/popups-dialogs-tooltips-and-popovers-ux-patterns-2-939da7a1ddcd
https://uiplaybook.dev/play/popover
https://mui.com/material-ui/react-popover/

**Comment by fremtindjonas** [comment]
Denne oppgaven er klar til utvikling.

**Comment by piofinn** [comment]
Denne kan potensielt hjelpe på #3775
