### ISSUE TITLE
Flytt supportlabel opp fra under input-kontroll til under label

### ISSUE THREAD

**Issue by ivarni** [fremtind/jokul#3876]
Falt ut fra diskusjon på DSF 30. April

Vi prøver oss på å flytte support-tekst for input-kontroller opp til under label. Feilmeldinger blir liggende der de er nå slik at de vises i tillegg til support-teksten i stedet for å erstatte den.

@fremtindjonas @Stormoen dette må også inn i Figma

## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** `Link til PR, ved endringer på kode`
**Designskisser:** `Link til Figma-branch, ved designendringer`
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

-   [ ] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by ivarni** [comment]
Her var det ikke like bred enighet om denne endringen som vi først trodde så denne stoppet litt opp

**Comment by piofinn** [comment]
Vi legger heller opp til at dette kan løses ved behov vha enkeltkomponenter for labels, inputs, etc.
