### ISSUE TITLE
Radio button v1.0.0

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#388]
## Make radio button components ready for publishing as v.1.0.0

The following should be ready in the style (`jkl-radio-button`) and react (`jkl-radio-button-react`) packages before we can publish v1.0.0
### Style package should…

- [x] …have a README.md file containing something that is not "TODO: …", preferrably simple usage instructions
- [x] …use only variables from jkl-core to define spacing, colors and font size/line height
- [x]  …cover all variants found in the design sketches

### React package should…

- [x] …have a README.md file containing link to documentation on the portal
- [x] …properly document all types/props in use and when/how to use them
- [x] …implement all variants present in style package
- [x] …implement all expected functionality (see below)
- [x] …generate WCAG-compliant and accessible HTML

### Expected functionality

- [x] Stack vertically by default
- [x] Can be stacked horizontally as an option
- [x] Accepts custom classNames (e.g. for spacing)
- [x] Can be forced to be small even on large screens

**Comment by Mikkelinski** [comment]
From the portal could not verify mobile scaling, vertical default (which is inline = false? I thought this was changing). Different font weight on selected option also not present.

**Comment by piofinn** [comment]
> From the portal could not verify mobile scaling, vertical default (which is inline = false? I thought this was changing). Different font weight on selected option also not present.

Haven't pushed the PR yet 😅 Will be fixed later today!
