### ISSUE TITLE
Feil: Native Select oppfører seg uønsket

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#3886]
As is viser Native Select alltid første alternativ som en placeholder selv om det ikke nødvendigivs er det, noe som skaper trøbbel ved valg av verdi. Ser også ut som det kan skape feil error states.

## Steg for å gjenskape

1. Gå til '...'
2. Klikk på '...'
3. Scroll ned til '...'

**Comment by ivarni** [comment]
Løsning: 

Dersom det ikke er sendt inn en placeholder så defaulter vi den til "Velg" slik at NativeSelect nå alltid har et placeholder option-element så lenge det ikke er satt en `value`.

Da blir APIet mer likt det til Select
