### ISSUE TITLE
Gjør interaksjonen med opplastede filer bedre

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#3898]
I filopplasteren (spesifikt i komponenten `File`, som viser enkeltfiler), har man mulighet til å lenke til den opplastede filen ved å sende inn en `path`. Man har imidlertid også mulighet til å slette filen vha. et ikon inne i komponenten.

Tidligere var hele komponenten klikkbar når `path` ble sendt inn, noe som krasjet med slettefunksjonaliteten. For å løse dette har vi gjort slik at kun filnavnet er klikkbart når `path` sendes inn. Dette løser problemet, men gir veldig dårlig affordance og liten klikkflate.

Vi bør gjøre om på komponenten slik at det er enklere å både gå til den opplastede filen og å slette den. Et forslag er å flytte "slett"-knappen utenfor komponenten (kanskje i form av en ghost button?) og igjen gjøre hele komponenten klikkbar. Men vi bør utforske flere løsninger.

### Relevante issues og pull requests:
#3891 
#3895  

## 🎯 Sjekkliste

-   [ ] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by ivarni** [comment]
@fremtindjonas 👆

**Comment by piofinn** [comment]
Her kan vi samtidig synkronisere figma/kode, bl.a. plassering av tekst i "filopplaster-boksen"

**Comment by Stormoen** [comment]
> Her kan vi samtidig synkronisere figma/kode, bl.a. plassering av tekst i "filopplaster-boksen"

Ser dette er fikset i portalen, lukker derfor denne.
