### ISSUE TITLE
Muliggjøre å endre teksten i TablePagination

### ISSUE THREAD

**Issue by bestedicte** [fremtind/jokul#3907]
Vi bruker Jøkul på et prosjekt hos oss i Addwize og er kjempefornøyde. Den ene appen vår er på engelsk, og den hardkodede `Rader per side:`-teksten skaper litt krøll. 

Er det mulig å legge til en optional prop hvor man kan endre label-teksten? Dette vil være bakoverkompatibelt så bør ikke være noe problem :) 

## 🔗 Praktiske lenker (om tilgjengelig)

https://github.com/fremtind/jokul/blob/37f96528eef184abe8c7bf719dc7a43e7713f097/packages/table-react/src/TablePagination.tsx#L149

**Comment by ivarni** [comment]
Det tenker jeg ikke burde være noe problem, jeg kan sikkert få satt sammen en PR i løpet av uka så får vi nok til en release før vi tar sommerferie.

Gøy at eksterne også bruker designsystemet vårt, vi ble litt nysgjerrige her på hvordan det ser ut så det hadde vært morro om dere vil dele noen skjermbilder eller lignende :)
