### ISSUE TITLE
Feil: Key problemer med tooltip i en map

### ISSUE THREAD

**Issue by PernilleWelle-Watne** [fremtind/jokul#3918]
## Steg for å gjenskape

1. Ha tooltips i en map
2. hovre over elementet
3. se i consollen at man får: 
Warning: Encountered two children with the same key, ``. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

## Forventet oppførsel

Ikke få key feil i AnimatedPresence

**Comment by ivarni** [comment]
Når `triggerOn` er satt til `"hover"` rendrer [TooltipContent en extra child til AnimatePresence](https://github.com/fremtind/jokul/blob/9a54cfe1fc7b139711ad2e6b9f73a7d80d9e835c/packages/tooltip-react/src/TooltipContent.tsx#L71-L75) og React blir sint fordi framer-motion gir begge `key=""` siden vi ikke har sendt noe (antar det er noe i koden der som defaulter dette til tom streng).

Gjenskapt i dev-mode i jokul-repoet, også med bare én tooltip. Løsningen ser ut til å være at vi gir begge elementene en eksplisitt key.
