### ISSUE TITLE
Lenkeliste-komponent fra Fremtind.no inn i Jøkul

### ISSUE THREAD

**Issue by olejorgenbakken** [fremtind/jokul#3920]
Vi har en del lenker til andre løsninger i dag, og bruker cards fordi de står veldig ut på siden vår. Problemet vi fort får er at alt på siden vår er cards, så det hadde vært nice med et annet virkemiddel som feks denne lenkeliste-komponenten:
<img width="2153" alt="Screenshot 2024-07-30 at 14 51 11" src="https://github.com/user-attachments/assets/f086a471-7375-43d3-8512-4f8c1573b614">

**Comment by ivarni** [comment]
Tanker om hvordan APIet burde se ut?

I mitt hode er kanskje den første en uordnet liste og den andre en ordnet? Da ligner det litt på `<ul>` og `<ol>` som de fleste sikkert er vant til å forholde seg til.

Kunne da sett ut som feks

```
<UnorderedLinkList>
    <LinkItem><a href="" /></LinkItem>
    <LinkItem><a href="" /></LinkItem>
</UnorderedLinkList>
```
og

```
<OrderedLinkList>
    <LinkItem><a href="" /></LinkItem>
    <LinkItem><a href="" /></LinkItem>
</OrderedLinkList>
```

feks noe som [dette](https://codesandbox.io/p/sandbox/crazy-legs-d8hpfj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clz9cr2hb00063b6jwfm3cmrn%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clz9cr2hb00023b6jw634t2p0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clz9cr2hb00033b6ja13ltgbg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clz9cr2hb00053b6jj0tb9ejc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B70.17361474413293%252C29.826385255867066%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clz9cr2hb00023b6jw634t2p0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz9cr2ha00013b6j8ljuc43p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clz9cr2hb00023b6jw634t2p0%2522%252C%2522activeTabId%2522%253A%2522clz9cr2ha00013b6j8ljuc43p%2522%257D%252C%2522clz9cr2hb00053b6jj0tb9ejc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz9cr2hb00043b6jp2dpjybx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clz9cr2hb00053b6jj0tb9ejc%2522%252C%2522activeTabId%2522%253A%2522clz9cr2hb00043b6jp2dpjybx%2522%257D%252C%2522clz9cr2hb00033b6ja13ltgbg%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clz9cr2hb00033b6ja13ltgbg%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Så kan man eventuelt ha en prop for om lenka er ekstern eller ikke (har pil vs ikke har pil). Kan jo og bare si at children må være `Link` eller `NavLink` komponentene vi allerede har.

**Comment by olejorgenbakken** [comment]
Jeg syns dette høres veldig fornuftig ut! 

I tillegg tror jeg dokumentasjonen da gjerne kunne sagt noe om at hvis man bruker <ol>-versjonen til innholdsfortegnelse burde den wrappes i <nav>. Jeg fant ut av dette først nå selv, mens jeg leste [dokumentasjonen til <nav>](https://html.spec.whatwg.org/multipage/sections.html#the-nav-element) for en oppgave jeg satt med haha.

**Comment by ivarni** [comment]
Ah, det kunne vi nok gjort på fremtind.no også men det er jo naturlig at vi bikkjemater komponenten der hvis den finnes i jøkul så vi kan nok ordne det da.

Er dette kanskje en god oppgave for onboarding @piofinn ?
