### ISSUE TITLE
Feil: Baseinput counter oppdatere seg ikke og ligger midt i høyden

### ISSUE THREAD

**Issue by PernilleWelle-Watne** [fremtind/jokul#3921]
## Steg for å gjenskape

Counteren oppdaterer seg ikke i Baseinput og den ligger litt rart.

```javascript
 <InputGroup
          className="input jkl-text-area"
          label={sporsmalstekst}
          labelProps={{ variant }}
          errorLabel={error?.message}
          render={(inputProps) => (
            <>
              <SupportLabel
                id={`${id}-help`}
                labelType="help"
                label={hjelpetekst}
                className="mb-12 mt-2 "
              />
              <BaseTextArea
                {...inputProps}
                {...register(fieldName)}
                counter={
                  true
                    ? {
                        maxLength: 200,
                        hideProgress: false,
                      }
                    : undefined
                }
              />
            </>
          )}
        ></InputGroup>
        
       
```

<img width="1241" alt="Skjermbilde 2024-07-30 kl  12 04 16" src="https://github.com/user-attachments/assets/af5cb712-028f-4955-a0c7-f992cb71058f">

## Forventet oppførsel

At counteren oppdaterer seg

**Comment by ivarni** [comment]
Quick-fix er å legge til klassen `jkl-text-area--with-counter` på `<InputGroup>` men her burde vi se på en bedre løsning for dette i jøkul dersom vi skal støtte å at man bruker `<BaseTextArea>` til dette selv. Rent teknisk kunne vi nok sett på å bruke `:has( )` selectoren.

**Comment by PernilleWelle-Watne** [comment]
Når jeg putter på en ny className på BaseTextArea så miser den alle den hadde fra før. Også oppdaterer ikke counteren seg

<img width="1489" alt="Skjermbilde 2024-08-01 kl  09 42 05" src="https://github.com/user-attachments/assets/5e867f05-8bef-404c-b0e2-8f6eb67aa98b">

**Comment by ivarni** [comment]
Den må settes oppe på `<InputGroup>`, det er derfor akkurat det med counteren ikke fungerer helt ut av boksen når man bruker base-komponenten.

**Comment by ivarni** [comment]
Det ser ut som telleren bare oppdaterer seg dersom komponenten brukes som en controlled component, uavhengig av om man bruker `<TextArea>` eller `<BaseTextArea>`.

**Comment by PernilleWelle-Watne** [comment]
Skal jeg putte den i en Controller? Vi bruker React router dom

**Comment by ivarni** [comment]
Det vil nok fungere med en Controller rundt hele InputGroup, legge på klassenavnet der og så sende inn value til BaseTextInput, men jeg tror at med fiksen i den linkede PRen trenger dere ikke noen av delene.
