### ISSUE TITLE
Feil: CookieConsent på jokul.fremtind.no lar meg ikke lagre justerte innstillinger

### ISSUE THREAD

**Issue by wkillerud** [fremtind/jokul#3927]
Halla folkens, håper alt er vel ❤️ Det popper opp aktivitet nå og da i GitHub feeden min, så jeg var innom jokul.fremtind.no for å glane litt 👀 Av gammel vane gikk jeg for å justere Cookie-samtykker og oppdaget at det ikke gikk an å lagre innstillinger.

## Steg for å gjenskape

1. Åpne https://jokul.fremtind.no/ i en ny/inkognito browser
2. Klikk på Innstillinger i cookiebanneret
3. Klikk Godta

## Forventet oppførsel

Forventet at modalen forsvant. Mangler kanskje en `onClick` her? 🕵️ 

https://github.com/fremtind/jokul/blob/be217592ea30de0b16860a9941fad4750bccdd71/packages/cookie-consent-react/src/CookieConsentModal.tsx#L201

## Systeminformasjon

Testet i Firefox 128 og Safari 17.5

**Comment by ivarni** [comment]
👋🏽 

Sees vel kanskje på noe burger i løpet av høsten?

**Comment by ivarni** [comment]
Så vidt jeg kan se så ble `type="button"` ny default for buttons ifm med innføring av `GhostButton` varianten og da submitter den ikke lenger `<form>` elementet på click.
