### ISSUE TITLE
Feil: `DatePicker` åpnes/lukkes ikke som forventet når `disableAfterDate` er satt

### ISSUE THREAD

**Issue by glennbarosen** [fremtind/jokul#3941]
Kalenderen i `Datepicker` lukkes ikke når man skriver inn gyldig dato dersom datoen er lik datoen satt i `disableAfterDate`

![image](https://github.com/user-attachments/assets/a4a87624-be55-4eda-87b4-b02bea5e31b0)

## Steg for å gjenskape

1. Sett en dato i `disableAfterDate`
2. **Skriv** inn en dato i inputfeltet når kalenderen er åpen. Ikke velg dato i kalenderen
3. Kalenderen lukkes ikke

## Forventet oppførsel

Kalenderen lukkes når gyldig dato skrives inn på samme måte som når `disableAfterDate` ikke er satt eller når man skriver en dato som ikke er lik `disableAfterDate`

## Systeminformasjon

- MacOS

**Comment by piofinn** [comment]
Jeg klarer ikke å reprodusere dette i hverken Safari eller Chrome (eller Arc). Hos meg lukker kalenderen seg i alle tilfeller. Om noe lukker den seg _for tidlig_: etter at det _første_ tallet i årstallet er skrevet inn.

Egentlig burde kanskje ikke kalenderen åpnes i det hele tatt med mindre man trykker på kalenderikonet? Det tilfører jo egentlig ikke så mye å se den mens man skriver inn en dato uansett 🤔

**Comment by kristianulv23** [comment]
Utgår, da komponenten nå kun kan åpnes ved trykk på kalenderikonet.
