### ISSUE TITLE
Ny Figma-komponent RadioPanel

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#3946]

**Comment by Stormoen** [comment]
Mangler variabler - gjøres ved merge

**Comment by jonashior** [comment]
Klar til utvikling. Komponenten er helt lik Checkbox Panel bortsett fra at det er brukt Radio i stedet for Checkbox og at man kun kan velge ett panel om gangen.

Skisse: https://www.figma.com/design/jd7QGZJIQ5ZU6AhAq31yuv/branch/8mbgUtjgQLWEctdRFN4ii3/J%C3%B8kul-v2.0-(beta)?m=auto&node-id=15866-2434&t=R7HSTQpGwQikaDrH-1
