### ISSUE TITLE
Accordion: Oppdatere med liten animert pil

### ISSUE THREAD

**Issue by zenabii** [fremtind/jokul#3956]
[Sync mellom design og utvikling](https://www.figma.com/board/Exc0F9YdbsSXYztsul9RRM/synk-kode-og-figma?node-id=0-1&t=9g6HmcX8lslcGqJK-0)

- [ ] I Figma må Accordion oppdateres med liten animert pil

**Comment by jonashior** [comment]
Denne går ut da Accordion blir erstattet med Expandable.
