### ISSUE TITLE
Alert Message: Navnendring og oppdatering

### ISSUE THREAD

**Issue by zenabii** [fremtind/jokul#3957]
[Sync mellom design og utvikling](https://www.figma.com/board/Exc0F9YdbsSXYztsul9RRM/synk-kode-og-figma?node-id=0-1&t=9g6HmcX8lslcGqJK-0)

- [x] #3998 
- [x] #3999

**Comment by Stormoen** [comment]
Kan man velge å ha tittel i kode? Usikker på om det er slik i Figma, da den er bygget sammen med message box.
