### ISSUE TITLE
Button: Pil og hovereffekt

### ISSUE THREAD

**Issue by zenabii** [fremtind/jokul#3959]
[Sync mellom design og utvikling](https://www.figma.com/board/Exc0F9YdbsSXYztsul9RRM/synk-kode-og-figma?node-id=0-1&t=9g6HmcX8lslcGqJK-0)

- [x] Liten pil på compact
- [ ] Hovereffekt på tvers av knapper

**Comment by jonashior** [comment]
Lukker denne da pil (ikon) er fikset og hovereffekt løses i denne oppgaven: https://github.com/orgs/fremtind/projects/57/views/3?pane=issue&itemId=86721250&issue=fremtind%7Cjokul%7C4276
