### ISSUE TITLE
Accordion icon is sometimes placed over title text

### ISSUE THREAD

**Issue by stianlik** [fremtind/jokul#397]
**Describe the bug**

Accordion icon is sometimes placed over title text because the title use inline-style padding. See screenshot.

**To Reproduce**

Class `.jkl-accordion-item__title-text` use `display: block` to avoid issues with inline-padding.

**Expected behavior**

Icon should never cover text.

**Screenshots**

![image](https://user-images.githubusercontent.com/410251/65961272-89b26100-e456-11e9-87b2-5d2bfd6b6a09.png)

**Desktop (please complete the following information):**

-   OS: RedHat
-   Browser Chrome
-   Version 76.0.3809.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

-   Device: iPhone
-   OS: iOS-something
-   Browser Safari

**Additional context**

Confirmed that the following style will resolve the problem in Chrome:

```CSS
.jkl-accordion-item__title-text {
    display: block;
}
```
Ev. skift ut `div`-element med `span`. Kommer med en PR.

**Comment by piofinn** [comment]
Great catch! The CSS approach is preferable here (see comment in the PR).
