### ISSUE TITLE
Checkbox: Bytte icon

### ISSUE THREAD

**Issue by zenabii** [fremtind/jokul#3981]
[Sync mellom design og utvikling](https://www.figma.com/board/Exc0F9YdbsSXYztsul9RRM/synk-kode-og-figma?node-id=0-1&t=9g6HmcX8lslcGqJK-0)

- [ ] Check icon buttes til material

**Comment by piofinn** [comment]
Finnes allerede et issue for denne: #3939 Legger inn lenken til Figma-boardet der i stedet 😊
