### ISSUE TITLE
Trekk ut System Message som egen komponent i Figma

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#3999]
Systemmeldinger (nå kalt Alert Message i portalen og kode) ligger i dag som en variant av Message Box i Figma. Vi ønsker å trekke den ut til en egen komponent som heter System Message

[Sync mellom design og utvikling](https://www.figma.com/board/Exc0F9YdbsSXYztsul9RRM/synk-kode-og-figma?node-id=0-1&t=9g6HmcX8lslcGqJK-0)

**Comment by Stormoen** [comment]
System Message i "componenter" er publisert
System message + Message (uten wide page alert) ligger klar i en branch i Jøkul v2.0.
