### ISSUE TITLE
Bug: Fremtind.no

### ISSUE THREAD

**Issue by Stormoen** [fremtind/jokul#4058]
Mobil
Padding bunn toppoppgaver + pil-ikoner bildekarusell

![Image](https://github.com/user-attachments/assets/ad1dea09-e7c6-485d-a3f4-300880edf655)
![Image](https://github.com/user-attachments/assets/04d8fc3f-23e8-4730-8323-3a96262c8705)

**Comment by piofinn** [comment]
@Stormoen kan du lage to separate issues for disse? Ta gjerne med en skriftlig beskrivelse av både feil og forslag til løsning, så blir de enklere å ta tak i senere 😊

**Comment by Stormoen** [comment]
Takk. De ble opprettet i et møte, så det gikk litt raskt.
