### ISSUE TITLE
Components: Field status message

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#41]
- [x] Initial design
- [x] Initial package

Component to go under  form-elements to inform about error, missing information and such.

**Comment by Steinop** [comment]
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-components?node-id=111%3A9

**Comment by lfbergee** [comment]
I'm not sure this should be it's own component anymore. The field message basicly do not have any particular design elements, it's just a paragraph, so I'm not sure its worth the extra complexity to have this a it's own components, instead it can be a part of whatever components that needs it.

Oh, and the error color do not look WCAG compliant to my eyes.

**Comment by lfbergee** [comment]
I think we should add the style to core, that way any component that needs it can pick the style from there.

Somethink like:
```
.jkl-form__help-text{}
.jkl-form__error-text{}
```
