### ISSUE TITLE
Feil: Select lukker seg ikke

### ISSUE THREAD

**Issue by carolinewtuftin** [fremtind/jokul#4134]
Select lukker seg ikke dersom man tab-er uten å velge et alternativ. 

[Screenshot 2024-10-01 at 13 17 56](https://github.com/user-attachments/assets/ad335110-88f4-4653-8620-7ed6e7f5c44f)

**Comment by ivarni** [comment]
@carolinewtuftin Hvilken app var dette i? Jeg klarte ikke helt å provosere det fram lokalt så om det er en testserver jeg kan se på eller en app i monorepo jeg kan starte opp eller noe lignende er det veldig nyttig.
