### ISSUE TITLE
Flytt Pagination ut som en egen komponent

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#4141]
Tabell-pakken vår har en komponent for paginering av tabeller. Denne kan fint brukes som en generell komponent for å paginere andre typer innhold, så den burde vært løftet ut som en egen pakke/komponent `Pagination`.

Vi får vurdere om vi skal lage en ny pakke for den à la `@fremtind/jkl-pagination` eller om vi bare skal skille den ut og gi den nytt navn inne i `@fremtind/jokul`.

**Comment by ivarni** [comment]
@piofinn Tar denne mens vi diskuterer dev-servere :)

Jeg tenker det holder å legge den i `@fremtind/jokul`, vi må ha et mål om at vi kan få ut en 1.0 av den om ikke altfor lenge men de som trenger denne komponenten kan jo uansett hende den derfra og hente det gamle fra `@fremtind/jkl-*` i mellomtiden.
