### ISSUE TITLE
Chips React-komponent

### ISSUE THREAD

**Issue by Stormoen** [fremtind/jokul#4155]

**Comment by jonashior** [comment]
Klar til utvikling. Som del av oppgaven må også muligheten for dismissable i Tag fjernes, og combobox må oppdateres til å bruke chipkomponenten.

Skisse: https://www.figma.com/design/jd7QGZJIQ5ZU6AhAq31yuv/branch/SQFKEeWYxiQffdm5zgTqtI/J%C3%B8kul-v2.0-(beta)?m=auto&node-id=17770-1084&t=C0P3HZlSYtlpN4HG-1

**Comment by jonashior** [comment]
Lenke til skisse i Figma: https://www.figma.com/design/jd7QGZJIQ5ZU6AhAq31yuv/branch/SQFKEeWYxiQffdm5zgTqtI/J%C3%B8kul-v2.0-(beta)?m=auto&node-id=17770-1084&t=C0P3HZlSYtlpN4HG-1
