### ISSUE TITLE
Feil: Pilen i ExpandButton er for stor så deler av den er kuttet av

### ISSUE THREAD

**Issue by PernilleWelle-Watne** [fremtind/jokul#4177]
Pilen i ExpandButton ser ut som den er for stor i boksen når den peker nedover.

## Steg for å gjenskape

1. Gå til [ExpandButton](https://jokul.fremtind.no/komponenter/expandbutton/)

## Forventet oppførsel

Slik som den er når den peker oppover. 

## Systeminformasjon

Google chrome

**Comment by PernilleWelle-Watne** [comment]
Legger også til at combobox sin pil i compact mode også blir kuttet av. Men jeg kan lage et eget issue på det

**Comment by ivarni** [comment]
På preview i den lenkede PRen ser det ut som combobox-issuet også tas av den fiksen.
