### ISSUE TITLE
Feil: jkl-menu-react finnes ikke?

### ISSUE THREAD

**Issue by marieihlefrogner** [fremtind/jokul#4183]
Ser at `ContextualMenu` (fra `@fremtind/jkl-contextual-menu-react`) er deprecated, og at `Menu` skal brukes. 

[Dokumentasjonen til Menu](https://github.com/fremtind/jokul/tree/main/packages/menu-react) sier at man skal bruke `@fremtind/jkl-contextual-menu-react` for dette komponentet også, men i den pakken finnes det ikke noe `Menu` komponent (versjon 2.3.2). 

Gjettet på at pakkenavnet skal være `@fremtind/jkl-menu-react`, men får 404 fra Nexus når jeg prøver å laste ned med npm.

Hvordan er det ment at man skal bruke det nye `Menu` komponentet? Virker i hvert fall som at dokumentasjonen er feil.

**Comment by ivarni** [comment]
@marieihlefrogner Noen har glemt å oppdatere navnet på komponenten da den ble flyttet ser jeg, skal se om vi får fikset det i løpet av dagen

**Comment by ivarni** [comment]
Bortsett fra at README-fila fremdels snakker om 

```

**Comment by marieihlefrogner** [comment]
Flott! Ser at pakken ligger på Nexus nå. Men jeg får en feil med at ikke forventede versjoner finnes av `@fremtind/jkl-toggle-switch` (krever 13.2.5) og `@fremtind/jkl-icons-react` (krever 9.1.13). 

```
> pnpm i @fremtind/jkl-menu-react
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @fremtind/jkl-icons-react@^9.1.13

This error happened while installing the dependencies of @fremtind/jkl-menu-react@3.4.38

The latest release of @fremtind/jkl-icons-react is "9.1.12".
 ```

Den bytter på å feile på `jkl-toggle-switch` og `jkl-toggle-switch`.

**Comment by ivarni** [comment]
😢 

Rekker ikke se mer på dette i dag men tar en titt i morgen om ikke @piofinn har tid etterpå

**Comment by ivarni** [comment]
Det kan rett og slett hende at du var veldig uheldig med timingen også, og endte opp halvveis i en NPM-publish byge. Alle disse modulene publiseres omtrent samtidig men det er litt random når nexus får de inn i cachen sin. Det kan noen ganger ta en dag :/

**Comment by marieihlefrogner** [comment]
@ivarni Jepp, nå funka det. Takk!
