### ISSUE TITLE
On alert - farger på error-bakgrunn: Subdued tekst + ikon

### ISSUE THREAD

**Issue by Stormoen** [fremtind/jokul#4194]
I arbeidet med select, combox og textinput i Figma så vi at vi mangler noen "on alert" farger på **errorstate.**

Theme
Icon: on alert (granitt, granitt)
Text: on alert subdued (fjellgrå, fjellgrå) 

On alert subdued er ny, og en quickfix. Tenker at vi får bedre roller og kontraster når vi får på plass fargesystem. Ser ut som dere allerede har håndtert dette i kode - men vet ikke hvilken farge dette er:
    --jkl-select-error-text-color: #636060 ?

![Image](https://github.com/user-attachments/assets/e832cbc6-d753-41c0-9429-471cc2e99422)

![Image](https://github.com/user-attachments/assets/09588302-dfe4-4f38-9a25-98b5134c2ae7)
![Image](https://github.com/user-attachments/assets/85120062-7578-4850-8388-f2498bcd5421)

**Comment by ivarni** [comment]
@Stormoen Når jeg ser i tokens-fila vår finner jeg

```
@color-brand-stein: #636060;
```

**Comment by Stormoen** [comment]
Takk. "Stein" failer på kontrast mot error bakgrunn - så da bør vi endre i kode også. 
Fjellgrå #444141 treffer hvertfall AA på error light og dark. 

I tillegg bør ikon som ligger på error bakgrunn endres til "on alert" så den ikke blir hvit i darkmode.

**Comment by Stormoen** [comment]
Synes det ser ut som ikonet har blitt subdued? 

Det er kun placeholder tekst som endres til en "text/on alert/subdued i **errorstate.**
Ikonene til høyre endres til icon on alert i **errorstate** - så den blir granitt, i stedet for hvit.

Synes det var vanskelig å inspektere disse tingene inni - tar gjerne en opplæringsøkt på det, hehe. Men ikonet ser litt for lyst ut i textinput, select og comboboks. Og i comboboks error ser det ut som placeholder "søk" fortsatt er for lys.

![Image](https://github.com/user-attachments/assets/86172d66-ae8c-483b-82fd-a614c90548e5)

**Comment by ivarni** [comment]
@Stormoen Jeg visste ikke at vi hadde en icon/on alert siden denne ikke eksisterer i kode så jeg antok den skulle følge teksten. Hvilken farge er icon/on alert? Og er det flere semantiske ikon-farger som vi burde legge til samtidig?

Jeg sliter også med å finne disse verdiene i Figma, syns det var enklere da vi hadde frames for alle kombinasjonene tilgjengelig for jeg klarer ikke å bytte mellom de på noen effektiv måte. Vet ikke om det er manglende tilgang eller manglende kunnskap :)

**Comment by ivarni** [comment]
Avklart på standup i dag at ikonet i kode skal ha text/on alert og at icon-verdiene er noe som bare finnes i Figma.
