### ISSUE TITLE
Components: TextArea

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#42]
- [x] Initial design
- [x] Initial package

**Comment by Steinop** [comment]
Text area is based on the Input field style with the same reactions for focus, hover and error messages. 

Consider two alternatives:
Alt1: Underline is pushed down by new text rows
Alt2: Underline is pushed down a suitable distance to indicate possibly more input than a regular input field. (ref. attached animation)

![Fremtind_TextArea_1](https://user-images.githubusercontent.com/51952891/60163249-7d858a80-97fb-11e9-9d77-2169ba88f98e.gif)
