### ISSUE TITLE
Keyboard focus states inside datepicker

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#420]
We need a keyboard focus state for the arrow buttons used to select a month in the datepicker:

![Skjermbilde 2019-10-07 kl  16 42 49](https://user-images.githubusercontent.com/25739615/66321962-aa305e80-e921-11e9-88d4-1326324b3c7e.png)

We also need a specific keyboard focus state for the selected day.

**Comment by piofinn** [comment]
I'll just tag the designers here to get your attention 😅
@Steinop @Mikkelinski @idalower

**Comment by Mikkelinski** [comment]
@piofinn https://www.figma.com/file/Wh8Gfnesn25shH31sKyIaT/J%C3%B8kul-bibliotek?node-id=1143%3A65

Could work as a first draft for focus & hover in the datepicker
