### ISSUE TITLE
Feil: Klikk på kalender ikon scroller side til topp

### ISSUE THREAD

**Issue by SercanSercan** [fremtind/jokul#4207]
Når jeg trykker på kalender ikon av Datepicker, skroller siden til topp. Feil skjer på siste versjon v15.2.6. Jeg observerer samme feil på jøkul portal side. Jeg har testet Datepicker på kunde-frontend og admin applikasjonene våre. Jeg har laget en video som viser feil. 

https://github.com/user-attachments/assets/48e9ae1f-944d-4fdb-b4aa-9625d3395b71

**Comment by ivarni** [comment]
Det er interessant at dette bare skjer første gang man åpner datepickeren 🤔
