### ISSUE TITLE
Input fields /w suffix + inline input fields

### ISSUE THREAD

**Issue by Mikkelinski** [fremtind/jokul#426]
We might need the ability to add a suffix to our input fields (e.g. _______ years / ______ kroner) or place input fields inline where the surrounding context replaces the label.

How should it look / act? Using the existing input field as a baseline

**Comment by vegardsoerlie** [comment]
A bit eager on the close button there 😅 

Before closing we need a better way to render a proper suffix input field. As it is now we can use `InlineTextField` but it's a bit hacky and already has its own `Label` that's only visible for screen readers.

**Comment by piofinn** [comment]
We're closing this for the time being, since the inline version covers current needs. We'll open a new issue if the need for suffixes surfaces again
