### ISSUE TITLE
Components: Inline Loader

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#43]
- [x] Initial design
- [ ] Initial package

Component that can go inside other components to indicate that its loading data.

**Comment by Steinop** [comment]
First edition loader - any comments
![Loader4](https://user-images.githubusercontent.com/51952891/60184678-c6a00380-9828-11e9-8e11-3e422e3b1715.gif)

**Comment by Steinop** [comment]
Reference to Figma:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-components?node-id=263%3A568

Timing information on request :)

**Comment by Steinop** [comment]
Timing from Inspector Spacetime:
Total Dur: 1160ms

≡ Shape Layer 3 ≡
- Scale -
Delay: -200ms
Dur: 560ms
Val: 0 ›› 80
(0.33, 0, 0.57, 1)

- Scale -
Delay: 360ms
Dur: 800ms
Val: 80 ›› 0
(0.65, 0, 0.67, 1)

- Rotation -
Delay: -200ms
Dur: 560ms
Val: 0››45
Linear

- Rotation -
Delay: 360ms
Dur: 800ms
Val: 45››90
Linear

≡ Shape Layer 2 ≡
- Scale -
Delay: -400ms
Dur: 560ms
Val: 0 ›› 90
(0.33, 0, 0.58, 1)

- Scale -
Delay: 160ms
Dur: 800ms
Val: 90 ›› 0
(0.74, 0, 0.67, 1)

- Rotation -
Delay: -400ms
Dur: 560ms
Val: 0››45
Linear

- Rotation -
Delay: 160ms
Dur: 800ms
Val: 45››90
Linear

≡ Shape Layer 1 ≡
- Scale -
Delay: -560ms
Dur: 560ms
Val: 0 ›› 80
(0.33, 0, 0.51, 1)

- Scale -
Delay: 0ms
Dur: 800ms
Val: 80 ›› 0
(0.73, 0, 0.67, 1)

- Rotation -
Delay: -560ms
Dur: 560ms
Val: 0››45
Linear

- Rotation -
Delay: 0ms
Dur: 800ms
Val: 45››90
Linear
