### ISSUE TITLE
Tekstbehov Jøkul: Logo

### ISSUE THREAD

**Issue by Gorild** [fremtind/jokul#430]
- Minstemål for logo
- Regler for farge på logo- Eks snehvit eller helhvit mot mattsvart og svart
- Symbol i header og logo i footer - eksempel webside og skjema
- Beskyttelsesområde
- Annen plassering av logo? I modul/kort/midt på siden
- Bruk av logo i andre flater? Feks SP1, DNB?
- Animert logo - når
- Ukorrekt bruk av logo
______
Workshop 22.10:

- Delt opp hva som er generell info og hva som tilhører komponenteten. Lagd to pull-requests.
Fem generelle punkter foreslått. 
- Når bruke logo hvit og når svart?
- Kommentar; Vi kan bruke logo og logsynbol på samme flate, men de må ikke stå sammen. Kan stå på ulike steder på flaten - hvert sitt hjørne.
- Lenke til Papirfly eller ikke nå?
-  om logo som visuelt element (i innledningen)
- På komponentdelen: WCAG, Alt-tekst skal beskrive hvor du ender opp.
- Nevne regler på papir/andre flater, men primært beskrive bruk på digitale flater i Jøkul?

Arbeides på i #465

**Comment by Gorild** [comment]
- Vi må forske mer på fargebruken og minstemål - vi er usikre på om dette hører til i beskrivelsen av selve logokomponenten, og hvileken teknikk man bruker for å fremstille logoen - trykk, gravering osv.

**Comment by Steinop** [comment]
Er det mulig å legge inn en lenke til tekstområdet på Git? Går meg alltid vill i filstrukturen her …

**Comment by Gorild** [comment]
Da er #465 oppdatert og jeg har sjekket at det vi snakket om her er med, unntatt det som skal stå på komponentdelen. Er det noe du jobber med nå @Steinop?

**Comment by Gorild** [comment]
Ønsker å lukke denne, men må vite om vi har fått med det som står her til under komponenten.
