### ISSUE TITLE
Opprette spacingskala

### ISSUE THREAD

**Issue by jonashior** [fremtind/jokul#4308]
Det er behov for en skala til bruk for avstander mellom elementer. Det er også en idé om at denne spacingskalaen kan være grunnlaget for konseptet comfortable/compact, slik at density styrer avstanden mellom elementer i et grensesnitt i stedet for størrelsen på komponenter.

- [x] Opprette ny unit-skala
- [ ] #4335

- Closes #4308
- Closes #4314 
- Closes #4315

**Comment by piofinn** [comment]
Det er sikkert en god idé å se på dynamisk spacing i samme slengen, altså spacing som endrer seg ut fra skjermstørrelse. Vi kommer sikkert til å trenge både faste og dynamiske verdier, men er fint å se på det i sammenheng 😊
