### ISSUE TITLE
Legg til `texInputProps` i `DatePicker`

### ISSUE THREAD

**Issue by glennbarosen** [fremtind/jokul#4332]
Mangler props på `DatePicker` som hadde vært fine å ha, f.eks `autocomplete`. Gjør at man må bruke noen mindre pene løsninger. 

<img width="564" alt="image" src="https://github.com/user-attachments/assets/f2639c45-f18d-4cbb-8bcb-325161c54ac0">

 ---

## 🔗 Praktiske lenker (om tilgjengelig)

**Pull request:** `Link til PR, ved endringer på kode`
**Designskisser:** `Link til Figma-branch, ved designendringer`
**Forhåndsvisning:** `Preview-link fra @fremtind-bot (om tilgjengelig)`
**Discussion:** `Link til discussion (om tilgjengelig)`

## 🎯 Sjekkliste

-   [ ] Du har laget en branch i Figma og bedt om feedback
-   [ ] Du har sjekket at alt av kode og tester kjører som det skal
-   [ ] Dere har sammen sjekket at resultatet av design og kode matcher

Hvis du står fast og trenger tips kan du ta en kikk i [huskelista](https://jokul.fremtind.no/guider/hvordan-endre-jokul#klar-for-%C3%A5-lansere-huskelista-hjelper-deg-) vår, eller tagge noen fra [Jøkul-teamet](https://jokul.fremtind.no/kom-i-gang/hjelp/#j%C3%B8kul-teamet) i dette issuet.

**Comment by ivarni** [comment]
Jeg elsker ikke tanken på å legge til enda flere props men inntill vi eventuelt kan bryte den opp i mindre deler som kan komponeres av de som skal bruke den så er det nok bedre enn at man må gå rett på DOM-elementet.
