### ISSUE TITLE
Kan ikke interagere med innhold i Card-komponenten(e)

### ISSUE THREAD

**Issue by olejorgenbakken** [fremtind/jokul#4363]
Vi prøver å bruke Card-komponenten, og ser at bakgrunnen på dem settes med `::after`, uten `z-index: 0` eller tilsvarende. Dette betyr at når vi har interagerbart innhold i dem er de ikke reachable.

Er det mulig å sette bakgrunn med enten `background-color`, eller å putte `z-index` på `::after`? Jeg er tilsynelatende på nyeste versjon av jkl-card (13.0.11).

Bildet illustrerer bare at hover sonen er på hele kortet, når det egentlig skulle vært på innholdet.

![image](https://github.com/user-attachments/assets/994f8111-6bc7-4434-a5ff-e6eedcfc05be)

**Comment by ivarni** [comment]
@olejorgenbakken / @piofinn 
Er det dette det er tenkt at man bruker `TaskCard` til?
https://jokul.fremtind.no/komponenter/card/

Jeg kjenner ikke disse komponentene så godt men den varianten legger i hvert fall ikke på noe overlay som dekker alt inni.
