### ISSUE TITLE
Feil: Expandable(?) eksponerer ikke testid-er.

### ISSUE THREAD

**Issue by olejorgenbakken** [fremtind/jokul#4364]
Sånn det er nå får alle `data-testid="jkl-expand-section"`, som jo egentlig skulle vært unike. Kunne dere eksponert propen til teamene? 🥺 

![image](https://github.com/user-attachments/assets/c0a9cdef-aca9-4f24-81a9-8e5c981541f3)

**Comment by ivarni** [comment]
Det skal være mulig å sende inn alle data-* attributter til den. Man trenger ikke å spesifikt eksponere det som props i React nettopp fordi det er ment å kunne inneholde tilfeldige verdier. Når det har vært gjort tidligere er det fordi man har operert med whitelists for props mens vi nå har gått over til å heller tillate alle props som vanligvis er tilgjengelig for elementet vi rendrer.
