### ISSUE TITLE
Tekstbehov Jøkul: Tilgjengelighet

### ISSUE THREAD

**Issue by Gorild** [fremtind/jokul#439]
WCAG
    - Sikrer at alle har tilgang til informasjon på nett enten de har nedsatt syn, hørsel, alder, pølsefingre osv.

**Comment by piofinn** [comment]
Igjen er [GitHub sin dokumentasjon om dette](https://primer.style/design/global/accessibility) veldig bra fra et praktisk perspektiv. Særlig på tilgjengelighet er det viktig at vi viser konkrete metoder for å etterkomme standardene vi jobber med.

**Comment by Gorild** [comment]
OK @piofinn  - da kan jeg se på den og trekke ut og oversette, så starter vi med det?

**Comment by Gorild** [comment]
Lukker denne, siden jeg har lagt inn innhold i #499
