### ISSUE TITLE
Decide on and implement release procedure

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#454]
## Problem

We need to decide on a procedure for releasing new versions of Jøkul to npm. Right now this process is manual, and done from our own workstations.

We should have a more automated process for this, that removes as much human error from the equation as possible, to ensure stability as the user base grows.

## Proposal

I propose a strategy based on three branches; `master`, `releases/next` (or `canary` or similar) and `releases/stable`.

- `master` should be the main working branch, and any merges into master should be mirrored to `releases/next`
- `releases/next` should auto-publish its content to npm on push/merge, with `@next` version tags
- `releases/stable` should be merged into from master _manually_ when we want a release. This branch should both deploy docs and release to npm on push/merge.

### What we get

By doing it this way, we ensure a few things: The portal will be in sync with the stable release (fixing #351); We always have published versions of the latest working components; We have full control over when to publish stable versions, and can easily automate or schedule this process if we want/need to.

### How to do it

I suggest using GitHub Actions so long as our experiences with it continue to be good! Implementing the suggested functionality looks straight-forward enough.

**Comment by lfbergee** [comment]
I don't see the point in releases/next if that is just always master. Other than that, I'm quite comfortable with this strategy.

If you want som counter agument, I guess the fact that github actions still is beta is a good one. I think we can deal with breaking changes in the api though.

**Comment by piofinn** [comment]
> I don't see the point in releases/next if that is just always master.

The rationale for having a separate branch for next, was to keep the master free of tags from eventual releases. If that's not a problem I agree with you on this!

**Comment by lfbergee** [comment]
I don't mind, as long as its automagic.
