### ISSUE TITLE
Bodytekst på mobil – hva er riktig størrelse?

### ISSUE THREAD

**Issue by Murstam** [fremtind/jokul#463]
I dag er bodytekst på mobil satt til 16/24. Det har vært diskutert om vi bør gjøre den større og i såfall hvor mye større. Alt fra 17/24 til 22/32. 

For å gjøre valget litt enklere er det to faktorer som vi bør forholde oss til. Det første er at vi holder mobil nærmere øyet enn desktop, og derfor bør teksten på mobil settes mindre enn på desktop. Det vil si mindre enn 22/32. 

Det andre vi må forholde oss til er linjelengde, som bidrar til god lesbarhet. Her er anbefalingen å holde seg mellom 45-75 tegn der 66 blir sett på som optimalt. Hvis vi bruker en 375px skjerm  begynner vi å utfordre dette allerede med en størrelse på 18px. Som dere kan se på eksempelet blir det spesielt problemer med med middels lange ord som blir dyttet ned på neste linje når teksten settes i 20px og oppover. 

https://app.typographychecklist.com/ anbefaler body på mobil mellom 15-19 px.
 
[Bodytekst_mobil375.pdf](https://github.com/fremtind/jokul/files/3749591/Bodytekst_mobil375.pdf)

@idalower @Steinop

**Comment by Murstam** [comment]
Her er teksten jeg refererer til:

<img width="1279" alt="bodytext" src="https://user-images.githubusercontent.com/47025023/67365440-f0b4c880-f571-11e9-8814-d4f40650468e.png">

**Comment by Steinop** [comment]
Det ser ut som et godt utgangspunkt. 

På små skjermer kan vi vurdere å kjøre en prosentvis nedskalering slik at vi får en OK forhold mellom lesbarhet og linjelengde (hvis det lar seg gjøre i koden vår). Vi gjorde dette på en app for Norgesgruppen for noen år siden. Det fungerte fint for de få prosentene med skjermer ned til 320 px bredde.

**Comment by Murstam** [comment]
Nesten alle artikler jeg leser anbefaler ca 16px, og det er det vi ser praktisert mest. Dette i kombinasjon med fonttester på egen telefon (iphone8, 375px) gjør at jeg syns det er vanskelig å argumentere for å gå noe høyere 18/28. Hvis vi sammenligner med Akkurat Pro så er Fremtind Grotesk i tillegg 1px større.

**Comment by lfbergee** [comment]
@all-contributors please add @Murstam for design
