### ISSUE TITLE
Developer docs: usage

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#468]
Usage of pure css is not documented. Should document our BEM usage.

**Comment by Mikkelinski** [comment]
@piofinn @lfbergee fortsatt aktuell eller lukkes?

**Comment by eduardodir** [comment]
Det borde väl räcka om vi la till: CSS: BemCSS i denna lista?
<img width="507" alt="Screenshot 2020-04-13 at 23 33 31" src="https://user-images.githubusercontent.com/56429532/79163426-51b1b080-7ddf-11ea-9c45-28ebc4dfbee3.png">
