### ISSUE TITLE
Core v1.0.0

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#481]
## Make Jøkul Core ready for publishing of v1.0.0

The following should be ready in the package before we can publish v1.0.0

- [ ] ~~Have decided on font sizes for mobile and desktop~~
- [ ] ~~Have decided on breakpoints for screen sizes~~
- [x] Implement all styles from the library as design tokens
- [x] Expose all needed functionality and tokens in `.scss` files
- [x] Expose all needed core styling as a `.css` file

**Comment by lfbergee** [comment]
#386 should be fixed before 1.0
