### ISSUE TITLE
Ability to adjust underline in Datepicker 

### ISSUE THREAD

**Issue by thomasrognes** [fremtind/jokul#512]
**Is your feature request related to a problem?**
Datepicker component should have the ability to extend the underline in the input field. 

**Describe the solution you'd like**
The ability to adjust the underline as needed. 

**Describe alternatives you've considered**
The way we can adjust the underline today is to override this css, which is bad practice: 

.jkl-datepicker__input > .jkl-text-field__input {
  width: 10.5ch;
}

![DatepickerUnderline](https://user-images.githubusercontent.com/33520517/69051230-08159300-0a04-11ea-8531-eb367740daed.PNG)

**Comment by Mikkelinski** [comment]
Why would you want to adjust the underline when the dimensions are given (dates being given in dd.mm.yyyy)? One of the ideas behind the input fields (of which datepickers are a subtype) is that the underline should be representative of typical input, so you shouldn't want to extend the underline except for when opening the date select card.

**Comment by thomasrognes** [comment]
It is for responsiveness and layout. Without the modifications, the date picker will be very small compared to the "saksinformasjon" card, and will only fit a few screen sizes. "Lagre" button will not visually appear to be in the center even if it is. 

Datepickers without the modifications. 
![DatapickerUnderline2](https://user-images.githubusercontent.com/33520517/69057124-98a6a000-0a11-11ea-938e-1d728c087ea7.PNG)

Datepickers with modifications. 
![DatepickerUnderline](https://user-images.githubusercontent.com/33520517/69057311-e7ecd080-0a11-11ea-9159-4ea2c045f187.PNG) 

I can meet you if you want more explanation or/and a demo :)

**Comment by piofinn** [comment]
This sounds like a design issue and not a dev issue, to be honest. @Mikkelinski and/or Hilde (not on GitHub?) should probably take a look at this before we start developing exceptions to our patterns 😊

My gut reaction to solving the problem would be to either center the shorter inputs, or to put the button on the same line as the inputs and wrap it on very small screens. But I'll leave that to the designers! 👩‍🎨

**Comment by thomasrognes** [comment]
@piofinn I agree! I have spoken to the design team on ASK and they will take a closer look on the issue :)

**Comment by piofinn** [comment]
I'll close this issue, as it looks like this will be solved by the Flyt team internally
