### ISSUE TITLE
Implementere et tydeligere skille på besøkte og ubesøkte lenker

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#516]
Etter å ha gravet rundt i Figma for å orientere meg litt fant jeg siden "Tekstlenke" under byggesonen og så at 'unvisited' og 'visited' hadde like stiler. Lager denne issuen for å ha et sted å diskutere det.

Av egen erfaring har jeg en oppfatning av at normen heller mot å ha en mørkere farge for besøkte lenker. Etter noen raske google-søk kan jeg bekrefte at det står på papiret som best practice, men det virker som om færre og færre implementerer det. Feks sier [NN/g](https://www.nngroup.com/articles/guidelines-for-visualizing-links/) at det skal være et tydelig skille, men samtidig har ikke deres egen nettside et skille i det hele tatt. Er dette noe man går bort ifra i 2019 og fremover?

**Comment by joms** [comment]
Tar med denne til design-forum for å høre hva folk generelt tenker om dette. For min del har jeg aldri tenkt noe stort over å gjøre forskjell på en besøkt/ikke besøkt lenke.

**Comment by eduardodir** [comment]
Detta gav mening ganska mycket förr när man hade bara vita sidor med svart text där man oftast följde vendor färgerna i browsern, då gav det mening, för alla förstod vad dessa färger stod för, nu så har detta nästan helt tappat sitt värde, då många lägger in sina egna färger och stilar. Det absolut viktigaste är att en Link uppfattas som en Link och inget annat.

Lite mer: https://www.brainbell.com/tutorials/HTML_and_CSS/Working_With_Link_States.htm

**Comment by gbrownlee** [comment]
@vegardsoerlie Ønsker du mer input her eller skal vi lukke denne inntil videre?

**Comment by vegardsoerlie** [comment]
Den kan lukkes, var kun for å starte en diskusjon rundt det siden NN/g hadde det "best practice"-innlegget. Er enig i at behovet ikke er der.
