### ISSUE TITLE
Initial display value for select with value pair should use label instead of value

### ISSUE THREAD

**Issue by stianlik** [fremtind/jokul#517]
**Describe the bug**

Initial render of select with `ValuePair` shows the value instead of the label. I.e. `{ value: 9, label: 'My pretty little string' }` will display `9` to the user where one would expect `'My pretty little string'`.

This is likely resolved as a side-effect in https://github.com/fremtind/jokul/commit/1fa7c2f4a1046be27298d73209b43b8e6cbcb341 which is not yet released. In any case, it would be best to should account for `ValuePair` explicitly.

**Comment by piofinn** [comment]
@stianlik See above PR for a fix :)
