### ISSUE TITLE
Date Picker - Ønske om utvidet funksjonalitet

### ISSUE THREAD

**Issue by EspenSmith** [fremtind/jokul#567]
Hei!

Jeg arbeider med å porte et stort antall webskjema til den nye nettskjema-plattformen som bruker Jøkul.

I disse skjemaene er det ofte angivelse av datoer med begrenset gyldig intervall. Svært ofte dreier det seg om datoer i fortid eller fremtid, men andre gyldighets-intervaller kan også være aktuelle.

Det hadde vært gjevt om date-pickeren kunne konfigureres med et gyldig dato-intervall slik at brukeren ikke kan velge utenfor dette, istedenfor at applikasjonen må validere og evt avvise etter at brukeren har angitt dato.

Dette betyr mye for usability, så jeg håper det er mulig å få til dette :-)

mvh Espen Smith, ASK

**Comment by lfbergee** [comment]
@all-contributors please add @EspenSmith for idea
