### ISSUE TITLE
Multiple Select from large amounts of data

### ISSUE THREAD

**Issue by sigvehag** [fremtind/jokul#570]
**Is your feature request related to a problem? Please describe.**
Currently there is not a good way (that I've found) within Jøkul to handle selection of multiple items from within a large dataset.

**Describe the solution you'd like**
I would like a solution like [React-select's](https://react-select.com/home) multi-select. This allows the user to select several options from within a drop-down-list, and also search for items within this list. This allows for a tidy way for the user to select multiple options from a large number of alternatives.

**Describe alternatives you've considered**
I've considered using checkboxes, however the dataset I'm currently working on contains 700 items, so this takes too much space.

I've also considered a new drop-down-list to appear every time the user has selected an item in the previous ddl, but this is also not an elegant solution.

**Comment by eduardodir** [comment]
This is a snowflake for now and I will guide the team to use from the demos I did when they will get started again.
