### ISSUE TITLE
Radiobuttons with text field

### ISSUE THREAD

**Issue by Saegrov** [fremtind/jokul#575]
**Is your feature request related to a problem? Please describe.**
We have a use case where we need a set of Radiobuttons where one of the choices is "Other", which should allow you to type into a TextField.

![radio-buttons](https://user-images.githubusercontent.com/124469/70564685-ed60b500-1b90-11ea-8cac-9d438314828f.gif)

This is possible to achieve using RadioButtons and TextField together. The problem has to do with labels where we don't really want a label on the TextField since it's part of of the radio-buttons label. If we set the label to "", we get WCAG-complaints:

<img width="542" alt="empty-form-label" src="https://user-images.githubusercontent.com/124469/70565005-8263ae00-1b91-11ea-9a38-4e0b9a8a3f7f.png">

If we to add the label it seems like it is a separate TextField and not part of the radio-buttons:

<img width="698" alt="detached-textfield" src="https://user-images.githubusercontent.com/124469/70565269-0453d700-1b92-11ea-9030-2d0fba5a2b05.png">

**Describe the solution you'd like**
This might be considered a common use case for radio-buttons and thus warrant its own component or set of props to enable this behaviour. If you don't think thats the case do you have any suggestions on how to achieve this?

**Comment by vegardsoerlie** [comment]
In the last iteration of text-input we exposed `BaseInputField` as its own component. Would using that work for your case? https://github.com/fremtind/jokul/pull/488#discussion_r340866565

**Comment by Saegrov** [comment]
@vegardsoerlie Is BaseInputField documented anywhere?

**Comment by vegardsoerlie** [comment]
@Saegrov It was deliberately undocumented as it is not a desired pattern and was exposed for a very specific case. Another component that could work in your case is `InlineTextField`, since the required label there is for screen readers only.

**Comment by vegardsoerlie** [comment]
> "It was deliberately undocumented [...]"

My memory is playing tricks on me. It's documented (somewhat) [here](https://github.com/fremtind/jokul/blob/master/packages/text-input-react/README.md#særskilt-bruk).

**Comment by joms** [comment]
@Saegrov Is the documentation that @vegardsoerlie mentions covering what you need? Or would you say that this is such a common thing that it'd be worth creating a component honouring a thought through pattern?

**Comment by Saegrov** [comment]
Yes. It does mean that we would have to use a combination of `RadioButtonOption` and `InlineTextField` to create this if we want this to work both visually and for screen reader. 

I tried to combine `RadioButton` and `InlineTextField` and it reads weirdly for screen reader since it reads like two separate entities that has nothing to do with each other. Visually i looked fine tho (with some tweaking)

I'm not sure if this is common thing that is worth to create a component for - I guess that's up to you guys.

**Comment by joms** [comment]
Okay. I feel like if it reads weird for a screen reader and this is something with potential extensive use it's a deal breaker.

What do you think @piofinn? How about we assemble a meeting with relevant parties to discuss whether this is something that should be solved, or if we can go with the `RadioButton`+`InlineTextField` combination for now?

**Comment by eduardodir** [comment]
This pattern can be very common for the type of insurance solutions we are doing. From a semantic perspective, it is actually two separate things you are doing, so I cannot see how you can do this in a way where a screen reader could see this as one entity. A good solution for this case is much appreciated but I think more as a pattern than its own component. Why not even clear it out as two entities Example to toggle between Know and Custome?

**Comment by piofinn** [comment]
I agree with @eduardodir here. This looks like a pattern with two components, with the last being toggled by the first. The screen reader issue will probably be there no matter what, as it will always declare that it is in a text field. The `InlineTextField` component _does_ support a label that will be read by screenreaders (as @vegardsoerlie  mentioned), so it can be formulated to give context.

**Comment by eduardodir** [comment]
As suggested just enable a second input component for "Annen kilde"
