### ISSUE TITLE
Not adding title to card-component renders "undefined"

### ISSUE THREAD

**Issue by sigvehag** [fremtind/jokul#576]
**Describe the bug**
If one doesn't add the title-attribute to the JSX of the Card-component the title gets rendered as undefined.

**To Reproduce**
This is shown in the components example in the [portal](https://fremtind.github.io/jokul/components/card)

**Expected behavior**
I expect there to be no title if one doesn't add the title-attribute.

**Comment by lfbergee** [comment]
@all-contributors please add @sigvehag for bug

**Comment by lfbergee** [comment]
`title` er required prop, så mulig at den ønskes at `Cards` alltid skal ha tittel. Men det er litt rart. Lagde en PR som tillater kort uten tittel.

**Comment by piofinn** [comment]
Dere bruker ikke Typescript, @sigvehag?
