### ISSUE TITLE
Progressbar kan ikke være en aside

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#583]
**Describe the bug**
WCAG spesifiser at aside ikke kan ha rolle progressbar

**To Reproduce**
axe-test på progressbar i portalen

**Expected behavior**

Løsning, bytt semantiske elementet til å være en div.

**Comment by piofinn** [comment]
Kan vi endre a11y-tag'en? Den er ikke så tilgjengelig 😅:  ![Skjermbilde 2019-12-12 kl  13 31 55](https://user-images.githubusercontent.com/25739615/70712358-e5655a00-1ce3-11ea-8e58-a53b13d00ff0.png)

**Comment by lfbergee** [comment]
Fin rullestol hos meg.. Overraskende at Apple ikke implmenenterer standarden...

**Comment by piofinn** [comment]
> Fin rullestol

Ah, det er en av de nye! Har ikke fått oppdatert Mac'en ennå pga noe surr hos Origo ☹️
