### ISSUE TITLE
Component: Accordion

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#59]
- [x] Initial design
- [x] Initial package

**Comment by Steinop** [comment]
![Fremtind_Accordion](https://user-images.githubusercontent.com/51952891/59928353-db525500-943e-11e9-9453-107e8e96605f.gif)
Prototype på Accordion med blå fokusringer. Har testet ut hover med Akkurat Pro Regular - vi får teste hvordan det fungerer. Prøver å unngå fargeskifte på bakgrunnen for et renest mulig uttrykk men mulig det går på bekostning av typografi som flytter seg noen pixler. Ved ekspandering er det brukt lead size på tekst for å gi mest mulig fokus til innholdet.

**Comment by Steinop** [comment]
Figma referanse: 
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-components?node-id=24%3A0

**Comment by lfbergee** [comment]
@all-contributors please add hhannestad for design
