### ISSUE TITLE
Portal example for LogoAnimated is wrong

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#590]
We forgot to update the portal example for `LogoAnimated` when we changed the `showSymbol` prop to `isSymbol`. As a result, the animations don't work. Should be fixed with a simple search and replace.

**To reproduce**
1. Go to the Logo portal page
2. Try to click the "Animate" button
3. Nothing happens
4. Open the code editor below the example, and change `showSymbol` to `isSymbol` on a `LogoAnimated`-component.
5. See that the example works when clicking the "Animate" button

**Comment by lfbergee** [comment]
Blir ikke dette løst av å bruke eksemplet fra pakken?
