### ISSUE TITLE
Inconsistent naming of variables

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#592]
~~_spacing.scss does not match figma spacing scale. Spacing-10 168px v. 128px~~

Typography naming is not 1:1 with figma either:

Figma | Code (mixins) | Code (css classes)
--- | --- | ---
h1 | h1-heading | jkl-h1
h2 | h2-heading | jkl-h2
h3 | h3-heading | jkl-h3
h4 | h4-heading | jkl-h4
label | h5-heading | jkl-h5
lead | lead-paragraph | jkl-lead
body | body-paragraph | jkl-p
body-small | body-small-paragraph | jkl-small
small | micro-paragraph | jkl-tiny

I figma er formatet `desktop/h1` & `mobil/h1`.

I code (mixins) er de på formatet `h1-heading--desktop` & `h1-heading--mobile`, hvor man kan bruke `h1-heading` for å benytte begge (skaleres automatisk ned hvis skjermbredden er smal). Med unntak av `body-small-paragraph` & `micro-paragraph` som er like for desktop og mobil og derfor ikke har egne `--desktop` eller `--mobile` varianter

I code (css classes) brukes mixin fra den over, slik at den også automatisk skaleres med skjermbredden.

----

H5 is added in #591

**Comment by vegardsoerlie** [comment]
Spacing is fixed to match. Now 168px in both locations.

**Comment by vegardsoerlie** [comment]
@Murstam jeg husker ikke hva vi konkluderte med når vi diskuterte dette smått sist, vi kom vel kanskje aldri langt nok inn i det.

Jeg foreslår:
H1, H2, H3, H4, H5, lead, body, small, micro

Slik at det blir:

Figma | Code (mixins) | Code (css classes)
-- | -- | --
h1 | h1-heading | jkl-h1
h2 | h2-heading | jkl-h2
h3 | h3-heading | jkl-h3
h4 | h4-heading | jkl-h4
h5| h5-heading | jkl-h5
lead | lead-paragraph | jkl-lead
body | body-paragraph | jkl-body
small | small-paragraph | jkl-small
micro | micro-paragraph | jkl-micro

Og da samtidig som det oppdateres i Figma også endre fra "Headline" til "Heading" i visualiseringen. 
![image](https://user-images.githubusercontent.com/14551408/71885841-7987dd00-313b-11ea-8d10-a741b1a029df.png)

**Comment by Murstam** [comment]
Det ser bra ut! Skal endre visualisering til «Heading». Mikkel endrer stilene i Figma nå! :D
