### ISSUE TITLE
Datepicker: No error when setting date as text-input outside of valid range

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#593]
**Describe the bug**
No error when you specify a date directly into the text-input when it falls outside the valid range. It should display an error when you're outside the range.

**To Reproduce**

1. Run the datepicker example
2. Go to the third example (it has a valid range set) and input a date outside the valid range
3. Nothing shows up to indicate this is wrong, but the date is not actually set.

**Expected behavior**
We haven't clearly discussed the wanted outcome, but it should probably use the errorLabel.

**Comment by piofinn** [comment]
Maybe the best option would be to allow the inputs (via typing in the date), and actually setting the date. The implementing team can then handle the validation of the field value as normal, potentially showing an error message.

**Comment by joms** [comment]
How is this handled on other components with constraints?

One might expect that if a component exposes a constraint like date range, the component itself would handling both validating the constraint and showing an error.

However, this might be a bigger question on who should have responsibility for what validation. E.g. if one can set type="email" on a text input. Who has the responsibility for showing the error? The component itself that exposes the constraint, or the component consumer setting the constraint?

**Comment by joms** [comment]
Any input here @piofinn, @frisol97, @eduardodir?

**Comment by joms** [comment]
You might have some input here in regards of #774, @Saegrov?

**Comment by Saegrov** [comment]
I don't think there are other components that expose contraints like this.
If `DatePicker` is responsible for showing the error, it also means that `DatePicker` will be responsible for error messages as well which might not be what you want. Or you would have to expose props for error messages as well.

Another solution might be to rename props `disableAfterDate` and `disableBeforeDate` so it clearer that they only disable the actual datepicker. Maybe `disableSelectionAfterDate`.

**Comment by Saegrov** [comment]
With regards to #774 i think the main issue is that the datepicker popup changes value when you type and the actual picker is always open since it opens on focus. And that collides with `disableAfterDate` and `disableBeforeDate` since there is nothing preventing you typing a date outside the valid range. 

I think the main issue with #774 could be solved by having the datepicker open with a button instead of on focus. Which would also solve #773.

**Comment by joms** [comment]
This sounds like a sensible solution, bringing a lot of positives to the Datepicker.
