### ISSUE TITLE
Kompaktversjonen av stiler og komponenter heter "mobile", men brukes utover mobil

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#598]
Både i Figma og kode kaller vi kompaktversjon av komponenter og stiler for "mobile/mobil", men det brukes også i kompaktmodus på desktop.

Jeg foreslår å endre navn på disse til "compact" slik at det er tydeligere hva det kan brukes til. Rett og slett flytte fokus over på egenskapen og bort fra device-type. Dette krever at en utvikler og en designer setter seg ned sammen og får alt til å matche.

**Comment by piofinn** [comment]
> Jeg foreslår å endre navn på disse til "compact" slik at det er tydeligere hva det kan brukes til.

Burde man da også endre den andre versjonen fra "desktop" til "normal"?

**Comment by vegardsoerlie** [comment]
> > Jeg foreslår å endre navn på disse til "compact" slik at det er tydeligere hva det kan brukes til.
> 
> Burde man da også endre den andre versjonen fra "desktop" til "normal"?

Ja, det høres fornuftig ut
