### ISSUE TITLE
Endringer på funksjonsfarger

### ISSUE THREAD

**Issue by Murstam** [fremtind/jokul#617]
– Nye farger med bedre kontrastverdier mot lys og mørk bakgrunn
– Nye og beskrivende fargenavn

https://www.figma.com/file/fjn0P2YLDcp91s8JJgJdlAN4/Test_Murstam?node-id=1282%3A1

@vegardsoerlie

**Comment by vegardsoerlie** [comment]
Det som ligger under funksjonsfarger i koden i dag er:

Farge | hex
--- | --- 
gress | 50e68c
himmel | 509ce6
ux-rød | d73704
ux-blå | 1c74ca
ux-grønn | 35c16d

Suksess erstatter gress.
Info erstatter himmel.
Advarsel blir i tillegg siden den i dag bruker sol.
Feil blir i tillegg siden den i dag bruker blomst.
Feil blir lik som ux-rød.

De nye fargene under funksjonsfarger blir da:

Farge | hex
--- | --- 
Suksess | 2f8551
Info | 0073e3
Advarsel | ffa647
Feil | d73704
ux-blå | 1c74ca
ux-grønn | 35c16d

ux-blå brukes som farge på focus state
ux-grønn brukes på progress-bar

---

Har jeg forstått det riktig da? @Murstam
Det ser i hvert fall bra ut med de nye fargene

Jeg var ikke her når "ux"-fargene oppsto. Skal de kun leve i kodebasen og ikke under "jøkul styles" i Figma?

Toggle-switch bruker i dag `gress`. Den blir ganske annerledes hvis den blir erstattet med `suksess`. Er det tatt høyde for?

**Comment by Murstam** [comment]
Supert! Tanken var at info erstatter begge blåfargene og at suksess erstatter begge grønnfargene. Slik at focus state bare bruker info, hvis ikke det er forvirrende? 

Når det gjelder toggle-switch så burde den kanskje oppføre seg som checkmark og radio buttons og være svart/hvit?

**Comment by vegardsoerlie** [comment]
Da så, da er jeg med! Synes det ser like bra ut med den nye blåfargen som fokusfarge.

De eneste "problemene" (så vidt det kan kalles det) jeg ser er at progress-bar og toggle-switch blir mørkere grønne, men det er vel bare uvant. Hvis toggle-switch gjøres om til svart/hvit i tillegg, som høres fornuftig ut, så er vi vel i boks 😊
