### ISSUE TITLE
Endre navn på fargekategorier

### ISSUE THREAD

**Issue by Murstam** [fremtind/jokul#618]
Hovedfarger -> primærfarger
Støttefarger -> sekundærfarger og illustrasjonsfarger
Funksjonsfarger -> meldingsfarger

@vegardsoerlie

**Comment by vegardsoerlie** [comment]
Liker denne navngivningen! 

Har noen spørsmål som jeg tar i #617 siden det er mer spesifikt til meldingsfargene.

**Comment by vegardsoerlie** [comment]
Gjenstår: 
Jøkul styles må oppdateres i Figma
En siste avsjekk på kode
