### ISSUE TITLE
Radioknapp trykkflate utenfor tekst

### ISSUE THREAD

**Issue by idalower** [fremtind/jokul#623]
På radioknappene i AHV er trykkflater veldig lang - den går utenfor teksten. Kan dere se på det?

**Comment by frisol97** [comment]
En er nødt til å sette bredden på selve radio button option, det vil si bredden på label. Dette er fordi label ikke har en satt bredde og vil strekke seg ut til bredden av fieldgroup som rammer alle knappene.

**Så brede er de uten å definere bredden**
![image](https://user-images.githubusercontent.com/51901763/71967814-275ebe80-3204-11ea-8ba1-b5fefaa436e4.png)

**Dersom en setter bredden til f.eks 25% av fieldgroup**
![image](https://user-images.githubusercontent.com/51901763/71967935-57a65d00-3204-11ea-9f84-062ca7615432.png)

Det beste er å finne en løsning som gjør at width tilpasser seg tekstlengden. Usikker på om det lar seg gjøre uten å gå vekk fra flex.
