### ISSUE TITLE
Button (mobile)

### ISSUE THREAD

**Issue by mariusthedesigner** [fremtind/jokul#642]
Knappene er for små når det gjelder touch-område på mobil/tablet. Knappene er 40px høye, men anbefalt høyde på knapper er 45px eller høyere for å få et tilstrekkelig touchområde. Kan relatere flere artikler på dette, men fant denne i farten: https://www.smashingmagazine.com/2012/02/finger-friendly-design-ideal-mobile-touchscreen-target-sizes/ 

Jeg foreslår at man øker høyden på knappen til 45px eller større for å virkelig gi et godt inntrykk av enkel navigasjon.

**Comment by mariusthedesigner** [comment]
label:"🎨 design"

**Comment by Mikkelinski** [comment]
Når jeg har sett på knappene våre i forbindelse med autolayout så har jeg sett at kompaktknappen ikke har samme proposjoner som desktopknappen. En mer proposjonal størrelse hadde vært en høyde på 48px.

Kan dette være tilstrekkelig til at vi bør skille mobil & kompaktkomponentene i dette tilfellet?

**Comment by piofinn** [comment]
48px er vel en fin størrelse som også går opp i 8px-skalaen vår 😊
