### ISSUE TITLE
Feil: Grunnleggende er tom+rekkefølge på profiltekster

### ISSUE THREAD

**Issue by Mikkelinski** [fremtind/jokul#655]
I portalen er "Grunnleggende" tom - den bør slettes

I tillegg er rekkefølgen på det som presenteres i "Profilelementer" vilkårlig. Vi burde ha en mer hensiktsmessig rekkefølge. Jeg foreslår:
Designprinsipper
Tilgjengelighet
Farger
Layout
Typografi
Stil og tone
Logo
Bildebruk
Skjemadesign
Ikoner
Skygger
Vanlige mønstre

**Comment by piofinn** [comment]
Per nå har vi ingen fornuftig måte å bestemme rekkefølgen på (annet enn å sortere alfabetisk), men skal i hvert fall få tatt vekk den tomme kategorien! Glemte å gjøre det før vi merga dokumentasjonsendringene 😅
