### ISSUE TITLE
Tabell eller liste?

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#662]
## Problemstilling

Jeg har jobbet med en responsiv tabell for BM, og har i den anledning tenkt litt på hva som utgjør en tabell, og hva som eventuelt er en type liste?

Eksempelet hos BM er en oversikt over fakturaene til et gitt selskap, med informasjon om forfallsdato, beløp, om den er betalt, og link til PDF. Selv om dette er presentert som en tabell, med overskrifter over kolonnene, er det kanskje egentlig en liste? Det er jo ikke slik at man ønsker å sammenlikne verdiene i tabellen (nødvendigvs), men heller bare se informasjon om hver enhet (i dette tilfelle faktura).

## Hvorfor har det noe å si?

Grunnen til at jeg tar opp dette som et spørsmål er at typen innhold vil diktere hvordan man viser informasjonen på små skjermer. I en _tabell_ vil man gjerne ha verdier som tilhører samme kolonne ved siden av hverandre, altså gruppert etter egenskap. I en _liste_ vil man kanskje heller gruppere informasjonen etter enhet, slik at man ser alle egenskapene på en gang.

## Eksempel

I arbeidet for BM har jeg utvidet vår tabellkomponent med stil for små skjermer, på bakgrunn av skissene deres. Her er tabellen slik den ser ut på stor og liten skjerm:

<img width="776" alt="Skjermbilde 2020-01-13 kl  14 50 22" src="https://user-images.githubusercontent.com/25739615/72262649-a2b2dc80-3617-11ea-92d1-b254d6250de4.png">
<img width="330" alt="Skjermbilde 2020-01-13 kl  14 50 43" src="https://user-images.githubusercontent.com/25739615/72262652-a47ca000-3617-11ea-8d81-9d9fe1564c0a.png">

Dette eller et alternativ der egenskapene listes under hverandre (se f.eks. [Hildes tidlige skisse](https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=2932%3A2879) i Figma) funker bra for "liste"-varianten, men blir uhåndterlig med mange kolonner eller kolonner som skal sammenliknes (klassiske tabelldata).

## Forslag

Vi bør undersøke muligheten for å lage en egen komponent for lister med informasjon som er enhetlig, og heller benytte Table for data og lister der egenskaper skal sammenliknes eller sorteres. Dette mønsteret finnes f.eks. i Carbon ([Data Table](https://www.carbondesignsystem.com/components/data-table/usage) vs. [Structured List](https://www.carbondesignsystem.com/components/structured-list/usage)). Shopify Polaris har også et tilsvarende mønster med sine [Resource Lists](https://polaris.shopify.com/components/lists-and-tables/resource-list#section-purpose).

**Comment by eduardodir** [comment]
Det korrekta ur ett semantiskt perspektive är en "description list" https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl
Det finns en del som gjort denna implemenering på mobil Table > DL, dock så tar man hänsyn till långa texter i tabeller, därför kommer inte dessa skisser med "two column" å fungera, bättre göra en DL som DL, det betyder fallande lista. Stora tabeller fungerar inte på mobil, ovasett om dem är skrollbara, fasta header eller ikke.
