### ISSUE TITLE
Feil: Ulik styling av "text" og "textarea" input felt

### ISSUE THREAD

**Issue by EspenSmith** [fremtind/jokul#692]
**Feilbeskrivelse**
Jeg jobber med å sette opp web-skjema på den nye nettskjema-løsningen.
Sitter med et skjema som har input-felter av type "text" og "textarea".
Registrert input i disse feltene styles forskjellig. Det virker ikke hensiktsmessig.

Se vedlagt pdf.

Input tekst i feltene "Beskrivelse av skaden" ser korrekt ut, men teksten i "Hvem behandler/har behandlet deg i etterkant?" vises uthevet (bold).

[Jøkul-feil.20200116.pdf](https://github.com/fremtind/jokul/files/4071324/Jokul-feil.20200116.pdf)

Feltet "Beskrivelse av skaden" er type "textarea".
Feltet "Hvem behandler/har behandlet deg i etterkant?" er type "text".

**Comment by Mikkelinski** [comment]
Hei

Disse feltene styles forskjellig fordi textarea feltene potensielt har mye tekst i seg - Det er ikke lesevennelig med mye tekst satt i bold så vi har valgt å sette den i normal vekt.

Er enig i at det ikke gjør det like lett å scanne et skjema og skille label / inputs der det ikke er satt i bold - men vi ser på andre mulige endringer på textarea for å tydliggjøre hvor brukeren skal skrive og hva som er _i_ feltet
