### ISSUE TITLE
Feil: I portalmenyen snur ikke chevron hvis man blir direktelenket

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#698]
**Feilbeskrivelse**
Går man via en direktelenke til en side på portalen vil menyen starte expanded, men chevron vil ikke snu seg. Kommer til å være tilfelle hvis noen feks navigerer seg til et komponent fra npmjs.com

**For å reprodusere**
Fortell oss hvordan vi kan gjenskape feilen (det hjelper oss med å fikse den):

1. Gå til https://fremtind.github.io/jokul/button-react/documentation/buttons/
2. Observer chevron på menyen

**Forventet oppførsel**
Chevron skal ha endret seg for å vise at undermenyen er synlig.

**Skjermbilder**
Bug: 
![image](https://user-images.githubusercontent.com/14551408/72541493-e9f0d580-3882-11ea-8c69-6bb739f91664.png)

Forventet: 
![image](https://user-images.githubusercontent.com/14551408/72541529-fa08b500-3882-11ea-8bce-d72a1d0ff66d.png)

**Comment by piofinn** [comment]
Closing, as it is no longer relevant for the new portal
