### ISSUE TITLE
Animere trykk av knapper på mobil

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#711]
I dag føles knappene våre ganske "døde" på mobil, ettersom det ikke er noen hover state før man klikker. I stedet får knappen hover/focus state etter at man har klikket, og vokser dermed litt (og holder den størrelsen).

Det hadde vært ønskelig å i stedet animere en "bounce" eller annen respons på knappen i hover state på mobil, slik at det simulerer en respons fra trykket.

**Comment by Mikkelinski** [comment]
Føler denne kanskje bør prioriteres opp så fort vi har løsninger som kommer til å brukes på mobil (SeOpp er første kandidat?)

**Comment by espkva** [comment]
3 forslag på tilbakemeldinger ved "tap". Gjelder kun flater uten støtte for hover.
https://vimeo.com/417180945/7ae4b65deb

**Comment by Mikkelinski** [comment]
Syntes forslagene var bra - spesielt forslag 3 opplevde jeg at var veldig i tråd med profilen estetisk, selv om forslag 2 også kunne fungert. Litt mye bounce i forslag en kanskje?

@Steinop hvordan føler du det bør matche på tvers av desktop og mobile flater? Gitt at man ikke har hover og fokus så kan man jo bruke noe av den samme visuelle effekten på aktiv istedet - eller bør det ha et mer eget formspråk når du er på mobil?

**Comment by Steinop** [comment]
Liker retning 1 og 3 best men litt usikker på å blande inn focus-effekten på trykk. Hva med å ta utgangspunkt i retning 1 og fade over til blått på trykk (tilsvarende hovereffekten som er skissert). Uten bounce men med en myk ease-out slik at man får litt "motstand" når knappen trykkes inn (forminskes)? Kan lage noen Figma-skisser på dette men interessant å se at det fungerer i kode.

**Comment by espkva** [comment]
Var det noe i denne retningen du tenkte @Steinop ?
https://vimeo.com/417607231/2599426af9

Et "tap" har en veldig kort tidsperiode for å vise bevegelse i motsetning til hover, så det blir fort bare et blink som du ser i eksempelet.  Prøvde med en tregere transition, men da ble knappen veldig "seig" og føltes ikke veldig responsiv.

**Comment by lfbergee** [comment]
@piofinn @Steinop er dette noe å ta tak i igjen? Tror gjerne man kan ta med Link og NavLink i samme tankegang her.

**Comment by Steinop** [comment]
Absolutt. @lfbergee  Vi trenger en respons når man trykker på knapper på mobil også

**Comment by Steinop** [comment]
Note to self: Kan man gi en følelse av hover effekt/elevasjon/tydeliggjøring på mobil ved å la knapper fade inn til blå farge (som på hover state) og ut etter et par sekunder eller i forhold til prosentvis plassering i skjermbildet ved scroll?
Dette i tillegg til en respons når man trykker med fingeren.

**Comment by Steinop** [comment]
Tester ut en retning her der knappen blir blå og forminskes når man trykker. Samtidig har jeg lagt inn et ekstra "blå-flash" som fader ut for å tydeliggjøre at man trykker. Hva synes dere om denne retningen?

På denne måten kan vi få inn noe av det blå uttrykket som vi ellers har på hover.

https://vimeo.com/465007164/090fec0316

**Comment by Steinop** [comment]
Ferdig skissert mobilknapp ligger her i byggesonen:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=17454%3A4

Se klikkbar prototype:
https://www.figma.com/proto/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=17454%3A4&viewport=-67%2C-1975%2C0.7894088625907898&scaling=scale-down

Dette skjer:
Når knappen trykkes på blir knappen blå og forminskes proposjonalt 5% (x0.95) med nullpunkt i senter av knappen.
For å markere trykket får vi et blått flash som ekspanderes ut fra 0-16 px rundt knappen på alle sider og fra 50%-0% transparent blå. 
Timing: 400 ms
Easingkurve: 0, 0, 0.3, 1

Foreløpig legger jeg ikke denne inn i komponentbiblioteket - dels fordi det kommer bedre statehåndtering i Figma og fordi behovet er begrenset til avansert prototyping.

**Comment by Steinop** [comment]
Denne er kun tegnet for primærknapp - ser videre på hvordan det kan fungere på sekundær-, tertiær-, menyknapper, lenker og navigasjonsknapper.
