### ISSUE TITLE
Refaktorering av toggle-switch

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#726]
**Er ønsket tilknyttet et problem? Fortell oss mer!**
Toggle Switch leses ut som "avmerkingsboks" av VoiceOver.

**Beskriv løsningen du ønsker**
Endre Toggle Switch til å ta i bruk `button` med attribute `aria-pressed="true/false"` kontra `input type="checkbox"`.

Dette følger [best practice](https://www.w3.org/TR/wai-aria-practices-1.1/#button) mtp. a11y. Da vil VoiceOver lese det som "veksleknapp".

**Hvilke alternativer har du vurdert?**

**Mer info**
Videre lesestoff som kan være nyttig: 
https://scottaohara.github.io/a11y_styled_form_controls/src/toggle-button-switch/
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role
https://www.w3.org/TR/wai-aria-practices/examples/button/button.html

**Comment by vegardsoerlie** [comment]
Alternativ løsning: Gi eksisterende `<input type="checkbox">` attributene `role="switch"` og `aria-checked={checked}`.

Blir lest som "switch" av skjermleser. Dessverre leser norske VoiceOver det som "bytt", så det er en ganske dårlig oversetting der.

Jeg ser på dette som like riktig og derfor den foretrukne løsningen av de to siden den ikke krever noe særlig endring. Derimot veldig dumt at oversettelsen er så dårlig, men det er fortsatt korrekt i følge [w3](https://www.w3.org/TR/wai-aria-1.1/#switch). Tanker @piofinn @frisol97 @lfbergee?

**Comment by frisol97** [comment]
Med tanke på skjermleseren ville jeg gått for løsning nr.1, også fordi det er best practice. Har du testet med andre skjermlesere?
