### ISSUE TITLE
Feil: Farger ikke oppdatert

### ISSUE THREAD

**Issue by Mikkelinski** [fremtind/jokul#727]
Ny fargeprofil er ikke implementert. Fargeprofilen er etter gjennomgang med marked blitt oppdatert.

Vi kommer til å benytte oss av en gråtoneskala og en vardeskala for å erstatte "hovedfargene" vi hadde utenom Hvit, Svart og Varde.

Melding og illustrasjonsfargene forblir urørt.

https://www.figma.com/file/e2ySi9kFBEICxiHwsBU7pt04/J%C3%B8kul-Styles?node-id=0%3A1

Her finnes stilene med navn oppdatert

**Comment by vegardsoerlie** [comment]
Ved overgangen fra gamle til nye farger er det de følgende som ikke hadde en identisk verdi. Dette er forslaget mitt til de nærmeste verdiene. @Murstam @Mikkelinski 

![image](https://user-images.githubusercontent.com/14551408/73159717-80c15b80-40e7-11ea-9f96-6f8672499cad.png)

**Comment by Murstam** [comment]
Enig i det forslaget.
