### ISSUE TITLE
Feil: RadioButtons tar ikke imot className

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#740]
**Feilbeskrivelse**
`RadioButtons`-komponenten tar ikke imot `className`

**Forventet oppførsel**
Komponenten burde ta imot `className` så man kan sette stil på komponenten

**Comment by joms** [comment]
@piofinn Vil korrekt oppførsel være at `className` blir satt på `FieldGroup`, eller vil det være for å styre `RadioButtonOption`?
