### ISSUE TITLE
Finne bilde til portalforsiden

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#743]

**Comment by Steinop** [comment]
Idé: Hva synes dere om å lage en animert loop av et 3D mesh som ligger over et bilde av en isbre, isfjell eller lignende? Kan gi en fin referanse til rammeverk, bygging, komponenter samtidig som det kombineres med fremtindsk naturtema.
Se for dere en combo av bildene nedenfor. Her kan vi også utforske et animert bølgende teppe av diamanter som ligger over bildet. Mange muligheter. Synes bildet bør ha en viss "mindblowing kulhetsfaktor" :)

<img width="1010" alt="generate_plane_vertices_coordinates" src="https://user-images.githubusercontent.com/51952891/73742862-a4bb1780-474d-11ea-8469-07feb0634444.png">
![willian-justen-de-vasconcellos-WMOwLypr_2I-unsplash_low](https://user-images.githubusercontent.com/51952891/73742872-ac7abc00-474d-11ea-814d-5c7357a0b78d.jpg)

**Comment by Steinop** [comment]
Synes fortsatt vi bør utforske mulighetene for Cinemagraph/film istedenfor stillbildet vi har nå. 
Dette må uansett vente pga Korona/Hjemmekontor.
