### ISSUE TITLE
Simplify use of classNames internally in components

### ISSUE THREAD

**Issue by joms** [fremtind/jokul#745]
Currently, a repeating pattern for using `classNames` is using string concatenation. It's a bit hard to read, not really intuitive, and feels repetitive to generate.

I'm not sure what the guidelines for using external libraries are, but one could use the [classnames package](https://www.npmjs.com/package/classnames), or create a simplified utility function for generating classNames.

This would change

```
const componentClassName = "jkl-accordion-item".concat(
    isOpen ? " jkl-accordion-item--expanded" : "",
    className ? ` ${className}` : "",
);
```

into

```
const componentClassName = className(
	"jkl-accordion-item", {
	    "jkl-accordion-item--expanded": isOpen,
    },
	className
);

// alternatively
const componentClassName = className({
		"jkl-accordion-item",
	    "jkl-accordion-item--expanded": isOpen,
    },
	className
);
```

Pros of the proposed way of doing this:
- Clear definition which is easy to read and get an overview of what's happening and how each class is controlled
- No need for hard to read ternary expressions
- Easy to control dynamic behaviour within the component
- `className` prop could be a dynamic object controlling styles from outside the component

**Comment by piofinn** [comment]
The current pattern stems from when we had few dynamic classes in the library. We considered `classnames` back then, but decided to wait.

This is probably as good a time as any to start using it, so I'm all for it! Sounds like a great little refactor if you want to get to know the components better, @joms 😊

**Comment by joms** [comment]
Awesome @piofinn! Would we benefit for creating a `jkl-util` package where we could store our utilities (I assume that this won't be the last one), or are there other patterns for creating utility functionality?

**Comment by piofinn** [comment]
We have discussed a `jkl-util` package before, and it might be a good idea at some point. We already have a package with React hooks that could be moved there if we find the need.

For this case though, I think it's easiest to just use the `classnames` package. It works well and seems to have types available. We don't have any formal rules about new packages, but the practice has been "add it if you think it adds value, and we'll discuss it in the PR" 😊

**Comment by joms** [comment]
Refactored quite a lot of classname definitions to use the classnames package. Will look for more definitions to replace tomorrow before starting CR.

**Comment by joms** [comment]
🎉
