### ISSUE TITLE
Lage favikon

### ISSUE THREAD

**Issue by idalower** [fremtind/jokul#747]
Kan vi få inn et Favikon i designsystemet som vi kan bruke på AHV, SeOpp, Jøkul og Fremtind.no
Legger ved forslag (228x228px)

![fremtind-favikon](https://user-images.githubusercontent.com/47539074/73756870-91697580-4768-11ea-8eff-2317d079d693.png)

**Comment by joms** [comment]
Tror det kan være lurt å lage et lyst favicon for nettlesere som kjører dark theme også ettersom Fremtind logoen ikke synes veldig godt i dark theme.

![image](https://user-images.githubusercontent.com/537060/73838018-04c7c180-4813-11ea-8832-df18839c733e.png)

https://dev.to/rumkin/smart-web-design-part-i-light-dark-mode-favicon-31f0

**Comment by Steinop** [comment]
Lagde favicons i mai 2019. Kan vi fortsatt bruke disse?
[favicon_package_v0.16.zip](https://github.com/fremtind/jokul/files/4329874/favicon_package_v0.16.zip)

**Comment by eduardodir** [comment]
För att ungdå issues med vilken mode som webläsare har, så sätt en vit bakgrundsram på logotypen, så fungerar den överallt.

**Comment by Steinop** [comment]
Oppdaterte Favicons - nå med hvit bakgrunn. Ser litt røft ut i dark mode med den hvite firkanten bak. Er det mulig å bytte til negativ versjon at F-en for dark mode? I så fall kan jeg lage en slik.
Hvis ikke er det denne som gjelder:

[Favicon_package_Fremtind.zip](https://github.com/fremtind/jokul/files/4380066/Favicon_package_Fremtind.zip)

**Comment by eduardodir** [comment]
@Steinop Det finns ingen stötte på tvärs och göra detta utan och bruka JavaScript, det är lite stygga lösningar jag sett för å få detta å fungera. Det bästa är menar jag att finna något som fungera i både light och darkmode.

**Comment by Steinop** [comment]
Da er løsningen å kjøre en helhvit boks bak en sort F for å ivareta vårt sort/hvite uttrykk. 
For å lage en vennligere variant (enn en hard firkant) kan vi legge en hvit sirkel som bakgrunn. Hvordan er stemningen for noe slikt?

**Comment by eduardodir** [comment]
@Steinop Ja, hade tanken själv kring en vit sirkel, vi kan alltid ändra efterpå, jag vill bara nå laga implementationen så andra kan bruka det.

**Comment by Steinop** [comment]
Hold an implementasjonen @eduardodir - så lager jeg en rund versjon.
Forhåpentligvis klar før standup.

**Comment by Steinop** [comment]
Her er en rund versjon. Ble bedre å legge F-en negativt på en sort bakgrunn fordi F-en måtte bli noe mindre i størrelse for å fungere i en sirkel. På denne måten blir det også mindre sensitivt om bunnen av F-en ikke havner på nøyaktig samme linje som dynamisk tekst i ulike browsere/løsninger.
[Fremtind_favicon_package_round.zip](https://github.com/fremtind/jokul/files/4386458/Fremtind_favicon_package_round.zip)

**Comment by eduardodir** [comment]
I have som Gatsby challenge to finish this one I need help with.

**Comment by gbrownlee** [comment]
Jeg har laget en PR som en midlertidig løsning: #892 . Denne har ikke alle formater, så vi må ta jobben med å fikse dette med f.eks. en Gatsby-plugin.
