### ISSUE TITLE
DatePicker#React does not change “intialDate” when receiving changed props from parent

### ISSUE THREAD

**Issue by BjornBakke** [fremtind/jokul#749]
```
   it("should change date on new props", () => {
        const { container, getByTestId } = render(<DatePicker initialDate={new Date("02.02.2019")} />);
        render(<DatePicker initialDate={new Date("12.09.2019")} />, { container });

        const input = getByTestId("jkl-datepicker__input");
        expect(input).toHaveProperty("value", "12.09.2019");
    });
```
https://github.com/testing-library/react-testing-library/issues/65#issuecomment-385529996

**Comment by SercanSercan** [comment]
I noticed that Datepicker-react did not have useEffect() for initialDate and hence, it was not updated after re-initialisation of the value. So, this has been fixed. Plus, @piofinn  noticed the unit test written above had a bug as well. See his fix below:

`it("should change date on new props", () => {
        // New date takes MM.DD.YYYY values
        const { container, getByTestId } = render(<DatePicker initialDate={new Date("02.02.2019")} />);
        render(<DatePicker initialDate={new Date("09.12.2019")} />, { container });

        const input = getByTestId("jkl-datepicker__input");

        // Check for date formatted as DD.MM.YYYY
        expect(input).toHaveProperty("value", "12.09.2019");
    });`

Closing the issue.
