### ISSUE TITLE
ToggleSwitch does not update in Select example

### ISSUE THREAD

**Issue by joms** [fremtind/jokul#752]
**Describe the bug**
When viewing the Select example in Portal, and clicking the ToggleSwitch components to change the ui state - the ui state is changed, but the ToggleSwitch does noe reflect the update.

**To Reproduce**

1. Go to https://fremtind.github.io/jokul/select-react/documentation/Select/
2. Click on the Dark Mode toggle switch

**Expected behavior**
When the ToggleSwitch changes state, the switch is updated accordingly reflecting the state in the UI.

**Desktop (please complete the following information):**

-   OS: MacOs
-   Browser Chrome
-   Version 79

**Comment by piofinn** [comment]
Looks like this is a result of the recent refactor of `ToggleSwitch` (#732). My guess is that the `checked` prop has not been renamed to `pressed` in the example code for `Select`.
