### ISSUE TITLE
WIP: CI/CD QoL for developers

### ISSUE THREAD

**Issue by joms** [fremtind/jokul#761]
**WIP** This task issue is still work in progress

Currently, there are some issues in regards of how the CI/CD works:

- Automatic release system is not optimal
- GreenKeeper seems to have issues clearing out its own branches
- Optimisations could be made to pipelines
- Add watch testing script

Related to https://github.com/fremtind/jokul/issues/748

**Comment by Mikkelinski** [comment]
@joms du på denne eller unassigne? Også - fortsatt relevant(må spørre siden jeg ikke kan noen av forkortelsene heh)?

**Comment by joms** [comment]
Jeg unassigner meg foreløpig, og fortsatt høyst relevant :)

**Comment by piofinn** [comment]
### Denne kan vel kanskje regnes som løst nå?

> Automatic release system is not optimal

Fikset i går

> GreenKeeper seems to have issues clearing out its own branches

Bruker ikke Greenkeeper lenger

> Optimisations could be made to pipelines

Ting går fortere (men her vil det vel alltid være rom for forbedring)

> Add watch testing script

Husker ikke om dette ble dratt inn, men er uansett bare å kjøre `yarn test:unit [navn] --watch`

**Comment by joms** [comment]
Ja, tenker kan stenges. Har lagt inn watching for tester også 👍
