### ISSUE TITLE
$hvit er ikke definert i jkl-core/variables/_colors.scss men brukt i button.scss

### ISSUE THREAD

**Issue by rlalaina7** [fremtind/jokul#766]
**Feilbeskrivelse**
$hvit er brukt i button.scss ()
=> $button-bg-color: $hvit;
Men det finnes ikke i @fremtind/jkl-core/variabels/_colors.scss (fra jkl-core.2.0.1 package). 
= > $snohvit: #fafafa;
       $helhvit: #ffffff;

**For å reprodusere**
1. Instalere pakke jkl-button : yarn add @fremtind/jkl-button
=> Den installere jkl-core 2.0.1 og jkl-button 1.2.1
2. Kopiere button.scss fra jokul prosjektet: packages/button. Og importere det i din lokal sass fil
3. Bygg prosjeket dit igjen
4. Se feilen i terminal:
=> Undefined variable.
    $button-bg-color: $hvit;

**Forventet oppførsel**
Ingen feil i Terminalen

**Mer info**
Jeg har et enkelt lokalt prosjekt (node UTEN React). Jeg tenkte å prøve den Jokul knappen. 
Så har jeg gjort : yarn add @fremtind/jkl-button (OK)
=> jkl-core 2.0.1 og jkl-button 1.2.1
Jeg bruker scss. Så jeg ville ikke bruke den min.css filen. Jeg har da kopiert button.scss fra jokul-prosjektet. Men den filen bruker $hvit variabel. Og den er ikke definert.

**Comment by piofinn** [comment]
Hei, @rlalaina7 

Pakkene som ligger i **master** i prosjektet på GitHub er ikke nødvendigvis i synk med pakkene som er publisert til NPM (selv om vi prøver å holde dem synkronisert). Det er derfor ikke sikkert at det vil fungere å kopiere filer fra GitHub og bruke dem sammen med pakker du har installert fra NPM, slik som i dette tilfellet.

Per nå eksponerer vi ikke .scss-filene i de publiserte pakkene (annet enn `jkl-core`), men vi vil implementere dette ved en senere release 😊

For å fikse problemet ditt i mellomtiden kan du kopiere filen `variables/_colors.scss` fra `jkl-core` som ligger i **master** her på GitHub. Den har variabelen du mangler nå 😊 Vær imidlertid obs på at det kan dukke opp feil i andre komponenter som følge av dette.

**Comment by rlalaina7** [comment]
Takk for raskt svar. Jeg skal bare kopiere _colors.scss fra master for nå og teste litt rundt :)
