### ISSUE TITLE
Datepicker - Month in month-dropdown disabled when there are valid dates in next month

### ISSUE THREAD

**Issue by Saegrov** [fremtind/jokul#772]
**Describe the bug**
When using `DatePicker` with the extended variant, we are unable to use the month dropdown for months that are inside the valid range.

**To Reproduce**

1. Use DatePicker with the extended variant.
2. Set `initialDate` to 16.01.2020.
3. Set `disableAfterDate` to 15.02.2020
4. Try to use the month dropdown and select February
5. This is not possible since February is disabled.
6. If `disableAfterDate` is set to 16.02.2020 February is enabled and selectable.

For a full example go to:
https://codesandbox.io/s/friendly-https-7ykpf?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
I expect to be able to select the next month if there is a date in the next month within the valid date range.

**Comment by Saegrov** [comment]
I just found this: 
https://github.com/nrkno/core-components/issues/386

**Comment by piofinn** [comment]
We might want to help out with https://github.com/nrkno/core-components/pull/391 to get this fixed

**Comment by eduardodir** [comment]
Anbefaller verkligen starkt och separera inputfield från datepicker å ha datepicker som datepicker, med tex en ikon för å toggle den.

**Comment by gbrownlee** [comment]
@Saegrov Kan du følge opp denne med NRK?

**Comment by Saegrov** [comment]
@gbrownlee Jeg skal høre.

**Comment by Saegrov** [comment]
@gbrownlee: Har noen prøvd workarounden som er lenket i issuet? (https://github.com/nrkno/core-components/issues/386#issuecomment-562607407). Jeg pratet med han som opprettet issuet. Siden det finnes en workaround så døde https://github.com/nrkno/core-components/pull/391 litt.

**Comment by gbrownlee** [comment]
> @gbrownlee: Har noen prøvd workarounden som er lenket i issuet? ([nrkno/core-components#386 (comment)](https://github.com/nrkno/core-components/issues/386#issuecomment-562607407)). Jeg pratet med han som opprettet issuet. Siden det finnes en workaround så døde [nrkno/core-components#391](https://github.com/nrkno/core-components/pull/391) litt.

Noen erfaringer med dette, @piofinn eller @eduardodir? Kan workarounden løse problemet godt nok?

**Comment by eduardodir** [comment]
@SercanSercan jobbar du fortsatt med den issue?

**Comment by SercanSercan** [comment]
nei.

**Comment by piofinn** [comment]
Closed by #1214
