### ISSUE TITLE
DatePicker - typing a date outside the valid date range

### ISSUE THREAD

**Issue by Saegrov** [fremtind/jokul#774]
**Describe the bug**
If you set `disableBeforeDate` and `disableAfterDate` there is no validation or anything preventing you from typing a date that is outside of this range with the keyboard.

**To Reproduce**

1. Use `DatePicker` and set `disableBeforeDate` to 05.01.2020 and `disableAfterDate` to 15.01.2020.
2. Click on the DatePicker and type 01.02.2020.
3. The DatePicker popup shows some other date - usually the previous valid date.

**Expected behavior**
I'm not sure. Either the datepicker should show the actual date that you type. Or maybe display an error message if the date is outside the valid range.

**Comment by joms** [comment]
Related to #593

**Comment by piofinn** [comment]
Marked as duplicate. Please go to #593 if you want to discuss this issue.
