### ISSUE TITLE
Støtte for referanser

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#776]
**Is your feature request related to a problem? Please describe.**
Per i dag er det ingen komponenter i Jøkul som støtter å ta imot referanse. Det gjør at man ikke kan feks sette fokus på et inputfelt, eller hente ut verdien av et ukontrollert inputfelt.

**Describe the solution you'd like**
Implementere forwardRef på komponenter som Button, TextField, TextArea, RadioButton, Checkbox

**Additional context**
https://reactjs.org/docs/forwarding-refs.html

NOTE: `When you start using forwardRef in a component library, you should treat it as a breaking change and release a new major version of your library.`

**Comment by eduardodir** [comment]
Tyckte denna var mycket mer informativ, https://blog.logrocket.com/cleaning-up-the-dom-with-forwardref-in-react/
Klart intressant om det görs för rätt bruk.

**Comment by piofinn** [comment]
Gjør om denne til en milestone: https://github.com/fremtind/jokul/milestone/6
