### ISSUE TITLE
For bred minimumsbredde på tertiærknapp

### ISSUE THREAD

**Issue by stiansuren** [fremtind/jokul#802]
**Er ønsket tilknyttet et problem? Fortell oss mer!**
Jeg skal bruke tertiærknappen til "Logg ut" og minmimumsbredden på knappen gjør at understreken ser underlig lang ut. 

**Beskriv løsningen du ønsker**
Enten at minimumsbredden er kortere for tertiærknappen eller at den ikke har en minimumsbredde

**Mer info**
![image](https://user-images.githubusercontent.com/13797642/75855638-ff9a6a00-5df2-11ea-8c7a-61f5c12f3946.png)

**Comment by piofinn** [comment]
Stemmer. Det er en bug med kompaktversjonen spesifikt, siden vi overskriver den opprinnelige minimumsbredden, og dermed også at `tertiary` ikke har noen.

Blir nok et bugfix-maraton neste uke nå som vi er ferdige med ny portal, så skal få tatt den da 😊
