### ISSUE TITLE
Nytt Inputfelt, Dropdown og Text Area

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#803]
Inputfelter, dropdowns og tekstfelter trenger bedre affordance i informasjonsintensive løsninger. 
Vi ser på oppdatering basert på ny visuell input fra SDG

**Comment by Steinop** [comment]
XD-prototyper (dark mode):

Inputfelt: https://vimeo.com/395422851/f4604ca040
Dropdown: https://vimeo.com/395422882/bea3fca3a0
Text Area: https://vimeo.com/manage/395422822/general

Animasjonen inn er tenkt brukt ifm loading av sider. Feltene bør da lastes sekvensielt / med et kort delay mellom hvert felt tilsvarende slik vi gjør i menyen på Jøkul portalen. 
På informasjonstunge sider kan dette bli overveldende - der må vi ha mulighet til å skru av animasjon inn og heller legge animasjon på cards, felter etc.

I de nye komponentene prøver vi nå signalfarger på hover - dette må vi også se på for øvrige komponenter i designsystemet. Fargen bidrar til økt fokus på hover eller når en komponent er trykket på. Hoveduttrykket er fortsatt sort/hvitt/varde

**Comment by piofinn** [comment]
Denne svarer direkte på #648 (legger inn kommentar så de linkes)

**Comment by Steinop** [comment]
Note to self: Bør se på hvordan hjelpetekster erstattes med feilmeldinger ved hjelp av animasjon. Det samme gjelder ved feilmeldinger i tilfeller hvor man ikke har hjelpetekster. Kan vi bruke samme animasjonsprinsipp som vi bruker på pila i accordions og ved valg i Select?

**Comment by Steinop** [comment]
Her er et par lenker til animerte feilmeldingstekster i Figma. Har også lagt inn et par hovereffekter fra default og error state for å gi litt inntrykk av hvordan dette kan se ut når man også involverer musepekeren.

Prototype - Kun feilmelding:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=12521%3A289

Prototype - Hjelpetekst erstattes med feilmelding:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=12521%3A240

Hvis hjelpetekstene blir lange bør det muligens legges inn en maske som hjelpeteksten forsvinner ut av. Har ikke lagt dette inn i Figma.

**Comment by Steinop** [comment]
Prototype av Text Area / Ekspanderbart inputfelt:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=12538%3A33856

Feltet ekspanderer til 5 linjers høyde på klikk og ekspanderer seg videre. Ved max/minimum antall tegn brukes hjelpetekst som indikator. Kan også være aktuelt med en teller - type "10 av 400 tegn" eller lignende dersom det bør være en begrensning.

**Comment by Mikkelinski** [comment]
@piofinn kan denne lukkes nå?
