### ISSUE TITLE
Feil: Portalen: Dobbelt menypunkt under "Kom i gang"

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#809]
**Feilbeskrivelse**
Designsystem prosessen ligger dobbelt opp under "Kom i gang"

**Skjermbilder**
<img width="1630" alt="Screenshot 2020-03-06 at 09 00 43" src="https://user-images.githubusercontent.com/51952891/76064039-2ab6c200-5f89-11ea-940e-73b63e08a30d.png">

**Comment by steffenz** [comment]
Jeg også bet meg merke i denne. Ser at det er to filer for denne siden; [processGuide.md](https://github.com/fremtind/jokul/blob/master/portal/src/texts/getstarted/processGuide.md) og [ProcessGuide.md](https://github.com/fremtind/jokul/blob/master/portal/src/texts/getstarted/ProcessGuide.md). Sistenevnte har kun en bidragsyter og jeg mistenker at vedkommende sitter på OSX eller Windows, som i motsetning til Linux ikke bryr seg om casing i filsystemet. Dette kan skape mye hodebry i Git. Litt mer informasjon [her](https://www.hanselman.com/blog/GitIsCasesensitiveAndYourFilesystemMayNotBeWeirdFolderMergingOnWindows.aspx)
Ser ikke noe forskjell i filene heller, så det kan virke som den ene trygt kan slettes (den med kun en bidragsyter). :smile:
