### ISSUE TITLE
Fremtind logo symbol does not rotate in IE 11

### ISSUE THREAD

**Issue by joms** [fremtind/jokul#827]
**Describe the bug**
`jkl-logo jkl-logo--symbol-only` does not render correct in IE 11. This is caused by [IE 11 apparently not supporting CSS transforms on SVG elements](https://greensock.com/forums/topic/8724-svg-transforms-and-ie/?do=findComment&comment=34510).

By render correct, I mean it is not rotated 45 degrees as described in the CSS.

However, when applying `transform: rotate(45deg)` on the svg element itself _something_ happens. Will need to test more on this.

**Expected behavior**
Logo is rotated 45 degrees.

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser: Internet Explorer
-   Version: 11

**Comment by joms** [comment]
When applying the attribute `transform="rotate(45)"` to `g` the object is rotated, but not transformed. ![screenshot](https://i.imgur.com/f2Mg4nh.png)

**Comment by joms** [comment]
Managed to put together a set of transform attributes which seems to work. CSS overrides these, so I don't think we'll have to separate browsers 🎉

**Comment by joms** [comment]
Solved many of the issues, but I am not able to center the symbol in a reliable way using transforms.

https://github.com/fremtind/jokul/commit/dda29da3755b55b7703afc3693ff3c00922f0111

Any suggestions @piofinn?

**Comment by eduardodir** [comment]
The main issue here is that we do not have a clear definition of what we accept as "okay" or not in older browsers. We should only care for "logics" and not "looks" when it comes to IE11 compatibility or any other older/minority browser.

**Comment by joms** [comment]
@eduardodir This is actually an issue where the Fremtind logo is not shown correct, breaking our brand. I'm not seeking for perfection when it comes to looks, but I feel that the logo should be shown correct 😄

**Comment by eduardodir** [comment]
Then do not rotate it, show it correctly as "default"

**Comment by lfbergee** [comment]
I usually air on the side of not caring about IE11. But here I must agree with @joms, not rendering our own logo correctly seems dumb.

**Comment by Mikkelinski** [comment]
@joms er du på denne eller skal jeg unassigne?

**Comment by joms** [comment]
Denne er jeg fortsatt på. Den har bare ligget brakk en liten stund. Tenker jeg får tid til å ta den opp igjen ganske snart.
