### ISSUE TITLE
Eksempler til vår profil

### ISSUE THREAD

**Issue by Mikkelinski** [fremtind/jokul#828]
Eksempler til “Vår Profil” og undersidene i portalen.

Foreløpig liste (subject to change)

- [ ] Elevasjon
- [ ] Bevegelse
- [ ] Klarhet
- [ ] Tilgjengelighet
- [ ] Primærfargebruk
- [ ] Støtte/sekundærfargebruk
- [ ] Farger UU
- [ ] Logo Ornamentering (flere eksempler)
- [ ] Layout whitespace eksempel (full width / large)
- [ ] Layout midstilling
- [ ] Stemmen vår (jeg deg, sjargong, passive formuleringer)
- [ ] Typografi (modig typo)
- [ ] Bildebruk
- [ ] Ikoner
- [ ] Skjemadesign (validering riktig validering feil)

Bruke “riktig / feil” komponentene som på komponentsidene øvrig.

**Comment by kristineSorensen** [comment]
Tenker jeg begynner å jobbe med eksempler til bildebruk i dag.

**Comment by kristineSorensen** [comment]
Ser også på eksempler til Logo

**Comment by kristineSorensen** [comment]
https://www.figma.com/file/dWhCsnlMAmJEBPyGnRrse5RM/J%C3%B8kul-portalen?node-id=2169%3A0 

Her ligger det jeg har fått tegnet opp så langt på bildebruk og logo. Tar gjerne imot feedback på det.

**Comment by Mikkelinski** [comment]
Anbefaler at denne deles opp og det opprettes nye issues når behovet melder seg - en rekke av komponentene og profilsidene har nå fått eksempler.
