### ISSUE TITLE
Shadow is not drawn on table rows in IE

### ISSUE THREAD

**Issue by joms** [fremtind/jokul#837]
**Describe the bug**
`.jkl-table__row` uses drop-shadow in stead of border, but this ends up not being rendered.

**Expected behavior**
Shadowssss

**Desktop (please complete the following information):**

-   OS: Window$
-   Browser: Internet Explorer
-   Version: 11

**Additional context**
Seems like the issue is solved by adding inset and change from a positive value to a negative.

**Comment by piofinn** [comment]
Was fixed by #838
