### ISSUE TITLE
Kortanimasjon for Flyt og tilsvarende løsninger

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#840]
Flyt-prosjektet har behov for å animere oppgave- og infokort for å tydeliggjøre hvor de kommer fra og hvor de blir av i gitte situasjoner.

Følgende scenarier ønskes animert:
1. Oppgave blir til. Kortet oppstår ut av “intet”. 
2. Oppgave er ferdig. Kortet skal bort, samtidig som loggen får en ny post. (det ferdige kortet blir transformert til en loggpost?)
3. Oppgave legges til fra plussmenyen.
4. Infokort åpner edit mode-kort til siden. Oppgave og logg-delene skyves til side.

Her er lenke med skisser fra Flyt-teamet:
https://www.figma.com/file/n0vTMvp78LHl9khqCo9zSo/Flyt.Januar.2020?node-id=9414%3A88673

Designsystemteamet ønsker å kunne gjenbruke tilsvarende komponenter i størst mulig grad på tvers av alle Fremtinds løsninger slik at vi unngår å utvikle "snow flakes" for produktteamene.
Derfor viktig å undersøke behovene hos BM, SeOpp, Sam med tanke på felles animasjonsmønster.

**Comment by eduardodir** [comment]
Skulle vi i tillägg till denna kunna börja skriva på en sida kring animationer?

**Comment by Mikkelinski** [comment]
@CamillaDahlstroem kortene dere har i flyt, bruker de kortkomponenten as is i Jøkul? Ser at portaleksemplene våre ikke viser det dere bruker helt.
@piofinn vet du om portalen er reperesentative for kortkompoentene vi har?

Skal oppdatere figmabiblioteket med skisser fra Stein Olav

**Comment by Mikkelinski** [comment]
Tar opp denne om det meldes videre behov
