### ISSUE TITLE
Header/label tabell

### ISSUE THREAD

**Issue by Murstam** [fremtind/jokul#841]
Header for hver enkelt kolonne i en tabell er satt som micro (12px bold). Dette er veldig lite, men header small (21px bold) er for stor. Noe midt i mellom ville blitt mer riktig, 16px bold. har laget skisse på det. Hvordan bør vi gå frem her? 

https://www.figma.com/file/yZuhGH67kdhYwLWYeJzuaT/Faktura?node-id=415%3A138

**Comment by Steinop** [comment]
@Murstam Synes 16 fungerer fint i det minimalistiske universet for desktop small. Ser at vi også har behov for en "BodyBold" for bruk i inputfelter og dropdowns. I enklere tabeller til bruk i publikumsløsninger kan det kanskje være aktuelt med en tabell satt i body-størrelse i tillegg til disse i small?

**Comment by Murstam** [comment]
Jepp, kan vi da si at den skal bruke stilen small satt i vekt bold? Ja, tenker det sikkert vil bli behov for det etterhvert.

**Comment by Steinop** [comment]
Ja, det høres OK ut. Enkelt og greit.

**Comment by eduardodir** [comment]
Kan denna stängas nå?
