### ISSUE TITLE
Min-width i button samsvarer ikke med figma

### ISSUE THREAD

**Issue by frisol97** [fremtind/jokul#842]
**Feilbeskrivelse**
I figma er min-width-compact for button definert som 5rem, mens i koden er den 104px som er 6.5rem.
Vil si 5rem er penest i compact-mode.

**Comment by Murstam** [comment]
I Figma er knappen også 36px høy, og tekst satt i 14 px bold.

**Comment by piofinn** [comment]
Her har det nok vært noen endringer som har blitt borte i kommunikasjonen et sted. Husker det var en del frem og tilbake med størrelser på knappene, og om de i det hele tatt skulle ha en kompakt variant, så det ble avventet å gjøre endringer i kode. Men det skal altså være de dimensjonene som er i Figma nå?

**Comment by Mikkelinski** [comment]
@piofinn Jeg tror de minWidthene og tilpassningene som er satt i figma var de siste vi gjorde på knappene, husker iallfall at jeg drev å tweaka de en del (både tekst, height, minwidth)

**Comment by Murstam** [comment]
Det har du helt rett i 😅Ja, det tro jeg også Mikkel. Så min width 80px på compact og 104px på vanlig. Tertiaryknappene har ikke min width.
