### ISSUE TITLE
Datepicker selve dato-knappen har default outline i Firefox

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#854]
**Describe the bug**
Når man åpner datepickeren, så har den valgte datoen default stiplet outline i Firefox, ser ikke helt heldig ut.

**To Reproduce**
I Firefox
1. Go to https://fremtind.github.io/jokul/datepicker-react/documentation/Datepicker/
2. Click on datovelger

**Expected behavior**
Ingen default outline

**Desktop (please complete the following information):**

-   OS: RedHat Server 7
-   Browser Firefox
-   Version 75

**Comment by piofinn** [comment]
Har tenkt på at vi kanskje burde lage en (eller flere) litt mer spisset utgave av `reset-outline` mixinen. Den spytter ut fryktelig mange linjer CSS nå, og føles litt som å teppebombe uten at man treffer alt man vil 😅

Kunne det for eksempel vært en idé med en `reset-button` mixin som fjernet det nødvendige kun på en knapp, inkludert bakgrunnsfarge og tekstfarge som man nå må endre i tillegg? Så kan man evt ha en tilsvarende for andre felter som trenger diverse rare resets..

**Comment by lfbergee** [comment]
Høres smart ut det. Firefox er litt hissigere enn Chrome for å beholde outlinen sin, så greit å teste der :)
