### ISSUE TITLE
Redesign av meldingsbokser

### ISSUE THREAD

**Issue by Mikkelinski** [fremtind/jokul#859]
I "byggesonen" på Figma ligger forslag til redesign av meldingsbokser som er mer i tråd med øvrig visuelt design enn de vi har nå. Designforslaget introduserer også ikon slik at vi ikke bare har farge som virkemiddel for å skille meldingstypene (UU)

Mobildesign bør også sees på, men forslaget som er tegnet kan håndtere det godt nok tror jeg.

**Comment by Steinop** [comment]
Den transparente bakgrunnsfargen i de nåværende skissene vil ikke fungere hvis man legger meldingsboksen over tekst. Ellers er disse meldingsboksene mye tydeligere enn de eksisterende.

**Comment by kristineSorensen** [comment]
Bra med ikoner i tilegg til farge. Ser at det i dag er feilmelding over varde-bakgrunn i skjemaet for å melde skade. Vil det være aktuelt å se på hvordan disse fungerer i den sammenhengen, for da kan det bli problematisk med transparent bakgrunnsfarge på meldingsboksen.

**Comment by Mikkelinski** [comment]
Syntes det er uheldig med transparent pga risikoen for feilbruk ja.

Hvor mye forsvinner om vi bare går med ramme og symbol uten fargebakgrunn?

**Comment by Murstam** [comment]
Ja, en ting er transparent på gråtoner, men på farget bakgrunn kan det slå ut litt feil. Skal lage noen forsøk uten farget bakgrunn.

**Comment by Murstam** [comment]
En bedre løsning kan være å sette én fargeverdi som er er lik på de ulike lyse bakgrunnene og én for de mørke bakgrunnene. Meldingsboksene blir mer synlige med bakgrunnsfarge på boksen. https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=10857%3A30108

**Comment by eduardodir** [comment]
Har vi en slutling design på detta? Är även darkmode ivaratatt?

**Comment by Mikkelinski** [comment]
Tror det er litt variasjoner i farge som er ubestemt - men lenken som Joachim posta over er det vi har nå - den ivaretar også dark mode ja. Tror denne kan påstartes, så kan man evt vurdere farge etterhvert om det skjer endringer der.
