### ISSUE TITLE
Menyen flasher på load av portalen

### ISSUE THREAD

**Issue by Mikkelinski** [fremtind/jokul#868]
Når jeg laster portalen (https://fremtind.github.io/jokul/) så flasher menyen når siden lastes før den forsvinner igjen.

+ syntes diamanten animeres altfor fort når jeg scroller vanlig ned siden. Ser ut som en 1-1 forhold til scroll position uten noe delay innebygd. 

(Funnet i Chrome på Mac)

**Comment by piofinn** [comment]
Jeg tror denne bugen ligger i `useAnimatedHeight`-hooken. Den ble sannsysnligvis introdusert av meg i #860. Jeg skal se på den!
