### ISSUE TITLE
Feil: GitHub Actions kjører ikke på PR fra forks

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#881]
**Feilbeskrivelse**
GitHub Actions kjører ikke på pull requests fra forks av repoet.

**For å reprodusere**
Fork Jøkul, gjør en endring, og lag en PR. De automatiske sjekkene vil ikke kjøre som de skal, slik at PRen aldri får klarsignal for merge.

**Forventet oppførsel**
Alle pull requests inn mot Jøkul bør utløse de påkrevde automatiske sjekkene.

**Mer info**
Det er et potensielt sikkerhetsproblem å kjøre actions på pull requests fra forks, siden actions er definert i prosjektfiler. Så vidt jeg kan se, bør de derfor bli kjørt _i forken_ i stedet for i vårt repo. **Det _kan_ altså være så enkelt som at alt fungerer så lenge forfatteren av pull requesten har skrudd på GitHub Actions i sin versjon av repoet.**

**Comment by wkillerud** [comment]
Ser ut som Actions kjører i forken gitt at den blir satt opp med egne tokens og slikt:

- https://github.com/wkillerud/jokul/actions/runs/1217535919
- https://github.com/wkillerud/jokul/actions/runs/1217535922

Det ser dog ikke ut som om PRen blir oppdatert riktig med status. Begge runsene over er ferdig, men status er i skrivende stund _pending_ i PRen.

Kanskje vi trenger integreringsbranch med laxere settings som eksterne bidragsytere kan bruke som target? Så kan PRen reviewes manuelt, merges til `integration` og ta en PR fra den videre inn til main om alt er OK?

**Comment by wkillerud** [comment]
Etter litt diskusjon ønsker vi teste et oppsett med en egen branch `external-contributions` hvor vi henviser pull requests fra forks og hvor vi ikke har CI som en del av bygget av sikkerhetshensyn. For å forenkle vedlikehold setter vi opp en action som jevnlig oppdaterer.

- [ ] Opprett branch `external-contributions` basert på dagens hovedbranch
- [ ] Gjør `external-contributions` protected for å unngå at pull requests fra den til hovedbranch kan slette `external-contributions`
- [ ] Sett opp en Github Action som oppdaterer `external-contributions` nattlig
- [ ] Oppdater reglene for pull requests mot `external-contributions` så vi ikke kjører tasks som skaper problemer med merge
- [ ] Oppdater `CONTRIBUTING` med instruksjoner for pull requests fra forks
- [ ] Undersøk om vi kan sette opp en Github Action som lager en pull request fra `external-contributions` til hovedbranchen hvis den har commits som ikke er i main for å delautomatisere rutinen for maintainers

**Comment by wkillerud** [comment]
@piofinn, får du gjort de nødvendige endringene i Settings for branch protection og regler ved pull request?

**Comment by wkillerud** [comment]
Da har vi prosedyrene på plass, om enn ikke helt optimalt på oppløpet `external-contributions -> main`. Spør en admin om hjelp om du står i en situasjon der en pull request mellom de to branchene står fast i en pending state.
