### ISSUE TITLE
Mobilheader med meny

### ISSUE THREAD

**Issue by Murstam** [fremtind/jokul#884]
På BM har jeg laget et forslag til header og meny for mobil. Jeg har brukt både tekst og ikon til menyen. Selv om hamburgeren er kjent for mange tror jeg at det for noen brukere kan være enklere å forstå med tekst.

Menyen glir inn ovenfra i medium tempo og lukkes raskt. 

Har foreløpig ikke animasjon på ikon. 

Brukeren står på «Forsikring» som er markert med infofarge.

Prototype:
https://www.figma.com/proto/23lrZ2wNVtipKIUCKNvr0x/Forsikringer?node-id=318%3A770&viewport=-20074%2C-3045%2C0.7190404534339905&scaling=min-zoom

**Comment by Mikkelinski** [comment]
Først som slo meg var - burde denne og menyen i portal benytte samme animasjon siden de lener seg på samme uttrykk? Om ikke hastigheten - så samme retning? Føler det er litt av det vi burde prøve få dekket i et slags "animasjonsbibliotek" / retningslinjer fremover.

**Comment by Murstam** [comment]
Absolutt! Både retning og hastighet kan nok være lik. Bytter retning med en gang.

**Comment by Mikkelinski** [comment]
Hastighet tenker jeg man kan utforske litt på - menyen i portalen er jo litt mer i retning "fancy" enn ren funksjonell (føler jeg personlig iallfall), men prøve likt i utgangspunktet og se om man har behov for noe annet kanskje?

**Comment by Murstam** [comment]
Ja, jeg tenker det er et godt utgangspunkt hvertfall.

**Comment by Steinop** [comment]
Tenker at Fremtindlogoen og burgerknappen bør stå på samme sted når menyen dukker opp (også på samme måte som i portalen). Synes ellers det blir litt smør på flesk med både burgerikon og meny. Ville kjørt enten eller i minimalismens navn. Så er spørsmålet om tekst trumfer ikon? 

Fungerer ikke så bra med plasseringen av "meny" i forhold til ikonet som ser ut til å å ha vertikal sentrering i forhold til hverandre. Dette fører til at Fremtind og Meny ikke står på linje. (Løses lett ved å enten fjerne tekst eller burgerikon :)

**Comment by Murstam** [comment]
Jepp, de skal stå på samme sted når menyen åpner seg. Ok, da tror jeg at jeg dropper tekst og bruker bare ikon!

**Comment by gbrownlee** [comment]
Vi lukker denne. Nytt issue kan opprettes hvis det dukker opp konkret komponent.
