### ISSUE TITLE
Accordions: Ny stil

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#888]
I sammenheng med nye inputfelter og dropdowns/select må vi gå gjennom utseende, oppførsel og animasjon for denne komponenten i både dark og light mode.

**Comment by Steinop** [comment]
Even Knutlie på SeOpp får heller ikke assignet oppgaven til seg. Melder tilbake at det ikke nødvendigvis er han som skal utvikle denne. SeOpp-teamet har lagt dette issuet inn i Jira slik at det blir fanget opp.

**Comment by Mikkelinski** [comment]
Disse er lagt inn i Figma - @Steinop vet du noe om hvordan det blir tatt videre av SeOpp?

**Comment by Steinop** [comment]
SeOpp har lagt til dette i sin Jira. Forhåpentligvis får vi assignet oppgaven til noen på SeOpp-teamet når vi får oppdatert brukerne som legges inn i listen på Confluence

**Comment by eduardodir** [comment]
@Steinop Har vi fått något navn å assign till i SeOpp?

**Comment by Steinop** [comment]
Samme status som over. Den avhenger av at listen til @gbrownlee på Confluence oppdateres med relevante navn slik at vi får assignet.

**Comment by Mikkelinski** [comment]
Denne er oppdatert i Figma - trenger utvikling
