### ISSUE TITLE
Spacing på field groups

### ISSUE THREAD

**Issue by Mikkelinski** [fremtind/jokul#893]
For radio buttons og checkboxes er avstandene fra overskrift til første element for liten på "liten header".

https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=11864%3A32298

Her er forslag som legger inn en padding på 8px mellom liten overskrift og første radio/checkbox på compact og 12px på vanlig. Ønsker at dette legges inn i komponenten slik at det blir riktig.

I tillegg - ønsker at vertikal spacing har 12px mellomrom for compact (i dag tror jeg den har 16), slik forslaget viser det.

**Comment by Mikkelinski** [comment]
@Murstam hvis du finner noe som er "mer" riktig - legg det inn her så kan jeg oppdatere issue, men tar forslaget ditt som det endelige for nå.

**Comment by piofinn** [comment]
I dag er avstanden her lagt inn i `Label`-komponenten, siden den har vært den samme for alle komponenter som bruker den. Det er sikkert en idé å ta det ut derfra og inn i komponentene som bruker den, i hvert fall i kode.

**Comment by piofinn** [comment]
Siden vi bær gjøre endringer i alle komponentene når vi fikser denne har jeg laget enda et issue #900 for det. Er fint å la dette stå fortsatt for å vise sammenhengen 😊
