### ISSUE TITLE
Responsive main menu

### ISSUE THREAD

**Issue by eduardodir** [fremtind/jokul#894]
**Is your feature request related to a problem? Please describe.**
The problem is that some links can. be out of viewport and then you do not know there is more content.

**Describe the solution you'd like**
A responsive breaking menu. The links should always be in viewport.

**Describe alternatives you've considered**
An indicator that there is more content out of  viewport.

**Additional context**
<img width="1653" alt="Screenshot 2020-04-13 at 21 56 44" src="https://user-images.githubusercontent.com/56429532/79155828-0fce3d80-7dd2-11ea-985c-fc52874c0be7.png">

**Comment by eduardodir** [comment]
The top menu, mode switcher are not either breaking in a good way
<img width="301" alt="Screenshot 2020-04-22 at 14 24 40" src="https://user-images.githubusercontent.com/56429532/79981812-96a3aa00-84a5-11ea-9e7d-71245cea60d7.png">

**Comment by eduardodir** [comment]
Heidi has a proposal she will show up wednesday

**Comment by Stormoen** [comment]
Foreslår følgende: Bruke megamenyen til de tre hovedområdene - for å ivareta flaten med litt boldere profiluttrykk og animasjon, og legge til en oversikt når man kommer inn på undersidene med sidemeny. Det er mer oversettelig til mobilflate, se skisser. Har ikke brukt tid på å designe disse oversiktskortene - ville lufte forslaget først.
![Megameny](https://user-images.githubusercontent.com/64519175/80568687-c0a22280-89f7-11ea-81db-06f8b8e73e3a.png)
![Komponentside - oversikt](https://user-images.githubusercontent.com/64519175/80568708-c6980380-89f7-11ea-8047-8e773519d410.png)
![Mobil-Megameny](https://user-images.githubusercontent.com/64519175/80569419-2e028300-89f9-11ea-9f69-8b591e195de6.png)
![Mobil-Komponentside - oversikt](https://user-images.githubusercontent.com/64519175/80569428-31960a00-89f9-11ea-848a-a052f3589467.png)
![Mobil-Komponentside - komponent](https://user-images.githubusercontent.com/64519175/80569430-335fcd80-89f9-11ea-965a-4cb9be5dc714.png)

**Comment by Stormoen** [comment]
Har laget en oppdatert versjon etter gjennomgangen i går her:
https://www.figma.com/file/dWhCsnlMAmJEBPyGnRrse5RM/J%C3%B8kul-portalen?node-id=3368%3A2

**Comment by Stormoen** [comment]
Hei! Da har jeg oppdatert skissene etter møtet på mandag: https://www.figma.com/file/dWhCsnlMAmJEBPyGnRrse5RM/J%C3%B8kul-portalen?node-id=3990%3A12837

**Comment by vegardsoerlie** [comment]
@piofinn Ser du har den assigned, men er ikke dette fikset? Klarer ikke reprodusere det i portalen nå. Er på tur gjennom issues for å sjekke at jeg ikke poster dupe og kom borti denne.

**Comment by wkillerud** [comment]
Jeg rydder i gamle issues og synes det virker som om dette har blitt løst på et vis, men at saken ikke har blitt lukket. Den kan gjenåpnes dersom det gjenstår noe :)
