### ISSUE TITLE
Secondary menu toggle

### ISSUE THREAD

**Issue by eduardodir** [fremtind/jokul#895]
**Is your feature request related to a problem? Please describe.**
In some cases, you have a limited viewport for the portal and you might want to have some IDE on the side at the same time then, the side menu becomes a disturbance, it would be good if one could be able to toggle it.

**Describe the solution you'd like**
A toggle menu secondary menu hamburger on the top left

**Describe alternatives you've considered**

**Additional context**
<img width="1678" alt="Screenshot 2020-04-13 at 22 03 16" src="https://user-images.githubusercontent.com/56429532/79156485-46f11e80-7dd3-11ea-871b-1a19f8a11fa5.png">

**Comment by eduardodir** [comment]
Gått igenom med Heidi, vi kallar in till en genomgång för å ta detta vidare.

**Comment by eduardodir** [comment]
Heidi har ska ta fram skisser och jag har implementerat ett exempel.

**Comment by piofinn** [comment]
Closed by #990
