### ISSUE TITLE
Inverted color darkgrey in example box?

### ISSUE THREAD

**Issue by eduardodir** [fremtind/jokul#897]
**Is your feature request related to a problem? Please describe.**
Because black is one of our primary colors for when something is selected, hover, marked, in our examples, they just blend into the "black" inverted color. From what I have seen on other Figma designs, the background is usually more dark grey than black.

**Describe the solution you'd like**
I would like the example box background color inverted color to be more black grey to clearly see our components black colors.

**Additional context**
<img width="625" alt="Screenshot 2020-04-13 at 22 31 50" src="https://user-images.githubusercontent.com/56429532/79158974-8b7eb900-7dd7-11ea-9089-662ff6c23a14.png">

**Comment by Mikkelinski** [comment]
Setter denne til on hold siden komponentene våre er i usync akkurat nå - se på eksemplene på nytt når nytt design er implementert.

**Comment by eduardodir** [comment]
@Mikkelinski ligger det någon issue som löser "komponentene våre er i usync"?

**Comment by Mikkelinski** [comment]
Ikke et overordnet et nei - men tror det er enkeltissues som dekker hvert tilfelle

**Comment by gbrownlee** [comment]
Løses på en annen måte ifm. dark mode-arbeid.
