### ISSUE TITLE
Oppdatere spacing på labels i komponentene

### ISSUE THREAD

**Issue by piofinn** [fremtind/jokul#900]
Avstanden mellom `Label` og noen av komponentene er endret i design, og må oppdateres tilsvarende i kode. Per i dag ligger disse avstandene som margin i `Label`-komponenten, så min anbefaling er å benytte denne anledningen til å flytte dette over i hver enkelt komponent.

Oversikt over riktige avstander finnes her: https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=11864%3A32298

**Comment by Steinop** [comment]
Oppdatert til denne - dersom vi skal ta utgangspunkt i horisontal alignment:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=12360%3A33337

Work in progress …

**Comment by eduardodir** [comment]
> Oppdatert til denne - dersom vi skal ta utgangspunkt i horisontal alignment:
> https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=12360%3A33337
> 
> Work in progress …

Ser bra ut, men vi extend exemplet med select, checkbox å textarea

**Comment by eduardodir** [comment]
Denna kan startas efter en nogran genomgång av samtliga komponenter som brukar label

**Comment by Murstam** [comment]
Men trenger vi å endre høyde på radio og check? Her er et forslag med med samme label, uten å endre høyde på de. https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=12726%3A34342

**Comment by Steinop** [comment]
Fordelen med å endre høyde på radio og check er at man samtidig slipper å forholde seg til spacingen mellom disse når man lager en gruppe med check/radiobuttons. De kan praktisk talt stables som Lego

**Comment by Mikkelinski** [comment]
Se Jøkul biblioteket i figma for å se hvordan spacing er blitt løst (large 16 medium 8 small 4 for desktop og 12,8,4 for compact). Det er lagt inn spacing på radio og check elementer slik at de er 48 / 40 i høyden (desktop compact).

**Comment by Steinop** [comment]
Godkjent fra meg @Mikkelinski

**Comment by piofinn** [comment]
Spacing for labels blir værende i `Label`-komponenten med den nye løsningen, men oppdateres til verdiene nevnt over.
