### ISSUE TITLE
Messagebox-komponenten: Ønsker å ha title valgtfritt

### ISSUE THREAD

**Issue by eknuff** [fremtind/jokul#902]
Idag er flere komponenter koblet opp mot markdown for å gjøre det enklere for å få ut meldinger og for de funksjonelle slik de skal kunne slippe å gå igjennom publisering. Vi bruker [markdown ](https://github.com/rexxars/react-markdown). 

Problemet er dette når vi ikke setter tittel:
![image](https://user-images.githubusercontent.com/51021658/79236066-bf57ee00-7e6c-11ea-800b-c733834910f5.png)

Men vi har også hvor det ikke blir satt tittel i boksen i det hele tatt.
![image](https://user-images.githubusercontent.com/51021658/79236899-d5b27980-7e6d-11ea-966d-6fe512248f28.png)

Så det vi ønsker er å ha tittel som valgfritt i komponenten `title?:string` og en sjekk på det . Evt, ha flere komponenter, men dette vil ta en god del tid fra vår side.

**Comment by Mikkelinski** [comment]
@eknuff 
er dette issuet like aktuelt med ny utforming på meldingsboksene? https://fremtind.github.io/jokul/komponenter/messagebox

Designet på boksen er endret - tror fortsatt ikke tittel er lagt som valgfritt men jeg tror heller ikke det er ønskelig å ikke ha tittel (ikon og farge ikke nødvendigvis er godt nok til å kommunisere hva slags type melding det dreier seg om e.g. i nedereste eksempel kunne overskrift vært "Lagring av kontaktinformasjon" eller lignende)

**Comment by eknuff** [comment]
Jepp det vil fortsatt gjelde, dette er for at teksten som står fra adminsystemet i dag kommer inn i body,
![image](https://user-images.githubusercontent.com/51021658/79831054-f9fae280-83a6-11ea-8053-19b9c800a65e.png)

**Comment by Mikkelinski** [comment]
Ok - fra designperspektiv er det ikke så vanskelig å strippe header og beholde bare brødtekst, men vet ikke helt hvordan det må løses i kode. Vil helst at Header er recommended - men om det er mulighet å fjerne så tror jeg ikke vi bryter noe. Blir litt mer tricky i figma derimot.

**Comment by CamillaDahlstroem** [comment]
Til info: Vi i Flyt har også ønsket oss optional header på meldingsboksene. Vi har rett og slett ikke alltid plass til både header og brødtekst 😅
