### ISSUE TITLE
Samlingsside for funksjonsikoner

### ISSUE THREAD

**Issue by MonaUF** [fremtind/jokul#908]
**Is your feature request related to a problem? Please describe.**
Savner en samling over ikonene som brukes i dag.

**Describe the solution you'd like**
En egen side i Figma og i Portalen

- [ ] Figma
- [ ] Portalen

**Comment by Mikkelinski** [comment]
har laget en samleside for ikoner i biblioteket - men kan flytte ikoner dit etter at vi samler de i en page på byggesonen først

**Comment by eduardodir** [comment]
Vem kan ta över denna?

**Comment by Mikkelinski** [comment]
De er lagt i Figma per nå - for å opprette en ny side i portalen trenger jeg utviklerhjelp men det er heller ikke like viktig som å få de ut i Figma i første rekke. Vet ikke om de faller under komponenter eller hvor de bør plasseres i kontekst av portalen? @eduardodir

**Comment by Mikkelinski** [comment]
Issue solved
