### ISSUE TITLE
Ferdigstille MessageBox-komponenten i Figma

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#910]
Designerne har behov for nye MessageBox komponent i Figma-biblioteket.
(Se også issue #904 ifm dette)

Siste versjoner ligger her i light og dark mode:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=10774%3A26695

**Comment by Steinop** [comment]
Gammel versjon (WIP) ligger her i biblioteket:
https://www.figma.com/file/Wh8Gfnesn25shH31sKyIaT/J%C3%B8kul-bibliotek?node-id=24%3A548

**Comment by Mikkelinski** [comment]
Kan fikse det i dag - eneste spørsmål jeg har er knyttet til Opacity, hva landet vi på der?

**Comment by Steinop** [comment]
@piofinn har en smart oppskrift på det ved å lage en funksjon av hovedfargen (hovedfarge med x% metning og x% lyshet). Det funker i kode men usikker på hvordan vi får det inn i Figma.

Mener disse er laget med det utgangspunktet: 
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=10902%3A30405

**Comment by piofinn** [comment]
> @piofinn har en smart oppskrift på det ved å lage en funksjon av hovedfargen (hovedfarge med x% metning og x% lyshet). Det funker i kode men usikker på hvordan vi får det inn i Figma.

@Steinop og @Mikkelinski Det er ganske greit å gjøre i Figma (var der jeg testet det først!) hvis man bytter fargemodus til HSL:
<img width="277" alt="Skjermbilde 2020-04-21 kl  14 34 38" src="https://user-images.githubusercontent.com/25739615/79866589-4a8d3280-83dd-11ea-9a99-71a13fb48acc.png">

Hvis man tar utgangspunkt i en av meldingsfargene får man riktig farge ved å sette `L` til `97` for de lyse boksene og `5` for de mørke 😊
<img width="265" alt="Skjermbilde 2020-04-21 kl  14 36 54" src="https://user-images.githubusercontent.com/25739615/79866839-aa83d900-83dd-11ea-8ec3-fe1f56f903d9.png">

**Comment by eduardodir** [comment]
@Steinop är ikke dessa redan implementerade???

**Comment by Steinop** [comment]
Det er de @eduardodir  You may close the case 👏
