### ISSUE TITLE
Diverse småfeil i Figma-komponentene

### ISSUE THREAD

**Issue by CamillaDahlstroem** [fremtind/jokul#911]
Jeg har notert meg noen små uoverensstemmelser mellom komponentene i Figma og Jøkul, og tenkte jeg skulle si i fra. Vet at det snart kommer nye versjoner av input, select, osv, så er kanskje ikke alt som blir like relevant da. Likevel:

- "radio-selected-mobile" har ikke bold tekst.
<img width="222" alt="Skjermbilde 2020-04-21 kl  15 15 44" src="https://user-images.githubusercontent.com/11536996/79870326-187ecf00-83e3-11ea-9fbb-1ed96afbe574.png">

- Og apropos punktet over: Det er fremdeles mange av komponentene i Figma som er navngitt med "Mobile" i stedet for "Compact". Det skaper litt forvirring.

- Placeholder-teksten i "Dropdown-compact" er svart, ikke grå slik som i tekstfelt og datepicker. Det gjør at de ser litt rare ut sammen.
<img width="802" alt="Skjermbilde 2020-04-21 kl  15 16 02" src="https://user-images.githubusercontent.com/11536996/79870552-71e6fe00-83e3-11ea-85d3-66c4ed295735.png">

- Jeg tror det mangler en dropdown med valgt verdi som ikke også har fokus. Jeg finner kun denne med blå og for tykk linje:
<img width="391" alt="Skjermbilde 2020-04-21 kl  15 22 10" src="https://user-images.githubusercontent.com/11536996/79870963-04879d00-83e4-11ea-88da-f109dd0c3cfb.png">

- Datepicker i Figma har ikke kalenderikon. Her ser man også at dropdown med valgt verdi ikke har riktig state (skulle vel vært bold)?.
<img width="413" alt="Skjermbilde 2020-04-21 kl  15 24 21" src="https://user-images.githubusercontent.com/11536996/79871139-3c8ee000-83e4-11ea-94c6-f9de4494227e.png">

- Det hadde forresten også vært suupert om buttons, radio- og check-bokser kunne hatt en invertert modus i Figma også <3 Jeg flipper fargene manuelt når jeg må, men er fint å slippe.

- Og det siste poenget mitt er at det litt rart at vi har denne bakgrunnsfarge-versjonen av tekstfeltene osv i Figma når det ikke er den som ligger i dagens kode. Jeg fjerner alle bakgrunnsfargene manuelt i skissene mine for å ikke forvirre utviklerne. 

Dere er flinke! Stå på! Gleder meg til de nye inputfeltene :D

**Comment by Mikkelinski** [comment]
Supert at du har funnet avvik/feil - er så lett at de glipper mellom stolene. Akkurat de siste dagene har vi laget masse komponenter som kommer til å utgjøre en ny stor "breaking" change i Figma. Inkludert her er nye radio og checkbox komponenter (også i inverted / dark mode) ++.

Jeg skal gå igjennom at de feilene du nevner her rettes opp i det som kommer.

**Comment by Mikkelinski** [comment]
Radio label rettet opp
Compact navngivning fikset
Dropdown er WIP
Datepicker er WIP
Dark mode på radio/check done
Bakgrunnsfarge er done

Lukker issue når vi har release av figma biblioteket

**Comment by eduardodir** [comment]
@Mikkelinski hur ofta görs relese av figma bibliotek?

**Comment by Mikkelinski** [comment]
Det varierer - ingen fast praksis, men disse er ute nå etter gårsdagens release så jeg lukker saken.
