### ISSUE TITLE
Table - fjerne innrykk på mobil

### ISSUE THREAD

**Issue by Murstam** [fremtind/jokul#913]
Innrykk på tekst bør droppes for table på mobil. Da vil vi få brukt bredden på skjermen mer effektivt og komponenten vil fungere bedre på smale flater.

**Comment by Murstam** [comment]
Jeg vet faktisk ikke hvor denne komponenten kommer fra eller hvor designskissene til denne ligger. Jeg tenker det gjelder alle plasser man bør være plasseffektiv, så sikkert interne løsninger også. 

Når jeg tenker meg om så bør vi heller bruke den responsive tabellen på det tilfellet jeg oppdaget her. Så da er det kanskje ikke så relevant for BM likevel.

**Comment by Murstam** [comment]
Men ja, sikkert accordions også. Jeg tenker at man i de fleste tilfeller på smale skjermer bør begrense innrykk. De stjeler mer enn de tilfører.

**Comment by eduardodir** [comment]
Kan man ta fram en visuell översikt över alla komponenter detta gäller och hur det skall vara?

**Comment by Steinop** [comment]
Referanse til hvordan tabeller er brukt i Flyt (i tillegg til alle andre komponenter):
https://www.figma.com/file/n0vTMvp78LHl9khqCo9zSo/Flyt.Mai.2020?node-id=1898%3A0
