### ISSUE TITLE
Jøkul default feilsider

### ISSUE THREAD

**Issue by eknuff** [fremtind/jokul#919]
I dag finnes det litt forskjellige feilsider på kryss og tvers av applikasjoner. Ved forrige snakk så pratet vi om vi skulle lage en standard på dette. Her er ett par eksempler på hvordan vi har det i seopp idag:

Her er ett eksempel på når noe har virkelig gått galt: 
![image](https://user-images.githubusercontent.com/51021658/80123175-d2666e80-858e-11ea-9829-83d1f66dbacd.png)

Mens f.eks hvis det bare ikke eksisterer i det hele tatt så har vi: 
![image](https://user-images.githubusercontent.com/51021658/80122338-b31b1180-858d-11ea-92c6-86d752969cc8.png)

**Comment by piofinn** [comment]
Hei! @idalower og @stiansuren jobber med utkast til standardiserte feilsider i to versjoner. Ta gjerne kontakt med dem for å komme med innspill 😊

**Comment by Mikkelinski** [comment]
Denne er in progress - men får ikke assigned ida og stian

**Comment by eduardodir** [comment]
Följer upp dem.

**Comment by stiansuren** [comment]
Ida og jeg tar med problemstillingen i Kreativ time 15. mai.

**Comment by gbrownlee** [comment]
@idalower og @stiansuren har utformet noen skisser (vedlagt). Det er mulig de tar tak i denne igjen etter noen utestående leveranser, men denne er da klar til utvikling.

[Figma-skisser](https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=12512%3A33699)

![06cd35e3-69d0-4772-a54b-5bddc8fdd58c](https://user-images.githubusercontent.com/888229/81947544-f9014d80-9600-11ea-91a7-f6e10ec07749.jpg)
![610e91c2-adf0-4c85-bb70-6debae1c46ba](https://user-images.githubusercontent.com/888229/81947545-fa327a80-9600-11ea-99ee-a4f6884331ed.jpg)
![b4017b90-fa66-45ed-9fd6-0c7ddb155620](https://user-images.githubusercontent.com/888229/81947547-fa327a80-9600-11ea-86fd-ace82b9fb16d.jpg)

**Comment by kristineSorensen** [comment]
Skal ta med disse skissene på designkritikk i morgen.
