### ISSUE TITLE
Datepicker - oppdatere med nye input / select

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#925]
Komponenten må oppdateres med nye input/selct i tillegg til kalenderikon.

**Comment by Steinop** [comment]
Utkast til oppdatert datepicker:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=13670%3A713

Her ligger tre frames på rekke: 
1. Sammenstilling med Select + Datepicker
2. Fra-til datepicker
3. Datepicker med og uten skygge

Utfordringen har vært å knytte velgeren opp mot inputfeltet slik man kan se i skissene ovenfor. Ved å gi litt space mellom input og datepicker og legge på en liten pil eller "halv diamant" knyttes disse bedre sammen.

Kommenter gjerne 😁

**Comment by Steinop** [comment]
Siste versjoner av Datepicker (normal) i Dark og Light mode ligger her:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=10761%3A1895

Har lagt inn spacing i kalendermenyen slik at den kan stables rett under kalenderinputfeltet.

Videre må denne skissen oppdateres i komponentbiblioteket

**Comment by Steinop** [comment]
Datepicker med animasjon:
https://vimeo.com/413605435/214e4229c5

Figmaprototype (Trykk bokstaven R for å nullstille):
https://www.figma.com/proto/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=13719%3A6848&viewport=278%2C-4726%2C0.48899295926094055&scaling=min-zoom

NB:
Litt ujevn overgang når man bytter måned i animasjonen pga noe som henger igjen fra en tidligere prototype. Testet først en annen vri der måneden ble animert opp (på samme måte som i Select) men det fungerer bedre når hele måneden animerer inn samtidig fra den siden pilen peker.

Hvordan tror du dette vil fungere mot NRKs Core-komponent @piofinn ?

**Comment by eduardodir** [comment]
Är detta kritiskt eller är det mer än "facelift" eller något annat?

**Comment by Mikkelinski** [comment]
Grafisk løft som passer på at vi oppdaterer den i tråd med de andre komponentene vi oppdaterer nå - gir ikke mye mening å ha den som et etterslep når vi først fresher opp inputs / selects øvrig.

**Comment by piofinn** [comment]
@Steinop Overgangene ser bra ut! Men de vil nok igjen innebære at vi skriver hele komponenten selv. Det er såpass mange ting som er foreslått nå som vil kreve det at det kanskje er verdt å se på, men det kommer til å ta _mye_ utviklingstid å få på plass brukervennlighet og UU, så vi må vurdere det nøye.

**Comment by Steinop** [comment]
Thanks @piofinn. Du får se hva som er mulig i første omgang mht utseende. Hadde vært fint å hatt vår egen komponent så slipper vi samtidig avhengighetene til NRK mht bugfix 😁

**Comment by eduardodir** [comment]
Jag kan ikke se hur vi ska få möjlighet och göra en så stor ändring nå på den komponenten som inte ens är vår. Kan vi nöja oss med lite facelift så länge?

**Comment by Steinop** [comment]
Vi kjører en pragmatisk tilnærming til denne hvor vi prioriterer det visuelle. Der det er mulig å få til smooth animasjon gjør vi det. Spørsmålet på lang sikt er om vi skal være avhengige av en core component som ikke blir oppdatert og ikke lar seg tilpasse det som skal være vårt (animerte) uttrykk.
