### ISSUE TITLE
Dropdown i meny

### ISSUE THREAD

**Issue by Murstam** [fremtind/jokul#926]
På BM har man som innlogget bruker mulighet til å bytte mellom ulike bedrifter. Det hadde vært fint å fått integrert en slik dropdown i headeren. Dropdownkomponenten vi har egner seg egentlig ikke til det.

Skisse: https://www.figma.com/file/23lrZ2wNVtipKIUCKNvr0x/Forsikringer?node-id=160%3A0

**Comment by Steinop** [comment]
Er dette med tanke på at den mister "luftigheten" som den har i Figma-skissen, eller er det andre issues med den nye select-komponenten?

**Comment by piofinn** [comment]
Jeg lurer også på det @Steinop lurer på, men uavhengig av det tror jeg kanskje vi her uansett snakker om to forskjellige komponenter (ref. diskusjonen rundt dropdown/select): I mine øyne er det dere har i BM en dropdown-**meny**, mens det vi har i Jøkul er et skjemaelement med samme funksjon som radioknapper (men med flere valg).

Kan dette være et godt utgangspunkt for å finne et mønster for enkle menyer? Så langt har vi jo egentlig bare laget omfattende menyer i det oppdaterte designet (megamenyene og sidemenyen i portalen). Hva tenker dere andre @Mikkelinski @Steinop @Murstam ?

**Comment by Steinop** [comment]
Det er et godt poeng @piofinn. De øvrige menyknappene (både i Jøkul og i BM) har en tykk strek under på hover. Kanskje man kunne brukt noe av det samme mønsteret med en tykk strek som animeres ned med valgene listet opp vertikalt over streken. Litt inspirert av Select eller megamenyen i Jøkul portalen?

**Comment by Murstam** [comment]
Ja, tror dette er en annen komponent, dropdown-meny. 

Ja, dette kan sikkert være et godt utgangspunkt for enkle menyer. 

Det tror jeg at jeg må se for å forstå Stein Olav 😅

**Comment by Murstam** [comment]
Men dropdownalternativene kan kanskje presenteres på samme måte som den vi har?

**Comment by Steinop** [comment]
Lager en skisse på det jeg har i hodet @Murstam - lettere å se for seg med noe visuelt 😁
Prøvde meg forøvrig med en luftigere variant av Select med outline på hover. Den matcher ikke helt de andre menyelementene men var en kjapp test på gjenbruk av Select: https://www.figma.com/proto/23lrZ2wNVtipKIUCKNvr0x/Forsikringer?node-id=1216%3A324&viewport=-5507%2C-2044%2C0.2579460144042969&scaling=min-zoom

**Comment by Murstam** [comment]
Nice! Men det er kanskje greit at staten ligner mer på navigasjonselementene i menyen? Sjekk: https://www.kron.no/

**Comment by Steinop** [comment]
Ja, var det jeg mente. Interessant løsning på kron.no hvis man har begreper som er uklare for en bruker. Her er et kjapt grovutkast på det jeg prøvde å si ovenfor: https://www.figma.com/file/23lrZ2wNVtipKIUCKNvr0x/Forsikringer?node-id=1244%3A1729

**Comment by eduardodir** [comment]
Behövs en designkritik att komma i mål med denna?

**Comment by Murstam** [comment]
Ikke nødvendigvis, men den krever mer arbeid.

**Comment by eduardodir** [comment]
@Murstam det är 3 personer assigned, "mer arbeid" av vem å hvad borde vi kunna få framlyst mer i dessa typer av issues som berör en helhet.

**Comment by Murstam** [comment]
De som er assigned er bare de jeg ønsket tilbakemelding fra. Nå jobber jeg med et par alternativer på styling og har fått litt tilbakemeldinger fra Stein Olav. Tenker jeg jobber mer med denne i morgen og har noe vi kan ta stilling til da.

**Comment by Murstam** [comment]
Etter samtale med Stein Olav har vi valgt å se nærmere på disse to alternativene: https://www.figma.com/file/23lrZ2wNVtipKIUCKNvr0x/Forsikringer?node-id=1373%3A515

Skal lage prototype i Figma så får vi se hva som passer oss best.

**Comment by Murstam** [comment]
Har laget prototype på den ene retningen, men ikke den andre. Kommer til å vente litt med denne.

**Comment by CamillaDahlstroem** [comment]
Inspill: I Flyt har vi også behov for dropdown-menyer i headeren vår. Vi lagde noen egne for lenge siden (i høst) basert på selectene som fantes da. Hovedgrunnene til at vi gjorde dette var at vi ikke ønsket å bruke label over menyene i headeren vår, og i selecten var (er?) label påkrevd. 
Her er dette rotete hjørnet av løsningen vår in all it's glory:

<img width="419" alt="Skjermbilde 2020-05-28 kl  10 20 59" src="https://user-images.githubusercontent.com/11536996/83117374-45eb2680-a0cd-11ea-906e-e1f4bd7401ba.png">

**Comment by wkillerud** [comment]
Er dette samme problemstilling som #2328 (sekundærtekst i Select)?

**Comment by onordbo** [comment]
Foreldet.
