### ISSUE TITLE
text-input-react: eksponere onkeydown

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#927]
**Er ønsket tilknyttet et problem? Fortell oss mer!**
Per nå tar vi i bruk ref med eventlistener for å lytte etter keystrokes. 

**Beskriv løsningen du ønsker**
Ønsker eksponering av onkeydown for å slippe å ta i bruk ref

Kan det være aktuelt, er det evt en grunn til at det ikke er eksponert?

**Comment by lfbergee** [comment]
Hvis du skal bruke den til å formatere et inputfelt, så mener jeg at det er noen quriks med det på android eller ios, med mindre det relativt nylig er fikset hvor cursoren ikke henger med. Så formatering burde skje på keyup (om jeg husker rett).

**Comment by eduardodir** [comment]
Formatering över lag må vi ta fram mer principer och riktlinjer, för å underlätta för de som skall bruka vårt DS, ligger i tråd kring Label diskussionen som drog igång, om man tar det ett steg vidare vilket vi bör göra.
