### ISSUE TITLE
Radiobutton: Kuttet i topp under animasjon

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#934]
**Describe the bug**
Ytterste sirkel i radiobutton mangler en pixel slik at den blir kuttet i toppen. Dette skjer under animasjon når man aktiviserer en radiobutton.

**Expected behavior**
Sirkelen skal være helt rund hele veien 😁

**Desktop (please complete the following information):**
-   OS: Mac
-   Browser Chrome
-   Version [e.g. 22]

**Comment by piofinn** [comment]
Ser ut som dette er spesifikt til Chrome. Skal se nærmere på det. Men vi burde kanskje gå gjennom animasjonene på radio buttons generelt? De begynner å føles litt utenfor resten av systemet

**Comment by Steinop** [comment]
Enig vedr animasjonene @piofinn. Vi bør i hvert fall fjerne overgangen fra diamantform til sirkel i animasjonen. Mulig blå på hover er på sin plass her også men det er nok litt utenfor dette issuet.

Kanskje det er bedre å la sirkelen vokse fra 1-2 px istedenfor animasjonen her. Henger mer på greip med innrammingen på input/select.

**Comment by Steinop** [comment]
Opprettet nytt issue på visuell oppdatering av komponentene: #938

**Comment by Steinop** [comment]
Lukker dette issuet - viktig at dette tas hånd om i ny versjon av radiobutton.
