### ISSUE TITLE
Dividerline: Fjernes fra Jøkul

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#935]
Brukes komponenten i noen grad?
Har vi behov for dividerline i våre løsninger eller bruker vi primært blank space?

Hvis det er behov for dividerline foreslår jeg å fjerne animasjon fordi dividerlinens funksjon er å markere et skille - ikke tiltrekke seg oppmerksomhet.

**Comment by Mikkelinski** [comment]
Er veldig enig i denne - om den skal forbli en komponent bør den være en enkel linje uten ytterligere dekorasjon.

**Comment by eduardodir** [comment]
Kan vi få fram tydliga exempel där dividerline har ett bruk? Kanske fråga runt de olika teamen? Bruket må dokumenteras å.

**Comment by Steinop** [comment]
Ingen tilbakemeldinger på denne. Foreslår at vi fjerner komponenten fra Jøkul og lukker dette issuet. OK?

**Comment by gbrownlee** [comment]
Denne kan saneres ved å fjernes fra portalen. Sorry, @lfbergee...
