### ISSUE TITLE
Buttons: Blå farge på hover

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#936]
Nå som vi innfører blå hover på alle andre komponenter:
1. Bør vi gjøre det samme på primær, sekundær og tertiær?
2. Bør vi også innføre en blå versjon av primærknappen for tydeligere call to action?

**Comment by eduardodir** [comment]
Föreslår å bara skissa hur det skulle se ut på alla varianter.

**Comment by Steinop** [comment]
Allerede gjort:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=10747%3A22
😁

Fargen bør fade over eller skifte på en smooth måte. Foreslår å teste fade fra sort til blå på hover rett i kode først.

**Comment by eduardodir** [comment]
Är detta godkänt för utveckling?

**Comment by Steinop** [comment]
Nei. Venter på tilbakemeldinger på dette.
Når vi er enige om dette kan den endres 😁

**Comment by Steinop** [comment]
Kommentarer til dette issuet @Mikkelinski @Murstam @piofinn?

**Comment by Murstam** [comment]
Henger i teorien godt sammen med måten vi har brukt blå på som hover på andre komponenter. Bare det ikke oppleves for blinkete?

Tror ikke vi skal legge til blå knapp, men heller vurdere å erstatte den sorte. Blir fort rotete med for mange knapper.

**Comment by Steinop** [comment]
Fikk samme spørsmål fra @Mikkelinski vedr blinking. 
Ser ikke for meg at det blir mer blinkete på knappene enn på andre komponenter. Blir bare en ekstra tydeliggjøring på hover.

Foreslår at vi venter med å evt lage blå knapp til vi ser behov for det.

**Comment by Mikkelinski** [comment]
Denne er oppdatert i Figma - trenger utvikling

**Comment by Mikkelinski** [comment]
@espkva ser du fortsatt på denne?
