### ISSUE TITLE
Progressbar: Endre til blå?

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#937]
Grønn farge indikerer normalt suksess. Vil det være mer naturlig å bruke blå farge?
Man vet ikke om noe er lastet (med suksess) før det er lastet 100%

**Comment by eduardodir** [comment]
Blå färg vid upload å grön vid success, samt röd vid error, låter mer naturligt.

**Comment by Mikkelinski** [comment]
Skeptisk til denne komponenten as is - har den en funksjon i biblioteket eller er det noe som bare har blitt innlemmet uten å reflektere rundt bruk?

**Comment by piofinn** [comment]
Tror den ble laget for å tilfredsstille et behov i AHV for å vise fremgang i skjemautfylling. Kanskje den skal få lov til å leve hos dem i stedet hvis vi ikke har noe generelt behov ennå?

**Comment by Steinop** [comment]
Hvis vi fjerner komponenten fra Jøkul: Har vi et arkiv eller en oversikt noe sted over hvilke komponenter / snowflakes om brukes ute i prosjektene? Nyttig å ha en oversikt slik at vi får en indikasjon på hvilke komponenter som evt skal tas inn i Jøkul.

**Comment by eduardodir** [comment]
Så detta är igentligen en Snowflake?

**Comment by Steinop** [comment]
Det er et snowflake med mindre det er relevant for andre prosjekter?
Noen som har forslag til hvordan vi arkiverer og holder oversikt over snowflakes?

**Comment by Steinop** [comment]
Foreslår at vi fjerner komponenten og lukker dette issuet. OK?
Har vi et sted snowflakes og historiske komponenter kan lagres?

**Comment by gbrownlee** [comment]
> Foreslår at vi fjerner komponenten og lukker dette issuet. OK?
> Har vi et sted snowflakes og historiske komponenter kan lagres?

Vi ønsker å bruke denne på filopplaster. Den er derfor ikke et snowflake og bør videreutvikles/endres.

**Comment by lfbergee** [comment]
Denne fjernes nok fra AHV i design refresh. Behovet står enda, men denne komponenten trenger nok litt mer kjærlighet for å løse vårt problem.

**Comment by piofinn** [comment]
Frem har cirka tusen fremdriftsindikatorer 😅 Kanskje samkjøre litt med dem? Se f.eks. presentasjonen til Marius fra forrige deletime: https://www.figma.com/file/gNEaoVuI1t7taOvrLri5Uc/Presentasjoner-og-annet?node-id=1%3A17

Jeg tenker også på blogg-/magasinnettsteder der man har en indikator på hvor langt man er kommet i en artikkel. De pleier å ha en fin balanse mellom synlighet og diskresjon 😊

**Comment by Slaine2** [comment]
Jeg tilpasset versjonene av Marius litt. Tynnere linjer og endret til blå i stedet for den svarte fremdriftslinjen.
Viser fremgang bedre, ser mer positiv ut og er ikke like tung.
![Skjermbilde 2020-10-19 kl  10 05 47](https://user-images.githubusercontent.com/64286523/96418369-f54aa600-11f2-11eb-9d62-cad2c9cf9ae6.png)

**Comment by Slaine2** [comment]
Jeg gjorde det samme for kakediagrammet og en versjon som muligens kunne endres, hvor antall trinn er synlige.
![Skjermbilde 2020-10-19 kl  10 06 13](https://user-images.githubusercontent.com/64286523/96418462-0e535700-11f3-11eb-9402-a9c5f93a515f.png)

![Skjermbilde 2020-10-19 kl  10 06 19](https://user-images.githubusercontent.com/64286523/96418479-16ab9200-11f3-11eb-96cb-930b43b87cde.png)

**Comment by Slaine2** [comment]
Jeg gjorde det samme for kakediagrammet og en versjon som muligens kunne endres, hvor antall trinn er synlige.

![Skjermbilde 2020-10-19 kl  10 06 13](https://user-images.githubusercontent.com/64286523/96418601-4c507b00-11f3-11eb-9365-aaa92be695f7.png)

![Skjermbilde 2020-10-19 kl  10 06 19](https://user-images.githubusercontent.com/64286523/96418616-56727980-11f3-11eb-84b3-55054a3a5ca1.png)

**Comment by Slaine2** [comment]
Jeg gjorde det samme for kakediagrammet og en versjon som muligens kunne endres, hvor antall trinn er synlige.

![Skjermbilde 2020-10-19 kl  10 06 13](https://user-images.githubusercontent.com/64286523/96418669-6d18d080-11f3-11eb-8a0f-4e2472617307.png)

![Skjermbilde 2020-10-19 kl  10 10 02](https://user-images.githubusercontent.com/64286523/96418677-7013c100-11f3-11eb-92b2-ab870b06564f.png)


Hvordan liker du?

**Comment by Steinop** [comment]
@Slaine2: Har du en lenke til Figma? Vanskelig å få inntrykk av størrelsesforhold her 😁

**Comment by Slaine2** [comment]
@Steinop https://www.figma.com/file/dWhCsnlMAmJEBPyGnRrse5RM/J%C3%B8kul-portalen?node-id=4853%3A37230

**Comment by Steinop** [comment]
@Slaine2 Liker at du bruker lys grå bakgrunn istedenfor sort outline. Det gir et lettere uttrykk. 
På stegindikatoren ville jeg også testet ut med diamanter istedenfor sirkler.

**Comment by Slaine2** [comment]
inramming gir oppgaven litt annen betydning. Jeg tror vi må fokusere på å være flere leverandører.

https://www.figma.com/file/5hKKA7RE6yc9zRynlR2ZJR/Progressbar?node-id=0%3A1
