### ISSUE TITLE
Checkbox / Radiobuttons: Visuell oppdatering

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#938]
Som en følge av en rekke redesignede komponenter med blå hovereffekt og subtile animasjoner bør vi også se på Checkbox og Radiobuttons.

Her er et utkast til oppgradering:
https://vimeo.com/414740158/0321098677

Figmaprototype (må klikkes på i samme rekkefølge som filmen over):
https://www.figma.com/proto/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=13865%3A553&viewport=429%2C303%2C0.17970889806747437&scaling=min-zoom

**Comment by Steinop** [comment]
Oppdaterte check + radios i byggesonen:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=13860%3A493

**Comment by Steinop** [comment]
Opptak av animert prototype:
https://vimeo.com/414802012/8fd3a4734b

Figmaprototype:
https://www.figma.com/proto/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=13865%3A1316&viewport=467%2C271%2C0.14430338144302368&scaling=min-zoom

**Comment by eduardodir** [comment]
Är detta klart för utveckling?

**Comment by Steinop** [comment]
De er klare til utvikling i normal versjon - de må også tegnes opp i compact og oppdateres i komponentbiblioteket i Figma.

Issue #934 kan stenges hvis vi er enige om denne nye retningen

**Comment by eduardodir** [comment]
Kan det vara på tid för en genmgång samman av alla dessa design uppdateringar eller sker enighet på design kritik?

**Comment by Steinop** [comment]
Noen av komponentene har vært gjennom designkritikk på et tidlig stadie. Ferdige komponenter blir ofte ikke kritisert på en designkritikk (som i stor grad brukes til å få kvalifiserte innspill og tilbakemeldinger) men presentert i designsystemforumet. Enig i at det kunne vært fint med en gjennomgang av helheten når alle komponentene er klare.

Compact-versjonene er forøvrig skisser opp i Figma og ligger her:
De må inn i Figmabiblioteket og oppdateres i kode.

(Blir muligens en liten endring på hvordan check animerer - nå blir den skalert ned og inn. Tror vi skal prøve å beholde animasjonen slik at den checkmarken tegnes opp fra venstre til høyre samtidig) - Mulig dette ble uklart. Jeg lager en skisse 😁

**Comment by Mikkelinski** [comment]
Denne er riktig i Figma - trenger utvikling

**Comment by Mikkelinski** [comment]
@piofinn vet du om det er gjort noe på denne? Veldig rask sjekk på portalen virker som det er samsvar mellom figma og det som er utviklet - isåfall kan denne lukkes
