### ISSUE TITLE
Loader: Legges til i Figma-biblioteket

### ISSUE THREAD

**Issue by Steinop** [fremtind/jokul#941]
Komponenten eksisterer kun i kode (og i After Effects) Må også gjenspeiles i Figmabiblioteket.
Bør samtidig vurdere en visuell oppdatering. Spesielt i tilfellene der den blir brukt som loader i en knapp/pilleform

**Comment by eduardodir** [comment]
Tar ni även hänsyn till "rätt" bruk av färger? Gör gärna en issue efterpå att uppdatera till den nya designen.

**Comment by Steinop** [comment]
Hvis "rätt" bruk av farger betyr UU-hensyn og visuell Jøkul-konsistens så ja 😁

**Comment by Mikkelinski** [comment]
Status: Jeg kommer til å bygge denne som en komponent i Figma - verdien her er jo for prototyping i utgangspunktet. Krever ikke utvikling

**Comment by Mikkelinski** [comment]
Done - 3 måneder forsinka
