### ISSUE TITLE
Feil: BaseInputField - hvis className prop blir tatt i bruk overskriver den jøkul-styling

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#947]
**Feilbeskrivelse**
BaseInputField har støtte for prop-en className, men hvis den blir tatt i bruk overskriver man enkelt og greit "jkl-text-input__input".

**Forventet oppførsel**
Dette er sikkert et ønsket pattern på visse komponenter, men akkurat på denne som er så enkel så ønsker jeg at den setter `jkl-text-input__input ${className}`.

Slik at jeg har kan definere `input--first` `input--second` etc. for å få korrekt margins
![image](https://user-images.githubusercontent.com/14551408/81562455-2cd83b00-9395-11ea-8d07-3f3387e35d32.png)

Mulig dette egentlig er en feature-request og ikke en feil, men føler at eksponering av className er feil når bruk av den kun fjerner styling.

**Comment by piofinn** [comment]
Dette er helt klart en bug, ja! Er meningen at den skal oppføre seg som du beskriver 😊 Lyst til å lage PR, @vegardsoerlie ?
