### ISSUE TITLE
Validering/formatering inkludert i Jøkul

### ISSUE THREAD

**Issue by frisol97** [fremtind/jokul#952]
**Is your feature request related to a problem? Please describe.**
Det er flere teams som bruker egne valideringer og formateringer i løsningene sine. For å slippe å måtte oppfinne hjulet på nytt hver gang burde vi samlet dette til en egen utility-pakke.

**Describe the solution you'd like**
Det er bedre at generell validering og formatering som blir brukt mye kommer fra samme bibliotek for å slippe redundant kode.

**Other comments**
Her er et utdrag fra hva for eksempel motor bruker av valideringer
![image](https://user-images.githubusercontent.com/51901763/81818255-1a453980-952e-11ea-871d-16d7f56870b6.png)

**Comment by eduardodir** [comment]
Efter samtal idag, är enklaste processen framåt är att börja med och skapa en ny mappe i Jøkul och bruka det existerande arbetet gjort av Team Motor som underlag. @frisol97 synes detta bör göras och testas på ert projekt, där behovet är nu, ping mig, så tar vi ett prat.
@lfbergee har sandboxat lit.

**Comment by lfbergee** [comment]
Noen tanker:
Jeg syns ikke vi direkte skal løfte repoet til kundeklient pm, for de det haster kan de bare bruke det repoet, ta kontakt med meg om du lurer på hvordan du får tak i det.

Hovedgrunnen til det er at vi bør tenke oss igjennom hvordan vi vil ha APIet vårt, ikke låse oss til det APIet som finnes. Dog kan vi nok ta i bruk alle reglene, men vi bør lage vår egen wrapper til det med det APIet vi ønsker.

Jeg lagde en liten sandbox, for å illurstrere mine tanker. Det jeg ønsker meg er små, enkle, fristilte funksjoner som kan brukes som klientene vil, med et enkelt API over for enkel referanseimplementasjon. Jeg vil at de skal være composable og utvidbare så det er enkelt og legge flere regler sammen og skape sine egne spesialvarianter uten å skitne til fellesfunksjonene. Jeg vil at hvordan det brukes skal være opp til klient.

https://codesandbox.io/s/validatorfns-iz0d9

**Comment by Saegrov** [comment]
@lfbergee Det så veldig kult ut!

Noen tanker: Trenger man å ha alle feilmeldingene? Hvis valideringene er laget for å brukes i forms så tenker jeg at man kun viser en feilmelding selv om det er flere feil. Så hvis `messages` i eksempelet ditt kun innehold den første feilmeldingen som inntreffer så tror jeg forenkler litt. 
Jeg er også litt usikker på hva man skulle brukt `rules` til. Det er kult men jeg klarer ikke å se hva det skulle blitt brukt til. Forhåpentligvis så vil feilmeldingen indikere hva som gikk galt.

**Comment by Saegrov** [comment]
Et annet innspill er at hvis validator-funksjonene skal brukes i forms så vil typen til `value` alltid være en string. Selv om man bruker `<input type="number" />` så vil alltid typen til `value` være `string`.

**Comment by lfbergee** [comment]
Er veldig usikker på om feilmeldingene trenger å være i det. Det kompliserer ting, så kanskje like greit å dra det helt ut av dette, og bare ha rene og pene funksjoner.

Det er jo fair, kan være string, funksjonene må bare ta høyde for det. Evt om man normaliserer først.

**Comment by lfbergee** [comment]
Okei, take2. Liker denne bedre. https://codesandbox.io/s/validatorfns2-tfc9t

**Comment by joms** [comment]
Jeg synes take2 ser veldig ryddig og pen ut. Men jeg foretrekker en utgave hvor validatorene tar en feilmelding og returnerer feilmeldingen hvis validatoren feiler. Pipen vil da returnere første feilmelding.

Da kan man gjøre

```
const largerThan10 = isLargerThan(10, "Tallet må være større enn 10");
const largerThan10LessThan15 = pipe(largerThan10, isSmallerThan(15, "Tallet må være mindre enn 15"));

<input name="input1" errorLabel={largerThan10LessThan15(value1)} />
<input name="input2" errorLabel={largerThan10LessThan15(value2)} />
<input name="input3" errorLabel={largerThan10(value3)} />
```

i stedet for løsninger som

```
const largerThan10(value) => {
	let errorLabel = '';
	if (isLargerThan(10)(value)) {
	    errorLabel = "Tallet må være større enn 10";
	}
	return errorLabel;
}

const largerThan10LessThan15(value) => {
	let errorLabel = '';
	if (largerThan10(value)) {
	    errorLabel = "Tallet må være større enn 10";
	} else if (isSmallerThan(15)(value)) {
	    errorLabel = "Tallet må være mindre enn 15";
	}
	return errorLabel;
}
<input name="input1" errorLabel={largerThan10LessThan15(value1)} />
<input name="input2" errorLabel={largerThan10LessThan15(value2)} />
<input name="input3" errorLabel={largerThan10(value3)} />
```

**Comment by gbrownlee** [comment]
Ser ut til at denne er klar. Åpne den igjen om det er feil, @eduardodir.
