### ISSUE TITLE
Design på interne tredjepartsløsninger (whitelabel)

### ISSUE THREAD

**Issue by gbrownlee** [fremtind/jokul#963]
**Is your feature request related to a problem? Please describe.**
Vi mangler konkrete retningslinjer for tredjepartsløsninger som brukes internt (f.eks. Utsikt). Noen av disse er det ønskelig å tilpasse til Fremtind sin profil, men har mange begrensninger.

**Describe the solution you'd like**
Vi bør dokumentere hvordan vi kan justere slike løsninger til tross for begrenset fleksibilitet. F.eks. kan det være verdifullt å si noe om hvilke farger som bør brukes i en header vi ikke kan justere høyden på, hvilken logo og størrelse som bør brukes om vi ikke kan velge plassering selv, hvilken farge knapper vi ikke kan justere form på, bør ha, osv.

**Additional context**
Vi har anledning til å starte med Utsikt etter forespørsel fra dem og kan lære fra den prosessen.
Denne bør det kanskje lages et eget GH-project for.

**Comment by piofinn** [comment]
Godt innspill! Og veldig bra at Utsikt selv har tatt kontakt om dette.

En del av eksemplene du trekker frem bør være besvart av [siden om logoen i Portalen](https://fremtind.github.io/jokul/profil/logo), så vi bør kanskje prioritere å få gjort den ferdig med eksempler, og kanskje også spisse noen av dem litt mer etter å ha snakket med f.eks. Utsikt om hva de lurer på.

Hele #828 er vel egentlig ganske relevant for dette.

**Comment by Slaine2** [comment]
Hver side har en annen startposisjon. Derfor er det vanskelig å sette en ekte hvit etikett. Vi var imidlertid veldig fornøyde med Kompendia-siden, spesielt siden funksjonene ble gitt. 

Vi har fokusert på:
- Korrekte skrifter
Bildebrytelse
-Avstand
-Farger
-Bruk av logo 

Her som mal:
https://www.figma.com/file/jF3dQxaKMYgpiGbbKHmWqb/Tredjepartner-L%C3%B8sninger?node-id=1%3A2371

Og hvordan den deretter blir implementert:
https://cp.compendia.no/fremtind/personalhandbok/#all-content

Også Fjellini-siden som et eksempel 
https://fremtindservice.no/?gclid=Cj0KCQiA0-6ABhDMARIsAFVdQv8c1Mfc4kc5DqpvAFxqqDXLyVq4OUVJYIrRjyU34RnhZybLDDme0sgaAlk-EALw_wcB
