### ISSUE TITLE
ScrollElementIntoView hook

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#967]
**Is your feature request related to a problem? Please describe.**
A consistent way to make an element scroll into view

**Describe the solution you'd like**
A custom hook that allows an element to be scroll into view with an optional delay.

**Comment by piofinn** [comment]
@joms @frisol97 Dere bruker vel `scrollElementIntoView` i BM nå? Kanskje dere kan se på pull requesten som er linket her og se om den dekker deres behov?

**Comment by joms** [comment]
> @joms @frisol97 Dere bruker vel `scrollElementIntoView` i BM nå? Kanskje dere kan se på pull requesten som er linket her og se om den dekker deres behov?

Jeg har sett over og godkjent pull requesten. Tror dette vil dekke behovet. @frisol97 gjør litt ekstra testing
