### ISSUE TITLE
Double class in input field

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#969]
**Describe the bug**
The input field has the same class twice. 

**To Reproduce**

1. Go to https://fremtind.github.io/jokul/komponenter/textinput
1. Open devtools and find input field
1. Same class is listed twice

**Expected behavior**
Class should only be listed once

**Comment by vegardsoerlie** [comment]
Ser ut som om denne oppsto når jeg fikset className i BaseInputField. Endre da fra
`className=jkl-text-input__input`
til
`className={'jkl-text-input__input ${className}'}`

I TextInput blir BaseInputField kalt med `className="jkl-text-input__input`.

**Comment by piofinn** [comment]
Som @vegardsoerlie  sier kan dette enkelt fikses ved å fjerne `className` prop-en når `BaseInputField` blir brukt i `TextInput`.
