### ISSUE TITLE
Feil: Datepickeren mangler bakgrunn i produksjon

### ISSUE THREAD

**Issue by joms** [fremtind/jokul#970]
**Feilbeskrivelse**
Datepickeren har ingen bakgrunn i produksjon

**For å reprodusere**
Pio kjenner til denne, men kontakt meg for live eksempel.

**Forventet oppførsel**
Datepickeren har bakgrunn.

**Skjermbilder**
![image](https://user-images.githubusercontent.com/537060/82895649-cd615a00-9f54-11ea-8884-f22e93009363.png)

**Comment by Mikkelinski** [comment]
@joms vet du hva feilen skyldes? Jeg bare ser at det ikke er feil i eksempelet på portalen - så er det noe som er lokalt for dere?

**Comment by piofinn** [comment]
Fin liten `z-index` issue 😅 Er ikke et issue i portalen, men kan dukke opp andre steder avhengig av strukturen rundt. Veldig rask fiks!

**Comment by joms** [comment]
Kan faktisk se ut som det er verre enn som så. Fikk endelig satt meg ned og sammenlignet produksjonsversjonen og den jeg kjører i utviklingsbygget - der ser jeg at i utvikling lages elementet `core-datapicker-3-0-8` og får stilen `CORE-DATEPICKER-3-0-8 { display: block; }` mens i produksjon heter den bare `t-3-0-8` og får ikke tilsvarende stil.

Om jeg manuelt i chrome devtools setter stilen på elementet fungerer det fint. Så jeg er litt skeptisk til at det er `z-index` likevel. Men jeg forstår ikke helt hva som skjer med elementet. Har du noen tips @piofinn ?

**Comment by piofinn** [comment]
Hmm.. Det skal ikke settes noe stil basert på elementnavn, @joms . `{ display: block; }` blir satt inline (og bare midlertidig) av `useAnimatedHeight`-hooken. Det har vært en bug med at elementnavnet krasjer med `CoreToggle`-elementet, men det skal være fikset.
