### ISSUE TITLE
Brukeropplevelse, prinsipper for skjemavalidering

### ISSUE THREAD

**Issue by eduardodir** [fremtind/jokul#972]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Vi ønsker og tydeliggjøre hvordan vi validerer skjemaer på tvers.

Eksempler på problemer som kanskje må løses:

Når viser vi feil melding når noe går galt i et inputfelt, eller et annet element. Skjer det mens du skriver, eller blir onblur, eller på annen måte?

Hvordan viser vi feil for hele skjemaet når du klikker på send, og det er feil?

Bør jeg være i stand til å sende et skjema som er feil, eller skal sende-knappen være låst?

Scrolljacking i skjemaer kontra hva som er mulig med dagens valideringsbibliotek, hva gjør vi her? Er det ikke bedre å gå etter prinsipper som fungerer med eksisterende løsninger som is? Snakk med Frida Solhaug @frisol97 

Mennesker som har vært involvert i skjemaer og kjenner de tekniske begrensningene, er: Markus Rauhut, Simen Sægrov @Saegrov  og Leiv Fredrik Berge @lfbergee 

Defenition Of Done? (dokumenteres prinsipper og eksempler i portalen?

**Describe alternatives you've considered**
Figma exempel?

**Additional context**

**Comment by Mikkelinski** [comment]
Slik det er beskrevet i dag er det satt til OnBlur - og vi viser feil for alle felter som ikke validerer når man sender inn skjema. Vi låser ikke knappen du får trykke også blir du scrollet opp til øverste felt med feil - om dette ikke er mulig bør vi flytte brukeren til topp av skjema og gi en overordnet feilmelding (re det SeOpp har gjort) i tillegg til å vise feil på de enkelte skjemakomponentene.

Alle disse prinsippene er beskrevet. En endring jeg ville sett på er om det er mulig å ha onblur validering som default, men bytte fra onblur til validering mens man skriver (onchange?) dersom komponenten er i en error state.

**Comment by lfbergee** [comment]
Høres fornuftig ut det @Mikkelinski, tror jeg ville fjernet validering/feil ved fokus på et felt med feil i og validert på blur, isteden for onChange. Jeg syns det er mindre irriterende som bruker.

**Comment by Mikkelinski** [comment]
Både og - på et felt som ble forbigått er jeg enig i at man bør fjerne feil på fokus, men om de fylte ut feiltet men hadde feil formatering er det greit å gi informasjonen mens de "retter" det opp - E.g. ugyldig fødselsnummer ville jeg validert onchange når de prøver å rette det (siden de har fått feilen når de gikk videre fra feltet første gang onblur), mens et felt som er hoppet over mister errorstate om de fokuserer det.

Det byr på litt unødvendig kompleksitet kanskje - onchange validering gjør seg best i felter som har et format hvor brukeren setter pris på å vite at "nå er det riktig" - KID nr og den type ting.

**Comment by lfbergee** [comment]
Tja, er jo smak sak, men si telefonnummer da, du har tastet inn 456789, det blir feil på blur med feilmelding "Telefonnummer må ha 8 siffer", også visker jeg ut alt, og feilmeldingen bytter til "Telefonnummer kan ikke være tomt". Det syns jeg er annoying.

**Comment by Saegrov** [comment]
Jeg laget et eksempel på hvordan vi har gjort det i Flyt: https://codesandbox.io/s/keen-khorana-cw70j?fontsize=14&hidenavigation=1&theme=dark

Sånn fungerer det:
- Validering for et felt kjøres når feltet mister fokus. F.eks hvis man trykker seg videre til neste felt.
- Alle valideringer kjøres når man trykker "Submit"
- Feilmelding for et felt forsvinner i det du endrer verdien i feltet

**Comment by piofinn** [comment]
> Sånn fungerer det

Dette høres ut som det dekker både @lfbergee og @Mikkelinski sine synspunkter godt! 😊 Jeg synes i hvert fall det høres ut som en behagelig brukeropplevelse: umiddelbar oppdatering (onChange) er kun til noe positivt, mens feilmeldinger først kommer etter at man har fylt ut (onBlur, onSubmit).

**Comment by Mikkelinski** [comment]
Er fortsatt fan av onchange på felter som har først fått feilstatus pga onblur i første omgang - men kan fint leve med den implementeringen, den er i tråd med slik vi har beskrevet det i prinsippene.

**Comment by kristineSorensen** [comment]
Tenkte jeg kunne dele eksempler fra SeOpp og hva jeg har sett på i forbindelse med feilmeldinger der. I dagens seOpp løsning fungerer det slik at dersom brukeren trykker på et av de fremtidige stegene, så kommer det opp en feilmelding på selve steget (bilde 1) dersom brukeren prøver å gå videre uten å fylle inn alle felt kommer det en overordnet feilmelding i topp, samt feilmelding på feltene som mangler utfylling (bilde 2) - Også viser vi en feilmelding på feltet med en gang dersom brukeren f.eks fyller inn for få tall i et telefonnummer. 

Det vi har kommet frem til er å droppe feilmeldingen som kommer direkte på steget (bilde 1) og heller berike teksten i den overordnede feilmeldingen. (Bilde 3, PS: rask klipp og lim skisse, se bort fra visuelle feil) Slik at dette er det som skjer både når brukeren prøver å gå videre uten å fylle inn alle felt, eller prøver å trykke på et av de neste stegene, (eks brukeren er på steg 1 og prøver å åpne steg 3)

![Bilde 1](https://user-images.githubusercontent.com/62281382/83506513-9268a480-a4c7-11ea-9f88-8f2484d46db9.png)
![Bilde2](https://user-images.githubusercontent.com/62281382/83506543-9b597600-a4c7-11ea-9b36-5ae310bf60bb.png)
<img width="890" alt="Bilde 3" src="https://user-images.githubusercontent.com/62281382/83506570-a4e2de00-a4c7-11ea-8ce1-c751e22e9098.png">
