### ISSUE TITLE
Portalforbedringer

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#975]
**Er ønsket tilknyttet et problem? Fortell oss mer!**
1. Lettere inngang til github. Jeg hopper ofte mellom github og portalen, skulle gjerne sett at github/figma var lenket til litt mer tydelig enn i dag.
2. Typografi-komponentene er ikke dokumentert spesielt godt. Noen av komponentene ligger i komponent dokumentasjonen, noe under "Profilen vår", men ingen steder er det dokumentert hvordan man lager en h1 med tittel stil feks.
3. Fargene burde vise fargene. Per i dag så må jeg google hex koden for å se hvordan fargen ser ut, det burde vært vist i portalen.
4. Spacing utility klassen er ikke dokumentert.
5. Kunne gjerne vært listet publisert npm versionsnummer på komponenten, kanskje også lenke til changelog/migration
6. Flott med migrasjonsgide ved breaking change, men ønsker meg at de er hakket mer komplett. Ble en del gjetting og graving ved oppdatering av typografikomponentene

**Beskriv løsningen du ønsker**
1. Lenke til github/figma fra toppmeny eller hovedmeny
2. Dokumentert typografikomponenter i komponentseksjonen, også det som bare er klassenavn. Gjerne også font-mixins også.
3. Vise fargene som farger
4. Dokumentere spacing utilityklassene i komponentseksjonen
5. Legge til npm-shield på komponentsiden
6. Ikke noe konkret nå, men ønske for Fremtinden™ ved neste breaking change

**Mer info**
Ble litt mye i et issue, men tenke å liste opp det jeg har opplevd siste uke med oppgradering av en haug av Jøkul komponenter.

**Comment by Mikkelinski** [comment]
Tett koblet til denne: #828

**Comment by piofinn** [comment]
Hehe, satt akkurat og lette etter dokumentasjon på spacing-klassene 😅 Veldig bra oppsummering dette her, @lfbergee! Skriv gjerne litt om hva du konkret savnet i migrasjonsguiden også 😊 Er lett å overse ting som er nyttig å ha med når man kjenner endringene godt.

**Comment by lfbergee** [comment]
I migrasjonsguiden manglet det noen farger som var fjernet eller erstattet. Måtte også grave litt for å finne hva alle klassene hadde byttet navn til. Hvis store deler av et API endres, men noen få deler beholdes, så burde de beholdte delene kanskje også listes. 

Feks:

| Old | New |
| --- | --- |
| jkl-small | jkl-sm |
| jkl-large | jkl-lg |
| jkl-xl | jkl-xl |

**Comment by lfbergee** [comment]
Anser det meste som løst etter portalsprinten, evt andre pet pewes kommer sikkert opp igjen om de er viktige nok.
