### ISSUE TITLE
"Søkbar select" og søkefelt

### ISSUE THREAD

**Issue by CamillaDahlstroem** [fremtind/jokul#976]
**Er ønsket tilknyttet et problem? Fortell oss mer!**

I Flyt trenger vi både en "søkbar select" og et mer tradisjonelt søkefelt.

Den søkbare selecten trenger vi (minst) to steder: 
- I det vi kaller "legesøk", en evig lang liste der man kan velge mellom alle leger i Norge:
<img width="714" alt="Skjermbilde 2020-05-28 kl  10 41 31" src="https://user-images.githubusercontent.com/11536996/83119288-d165b700-a0cf-11ea-8656-ef9b47db3101.png">

- Og i den evig lange listen over årsakskoder:
<img width="729" alt="Skjermbilde 2020-05-28 kl  10 38 41" src="https://user-images.githubusercontent.com/11536996/83119039-8055c300-a0cf-11ea-8bb4-05940a006c80.png">

Og vi trenger et mer "vanlig" søkefelt for filtrering i tabellen/listen over saker.
<img width="1002" alt="Skjermbilde 2020-05-28 kl  10 15 46" src="https://user-images.githubusercontent.com/11536996/83119064-88adfe00-a0cf-11ea-9440-a27638d0d82c.png">

**Beskriv løsningen du ønsker**
Vi kommer til å lage disse, fordi vi må ha dem. Det jeg lurer på er:
- Tror dere at flere vil ha sånne søkefelt? Bør de bli en del av Jøkul? I såfall, hvilke andre behov enn våre egne må vi innfri?
- Har noen andre laget lignende søkefelt? Hvordan ser disse ut? Hvordan oppfører de seg? 

PS: Vi har også lyst på en multi-select, men ikke så mye at vi kommer til å lage den selv.

**Comment by lfbergee** [comment]
Begge disse finnes i AHV også. Der er det lagd en custom komponent basert på downshift. @Martinvks  hadde en PR på denne for en god stund tilbake, og strengt tatt burde vel den vært tatt inn, i det minste håntert bedre enn det som ble gjort.. Kanskje Martin fortsatt har den, så kan vi opprette den på nytt.

**Comment by Mikkelinski** [comment]
Føler at BM er en av løsningene som trolig trenger tilsvarende @Murstam - tanker/innspill?

**Comment by Murstam** [comment]
På sikt har vi trolig behov for både søkbar select og søkefelt ja.

**Comment by Mikkelinski** [comment]
Trenger dere noe funksjonalitet i det som ikke er dekket i eksempelet over? Hvis ikke tenker jeg at dette er noe vi kan ta inn så fort det lar seg gjøre - det baserer seg jo på eksisterende design så det jeg kan se av ubesvarte spørsmål er hvor mye custom formatering på listen vi skal åpne for

**Comment by Martinvks** [comment]
@lfbergee https://github.com/fremtind/jokul/pull/337

**Comment by piofinn** [comment]
Angående søkefelt. Er det noen grunn til at man ikke kan bruke `TextField` med en action ("search" eller "clear") til dette? Eventuelt et vanlig tekstfelt med en knapp ved siden av? I skissene til @CamillaDahlstroem ser det ut som det er brukt `TextField` med action.

Hva sier dere andre? @Murstam @lfbergee @Mikkelinski @Martinvks

**Comment by Mikkelinski** [comment]
For søkefelt som viser resultatslisten i egen visning (tabell/liste) er jeg helt enig - mer for den type søkefelt som vises øverst hvor det egentlig er en søkbar dropdown / filtrerbar dropdown, men med søkefelt over chevron/pil av affordance grunner.

**Comment by piofinn** [comment]
@Mikkelinski Ja helt enig i at søkbar nedtrekksliste må være en egen komponent 😊 Tenkte spesifikt på søk med resultater i egen visning, slik som det siste eksemplet.

**Comment by CamillaDahlstroem** [comment]
For det "vanlige" søkefeltet kan det sikkert gå an å bruke textField, ja! Visste ikke at det var laget støtte for at man kan legge til actions på det - burde sikkert stått noe om det her: https://fremtind.github.io/jokul/komponenter/textinput

**Comment by CamillaDahlstroem** [comment]
Aaah nå så jeg at det er et option for "Med handling" i eksempelet. Men ja, et eksempel på at man kan bruke tekstfeltet som et søkefelt er nok på sin plass, om det skal kunne fungere sånn.

**Comment by Murstam** [comment]
Ja, TextField med action funker sikkert bra det.

**Comment by piofinn** [comment]
> Visste ikke at det var laget støtte for at man kan legge til actions på det - burde sikkert stått noe om det her: https://fremtind.github.io/jokul/komponenter/textinput

Det kan sikkert stå bedre beskrevet i teksten, ja 😊

**Comment by SercanSercan** [comment]
I SeOpp teamet, har jeg utviklet en komponent som ligner til eksempel her. 
https://stash.intern.sparebank1.no/projects/SEOPP/repos/seopp-kunde-frontend/browse/src/Components/MapSearch

Når bruker skriver en addresse, dukker opp resultater fra Google Maps API. Til å implementere den, har jeg brukt Jøkul's TextInput. Den har også tastatur navigasjon. 

Se gif her: https://i.ibb.co/M9zVvkK/Map-Search-In-Action.gif

**Comment by CamillaDahlstroem** [comment]
Så, hvordan gjør vi det med søkbar nedtrekksliste? Hvem skal ta ansvaret for å lage den?

**Comment by Mikkelinski** [comment]
Foreslår at Flyt teamet tar denne videre da dere har det umiddelbare behovet for den? Dersom ingen sitter med overkapasitet i DS teamet og klør seg etter noe å gjøre men det tror jeg ikke, og det hadde vært interessant å få testet ut prosessen vår heh. https://fremtind.github.io/jokul/komigang/prosessen

Per denne ville jeg sagt vi er forbi avklaring og over på kravspec/utvikling.

**Comment by piofinn** [comment]
Enig med @Mikkelinski her. Sikkert en god idé å snakke med både AHV og SeOpp siden begge har lignende komponenter i sine løsninger. Alle tre tilnærmingene virker litt forskjellige, så det bør nok gjøres en liten kravspec-jobb for å se hva som skal med av funksjonalitet i Jøkul-komponenten i første omgang, og om noe eventuelt bør være egne komponenter.

Jeg tipper for øvrig at disse artiklene kan være nyttige både mtp kravspec og utvikling:
https://accessibility.blog.gov.uk/2019/04/08/accessibility-lessons-dealing-with-a-large-amount-of-form-inputs/
https://designnotes.blog.gov.uk/2017/04/20/were-building-an-autocomplete/

**Comment by CamillaDahlstroem** [comment]
Ok! Det er fremdeles noen uker til vi skal lage denne funksjonaliteten, så jeg vet ikke nøyaktig hvem som kommer til å jobbe med det da. I mellomtiden kan jeg assigne meg selv.

**Comment by lfbergee** [comment]
@all-contributors please add @CamillaDahlstroem for design
