### ISSUE TITLE
Komponent: Navigation Buttons

### ISSUE THREAD

**Issue by Mikkelinski** [fremtind/jokul#991]
I flere løsninger (inkludert portalen) er det brukt "pil-knapper" som navigasjonselementer. Dvs en pil med en liten animert effekt på hover, og tilhørende tekst.

Disse kan ikke erstatte tertiærknappen direkte, siden de ikke passer inn i skjemaflyter hvor tertiærknappen brukes typisk for regressive handlinger (avbryt, slett, angre). Men der vi ikke har et ønske om å bruke primary button som en slags CTA, eller inline tekstlenker, så fungerer disse knappene med piler som tydelige navigasjonselementer. Pilen indikerer om brukeren går tilbake eller "fremover" i løsningen.

Foreslår at vi etablerer pattern på disse sånn at det ikke fragmenterer. Se diskusjon:
https://www.figma.com/file/kd8Uassho8sxy8DXUfyfMq/Generelle-forbedringer-i-Se-Opp?node-id=77%3A113

Kom med innspill på hvordan vi best løser dette i kode og design.

**Comment by Mikkelinski** [comment]
@Steinop @Murstam @piofinn (btw - får ikke tagget Kristine Sørensen her av en eller annen grunn)? og evt andre som er interessert.

**Comment by Murstam** [comment]
Enig med @Steinop at tekst og pil bli blå ved hover og at bilen beveger seg i retningen den peker.

**Comment by lfbergee** [comment]
Hva med 
![image](https://user-images.githubusercontent.com/46530368/84384771-c55d1780-abee-11ea-8f32-e10e51e7da6e.png)

Hva skal bli blått her?

**Comment by piofinn** [comment]
Siden dette først og fremst er et navigasjonselement tror jeg vi skal være forsiktige med å eksplisitt kalle det en knapp: På nettsider skal navigasjon helst håndteres av lenker, mens knapper er reservert for å utføre handlinger på siden. I noen tilfeller vil det overlappe (som i skjemaer der knappen for å sende inn også tar deg til en ny side), men å implementere dette spesifikt som en knapp vil kunne skape dårlig tilgjengelighet der det brukes kun som navigasjon.

Hvis man implementerer dette som en ren CSS-klasse, på samme måte som tekststilene, vil det kunne brukes på semantisk rett element under utvikling.

**Comment by Mikkelinski** [comment]
@lfbergee på kortet ville jeg satt pilen, og evt en ramme rundt hele kortet, i blått.
@piofinn ja, knapp er kanskje feil betegnelse - og det bør være tydelig når disse elementene skal brukes over knappene vi allerede har. F.eks submit skal være en primærknapp - ikke tekst med pil.

**Comment by Murstam** [comment]
Enig. Som kort ville jeg hatt blå ramme og blå pil.

**Comment by piofinn** [comment]
@Murstam @Mikkelinski @lfbergee 

Enig om kortet. Noe sånt som @Steinop sin skisse her: https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=11110%3A828

**Comment by lfbergee** [comment]
![image](https://user-images.githubusercontent.com/46530368/84660149-b93bc780-af18-11ea-8733-09bae773c665.png)
Fra AHV.

Setter samme state på hover og focus. På mobil så setter vi denne staten når kortet er mer enn 50% synlig, og fjerner det når kortet går mer enn 1% ut av view i toppen. Det vil ikke fungere for alle kort, men i vårt tilfelle funker det. 

Men man bør lande på en god implementasjon for touch dingser før denne publiseres.

**Comment by Murstam** [comment]
Jeg tenker egentlig at kortene bør ha en konstant ramme av noe slag. Spesielt på mobil, men egentlig på desktop også. Bør være litt tydeligere før focus/hover at det er klikkbare kort.

**Comment by Mikkelinski** [comment]
De enkle kortene i Figma har ingen ramme som "default" men jeg er enig at det ikke er så lurt mtp mobil, så kan kanskje sees på - vi har ikke satt opp mange forskjellige "shadows" for å indikere ulike nivåer av "opphevethet" heh

**Comment by Steinop** [comment]
Når kortene er så store at de nærmest blir en fullskjermseksjon mister vi noe av effekten med skyggen. Da vil ikke kortet i seg selv oppleves som en stor trykkbar knapp og man bør heller bruke en tydelig navigasjonsknapp. 

Kortene jeg har skissert i Figma kan enten ha skygge eller ikke by default:
https://www.figma.com/file/TkbB9ANfejDSjB2u4u1OEuqM/J%C3%B8kul-komponenter-byggesone?node-id=10807%3A28744

Virker ellers som denne tråden har sporet litt av - utgangspunktet var pil-knappene.
Her diskuterer vi cards 😁

**Comment by Mikkelinski** [comment]
Pilknappe er løst - kan åpne issue om card ved behov
