### ISSUE TITLE
Feil: Grå bakgrunn på portalen

### ISSUE THREAD

**Issue by lfbergee** [fremtind/jokul#993]
**Feilbeskrivelse**
Skal være hvit bakgrunn, men er grå i Firefox 68ESR. Ser riktig ut på samme platform i chrome.

**For å reprodusere**
![image](https://user-images.githubusercontent.com/46530368/84649471-e2535c80-af06-11ea-9138-5b72d6a3f29a.png)

**Forventet oppførsel**
Hvit bakgrunn i alle browsere

**Mer info**
Firefox 68.9.0 ESR, RedHat 7.8

**Comment by piofinn** [comment]
Har lagt merke til dette når du har delt skjerm tidligere. Har du mulighet til å ta noen skjermdumper av "computed"-delen i inspektøren hos deg? Da blir det kanskje litt lettere å se hvor dette kommer fra (hvis du ikke kan/vil gjøre en fix selv, da).
